# Generated by Django 2.0.2 on 2018-06-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outstanding',
            name='outstanding_month',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
