# Generated by Django 2.0.5 on 2018-09-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            '''CREATE SEQUENCE IF NOT EXISTS device_info_seq START 10000000;'''
        ),
    ]
