# Generated by Django 2.0.5 on 2018-09-07 09:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20180906_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='device_info',
        ),
        migrations.AddField(
            model_name='visitor',
            name='device',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
