# Generated by Django 2.0.5 on 2018-09-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20180907_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='device',
            new_name='device_info',
        ),
    ]
