# Generated by Django 2.0.5 on 2018-09-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20180907_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='ip_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
