# Generated by Django 2.0.5 on 2018-09-24 10:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20180910_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingvisit',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
