# Generated by Django 2.0.5 on 2018-09-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_auto_20180927_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverhitmonitor',
            name='ip_address',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
    ]
