# Generated by Django 2.0.5 on 2018-09-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_auto_20180927_1631'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='serverhitmonitor',
            table='server_hit_monitor',
        ),
    ]
