# Generated by Django 2.0.5 on 2018-09-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_auto_20180927_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverhitmonitor',
            name='type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serverhitmonitor',
            name='ip_address',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
    ]
