# Generated by Django 2.0.5 on 2018-09-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_auto_20180928_1159'),
        ('tracking', '0016_auto_20180927_2100'),
    ]

    operations = [
    ]
