# Generated by Django 2.0.5 on 2018-09-28 12:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_auto_20180928_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverhitmonitor',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
