# Generated by Django 2.0.5 on 2018-12-12 10:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_auto_20180928_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingvisit',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingvisit',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
