# Generated by Django 2.0.5 on 2019-02-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_auto_20181212_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingevent',
            name='triggered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
