# Generated by Django 2.0.5 on 2019-02-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0021_trackingevent_triggered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingevent',
            name='triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
