# Generated by Django 2.0.5 on 2019-03-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0023_migratetracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingevent',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
