# Generated by Django 2.0.5 on 2019-03-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0024_trackingvisitor_client_category'),
        ('tracking', '0024_auto_20190318_2030'),
    ]

    operations = [
    ]
