# Generated by Django 2.0.5 on 2019-04-23 10:56

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresccriptionPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptoms', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('observations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('medicines', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('lab_tests', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('diagnosis', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('followup_instructions_date', models.DateTimeField(null=True)),
                ('followup_instructions_reason', models.CharField(max_length=256, null=True)),
                ('patient_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('appointment_id', models.CharField(max_length=64)),
                ('appointment_type', models.PositiveSmallIntegerField(choices=[(1, 'Docprime_Opd'), (2, 'Docprime_Lab'), (3, 'OFFline')])),
                ('prescription_file', models.FileField(null=True, upload_to='prescription/pdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
            options={
                'db_table': 'eprescription_pdf',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospitals', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('moderated', models.NullBooleanField()),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('time', models.CharField(max_length=64, null=True)),
                ('duration_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Day'), (2, 'Week'), (3, 'Month'), (4, 'Year')], null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('instruction', models.CharField(blank=True, max_length=256, null=True)),
                ('additional_notes', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'eprescription_medicine',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionObservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospitals', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('moderated', models.NullBooleanField()),
            ],
            options={
                'db_table': 'eprescription_observations',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionSymptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospitals', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('moderated', models.NullBooleanField()),
            ],
            options={
                'db_table': 'eprescription_symptoms',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospitals', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('moderated', models.NullBooleanField()),
                ('instruction', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'eprescription_tests',
            },
        ),
    ]
