# Generated by Django 2.0.5 on 2019-04-23 10:56

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresccriptionPdf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptoms_complaints', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('special_instructions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('medicines', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('lab_tests', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('diagnoses', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('followup_instructions_date', models.DateTimeField(null=True)),
                ('followup_instructions_reason', models.CharField(max_length=256, null=True)),
                ('patient_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                # ('appointment_id', models.CharField(max_length=64)),
                ('offline_opd_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eprescription', to='doctor.OfflineOPDAppointments')),
                ('opd_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eprescription', to='doctor.OpdAppointment')),
                ('appointment_type', models.PositiveSmallIntegerField(choices=[(1, 'Docprime_Opd'), (3, 'OFFline')])),
                ('prescription_file', models.FileField(null=True, upload_to='prescription/pdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('serial_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'eprescription_pdf',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospitals', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('moderated', models.NullBooleanField()),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('dosage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('time', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None)),
                ('duration_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Day'), (2, 'Week'), (3, 'Month'), (4, 'Year')], null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('instructions', models.CharField(blank=True, max_length=256, null=True)),
                ('additional_notes', models.CharField(blank=True, max_length=256, null=True)),
                ('source_type', models.IntegerField(blank=True, choices=[('', 'Select'), (1, 'Inhouse Chat'), (2, 'Mesh'), (3, 'Partners App')], default=None, editable=False, null=True)),
                ('is_before_meal', models.NullBooleanField(default=None)),
            ],
            options={
                'db_table': 'eprescription_medicine',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDiagnoses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospitals', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('moderated', models.NullBooleanField()),
                ('source_type', models.IntegerField(blank=True, choices=[('', 'Select'), (1, 'Inhouse Chat'), (2, 'Mesh'), (3, 'Partners App')], default=None, editable=False, null=True)),
            ],
            options={
                'db_table': 'eprescription_diagnoses',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionSymptomsComplaints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospitals', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('moderated', models.NullBooleanField()),
                ('source_type', models.IntegerField(blank=True, choices=[('', 'Select'), (1, 'Inhouse Chat'), (2, 'Mesh'), (3, 'Partners App')], default=None, editable=False, null=True)),
            ],
            options={
                'db_table': 'eprescription_symptoms_complaints',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospitals', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('moderated', models.NullBooleanField()),
                ('instructions', models.CharField(blank=True, max_length=256, null=True)),
                ('source_type', models.IntegerField(blank=True, choices=[('', 'Select'), (1, 'Inhouse Chat'), (2, 'Mesh'), (3, 'Partners App')], default=None, editable=False, null=True)),
            ],
            options={
                'db_table': 'eprescription_tests',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionSpecialInstructions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospitals', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('moderated', models.NullBooleanField()),
                ('source_type', models.IntegerField(blank=True, choices=[('', 'Select'), (1, 'Inhouse Chat'), (2, 'Mesh'), (3, 'Partners App')], default=None, editable=False, null=True)),
            ],
            options={
                'db_table': 'eprescription_special_instructions',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='prescription.PresccriptionPdf')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'eprescription_history',
            },
        ),
        migrations.CreateModel(
            name='OfflinePrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.FileField(upload_to='prescriptions')),
                ('prescription_details', models.TextField(blank=True, max_length=300, null=True)),
                ('appointment',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_prescription',
                                   to='doctor.OfflineOPDAppointments')),
            ],
            options={
                'db_table': 'offline_prescription',
            },
        ),
    ]
