# Generated by Django 2.0.5 on 2019-04-18 13:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0241_auto_20190418_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresccriptionPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptoms', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('observations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('medicines', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('lab_tests', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('diagnosis', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('followup_instructions_date', models.DateTimeField(null=True)),
                ('followup_instructions_reason', models.CharField(max_length=256, null=True)),
                ('appointment_id', models.CharField(max_length=64)),
                ('appointment_type', models.PositiveSmallIntegerField(choices=[(1, 'Docprime_Opd'), (2, 'Docprime_Lab'), (3, 'OFfline')])),
            ],
            options={
                'db_table': 'prescription_pdf',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('time', models.CharField(max_length=64, null=True)),
                ('duration_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Day'), (2, 'Week'), (3, 'Month'), (4, 'Year')], null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('instruction', models.CharField(blank=True, max_length=256, null=True)),
                ('additional_notes', models.CharField(blank=True, max_length=256, null=True)),
                ('moderated', models.NullBooleanField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Hospital')),
            ],
            options={
                'db_table': 'prescription_medicine',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionObservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation', models.CharField(max_length=64)),
                ('moderated', models.NullBooleanField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Hospital')),
            ],
            options={
                'db_table': 'prescription_observations',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionSymptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptoms', models.CharField(max_length=64)),
                ('moderated', models.NullBooleanField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Hospital')),
            ],
            options={
                'db_table': 'prescription_symptoms',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.CharField(max_length=64)),
                ('instruction', models.CharField(blank=True, max_length=256, null=True)),
                ('moderated', models.NullBooleanField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Hospital')),
            ],
            options={
                'db_table': 'prescription_tests',
            },
        ),
    ]
