# Generated by Django 2.0.5 on 2019-04-19 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presccriptionpdf',
            name='prescription_file',
            field=models.FileField(null=True, upload_to='prescription/pdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
