# Generated by Django 2.0.5 on 2019-05-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='dosage_type',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='duration_type',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='is_before_meal',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='time',
        ),
        migrations.RemoveField(
            model_name='prescriptiontests',
            name='instructions',
        ),
    ]
