# Generated by Django 2.0.5 on 2019-04-25 09:19

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionSpecialInstructions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospitals', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('moderated', models.NullBooleanField()),
            ],
            options={
                'db_table': 'eprescription_special_instructions',
            },
        ),
        migrations.RenameModel(
            old_name='PrescriptionObservations',
            new_name='PrescriptionDiagnosis',
        ),
        migrations.RenameModel(
            old_name='PrescriptionSymptoms',
            new_name='PrescriptionSymptomsComplaints',
        ),
        migrations.RenameField(
            model_name='presccriptionpdf',
            old_name='observations',
            new_name='special_instructions',
        ),
        migrations.RenameField(
            model_name='presccriptionpdf',
            old_name='symptoms',
            new_name='symptoms_complaints',
        ),
        migrations.AlterModelTable(
            name='prescriptiondiagnosis',
            table='eprescription_diagnosis',
        ),
        migrations.AlterModelTable(
            name='prescriptionsymptomscomplaints',
            table='eprescription_symptoms_complaints',
        ),
    ]
