# Generated by Django 2.0.5 on 2019-04-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_auto_20190425_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrescriptionDiagnosis',
            new_name='PrescriptionDiagnoses',
        ),
        migrations.RenameField(
            model_name='presccriptionpdf',
            old_name='diagnosis',
            new_name='diagnoses',
        ),
        migrations.AlterModelTable(
            name='prescriptiondiagnoses',
            table='eprescription_diagnoses',
        ),
    ]
