# Generated by Django 2.0.5 on 2019-04-25 10:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_auto_20190425_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiondiagnoses',
            name='source_type',
            field=models.IntegerField(blank=True,
                                      choices=[('', 'Select'), (1, 'Inhouse Chat'), (2, 'Mesh'), (3, 'Partners App')],
                                      default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='source_type',
            field=models.IntegerField(blank=True,
                                      choices=[('', 'Select'), (1, 'Inhouse Chat'), (2, 'Mesh'), (3, 'Partners App')],
                                      default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionspecialinstructions',
            name='source_type',
            field=models.IntegerField(blank=True,
                                      choices=[('', 'Select'), (1, 'Inhouse Chat'), (2, 'Mesh'), (3, 'Partners App')],
                                      default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionsymptomscomplaints',
            name='source_type',
            field=models.IntegerField(blank=True,
                                      choices=[('', 'Select'), (1, 'Inhouse Chat'), (2, 'Mesh'), (3, 'Partners App')],
                                      default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontests',
            name='source_type',
            field=models.IntegerField(blank=True,
                                      choices=[('', 'Select'), (1, 'Inhouse Chat'), (2, 'Mesh'), (3, 'Partners App')],
                                      default=None, editable=False, null=True),
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='instruction',
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='dosage_type',
            field=models.PositiveIntegerField(blank=True,
                                              choices=[(1, 'Tablet'), (2, 'Syrup'), (3, 'CAPSULE'), (4, 'Cream'),
                                                       (5, 'Drops'), (6, 'Foam'), (7, 'Gel'), (8, 'Inhaler'),
                                                       (9, 'Injection'), (10, 'Lotion'), (11, 'Ointment'),
                                                       (12, 'Powder'), (13, 'Spray'), (14, 'Syringe'),
                                                       (15, 'Suspension'), (16, 'Solution')], null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='is_before_meal',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True,
                                                            null=True, size=None),
        ),
    ]
