# Generated by Django 2.0.5 on 2019-04-22 09:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_auto_20190419_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='presccriptionpdf',
            name='patient_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
