# Generated by Django 2.0.5 on 2019-04-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_auto_20190425_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiondiagnoses',
            name='source_type',
            field=models.IntegerField(blank=True, choices=[('', 'Select'), (1, 'Inhouse Chat'), (2, 'Mesh'), (3, 'Doctors')], default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='source_type',
            field=models.IntegerField(blank=True, choices=[('', 'Select'), (1, 'Inhouse Chat'), (2, 'Mesh'), (3, 'Doctors')], default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionspecialinstructions',
            name='source_type',
            field=models.IntegerField(blank=True, choices=[('', 'Select'), (1, 'Inhouse Chat'), (2, 'Mesh'), (3, 'Doctors')], default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionsymptomscomplaints',
            name='source_type',
            field=models.IntegerField(blank=True, choices=[('', 'Select'), (1, 'Inhouse Chat'), (2, 'Mesh'), (3, 'Doctors')], default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontests',
            name='source_type',
            field=models.IntegerField(blank=True, choices=[('', 'Select'), (1, 'Inhouse Chat'), (2, 'Mesh'), (3, 'Doctors')], default=None, editable=False, null=True),
        ),
    ]
