# Generated by Django 2.0.5 on 2019-04-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_auto_20190425_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='presccriptionpdf',
            name='serial_id',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='dosage_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Tablet'), (2, 'Syrup'), (3, 'CAPSULE'), (4, 'Cream'), (5, 'Drop'), (6, 'Foam'), (7, 'Gel'), (8, 'Inhaler'), (9, 'Injection'), (10, 'Lotion'), (11, 'Ointment'), (12, 'Powder'), (13, 'Spray'), (14, 'Syringe'), (15, 'Suspension'), (16, 'Solution')], null=True),
        ),
    ]
