# Generated by Django 2.0.5 on 2019-06-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_auto_20190522_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='presccriptionpdf',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
