# Generated by Django 2.0.5 on 2019-04-30 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_prescriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionhistory',
            name='prescription_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='prescription.PresccriptionPdf'),
        ),
    ]
