# Generated by Django 2.0.5 on 2019-04-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0007_prescriptionhistory_prescription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionhistory',
            old_name='prescription_id',
            new_name='prescription',
        ),
    ]
