# Generated by Django 2.0.5 on 2019-04-30 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0249_merge_20190425_1948'),
        ('prescription', '0008_auto_20190430_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflinePrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.FileField(upload_to='prescriptions')),
                ('prescription_details', models.TextField(blank=True, max_length=300, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_prescription', to='doctor.OfflineOPDAppointments')),
            ],
            options={
                'db_table': 'offline_prescription',
            },
        ),
    ]
