# Generated by Django 2.0.5 on 2019-04-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0009_auto_20190430_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presccriptionpdf',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='presccriptionpdf',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
