# Generated by Django 2.0.5 on 2019-04-30 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0249_merge_20190425_1948'),
        ('prescription', '0010_auto_20190430_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presccriptionpdf',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='presccriptionpdf',
            name='object_id',
        ),
        migrations.AddField(
            model_name='presccriptionpdf',
            name='offline_opd_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='doctor.OfflineOPDAppointments'),
        ),
        migrations.AddField(
            model_name='presccriptionpdf',
            name='opd_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='doctor.OpdAppointment'),
        ),
    ]
