# Generated by Django 2.0.5 on 2019-04-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0009_offlineprescription'),
        ('prescription', '0010_auto_20190430_1722'),
    ]

    operations = [
    ]
