# Generated by Django 2.0.5 on 2019-04-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0011_merge_20190430_1914'),
        ('prescription', '0011_auto_20190430_1941'),
    ]

    operations = [
    ]
