# Generated by Django 2.0.5 on 2019-04-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0012_merge_20190430_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presccriptionpdf',
            name='appointment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Docprime_Opd'), (3, 'OFFline')]),
        ),
        migrations.AlterField(
            model_name='presccriptionpdf',
            name='offline_opd_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eprescription', to='doctor.OfflineOPDAppointments'),
        ),
        migrations.AlterField(
            model_name='presccriptionpdf',
            name='opd_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eprescription', to='doctor.OpdAppointment'),
        ),
    ]
