# Generated by Django 2.0.5 on 2019-05-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0013_auto_20190430_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='instruction',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='dosage_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
