# Generated by Django 2.0.5 on 2019-04-25 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporate_id', models.IntegerField(blank=True, null=True)),
                ('corporate_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('corporate_address', models.CharField(blank=True, max_length=10000, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10000, null=True, verbose_name='PAN no.')),
                ('gst_no', models.CharField(blank=True, max_length=10000, null=True, verbose_name='GST no.')),
                ('corporate_documents', models.FileField(upload_to='corporate_booking', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jfif', 'jpg', 'jpeg', 'png'])])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
