# Generated by Django 2.0.5 on 2019-04-29 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_booking', '0002_auto_20190429_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatebooking',
            name='matrix_city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='citymatrix', to='common.MatrixMappedCity'),
        ),
        migrations.AlterField(
            model_name='corporatebooking',
            name='matrix_state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='statematrix', to='common.MatrixMappedState'),
        ),
    ]
