# Generated by Django 2.0.5 on 2019-05-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_booking', '0003_auto_20190429_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatedeal',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='corporatedeal',
            name='tds_deducted',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=50),
        ),
    ]
