# Generated by Django 2.0.5 on 2019-05-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_merge_20190422_1443'),
        ('corporate_booking', '0004_auto_20190509_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CorporateBooking',
            new_name='Corporates',
        ),
        migrations.RenameField(
            model_name='corporates',
            old_name='corporate_address',
            new_name='building',
        ),
        migrations.AlterField(
            model_name='corporatedeal',
            name='tds_deducted',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=50, verbose_name='TDS deducted'),
        ),
    ]
