# Generated by Django 2.0.5 on 2019-05-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_booking', '0006_auto_20190510_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatedocument',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PAN Card'), (2, 'Address Proof'), (3, 'GST Certificate'), (4, 'Company Registration Certificate'), (5, 'Bank Statement'), (6, 'LOGO'), (7, 'Email Confirmation'), (8, 'Other')]),
        ),
    ]
