# Generated by Django 2.0.5 on 2019-05-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_booking', '0007_auto_20190510_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporatedeal',
            old_name='corporate_id',
            new_name='corporate',
        ),
    ]
