# Generated by Django 2.0.5 on 2019-05-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_booking', '0009_auto_20190516_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatedeal',
            name='service_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
