# Generated by Django 2.0.5 on 2020-01-16 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_booking', '0010_auto_20190516_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('GOLD', 'GOLD'), ('VIP', 'VIP')], max_length=100, null=True)),
            ],
            options={
                'db_table': 'corporate_groups',
            },
        ),
        migrations.AddField(
            model_name='corporates',
            name='corporate_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='corporate_group', to='corporate_booking.CorporateGroup'),
        ),
    ]
