# Generated by Django 2.0.5 on 2020-01-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_booking', '0011_auto_20200116_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporates',
            name='corporate_group',
        ),
    ]
