# Generated by Django 2.0.5 on 2020-01-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_booking', '0012_remove_corporates_corporate_group'),
        ('plus', '0057_auto_20200116_1259'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='CorporateGroup',
        # ),
    ]
