# Generated by Django 2.0.5 on 2020-01-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_booking', '0013_delete_corporategroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorporateGroup',
        ),
    ]
