# Generated by Django 2.0.5 on 2018-11-13 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoElastic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to='demoelastic', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])])),
            ],
            options={
                'db_table': 'demo_elastic',
            },
        ),
    ]
