# Generated by Django 2.0.5 on 2018-11-13 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoelastic',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='demoelastic', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
    ]
