# Generated by Django 2.0.5 on 2018-11-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0002_auto_20181113_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoelastic',
            name='path',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
