# Generated by Django 2.0.5 on 2018-11-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0004_auto_20181116_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoelastic',
            name='mongo_collection',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demoelastic',
            name='mongo_database',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
