# Generated by Django 2.0.5 on 2018-11-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0005_auto_20181116_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoelastic',
            name='mongo_connection_string',
            field=models.CharField(default='', max_length=200),
        ),
    ]
