# Generated by Django 2.0.5 on 2019-02-15 06:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0006_demoelastic_mongo_connection_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoelastic',
            name='elastic_alias',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demoelastic',
            name='elastic_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='demoelastic',
            name='primary_index',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demoelastic',
            name='primary_index_mapping_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='demoelastic',
            name='secondary_index_a',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demoelastic',
            name='secondary_index_b',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demoelastic',
            name='secondary_index_mapping_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='demoelastic',
            name='mongo_collection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demoelastic',
            name='mongo_connection_string',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='demoelastic',
            name='mongo_database',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
