# Generated by Django 2.0.5 on 2019-02-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0007_auto_20190215_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoelastic',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
