# Generated by Django 2.0.5 on 2019-02-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0008_demoelastic_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demoelastic',
            name='file',
        ),
        migrations.RemoveField(
            model_name='demoelastic',
            name='mongo_collection',
        ),
        migrations.RemoveField(
            model_name='demoelastic',
            name='mongo_connection_string',
        ),
        migrations.RemoveField(
            model_name='demoelastic',
            name='mongo_database',
        ),
    ]
