# Generated by Django 2.0.5 on 2019-03-12 13:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0009_auto_20190222_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoelastic',
            name='post_task_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
