# Generated by Django 2.0.5 on 2018-10-08 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_sitemapmanger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='seo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
            ],
            options={
                'db_table': 'robot',
            },
        ),
    ]
