# Generated by Django 2.0.5 on 2018-10-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_robot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemapmanger',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
