# Generated by Django 2.0.5 on 2018-10-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_sitemapmanger_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemapmanger',
            name='count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
