# Generated by Django 2.0.5 on 2018-10-11 14:04

import django.core.validators
from django.db import migrations, models
import ondoc.seo.models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_auto_20181011_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemapmanger',
            name='file',
            field=models.FileField(storage=ondoc.seo.models.OverwriteStorage(), upload_to='seo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])]),
        ),
    ]
