# Generated by Django 2.0.5 on 2018-11-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0118_auto_20181030_1552'),
        ('seo', '0008_seospecialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoLabNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField(default=0, null=True)),
                ('lab', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabNetwork')),
            ],
            options={
                'db_table': 'seo_lab_network',
            },
        ),
    ]
