# Generated by Django 2.0.5 on 2018-11-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0009_seolabnetwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seolabnetwork',
            old_name='lab',
            new_name='lab_network',
        ),
    ]
