# Generated by Django 2.0.5 on 2019-01-07 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0070_auto_20190104_1415'),
        ('seo', '0010_auto_20181105_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=5000)),
                ('content', models.TextField()),
                ('is_enabled', models.BooleanField(default=False)),
                ('url', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.EntityUrls')),
            ],
            options={
                'db_table': 'dynamic',
            },
        ),
    ]
