# Generated by Django 2.0.5 on 2019-01-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0077_merge_20190109_1556'),
        ('seo', '0010_auto_20181105_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('top_content', models.TextField(blank=True)),
                ('bottom_content', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('url', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.EntityUrls')),
            ],
            options={
                'db_table': 'dynamic_url_content',
            },
        ),
    ]
