# Generated by Django 2.0.5 on 2019-01-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0011_newdynamic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdynamic',
            name='content',
        ),
        migrations.AddField(
            model_name='newdynamic',
            name='bottom_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newdynamic',
            name='top_content',
            field=models.TextField(blank=True, verbose_name='search_content'),
        ),
    ]
