# Generated by Django 2.0.5 on 2019-01-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0011_newdynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdynamic',
            name='url_value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newdynamic',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.EntityUrls'),
        ),
    ]
