# Generated by Django 2.0.5 on 2019-01-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0012_auto_20190109_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdynamic',
            name='url',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.EntityUrls'),
        ),
    ]
