# Generated by Django 2.0.5 on 2019-01-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0012_auto_20190108_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdynamic',
            name='title',
        ),
    ]
