# Generated by Django 2.0.5 on 2019-01-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0013_remove_newdynamic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdynamic',
            name='top_content',
            field=models.TextField(blank=True),
        ),
    ]
