# Generated by Django 2.0.5 on 2019-01-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0013_auto_20190111_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdynamic',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='newdynamic',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
