# Generated by Django 2.0.5 on 2019-01-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0014_auto_20190108_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newdynamic',
            old_name='url',
            new_name='aabb',
        ),
    ]
