# Generated by Django 2.0.5 on 2019-01-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0015_auto_20190109_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newdynamic',
            old_name='aabb',
            new_name='url',
        ),
    ]
