# Generated by Django 2.0.5 on 2019-07-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0015_auto_20190503_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdynamic',
            name='h1_title',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
