# Generated by Django 2.0.2 on 2018-04-19 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lab',
            table='lab',
        ),
        migrations.AlterModelTable(
            name='labmanager',
            table='lab_manager',
        ),
        migrations.AlterModelTable(
            name='pathologytesttype',
            table='pathology_test_type',
        ),
        migrations.AlterModelTable(
            name='radiologytesttype',
            table='radiology_test_type',
        ),
    ]
