# Generated by Django 2.0.2 on 2018-04-19 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0002_auto_20180419_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOnboardingToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Generated'), (2, 'Rejected'), (3, 'Consumed')])),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.Lab')),
            ],
            options={
                'db_table': 'lab_onboarding_token',
            },
        ),
    ]
