# Generated by Django 2.0.2 on 2018-04-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0003_labonboardingtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='labonboardingtoken',
            name='verified_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
