# Generated by Django 2.0.2 on 2018-04-19 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0004_labonboardingtoken_verified_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lab',
            name='primary_mobile',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
