# Generated by Django 2.0.4 on 2018-04-23 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0005_auto_20180419_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcertification',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_certificates', to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='labonboardingtoken',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Generated'), (2, 'Rejected'), (3, 'Consumed')], default=1),
        ),
    ]
