# Generated by Django 2.0.2 on 2018-04-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0005_auto_20180419_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLabService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.Lab')),
            ],
            options={
                'db_table': 'active_lab_service',
            },
        ),
        migrations.CreateModel(
            name='LabDoctorAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_male_available', models.BooleanField(verbose_name='Male')),
                ('is_female_available', models.BooleanField(verbose_name='Female')),
                ('slot', models.CharField(choices=[('m', 'Morning'), ('e', 'Evening')], max_length=2)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.Lab')),
            ],
            options={
                'db_table': 'lab_doctor_availibility',
            },
        ),
        migrations.CreateModel(
            name='LabDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField(editable=False)),
                ('height', models.PositiveSmallIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.PositiveSmallIntegerField(choices=[('1', 'Pan card'), ('2', 'Address Proof'), ('3', 'GST Certificate'), ('4', 'Registration Certificate'), ('5', 'Cancel Cheque Copy')])),
                ('name', models.ImageField(height_field='height', upload_to='lab/images', width_field='width')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.Lab')),
            ],
            options={
                'db_table': 'lab_document',
            },
        ),
        migrations.CreateModel(
            name='LabService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'lab_service',
            },
        ),
        migrations.AlterField(
            model_name='labcertification',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_certificates', to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='labonboardingtoken',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Generated'), (2, 'Rejected'), (3, 'Consumed')], default=1),
        ),
        migrations.AddField(
            model_name='activelabservice',
            name='lab_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabService'),
        ),
        migrations.AlterUniqueTogether(
            name='activelabservice',
            unique_together={('lab', 'lab_service')},
        ),
    ]
