# Generated by Django 2.0.2 on 2018-04-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0007_auto_20180423_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labservice',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pathology'), (2, 'Radiology')], max_length=2),
        ),
    ]
