# Generated by Django 2.0.2 on 2018-04-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0008_auto_20180423_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labservice',
            name='name',
        ),
        migrations.AddField(
            model_name='labservice',
            name='service',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pathology'), (2, 'Radiology')], default=None),
        ),
    ]
