# Generated by Django 2.0.2 on 2018-04-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0009_auto_20180423_1656'),
        ('diagnostic', '0006_auto_20180423_1201'),
    ]

    operations = [
    ]
