# Generated by Django 2.0.2 on 2018-04-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0010_merge_20180423_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='labservice',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Is this Service Available?'),
        ),
        migrations.AlterField(
            model_name='labdoctoravailability',
            name='is_female_available',
            field=models.BooleanField(default=False, verbose_name='Female'),
        ),
        migrations.AlterField(
            model_name='labdoctoravailability',
            name='is_male_available',
            field=models.BooleanField(default=False, verbose_name='Male'),
        ),
        migrations.AlterField(
            model_name='labdoctoravailability',
            name='slot',
            field=models.CharField(choices=[[('m', 'Morning'), ('e', 'Evening')]], max_length=2),
        ),
        migrations.AlterModelTable(
            name='labdoctoravailability',
            table='lab_doctor_availability',
        ),
    ]
