# Generated by Django 2.0.2 on 2018-04-24 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0011_auto_20180424_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(max_length=100)),
                ('lab', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.Lab')),
            ],
            options={
                'db_table': 'lab_doctor',
            },
        ),
        migrations.AlterField(
            model_name='labdoctoravailability',
            name='slot',
            field=models.CharField(choices=[('m', 'Morning'), ('e', 'Evening')], max_length=2),
        ),
    ]
