# Generated by Django 2.0.2 on 2018-04-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0012_auto_20180424_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labservice',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='labdocument',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PAN Card'), (2, 'Address Proof'), (3, 'GST Certificate'), (4, 'Registration Certificate'), (5, 'Cancel Cheque Copy')]),
        ),
    ]
