# Generated by Django 2.0.2 on 2018-04-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0017_auto_20180430_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lab',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lab',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
