# Generated by Django 2.0.2 on 2018-04-30 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0018_auto_20180430_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='agreed_rate_list',
            field=models.FileField(blank=True, null=True, upload_to='lab/docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='labcertification',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_certificate', to='diagnostic.Lab'),
        ),
    ]
