# Generated by Django 2.0.2 on 2018-05-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0021_auto_20180502_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labdocument',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='labdocument',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='labimage',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='labimage',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
