# Generated by Django 2.0.2 on 2018-05-07 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0022_auto_20180502_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='agreed_rate_list',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='lab/docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
