# Generated by Django 2.0.2 on 2018-05-07 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0024_auto_20180507_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableLabTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mrp', models.PositiveSmallIntegerField()),
                ('agreed_price', models.PositiveSmallIntegerField()),
                ('deal_price', models.PositiveSmallIntegerField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabletests', to='diagnostic.Lab')),
            ],
            options={
                'db_table': 'available_lab_test',
            },
        ),
        migrations.CreateModel(
            name='CommonDiagnosticCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'common_diagnostic_condition',
            },
        ),
        migrations.CreateModel(
            name='CommonTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('is_package', models.BooleanField(verbose_name='Is this test package type?')),
                ('why', models.CharField(blank=True, max_length=1000)),
                ('pre_test_info', models.CharField(blank=True, max_length=1000)),
                ('sample_handling_instructions', models.CharField(blank=True, max_length=1000)),
                ('sample_collection_instructions', models.CharField(blank=True, max_length=1000)),
                ('preferred_time', models.CharField(blank=True, max_length=1000)),
                ('sample_amount', models.CharField(blank=True, max_length=1000)),
                ('expected_tat', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'lab_test',
            },
        ),
        migrations.CreateModel(
            name='LabTestSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'lab_test_sub_type',
            },
        ),
        migrations.CreateModel(
            name='LabTestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'lab_test_type',
            },
        ),
        migrations.CreateModel(
            name='PromotedLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.Lab')),
            ],
            options={
                'db_table': 'promoted_lab',
            },
        ),
        migrations.RemoveField(
            model_name='pathologytest',
            name='test_sub_type',
        ),
        migrations.RemoveField(
            model_name='pathologytest',
            name='test_type',
        ),
        migrations.RemoveField(
            model_name='radiologytest',
            name='test_sub_type',
        ),
        migrations.RemoveField(
            model_name='radiologytest',
            name='test_type',
        ),
        migrations.DeleteModel(
            name='PathologyTest',
        ),
        migrations.DeleteModel(
            name='PathologyTestType',
        ),
        migrations.DeleteModel(
            name='RadiologyTest',
        ),
        migrations.DeleteModel(
            name='RadiologyTestType',
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_sub_type', to='diagnostic.LabTestSubType'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_type', to='diagnostic.LabTestType'),
        ),
        migrations.AddField(
            model_name='commontest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commontest', to='diagnostic.LabTest'),
        ),
        migrations.AddField(
            model_name='availablelabtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availablelabs', to='diagnostic.LabTest'),
        ),
    ]
