# Generated by Django 2.0.5 on 2018-05-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20180430_1616'),
        ('diagnostic', '0025_auto_20180507_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('price', models.PositiveSmallIntegerField()),
                ('time_slot_start', models.DateTimeField(blank=True, null=True)),
                ('time_slot_end', models.DateTimeField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labappointment', to='diagnostic.Lab')),
                ('lab_test', models.ManyToManyField(to='diagnostic.AvailableLabTest')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labappointments', to='authentication.UserProfile')),
            ],
            options={
                'db_table': 'lab_appointment',
            },
        ),
    ]
