# Generated by Django 2.0.2 on 2018-05-12 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0025_auto_20180507_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labdocument',
            name='height',
        ),
        migrations.RemoveField(
            model_name='labdocument',
            name='width',
        ),
        migrations.AlterField(
            model_name='labdocument',
            name='name',
            field=models.FileField(upload_to='lab/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
