# Generated by Django 2.0.5 on 2018-05-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0026_labappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtiming',
            name='pickup_flag',
            field=models.BooleanField(default=False),
        ),
    ]
