# Generated by Django 2.0.5 on 2018-05-24 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0027_labtiming_pickup_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondiagnosticcondition',
            name='test',
            field=models.ManyToManyField(to='diagnostic.LabTest'),
        ),
        migrations.AlterField(
            model_name='labimage',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_image', to='diagnostic.Lab'),
        ),
    ]
