# Generated by Django 2.0.2 on 2018-05-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0028_auto_20180517_1212'),
        ('diagnostic', '0027_labtiming_pickup_flag'),
    ]

    operations = [
    ]
