# Generated by Django 2.0.5 on 2018-05-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0028_auto_20180524_1107'),
        ('diagnostic', '0029_merge_20180525_2024'),
    ]

    operations = [
    ]
