# Generated by Django 2.0.5 on 2018-06-02 07:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0030_merge_20180528_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointment',
            name='profile_detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
