# Generated by Django 2.0.5 on 2018-06-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0031_lab_is_ppc_pathology_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='is_ppc_radiology_enabled',
            field=models.BooleanField(default=False, verbose_name='Enabled for Radiology Pre Policy Checkup'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='is_ppc_pathology_enabled',
            field=models.BooleanField(default=False, verbose_name='Enabled for Pathology Pre Policy Checkup'),
        ),
    ]
