# Generated by Django 2.0.2 on 2018-06-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0031_labappointment_profile_detail'),
        ('diagnostic', '0032_auto_20180602_1158'),
    ]

    operations = [
    ]
