# Generated by Django 2.0.5 on 2018-06-05 09:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0034_auto_20180605_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointment',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labappointment',
            name='is_home_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
