# Generated by Django 2.0.5 on 2018-06-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0035_auto_20180605_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointment',
            name='agreed_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='labappointment',
            name='deal_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='labappointment',
            name='effective_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='labappointment',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
