# Generated by Django 2.0.5 on 2018-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0035_auto_20180605_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='test_sub_type',
        ),
        migrations.AddField(
            model_name='labtest',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='labtest',
            name='excel_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
