# Generated by Django 2.0.5 on 2018-06-13 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0036_auto_20180613_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestSubTypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'labtest_subtype_mapping',
            },
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='test_type',
        ),
        migrations.AddField(
            model_name='labtestsubtypemapping',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabTest'),
        ),
        migrations.AddField(
            model_name='labtestsubtypemapping',
            name='test_sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabTestSubType'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_sub_type',
            field=models.ManyToManyField(through='diagnostic.LabTestSubTypeMapping', to='diagnostic.LabTestSubType'),
        ),
    ]
