# Generated by Django 2.0.5 on 2018-06-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0037_auto_20180613_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='test_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Radiology'), (2, 'Pathology')], null=True),
        ),
    ]
