# Generated by Django 2.0.5 on 2018-06-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0039_auto_20180614_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestsubtype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
