# Generated by Django 2.0.5 on 2018-06-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0036_auto_20180618_1458'),
        ('diagnostic', '0040_auto_20180614_1308'),
    ]

    operations = [
    ]
