# Generated by Django 2.0.6 on 2018-06-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0040_auto_20180614_1308'),
        ('diagnostic', '0036_auto_20180618_1458'),
    ]

    operations = [
    ]
