# Generated by Django 2.0.6 on 2018-06-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0041_merge_20180619_1156'),
        ('diagnostic', '0041_merge_20180618_1756'),
    ]

    operations = [
    ]
