# Generated by Django 2.0.5 on 2018-06-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0042_auto_20180622_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='radiology_agreed_price_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='radiology_deal_price_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True),
        ),
    ]
