# Generated by Django 2.0.6 on 2018-06-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0043_labappointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointment',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Prepaid'), (2, 'COD'), (3, 'Insurance')], default=1),
        ),
        migrations.AlterField(
            model_name='availablelabtest',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='availablelabtest',
            name='deal_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='availablelabtest',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='labappointment',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='labappointment',
            name='deal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='labappointment',
            name='effective_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='labappointment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
