# Generated by Django 2.0.5 on 2018-06-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0044_auto_20180622_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablelabtest',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
