# Generated by Django 2.0.6 on 2018-06-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
        ('diagnostic', '0044_auto_20180625_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointment',
            name='insurance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.Insurance'),
        ),
    ]
