# Generated by Django 2.0.2 on 2018-06-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0046_auto_20180622_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestsubtypemapping',
            name='lab_test',
        ),
        migrations.RemoveField(
            model_name='labtestsubtypemapping',
            name='test_sub_type',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='test_sub_type',
        ),
        migrations.AddField(
            model_name='labtest',
            name='sample_type',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='LabTestSubTypeMapping',
        ),
    ]
