# Generated by Django 2.0.2 on 2018-06-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0047_auto_20180625_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='home_collection_possible',
            field=models.BooleanField(default=False, verbose_name='Can sample be home collected for this test?'),
        ),
    ]
