# Generated by Django 2.0.2 on 2018-06-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0048_labtest_home_collection_possible'),
        ('diagnostic', '0048_agreed_price_calc'),
    ]

    operations = [
    ]
