# Generated by Django 2.0.2 on 2018-06-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0049_merge_20180625_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPricing',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('diagnostic.lab',),
        ),
    ]
