# Generated by Django 2.0.2 on 2018-06-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0050_labpricing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labpricing',
            options={'default_permissions': []},
        ),
    ]
