# Generated by Django 2.0.6 on 2018-06-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0045_labappointment_insurance'),
        ('diagnostic', '0050_auto_20180627_1735'),
    ]

    operations = [
    ]
