# Generated by Django 2.0.6 on 2018-06-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0051_merge_20180628_1110'),
    ]

    operations = [

        migrations.AlterField(
            model_name='availablelabtest',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
