# Generated by Django 2.0.2 on 2018-06-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0050_auto_20180627_1735'),
        ('diagnostic', '0051_auto_20180628_1916'),
    ]

    operations = [
    ]
