# Generated by Django 2.0.2 on 2018-06-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0052_auto_20180628_1917'),
        ('diagnostic', '0052_merge_20180629_1905'),
    ]

    operations = [
    ]
