# Generated by Django 2.0.2 on 2018-06-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0053_merge_20180630_1827'),
    ]

    operations = [
            migrations.AlterField(
            model_name='availablelabtest',
            name='computed_agreed_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='availablelabtest',
            name='computed_deal_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='availablelabtest',
            name='computed_agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='availablelabtest',
            name='computed_deal_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
