# Generated by Django 2.0.5 on 2018-07-03 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnostic', '0054_auto_20180630_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lab', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labnetwork',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lab_networks', to=settings.AUTH_USER_MODEL),
        ),
    ]
