# Generated by Django 2.0.6 on 2018-07-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0055_labappointment_outstanding'),
        ('diagnostic', '0057_auto_20180706_1522'),
    ]

    operations = [
    ]
