# Generated by Django 2.0.5 on 2018-07-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0059_labpricinggroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablelabtest',
            name='lab_pricing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.LabPricingGroup'),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_pricing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.LabPricingGroup'),
        ),
    ]
