# Generated by Django 2.0.5 on 2018-07-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0059_lab_search_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='search_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
