# Generated by Django 2.0.5 on 2018-07-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0060_labtest_search_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticConditionLabTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'diagnostic_condition_labtest',
            },
        ),
        migrations.RemoveField(
            model_name='commondiagnosticcondition',
            name='test',
        ),
        migrations.AddField(
            model_name='diagnosticconditionlabtest',
            name='diagnostic_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.CommonDiagnosticCondition'),
        ),
        migrations.AddField(
            model_name='diagnosticconditionlabtest',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabTest'),
        ),
        migrations.AddField(
            model_name='commondiagnosticcondition',
            name='lab_test',
            field=models.ManyToManyField(through='diagnostic.DiagnosticConditionLabTest', to='diagnostic.LabTest'),
        ),
    ]
