# Generated by Django 2.0.5 on 2018-07-12 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0061_auto_20180712_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablelabtest',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabletests', to='diagnostic.Lab'),
        ),
    ]
