# Generated by Django 2.0.5 on 2018-07-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0061_auto_20180716_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='Is Live'),
        ),
    ]
