# Generated by Django 2.0.5 on 2018-07-12 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0063_labtestpricinggroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablelabtest',
            name='lab_pricing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='available_lab_tests', to='diagnostic.LabPricingGroup'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_pricing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='diagnostic.LabPricingGroup'),
        ),
    ]
