# Generated by Django 2.0.6 on 2018-07-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0063_auto_20180724_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtiming',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_timings', to='diagnostic.Lab'),
        ),
    ]
