# Generated by Django 2.0.5 on 2018-07-27 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0064_auto_20180724_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablelabtest',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availabletests', to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='availablelabtest',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availablelabs', to='diagnostic.LabTest'),
        ),
        migrations.AlterField(
            model_name='commontest',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commontest', to='diagnostic.LabTest'),
        ),
        migrations.AlterField(
            model_name='diagnosticconditionlabtest',
            name='diagnostic_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.CommonDiagnosticCondition'),
        ),
        migrations.AlterField(
            model_name='diagnosticconditionlabtest',
            name='lab_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.LabTest'),
        ),
        migrations.AlterField(
            model_name='labaccreditation',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='labappointment',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labappointment', to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='labappointment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labappointments', to='authentication.UserProfile'),
        ),
        migrations.AlterField(
            model_name='labappointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labaward',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='labcertification',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_certificate', to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='labdoctor',
            name='lab',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='labdoctoravailability',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='labdocument',
            name='lab',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='labimage',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_image', to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='labmanager',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='labnetworkaccreditation',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.LabNetwork'),
        ),
        migrations.AlterField(
            model_name='labnetworkaward',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.LabNetwork'),
        ),
        migrations.AlterField(
            model_name='labnetworkcertification',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.LabNetwork'),
        ),
        migrations.AlterField(
            model_name='labnetworkemail',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.LabNetwork'),
        ),
        migrations.AlterField(
            model_name='labnetworkhelpline',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.LabNetwork'),
        ),
        migrations.AlterField(
            model_name='labnetworkmanager',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.LabNetwork'),
        ),
        migrations.AlterField(
            model_name='labservice',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='labtiming',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_timings', to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='promotedlab',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.Lab'),
        ),
    ]
