# Generated by Django 2.0.6 on 2018-07-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0064_auto_20180724_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='is_home_collection_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
