# Generated by Django 2.0.6 on 2018-07-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0065_lab_is_home_collection_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtiming',
            old_name='pickup_flag',
            new_name='for_home_pickup',
        ),
    ]
