# Generated by Django 2.0.2 on 2018-07-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0068_auto_20180730_1255'),
        ('diagnostic', '0064_auto_20180712_1556'),
    ]

    operations = [
    ]
