# Generated by Django 2.0.2 on 2018-08-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0069_merge_20180730_1725'),
        ('diagnostic', '0065_auto_20180727_1126'),
    ]

    operations = [
    ]
