# Generated by Django 2.0.7 on 2018-08-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0069_merge_20180730_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labappointment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Booked'), (3, 'Rescheduled by lab'), (4, 'Rescheduled by patient'), (5, 'Accepted'), (6, 'Cancelled'), (7, 'Completed')], default=1),
        ),
    ]
