# Generated by Django 2.0.5 on 2018-08-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0070_auto_20180802_1403'),
        ('diagnostic', '0071_auto_20180802_1151'),
    ]

    operations = [
    ]
