# Generated by Django 2.0.5 on 2018-08-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0072_merge_20180807_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='is_test_doctor',
            field=models.BooleanField(default=False, verbose_name='Is Test Lab'),
        ),
    ]
