# Generated by Django 2.0.5 on 2018-08-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0073_lab_is_test_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='is_test_doctor',
            new_name='is_test_lab',
        ),
    ]
