# Generated by Django 2.0.2 on 2018-08-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0074_auto_20180809_1627'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availablelabtest',
            unique_together={('test', 'lab_pricing_group')},
        ),
    ]
