# Generated by Django 2.0.6 on 2018-08-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0075_auto_20180811_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='is_home_pickup_available',
        ),
    ]
