# Generated by Django 2.0.7 on 2018-08-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0075_auto_20180811_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription_details', models.TextField(blank=True, max_length=300, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabAppointment')),
            ],
            options={
                'db_table': 'lab_prescription',
            },
        ),
        migrations.CreateModel(
            name='LabPrescriptionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.FileField(upload_to='lab_prescriptions/')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabPrescription')),
            ],
            options={
                'db_table': 'lab_prescription_file',
            },
        ),
    ]
