# Generated by Django 2.0.7 on 2018-08-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0076_labprescription_labprescriptionfile'),
        ('diagnostic', '0076_remove_lab_is_home_pickup_available'),
    ]

    operations = [
    ]
