# Generated by Django 2.0.7 on 2018-08-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0077_labappointment_home_pickup_charges'),
        ('diagnostic', '0077_merge_20180814_1701'),
    ]

    operations = [
    ]
