# Generated by Django 2.0.5 on 2018-08-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0077_labappointment_home_pickup_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontest',
            name='icon',
            field=models.ImageField(null=True, upload_to='diagnostic/common_test_icons'),
        ),
    ]
