# Generated by Django 2.0.6 on 2018-08-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0078_merge_20180816_1737'),
        ('diagnostic', '0078_commontest_icon'),
    ]

    operations = [
    ]
