# Generated by Django 2.0.5 on 2018-08-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0079_merge_20180821_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.FileField(upload_to='lab_prescriptions/')),
            ],
            options={
                'db_table': 'lab_report_file',
            },
        ),
        migrations.RenameModel(
            old_name='LabPrescription',
            new_name='LabReport',
        ),
        migrations.RemoveField(
            model_name='labprescriptionfile',
            name='prescription',
        ),
        migrations.RenameField(
            model_name='labreport',
            old_name='prescription_details',
            new_name='report_details',
        ),
        migrations.AlterModelTable(
            name='labreport',
            table='lab_report',
        ),
        migrations.DeleteModel(
            name='LabPrescriptionFile',
        ),
    ]
