# Generated by Django 2.0.5 on 2018-08-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0080_auto_20180821_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreportfile',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.LabReport'),
        ),
        migrations.AlterField(
            model_name='labreportfile',
            name='name',
            field=models.FileField(upload_to='lab_reports/'),
        ),
    ]
