# Generated by Django 2.0.5 on 2018-08-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0081_auto_20180821_1232'),
        ('diagnostic', '0078_labappointment_cancellation_type'),
    ]

    operations = [
    ]
