# Generated by Django 2.0.5 on 2018-08-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diagnostic', '0082_merge_20180821_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePickupCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_pickup_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distance', models.PositiveIntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
