# Generated by Django 2.0.5 on 2018-09-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0083_homepickupcharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='live_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
