# Generated by Django 2.0.5 on 2018-09-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0084_auto_20180904_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='qc_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labnetwork',
            name='qc_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
