# Generated by Django 2.0.5 on 2018-09-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0084_labappointment_matrix_lead_id'),
        ('diagnostic', '0085_auto_20180904_1457'),
    ]

    operations = [
    ]
