# Generated by Django 2.1 on 2018-09-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0086_merge_20180904_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='diagnostic.LabTest')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='diagnostic.LabTest')),
            ],
            options={
                'db_table': 'labtest_package',
            },
        ),
    ]
