# Generated by Django 2.1 on 2018-09-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0087_labtestpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='test',
            field=models.ManyToManyField(through='diagnostic.LabTestPackage', to='diagnostic.LabTest'),
        ),
    ]
