# Generated by Django 2.0.5 on 2018-09-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0087_auto_20180913_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Is Enabled'),
        ),
    ]
