# Generated by Django 2.0.5 on 2018-09-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0090_auto_20180911_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='test_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Radiology'), (2, 'Pathology'), (3, 'Other')], null=True),
        ),
    ]
