# Generated by Django 2.0.5 on 2018-09-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0092_auto_20180911_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='number_of_tests',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
