# Generated by Django 2.0.5 on 2018-09-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0088_lab_enabled'),
        ('diagnostic', '0093_labtest_number_of_tests'),
    ]

    operations = [
    ]
