# Generated by Django 2.0.5 on 2018-09-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0089_auto_20180914_1654'),
        ('diagnostic', '0094_merge_20180914_1639'),
    ]

    operations = [
    ]
