# Generated by Django 2.0.5 on 2018-09-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0096_auto_20180917_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='parameter',
            field=models.ManyToManyField(through='diagnostic.ParameterLabTest', to='diagnostic.TestParameter'),
        ),
    ]
