# Generated by Django 2.0.5 on 2018-09-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0098_auto_20180917_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testparameter',
            name='lab_test',
        ),
    ]
