# Generated by Django 2.0.5 on 2018-09-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0099_remove_testparameter_lab_test'),
        ('diagnostic', '0096_auto_20180917_1609'),
    ]

    operations = [
    ]
