# Generated by Django 2.0.5 on 2018-09-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0100_merge_20180918_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Radiology'), (2, 'Pathology'), (3, 'Other')])),
                ('tests', models.ManyToManyField(to='diagnostic.LabTest')),
            ],
            options={
                'db_table': 'lab_test_group',
            },
        ),
    ]
