# Generated by Django 2.0.5 on 2018-10-11 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0102_labtest_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointment',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labappointment',
            name='rating_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='labappointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
