# Generated by Django 2.0.5 on 2018-10-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0102_labtest_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='approximate_duration',
            field=models.CharField(default='15 mins', max_length=50, verbose_name='What is the approximate duration for the test?'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='enable_for_ppc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtest',
            name='enable_for_retail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtest',
            name='report_schedule',
            field=models.CharField(default='After 2 days of test.', max_length=150, verbose_name='What is the report schedule for the test?'),
        ),
    ]
