# Generated by Django 2.0.5 on 2018-10-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0102_labtest_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
