# Generated by Django 2.0.5 on 2018-10-04 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('diagnostic', '0102_labtest_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.Coupon'),
        ),
    ]
