# Generated by Django 2.0.5 on 2018-10-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0103_auto_20181011_1422'),
        ('diagnostic', '0103_auto_20181017_1404'),
    ]

    operations = [
    ]
