# Generated by Django 2.0.5 on 2018-10-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0103_auto_20181017_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='dayend_booking_threshold_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
