# Generated by Django 2.0.5 on 2018-10-24 10:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0104_lab_dayend_booking_threshold_hours'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='labpricinggroup',
            managers=[
                ('timing_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
