# Generated by Django 2.0.5 on 2018-10-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0105_labappointment_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labappointment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
