# Generated by Django 2.0.5 on 2018-10-24 10:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0105_auto_20181024_1545'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='labpricinggroup',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='labtiming',
            managers=[
                ('timing_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
