# Generated by Django 2.0.5 on 2018-10-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0106_auto_20181024_1552'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='labtiming',
            managers=[
            ],
        ),
    ]
