# Generated by Django 2.0.5 on 2018-10-25 07:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0107_auto_20181024_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='dayend_booking_threshold_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
