# Generated by Django 2.0.5 on 2018-10-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0107_auto_20181005_1843'),
        ('diagnostic', '0103_commonpackage'),
    ]

    operations = [
    ]
