# Generated by Django 2.0.5 on 2018-10-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0103_auto_20181017_1404'),
        ('diagnostic', '0108_merge_20181017_1407'),
    ]

    operations = [
    ]
