# Generated by Django 2.0.5 on 2018-10-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0109_merge_20181017_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='order_priority',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
