# Generated by Django 2.0.5 on 2018-10-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0104_merge_20181018_1136'),
        ('diagnostic', '0110_lab_order_priority'),
    ]

    operations = [
    ]
