# Generated by Django 2.0.5 on 2018-10-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0110_lab_order_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtiming',
            name='end',
            field=models.DecimalField(choices=[(5.0, '5 AM'), (5.5, '5:30 AM'), (6.0, '6 AM'), (6.5, '6:30 AM'), (7.0, '7 AM'), (7.5, '7:30 AM'), (8.0, '8 AM'), (8.5, '8:30 AM'), (9.0, '9 AM'), (9.5, '9:30 AM'), (10.0, '10 AM'), (10.5, '10:30 AM'), (11.0, '11 AM'), (11.5, '11:30 AM'), (12.0, '12 PM'), (12.5, '12:30 PM'), (13.0, '1 PM'), (13.5, '1:30 PM'), (14.0, '2 PM'), (14.5, '2:30 PM'), (15.0, '3 PM'), (15.5, '3:30 PM'), (16.0, '4 PM'), (16.5, '4:30 PM'), (17.0, '5 PM'), (17.5, '5:30 PM'), (18.0, '6 PM'), (18.5, '6:30 PM'), (19.0, '7 PM'), (19.5, '7:30 PM'), (20.0, '8 PM'), (20.5, '8:30 PM'), (21.0, '9 PM'), (21.5, '9:30 PM'), (22.0, '10 PM'), (22.5, '10:30 PM'), (23.0, '11 PM'), (23.5, '11:30 PM')], decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='labtiming',
            name='start',
            field=models.DecimalField(choices=[(5.0, '5 AM'), (5.5, '5:30 AM'), (6.0, '6 AM'), (6.5, '6:30 AM'), (7.0, '7 AM'), (7.5, '7:30 AM'), (8.0, '8 AM'), (8.5, '8:30 AM'), (9.0, '9 AM'), (9.5, '9:30 AM'), (10.0, '10 AM'), (10.5, '10:30 AM'), (11.0, '11 AM'), (11.5, '11:30 AM'), (12.0, '12 PM'), (12.5, '12:30 PM'), (13.0, '1 PM'), (13.5, '1:30 PM'), (14.0, '2 PM'), (14.5, '2:30 PM'), (15.0, '3 PM'), (15.5, '3:30 PM'), (16.0, '4 PM'), (16.5, '4:30 PM'), (17.0, '5 PM'), (17.5, '5:30 PM'), (18.0, '6 PM'), (18.5, '6:30 PM'), (19.0, '7 PM'), (19.5, '7:30 PM'), (20.0, '8 PM'), (20.5, '8:30 PM'), (21.0, '9 PM'), (21.5, '9:30 PM'), (22.0, '10 PM'), (22.5, '10:30 PM'), (23.0, '11 PM'), (23.5, '11:30 PM')], decimal_places=1, max_digits=3),
        ),
    ]
