# Generated by Django 2.0.5 on 2018-10-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0111_auto_20181026_1247'),
        ('diagnostic', '0111_auto_20181026_1105'),
    ]

    operations = [
    ]
