# Generated by Django 2.0.5 on 2018-10-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0111_merge_20181024_1459'),
        ('diagnostic', '0109_auto_20181025_1438'),
    ]

    operations = [
    ]
