# Generated by Django 2.0.5 on 2018-11-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0113_auto_20181026_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labappointment',
            name='coupon',
            field=models.ManyToManyField(blank=True, null=True, related_name='lab_appointment_coupon', to='coupon.Coupon'),
        ),
    ]
