# Generated by Django 2.0.5 on 2018-10-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0113_auto_20181026_1932'),
        ('diagnostic', '0112_merge_20181026_1705'),
    ]

    operations = [
    ]
