# Generated by Django 2.0.5 on 2018-10-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0104_auto_20181011_1547'),
        ('diagnostic', '0114_merge_20181026_2055'),
    ]

    operations = [
    ]
