# Generated by Django 2.0.5 on 2018-10-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0115_merge_20181029_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='priority',
        ),
    ]
