# Generated by Django 2.0.5 on 2018-11-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0118_auto_20181030_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='rank',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
