# Generated by Django 2.0.5 on 2018-11-16 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0118_auto_20181030_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterlabtest',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labtests', to='diagnostic.LabTest'),
        ),
        migrations.AlterField(
            model_name='parameterlabtest',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_parameters', to='diagnostic.TestParameter'),
        ),
    ]
