# Generated by Django 2.0.5 on 2018-11-27 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0119_auto_20181116_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_key', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('is_live', models.BooleanField(default=False)),
                ('is_package_category', models.BooleanField(verbose_name='Is this a test package category?')),
                ('preferred_lab_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_in_lab_test_category', to='diagnostic.LabTest')),
            ],
            options={
                'db_table': 'lab_test_category',
            },
        ),
        migrations.CreateModel(
            name='LabTestCategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_lab_test_category_mappings', to='diagnostic.LabTest')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_mappings', to='diagnostic.LabTestCategory')),
            ],
            options={
                'db_table': 'lab_test_to_category_mapping',
            },
        ),
        migrations.AlterField(
            model_name='labreportfile',
            name='name',
            field=models.FileField(upload_to='lab_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jfif', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='labtest',
            name='categories',
            field=models.ManyToManyField(related_name='lab_tests', through='diagnostic.LabTestCategoryMapping', to='diagnostic.LabTestCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='labtestcategorymapping',
            unique_together={('lab_test', 'parent_category')},
        ),
    ]
