# Generated by Django 2.0.5 on 2018-11-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0119_auto_20181116_1202'),
        ('diagnostic', '0114_auto_20181113_1137'),
    ]

    operations = [
    ]
