# Generated by Django 2.0.5 on 2018-11-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0119_auto_20181116_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='about_test',
            field=models.TextField(blank=True, verbose_name='About the test'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='preparations',
            field=models.TextField(blank=True, verbose_name='Preparations for the test'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_may_include',
            field=models.TextField(blank=True, verbose_name='This test may include'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='why_get_tested',
            field=models.TextField(blank=True, verbose_name='Why get tested?'),
        ),
    ]
