# Generated by Django 2.0.5 on 2018-11-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0120_auto_20181127_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestcategorymapping',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
