# Generated by Django 2.0.5 on 2018-11-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0119_auto_20181128_1208'),
        ('diagnostic', '0120_auto_20181127_2029'),
    ]

    operations = [
    ]
