# Generated by Django 2.0.5 on 2018-11-20 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0120_auto_20181120_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(null=True, verbose_name='Answer')),
            ],
            options={
                'db_table': 'question_answer',
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='faq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_answers', to='diagnostic.QuestionAnswer'),
        ),
    ]
