# Generated by Django 2.0.5 on 2018-11-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0121_labtest_is_corporate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtest',
            old_name='is_corporate',
            new_name='hide_price',
        ),
        migrations.AddField(
            model_name='labtest',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
    ]
