# Generated by Django 2.0.5 on 2018-11-28 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0121_merge_20181128_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='diagnostic.LabAppointment'),
        ),
        migrations.AlterField(
            model_name='labreportfile',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='diagnostic.LabReport'),
        ),
    ]
