# Generated by Django 2.0.5 on 2018-11-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0122_auto_20181120_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='frequently_booked_together',
            field=models.ManyToManyField(related_name='related_tests', to='diagnostic.LabTest'),
        ),
    ]
