# Generated by Django 2.0.5 on 2018-11-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0121_labtestcategorymapping_is_primary'),
        ('diagnostic', '0122_auto_20181128_1547'),
    ]

    operations = [
    ]
