# Generated by Django 2.0.5 on 2018-11-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0122_auto_20181126_1156'),
        ('diagnostic', '0120_auto_20181128_1104'),
    ]

    operations = [
    ]
