# Generated by Django 2.0.5 on 2018-11-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0122_auto_20181128_1547'),
        ('diagnostic', '0121_merge_20181128_1247'),
    ]

    operations = [
    ]
