# Generated by Django 2.0.5 on 2018-11-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0123_labtest_frequently_booked_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='frequently_booked_together',
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test',
            field=models.ManyToManyField(related_name='package_test', through='diagnostic.LabTestPackage', to='diagnostic.LabTest'),
        ),
    ]
