# Generated by Django 2.0.5 on 2018-11-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0124_merge_20181129_1830'),
        ('diagnostic', '0123_merge_20181128_1645'),
    ]

    operations = [
    ]
