# Generated by Django 2.0.5 on 2018-12-04 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_auto_20181204_1550'),
        ('diagnostic', '0124_merge_20181129_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointment',
            name='merchant_payout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_appointment', to='account.MerchantPayout'),
        ),
    ]
