# Generated by Django 2.0.5 on 2018-11-21 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0124_auto_20181121_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAddedTogetherTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_together_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_together', to='diagnostic.LabTest')),
                ('original_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_test', to='diagnostic.LabTest')),
            ],
            options={
                'db_table': 'related_tests',
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='frequently_booked_together',
            field=models.ManyToManyField(related_name='frequent_test', through='diagnostic.FrequentlyAddedTogetherTests', to='diagnostic.LabTest'),
        ),
    ]
