# Generated by Django 2.0.5 on 2018-12-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0125_merge_20181204_1357'),
        ('diagnostic', '0125_merge_20181130_0915'),
    ]

    operations = [
    ]
