# Generated by Django 2.0.5 on 2018-12-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0124_merge_20181129_1237'),
        ('diagnostic', '0125_merge_20181204_1357'),
    ]

    operations = [
    ]
