# Generated by Django 2.0.5 on 2018-11-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0125_auto_20181121_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='why_get_tested',
        ),
    ]
