# Generated by Django 2.0.5 on 2018-11-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0126_remove_labtest_why_get_tested'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='why_get_tested',
            field=models.TextField(blank=True, verbose_name='Why get tested?'),
        ),
    ]
