# Generated by Django 2.0.5 on 2018-11-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0127_labtest_why_get_tested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='test_may_include',
        ),
    ]
