# Generated by Django 2.0.5 on 2018-11-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0128_remove_labtest_test_may_include'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionAnswer',
            new_name='FrequentQuestions',
        ),
    ]
