# Generated by Django 2.0.5 on 2018-11-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0128_remove_labtest_test_may_include'),
        ('diagnostic', '0119_labtest_rank'),
    ]

    operations = [
    ]
