# Generated by Django 2.0.5 on 2018-11-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0129_auto_20181122_1714'),
        ('diagnostic', '0119_labtest_rank'),
    ]

    operations = [
    ]
