# Generated by Django 2.0.5 on 2018-11-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0129_merge_20181122_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='answer',
            new_name='test_answer',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='question',
            new_name='test_question',
        ),
    ]
