# Generated by Django 2.0.5 on 2018-12-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0124_merge_20181129_1830'),
        ('diagnostic', '0130_auto_20181127_1250'),
    ]

    operations = [
    ]
