# Generated by Django 2.0.5 on 2018-12-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0131_merge_20181203_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='why_get_tested',
        ),
        migrations.AlterField(
            model_name='labtest',
            name='why',
            field=models.TextField(blank=True, verbose_name='Why get tested?'),
        ),
    ]
