# Generated by Django 2.0.5 on 2018-12-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0132_auto_20181204_1316'),
        ('diagnostic', '0125_merge_20181204_1357'),
    ]

    operations = [
    ]
