# Generated by Django 2.0.5 on 2018-12-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0133_merge_20181206_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtest',
            old_name='rank',
            new_name='priority',
        ),
        migrations.AlterModelTable(
            name='frequentlyaddedtogethertests',
            table='frequently_added_tests',
        ),
    ]
