# Generated by Django 2.0.5 on 2018-12-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0126_merge_20181206_1643'),
        ('diagnostic', '0134_auto_20181206_1731'),
    ]

    operations = [
    ]
