# Generated by Django 2.0.5 on 2018-12-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0125_labappointment_merchant_payout'),
        ('diagnostic', '0134_auto_20181206_1731'),
    ]

    operations = [
    ]
