# Generated by Django 2.0.5 on 2018-12-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0135_merge_20181207_1544'),
        ('diagnostic', '0135_merge_20181207_1957'),
    ]

    operations = [
    ]
