# Generated by Django 2.0.5 on 2018-12-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0135_merge_20181207_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='show_test',
            field=models.BooleanField(default=False),
        ),
    ]
