# Generated by Django 2.0.5 on 2018-12-13 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0136_labtest_show_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtest',
            old_name='show_test',
            new_name='show_details',
        ),
    ]
