# Generated by Django 2.0.5 on 2018-12-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0126_merge_20181207_1443'),
        ('diagnostic', '0137_auto_20181213_1047'),
    ]

    operations = [
    ]
