# Generated by Django 2.0.5 on 2018-12-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0137_auto_20181213_1047'),
        ('diagnostic', '0136_merge_20181210_1133'),
    ]

    operations = [
    ]
