# Generated by Django 2.0.5 on 2018-12-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0138_merge_20181217_1457'),
        ('diagnostic', '0138_merge_20181218_1938'),
    ]

    operations = [
    ]
