# Generated by Django 2.0.5 on 2018-12-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0138_merge_20181218_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAppointmentTestMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('computed_agreed_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('custom_agreed_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('computed_deal_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('custom_deal_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_mappings', to='diagnostic.LabAppointment')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_appointment_mappings', to='diagnostic.LabTest')),
            ],
            options={
                'db_table': 'lab_appointment_test_mapping',
            },
        ),
        migrations.AddField(
            model_name='labappointment',
            name='tests',
            field=models.ManyToManyField(through='diagnostic.LabAppointmentTestMapping', to='diagnostic.LabTest'),
        ),
    ]
