# Generated by Django 2.0.5 on 2018-12-31 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0138_merge_20181218_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab', to='diagnostic.LabNetwork'),
        ),
    ]
