# Generated by Django 2.0.5 on 2018-12-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0138_merge_20181218_1938'),
        ('diagnostic', '0136_labappointment_cashback'),
    ]

    operations = [
    ]
