# Generated by Django 2.0.5 on 2018-12-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0140_labappointment_price_data'),
        ('diagnostic', '0139_auto_20181225_0000'),
    ]

    operations = [
    ]
