# Generated by Django 2.0.5 on 2018-12-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0139_merge_20181221_1335'),
        ('diagnostic', '0140_labappointment_price_data'),
    ]

    operations = [
    ]
