# Generated by Django 2.0.5 on 2018-12-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0141_merge_20181227_1841'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='availablelabtest',
            index=models.Index(fields=['test_id', 'lab_pricing_group_id'], name='available_l_test_id_b8297a_idx'),
        ),
    ]
