# Generated by Django 2.0.5 on 2019-01-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0142_auto_20181229_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='priority',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
