# Generated by Django 2.0.5 on 2019-01-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0141_merge_20181227_1701'),
        ('diagnostic', '0142_auto_20181229_0505'),
    ]

    operations = [
    ]
