# Generated by Django 2.0.5 on 2019-01-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0142_auto_20181229_0505'),
        ('diagnostic', '0139_auto_20181231_1658'),
    ]

    operations = [
    ]
