# Generated by Django 2.0.5 on 2019-01-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0143_auto_20190103_1404'),
        ('diagnostic', '0143_merge_20190103_1239'),
    ]

    operations = [
    ]
