# Generated by Django 2.0.5 on 2019-01-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0144_merge_20190103_1621'),
        ('diagnostic', '0143_merge_20190102_1610'),
    ]

    operations = [
    ]
