# Generated by Django 2.0.5 on 2019-01-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0144_merge_20190103_1621'),
        ('diagnostic', '0141_merge_20181228_1550'),
    ]

    operations = [
    ]
