# Generated by Django 2.0.5 on 2019-01-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0145_merge_20190108_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='gender_type',
            field=models.PositiveIntegerField(blank=True, choices=[('', 'Select'), (1, 'male'), (2, 'female'), (3, 'all')], null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='max_age',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
