# Generated by Django 2.0.5 on 2019-01-17 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_moneypool'),
        ('diagnostic', '0145_merge_20190108_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointment',
            name='money_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.MoneyPool'),
        ),
    ]
