# Generated by Django 2.0.5 on 2019-01-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0145_merge_20190108_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
