# Generated by Django 2.0.5 on 2019-01-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0146_auto_20190129_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablelabtest',
            name='desired_docprime_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
