# Generated by Django 2.0.5 on 2019-01-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0146_auto_20190123_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestRecommendedCategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_recommended_screen', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'lab_test_recommended_category_mapping',
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='show_on_recommended_screen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrecommendedcategorymapping',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_lab_test_category_mappings', to='diagnostic.LabTest'),
        ),
        migrations.AddField(
            model_name='labtestrecommendedcategorymapping',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_lab_test_mappings', to='diagnostic.LabTestCategory'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='recommended_categories',
            field=models.ManyToManyField(related_name='recommended_lab_tests', through='diagnostic.LabTestRecommendedCategoryMapping', to='diagnostic.LabTestCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='labtestrecommendedcategorymapping',
            unique_together={('lab_test', 'parent_category')},
        ),
    ]
