# Generated by Django 2.0.5 on 2019-01-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0148_auto_20190123_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='show_on_recommended_screen',
        ),
        migrations.AddField(
            model_name='labtestcategory',
            name='show_on_recommended_screen',
            field=models.BooleanField(default=False),
        ),
    ]
