# Generated by Django 2.0.5 on 2019-02-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0149_auto_20190123_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='reference_code',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
