# Generated by Django 2.0.5 on 2019-02-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0150_labtest_reference_code'),
        ('diagnostic', '0147_availablelabtest_desired_docprime_price'),
    ]

    operations = [
    ]
