# Generated by Django 2.0.5 on 2019-02-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0151_merge_20190204_0951'),
        ('diagnostic', '0145_merge_20190107_1923'),
    ]

    operations = [
    ]
