# Generated by Django 2.0.5 on 2019-02-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0151_merge_20190204_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondiagnosticcondition',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonpackage',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commontest',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
