# Generated by Django 2.0.5 on 2019-02-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0152_auto_20190207_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestcategory',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
