# Generated by Django 2.0.5 on 2019-02-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0152_auto_20190206_1602'),
        ('diagnostic', '0152_auto_20190207_1307'),
    ]

    operations = [
    ]
