# Generated by Django 2.0.5 on 2019-02-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0152_auto_20190207_1307'),
        ('diagnostic', '0152_labnetwork_is_mask_number_required'),
    ]

    operations = [
    ]
