# Generated by Django 2.0.5 on 2019-02-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0151_merge_20190204_1303'),
        ('diagnostic', '0152_auto_20190207_1307'),
    ]

    operations = [
    ]
