# Generated by Django 2.0.5 on 2019-02-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0153_merge_20190212_1845'),
        ('diagnostic', '0153_labtestcategory_priority'),
    ]

    operations = [
    ]
