# Generated by Django 2.0.5 on 2019-02-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0153_labtestcategory_priority'),
        ('diagnostic', '0153_merge_20190208_1809'),
    ]

    operations = [
    ]
