# Generated by Django 2.0.5 on 2019-02-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0153_merge_20190212_2034'),
        ('diagnostic', '0154_merge_20190213_1729'),
    ]

    operations = [
    ]
