# Generated by Django 2.0.5 on 2019-02-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0155_merge_20190213_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='active_url',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
