# Generated by Django 2.0.5 on 2019-02-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0155_merge_20190213_1915'),
        ('diagnostic', '0153_merge_20190211_0207'),
    ]

    operations = [
    ]
