# Generated by Django 2.0.5 on 2019-02-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0156_labtest_active_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='active_url',
        ),
        migrations.AddField(
            model_name='labtest',
            name='custom_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='url',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
