# Generated by Django 2.0.5 on 2019-02-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0156_merge_20190214_1319'),
        ('diagnostic', '0157_auto_20190214_1547'),
    ]

    operations = [
    ]
