# Generated by Django 2.0.5 on 2019-02-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0153_lab_avg_rating'),
        ('diagnostic', '0157_auto_20190214_1547'),
    ]

    operations = [
    ]
