# Generated by Django 2.0.5 on 2019-02-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0157_auto_20190214_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lab_priority',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
