# Generated by Django 2.0.5 on 2019-02-20 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0158_auto_20190219_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestGroupTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start', models.DecimalField(choices=[(5.0, '5 AM'), (5.5, '5:30 AM'), (6.0, '6 AM'), (6.5, '6:30 AM'), (7.0, '7 AM'), (7.5, '7:30 AM'), (8.0, '8 AM'), (8.5, '8:30 AM'), (9.0, '9 AM'), (9.5, '9:30 AM'), (10.0, '10 AM'), (10.5, '10:30 AM'), (11.0, '11 AM'), (11.5, '11:30 AM'), (12.0, '12 PM'), (12.5, '12:30 PM'), (13.0, '1 PM'), (13.5, '1:30 PM'), (14.0, '2 PM'), (14.5, '2:30 PM'), (15.0, '3 PM'), (15.5, '3:30 PM'), (16.0, '4 PM'), (16.5, '4:30 PM'), (17.0, '5 PM'), (17.5, '5:30 PM'), (18.0, '6 PM'), (18.5, '6:30 PM'), (19.0, '7 PM'), (19.5, '7:30 PM'), (20.0, '8 PM'), (20.5, '8:30 PM'), (21.0, '9 PM'), (21.5, '9:30 PM'), (22.0, '10 PM'), (22.5, '10:30 PM'), (23.0, '11 PM'), (23.5, '11:30 PM')], decimal_places=1, max_digits=3)),
                ('end', models.DecimalField(choices=[(5.0, '5 AM'), (5.5, '5:30 AM'), (6.0, '6 AM'), (6.5, '6:30 AM'), (7.0, '7 AM'), (7.5, '7:30 AM'), (8.0, '8 AM'), (8.5, '8:30 AM'), (9.0, '9 AM'), (9.5, '9:30 AM'), (10.0, '10 AM'), (10.5, '10:30 AM'), (11.0, '11 AM'), (11.5, '11:30 AM'), (12.0, '12 PM'), (12.5, '12:30 PM'), (13.0, '1 PM'), (13.5, '1:30 PM'), (14.0, '2 PM'), (14.5, '2:30 PM'), (15.0, '3 PM'), (15.5, '3:30 PM'), (16.0, '4 PM'), (16.5, '4:30 PM'), (17.0, '5 PM'), (17.5, '5:30 PM'), (18.0, '6 PM'), (18.5, '6:30 PM'), (19.0, '7 PM'), (19.5, '7:30 PM'), (20.0, '8 PM'), (20.5, '8:30 PM'), (21.0, '9 PM'), (21.5, '9:30 PM'), (22.0, '10 PM'), (22.5, '10:30 PM'), (23.0, '11 PM'), (23.5, '11:30 PM')], decimal_places=1, max_digits=3)),
                ('for_home_pickup', models.BooleanField(default=False)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.Lab')),
            ],
            options={
                'db_table': 'lab_test_group_timing',
            },
        ),
        migrations.RenameModel(
            old_name='LabTestTimingGroup',
            new_name='LabTestGroupMapping',
        ),
        migrations.RemoveField(
            model_name='labtesttiming',
            name='lab_timing_group',
        ),
        migrations.RemoveField(
            model_name='labtestgroup',
            name='tests',
        ),
        migrations.RemoveField(
            model_name='labtestgroupmapping',
            name='lab_timing_group',
        ),
        migrations.AddField(
            model_name='labtestgroupmapping',
            name='lab_test_group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabTestGroup'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='labtestgroupmapping',
            table='lab_test_group_mapping',
        ),
        migrations.DeleteModel(
            name='LabTestTiming',
        ),
        migrations.DeleteModel(
            name='LabTimingGroup',
        ),
        migrations.AddField(
            model_name='labtestgrouptiming',
            name='lab_test_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabTestGroup'),
        ),
    ]
