# Generated by Django 2.0.5 on 2019-02-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0158_lab_lab_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
