# Generated by Django 2.0.5 on 2019-02-20 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0159_auto_20190220_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestgroup',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Radiology'), (2, 'Pathology'), (3, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='labtestgrouptiming',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.Lab'),
        ),
    ]
