# Generated by Django 2.0.5 on 2019-02-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0158_labtestcategory_icon'),
        ('diagnostic', '0159_auto_20190222_1228'),
    ]

    operations = [
    ]
