# Generated by Django 2.0.5 on 2019-02-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0159_auto_20190222_1228'),
        ('diagnostic', '0160_auto_20190220_1355'),
    ]

    operations = [
    ]
