# Generated by Django 2.0.5 on 2019-02-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0158_merge_20190214_1831'),
        ('diagnostic', '0161_merge_20190222_1443'),
    ]

    operations = [
    ]
