# Generated by Django 2.0.5 on 2019-02-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0160_merge_20190222_1435'),
        ('diagnostic', '0162_merge_20190222_1705'),
    ]

    operations = [
    ]
