# Generated by Django 2.0.5 on 2019-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0163_merge_20190225_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='test/image'),
        ),
    ]
