# Generated by Django 2.0.5 on 2019-02-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0164_auto_20190226_1512'),
        ('diagnostic', '0156_merge_20190214_1412'),
    ]

    operations = [
    ]
