# Generated by Django 2.0.5 on 2019-03-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0164_auto_20190226_1512'),
        ('diagnostic', '0158_merge_20190220_1626'),
    ]

    operations = [
    ]
