# Generated by Django 2.0.5 on 2019-02-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0164_auto_20190226_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='labnetwork',
            name='open_for_email',
            field=models.BooleanField(default=True),
        ),
    ]
