# Generated by Django 2.0.5 on 2019-02-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0165_labnetwork_open_for_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labnetwork',
            old_name='open_for_email',
            new_name='open_for_communication',
        ),
        migrations.AddField(
            model_name='lab',
            name='open_for_communication',
            field=models.BooleanField(default=True),
        ),
    ]
