# Generated by Django 2.0.5 on 2019-03-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0165_merge_20190304_1109'),
        ('diagnostic', '0166_auto_20190228_1752'),
    ]

    operations = [
    ]
