# Generated by Django 2.0.5 on 2019-03-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0165_merge_20190227_1144'),
        ('diagnostic', '0167_merge_20190304_1959'),
    ]

    operations = [
    ]
