# Generated by Django 2.0.5 on 2019-03-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0167_merge_20190304_1959'),
        ('diagnostic', '0152_merge_20190204_1401'),
    ]

    operations = [
    ]
