# Generated by Django 2.0.5 on 2019-03-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0168_testparameter_details'),
        ('diagnostic', '0168_merge_20190312_1851'),
    ]

    operations = [
    ]
