# Generated by Django 2.0.5 on 2019-03-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0168_testparameter_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablelabtest',
            name='is_package',
            field=models.BooleanField(default=False),
        ),
    ]
