# Generated by Django 2.0.5 on 2019-03-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0009_auto_20190315_1750'),
        ('diagnostic', '0169_merge_20190318_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointment',
            name='user_plan_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_using', to='subscription_plan.UserPlanMapping'),
        ),
    ]
