# Generated by Django 2.0.5 on 2019-03-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0169_availablelabtest_is_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablelabtest',
            name='is_package',
        ),
    ]
