# Generated by Django 2.0.5 on 2019-03-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0170_labappointment_user_plan_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labappointment',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Prepaid'), (2, 'COD'), (3, 'Insurance'), (4, 'Subscription Plan')], default=1),
        ),
    ]
