# Generated by Django 2.0.5 on 2019-03-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0170_remove_availablelabtest_is_package'),
        ('diagnostic', '0169_merge_20190318_1404'),
    ]

    operations = [
    ]
