# Generated by Django 2.0.5 on 2019-03-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0168_merge_20190312_1254'),
        ('diagnostic', '0171_merge_20190319_1219'),
    ]

    operations = [
    ]
