# Generated by Django 2.0.5 on 2019-03-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0171_merge_20190319_1219'),
        ('diagnostic', '0171_auto_20190320_1117'),
    ]

    operations = [
    ]
