# Generated by Django 2.0.5 on 2019-03-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0172_merge_20190320_1605'),
        ('diagnostic', '0172_auto_20190320_1642'),
    ]

    operations = [
    ]
