# Generated by Django 2.0.5 on 2019-03-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0173_merge_20190320_1712'),
        ('diagnostic', '0172_merge_20190319_1423'),
    ]

    operations = [
    ]
