# Generated by Django 2.0.5 on 2019-03-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_merge_20190318_1404'),
        ('diagnostic', '0174_lab_rating_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='matrix_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='labs_in_city', to='common.MatrixMappedCity', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='lab',
            name='matrix_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='labs_in_state', to='common.MatrixMappedState', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='labnetwork',
            name='matrix_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_networks_in_city', to='common.MatrixMappedCity', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='labnetwork',
            name='matrix_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_networks_in_state', to='common.MatrixMappedState', verbose_name='State'),
        ),
    ]
