# Generated by Django 2.0.5 on 2019-04-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0174_lab_rating_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='is_cod_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lab',
            name='is_prepaid_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
