# Generated by Django 2.0.5 on 2019-03-29 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0174_merge_20190326_1307'),
        ('diagnostic', '0174_lab_rating_data'),
    ]

    operations = [
    ]
