# Generated by Django 2.0.5 on 2019-04-01 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0174_lab_rating_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreportfile',
            name='name',
            field=models.FileField(upload_to='lab_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jfif', 'jpg', 'jpeg', 'png', 'xml'])]),
        ),
    ]
