# Generated by Django 2.0.5 on 2019-04-02 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0175_auto_20190401_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestParameterNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('min_range', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('max_range', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('test_name', models.CharField(max_length=40)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabTest')),
            ],
            options={
                'db_table': 'test_parameter_new',
            },
        ),
    ]
