# Generated by Django 2.0.5 on 2019-04-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0176_testparameternew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testparameternew',
            old_name='test_id',
            new_name='test',
        ),
    ]
