# Generated by Django 2.0.5 on 2019-04-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0176_auto_20190401_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='enabled_for_cod',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='enabled_for_prepaid',
        ),
    ]
