# Generated by Django 2.0.5 on 2019-04-02 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0177_auto_20190402_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testparameternew',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabTest'),
        ),
    ]
