# Generated by Django 2.0.5 on 2019-04-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0175_auto_20190401_1507'),
        ('diagnostic', '0177_auto_20190401_1426'),
    ]

    operations = [
    ]
