# Generated by Django 2.0.5 on 2019-04-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0178_auto_20190402_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testparameternew',
            name='test_name',
            field=models.CharField(max_length=60),
        ),
    ]
