# Generated by Django 2.0.5 on 2019-04-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0179_auto_20190402_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testparameternew',
            name='max_range',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='testparameternew',
            name='min_range',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
