# Generated by Django 2.0.5 on 2019-04-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0029_integratortestparameter_response_data'),
        ('diagnostic', '0180_auto_20190402_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestParameterNew',
            new_name='TestParameterChat',
        ),
        migrations.AlterModelTable(
            name='testparameterchat',
            table='test_parameter_chat',
        ),
    ]
