# Generated by Django 2.0.5 on 2019-04-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0178_merge_20190403_1634'),
        ('diagnostic', '0181_auto_20190403_1544'),
    ]

    operations = [
    ]
