# Generated by Django 2.0.5 on 2019-04-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0175_merge_20190329_1016'),
        ('diagnostic', '0181_auto_20190403_1544'),
    ]

    operations = [
    ]
