# Generated by Django 2.0.5 on 2019-04-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0181_auto_20190403_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonpackage',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packagelab', to='diagnostic.Lab'),
        ),
    ]
