# Generated by Django 2.0.5 on 2019-04-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0182_merge_20190403_2105'),
        ('diagnostic', '0182_merge_20190404_1712'),
    ]

    operations = [
    ]
