# Generated by Django 2.0.5 on 2019-04-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0184_auto_20190404_1909'),
        ('diagnostic', '0186_auto_20190404_2028'),
    ]

    operations = [
    ]
