# Generated by Django 2.0.5 on 2019-04-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0187_merge_20190409_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='is_cancellable',
            field=models.BooleanField(default=True),
        ),
    ]
