# Generated by Django 2.0.5 on 2019-04-10 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0239_auto_20190404_2028'),
        ('diagnostic', '0187_merge_20190409_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_tests', to='doctor.Doctor'),
        ),
    ]
