# Generated by Django 2.0.5 on 2019-04-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0187_labappointment_spo_data'),
        ('diagnostic', '0187_merge_20190409_1143'),
    ]

    operations = [
    ]
