# Generated by Django 2.0.5 on 2019-04-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0188_labtest_is_cancellable'),
        ('diagnostic', '0175_lab_is_location_verified'),
    ]

    operations = [
    ]
