# Generated by Django 2.0.5 on 2019-04-16 07:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0189_merge_20190412_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointment',
            name='auto_ivr_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
