# Generated by Django 2.0.5 on 2019-04-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0189_merge_20190412_2013'),
        ('diagnostic', '0188_labtest_author'),
    ]

    operations = [
    ]
