# Generated by Django 2.0.5 on 2019-04-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0191_auto_20190418_1649'),
        ('diagnostic', '0192_auto_20190417_1741'),
    ]

    operations = [
    ]
