# Generated by Django 2.0.5 on 2019-04-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0190_auto_20190418_1756'),
        ('diagnostic', '0193_merge_20190418_1852'),
    ]

    operations = [
    ]
