# Generated by Django 2.0.5 on 2019-04-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0193_merge_20190418_1852'),
        ('diagnostic', '0188_merge_20190410_1554'),
    ]

    operations = [
    ]
