# Generated by Django 2.0.5 on 2019-04-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0194_merge_20190419_0907'),
        ('diagnostic', '0194_merge_20190419_0857'),
    ]

    operations = [
    ]
