# Generated by Django 2.0.5 on 2019-04-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0195_merge_20190419_1241'),
        ('diagnostic', '0182_commonpackage_lab'),
    ]

    operations = [
    ]
