# Generated by Django 2.0.5 on 2019-05-03 09:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0195_merge_20190419_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointment',
            name='coupon_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
