# Generated by Django 2.0.5 on 2019-04-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0195_merge_20190419_1241'),
        ('diagnostic', '0194_merge_20190419_1303'),
    ]

    operations = [
    ]
