# Generated by Django 2.0.5 on 2019-04-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0190_auto_20190418_1554'),
        ('diagnostic', '0195_merge_20190419_1241'),
    ]

    operations = [
    ]
