# Generated by Django 2.0.5 on 2019-04-23 07:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0195_merge_20190419_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestThresholds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constraints', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabTest')),
            ],
            options={
                'db_table': 'lab_test_thresholds',
            },
        ),
    ]
