# Generated by Django 2.0.5 on 2019-04-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0196_labtestthresholds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestthresholds',
            name='constraints',
        ),
        migrations.AddField(
            model_name='labtestthresholds',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestthresholds',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='labtestthresholds',
            name='max_age',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='labtestthresholds',
            name='max_value',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='labtestthresholds',
            name='min_age',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='labtestthresholds',
            name='min_value',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='labtestthresholds',
            name='what_to_do',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestthresholds',
            name='color',
            field=models.CharField(choices=[('GREEN', 'GREEN'), ('ORANGE', 'ORANGE'), ('RED', 'RED')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labtestthresholds',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE'), ('OTHER', 'OTHER')], default=None, max_length=50, null=True),
        ),
    ]
