# Generated by Django 2.0.5 on 2019-04-24 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0197_auto_20190423_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestthresholds',
            name='test_parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_thresholds', to='diagnostic.TestParameter'),
        ),
        migrations.AlterField(
            model_name='labtestthresholds',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_parameter_thresholds', to='diagnostic.LabTest'),
        ),
    ]
