# Generated by Django 2.0.5 on 2019-04-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0198_auto_20190424_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestthresholds',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default=None, max_length=50, null=True),
        ),
    ]
