# Generated by Django 2.0.5 on 2019-05-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0196_merge_20190423_1626'),
        ('diagnostic', '0199_auto_20190424_1304'),
    ]

    operations = [
    ]
