# Generated by Django 2.0.5 on 2019-05-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0200_merge_20190502_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestthresholds',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other'), (None, 'Null')], default=None, max_length=50, null=True),
        ),
    ]
