# Generated by Django 2.0.5 on 2019-05-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0200_merge_20190502_1845'),
        ('diagnostic', '0200_merge_20190501_1856'),
    ]

    operations = [
    ]
