# Generated by Django 2.0.5 on 2019-05-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0202_auto_20190503_1737'),
        ('diagnostic', '0201_merge_20190503_1403'),
    ]

    operations = [
    ]
