# Generated by Django 2.0.5 on 2019-05-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0196_labappointment_coupon_data'),
        ('diagnostic', '0202_auto_20190503_1737'),
    ]

    operations = [
    ]
