# Generated by Django 2.0.5 on 2019-05-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0203_merge_20190507_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='search_distance',
            field=models.FloatField(default=15000),
        ),
    ]
