# Generated by Django 2.0.5 on 2019-05-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0203_merge_20190507_1222'),
        ('diagnostic', '0203_merge_20190507_1219'),
    ]

    operations = [
    ]
