# Generated by Django 2.0.5 on 2019-05-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0204_merge_20190510_1419'),
        ('diagnostic', '0204_lab_search_distance'),
    ]

    operations = [
    ]
