# Generated by Django 2.0.5 on 2019-05-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0204_lab_search_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='search_distance',
            field=models.FloatField(default=20000),
        ),
    ]
