# Generated by Django 2.0.5 on 2019-05-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0205_merge_20190516_1754'),
        ('diagnostic', '0205_lab_url'),
    ]

    operations = [
    ]
