# Generated by Django 2.0.5 on 2019-06-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0207_lab_deleted'),
        ('diagnostic', '0206_merge_20190524_1533'),
    ]

    operations = [
    ]
