# Generated by Django 2.0.5 on 2019-06-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0208_merge_20190612_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='insurance_cutoff_price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
