# Generated by Django 2.0.5 on 2019-06-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0210_labappointment_hospital_reference_id'),
        ('diagnostic', '0210_labappointment_reports_physically_collected'),
    ]

    operations = [
    ]
