# Generated by Django 2.0.5 on 2019-06-25 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0212_auto_20190625_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='related_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ipd_hospital', to='doctor.Hospital'),
        ),
    ]
