# Generated by Django 2.0.5 on 2019-07-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0214_auto_20190704_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablelabtest',
            name='insurance_agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
