# Generated by Django 2.0.5 on 2019-07-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0215_availablelabtest_insurance_agreed_price'),
        ('diagnostic', '0216_auto_20190715_1600'),
    ]

    operations = [
    ]
