# Generated by Django 2.0.5 on 2019-07-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0217_merge_20190725_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestcategorylandingurls',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='labtestcategoryurls',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
