# Generated by Django 2.0.5 on 2019-07-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0218_auto_20190730_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestcategoryurls',
            name='title',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
