# Generated by Django 2.0.5 on 2019-08-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0196_merge_20190424_1637'),
        ('diagnostic', '0219_auto_20190730_1453'),
    ]

    operations = [
    ]
