# Generated by Django 2.0.5 on 2019-08-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0219_auto_20190730_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='disabled_after',
            field=models.PositiveIntegerField(blank=True, choices=[('', 'Select'), (1, 'Welcome Calling'), (2, 'Escalation'), (3, 'INSURANCE')], null=True),
        ),
    ]
