# Generated by Django 2.0.5 on 2019-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0220_auto_20190806_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointmenttestmapping',
            name='time_slot_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
