# Generated by Django 2.0.5 on 2019-08-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0220_merge_20190806_1629'),
        ('diagnostic', '0220_auto_20190806_1635'),
    ]

    operations = [
    ]
