# Generated by Django 2.0.5 on 2019-08-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0220_auto_20190806_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='enabled_for_plus_plans',
            field=models.NullBooleanField(),
        ),
    ]
