# Generated by Django 2.0.5 on 2019-08-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0221_ipdmedicinepagelead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipdmedicinepagelead',
            old_name='city',
            new_name='matrix_city',
        ),
    ]
