# Generated by Django 2.0.5 on 2019-08-19 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0221_labappointmenttestmapping_time_slot_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestgrouptiming',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_group_timings', to='diagnostic.Lab'),
        ),
    ]
