# Generated by Django 2.0.5 on 2019-08-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0222_auto_20190819_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointmenttestmapping',
            name='is_home_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
