# Generated by Django 2.0.5 on 2019-08-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0224_auto_20190828_2335'),
        ('diagnostic', '0223_labnetwork_enabled_for_plus_plans'),
    ]

    operations = [
    ]
