# Generated by Django 2.0.5 on 2019-09-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0224_auto_20190828_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='is_b2b',
            field=models.BooleanField(default=False),
        ),
    ]
