# Generated by Django 2.0.5 on 2019-08-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0224_labappointment_action_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labappointmenttestmapping',
            name='is_home_pickup',
        ),
        migrations.RemoveField(
            model_name='labappointmenttestmapping',
            name='time_slot_start',
        ),
    ]
