# Generated by Django 2.0.5 on 2019-09-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0225_merge_20190830_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='center_visit',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='labnetwork',
            name='center_visit',
            field=models.NullBooleanField(),
        ),
    ]
