# Generated by Django 2.0.5 on 2019-09-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0225_merge_20190830_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='is_b2b',
            field=models.BooleanField(default=False),
        ),
    ]
