# Generated by Django 2.0.5 on 2019-09-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0222_labappointment_spo_lead_id'),
        ('diagnostic', '0225_merge_20190830_1218'),
    ]

    operations = [
    ]
