# Generated by Django 2.0.5 on 2019-09-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0225_auto_20190828_2008'),
        ('diagnostic', '0226_auto_20190910_1327'),
    ]

    operations = [
    ]
