# Generated by Django 2.0.5 on 2019-09-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0226_auto_20190910_1327'),
        ('diagnostic', '0226_lab_is_b2b'),
    ]

    operations = [
    ]
