# Generated by Django 2.0.5 on 2019-09-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0227_merge_20190912_0055'),
        ('diagnostic', '0226_auto_20190910_2022'),
    ]

    operations = [
    ]
