# Generated by Django 2.0.5 on 2019-09-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0228_merge_20190912_2137'),
        ('diagnostic', '0227_merge_20190912_1205'),
    ]

    operations = [
    ]
