# Generated by Django 2.0.5 on 2019-09-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0226_merge_20190905_1209'),
        ('diagnostic', '0229_merge_20190913_1621'),
    ]

    operations = [
    ]
