# Generated by Django 2.0.5 on 2019-11-01 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0230_merge_20190924_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabtestNameMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'labtest_master',
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='search_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.LabtestNameMaster'),
        ),
    ]
