# Generated by Django 2.0.5 on 2019-11-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0231_auto_20191018_1716'),
        ('diagnostic', '0232_auto_20191101_1623'),
    ]

    operations = [
    ]
