# Generated by Django 2.0.5 on 2019-11-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0233_merge_20191113_1251'),
        ('diagnostic', '0232_auto_20191105_1717'),
    ]

    operations = [
    ]
