# Generated by Django 2.0.5 on 2019-11-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0234_merge_20191125_1222'),
        ('diagnostic', '0234_auto_20191115_1224'),
    ]

    operations = [
    ]
