# Generated by Django 2.0.5 on 2019-12-23 06:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0237_auto_20191210_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablelabtest',
            name='convenience_pricing',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
