# Generated by Django 2.0.5 on 2020-01-08 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0240_auto_20200108_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestcategory',
            name='svg_icon',
            field=models.FileField(null=True, upload_to='test/image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
