# Generated by Django 2.0.5 on 2020-01-08 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0241_labtestcategory_svg_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestcategory',
            name='svg_icon',
            field=models.FileField(blank=True, null=True, upload_to='test/image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
