# Generated by Django 2.0.5 on 2020-01-31 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0242_auto_20200108_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAppointmentFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ratings', models.PositiveIntegerField(max_length=10)),
                ('comment', models.TextField()),
                ('appointment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diagnostic.LabAppointment')),
            ],
            options={
                'db_table': 'lab_appointment_feedback',
            },
        ),
    ]
