# Generated by Django 2.0.5 on 2020-01-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0243_labappointmentfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labappointmentfeedback',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
