# Generated by Django 2.0.5 on 2020-01-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0244_auto_20200131_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labappointmentfeedback',
            old_name='appointment_id',
            new_name='appointment',
        ),
    ]
