# Generated by Django 2.0.5 on 2020-02-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0243_labtestprecsriptions'),
        ('diagnostic', '0245_auto_20200131_1652'),
    ]

    operations = [
    ]
