# Generated by Django 2.0.5 on 2020-02-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0245_auto_20200131_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappointment',
            name='revenue_transferred',
            field=models.NullBooleanField(),
        ),
    ]
