# Generated by Django 2.0.5 on 2020-03-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0246_labappointment_revenue_transferred'),
        ('diagnostic', '0246_merge_20200227_1440'),
    ]

    operations = [
    ]
