# Generated by Django 2.0.5 on 2018-09-05 06:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityaddress',
            name='centroid',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='entityaddress',
            name='parent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entityaddress',
            name='type',
            field=models.CharField(choices=[('LOCALITY', 'LOCALITY'), ('POLITICAL', 'POLITICAL'), ('ROUTE', 'ROUTE'), ('STREET_NUMBER', 'STREET_NUMBER'), ('SUBLOCALITY', 'SUBLOCALITY')], max_length=128),
        ),
    ]
