# Generated by Django 2.0.5 on 2018-09-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('location', '0002_auto_20180905_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityLocationRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('ADMINISTRATIVE_AREA_LEVEL_1', 'ADMINISTRATIVE_AREA_LEVEL_1'), ('ADMINISTRATIVE_AREA_LEVEL_2', 'ADMINISTRATIVE_AREA_LEVEL_1'), ('COUNTRY', 'COUNTRY'), ('LOCALITY', 'LOCALITY'), ('SUBLOCALITY', 'SUBLOCALITY')], max_length=128)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'entity_location_realation',
            },
        ),
        migrations.AlterField(
            model_name='entityaddress',
            name='type',
            field=models.CharField(choices=[('ADMINISTRATIVE_AREA_LEVEL_1', 'ADMINISTRATIVE_AREA_LEVEL_1'), ('ADMINISTRATIVE_AREA_LEVEL_2', 'ADMINISTRATIVE_AREA_LEVEL_1'), ('COUNTRY', 'COUNTRY'), ('LOCALITY', 'LOCALITY'), ('SUBLOCALITY', 'SUBLOCALITY')], max_length=128),
        ),
        migrations.AddField(
            model_name='entitylocationrelationship',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.EntityAddress'),
        ),
    ]
