# Generated by Django 2.0.5 on 2018-09-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20180906_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, null=True, unique=True)),
                ('extras', models.TextField(default='{}')),
                ('is_valid', models.BooleanField(default=True)),
                ('valid_reference', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'entity_urls',
            },
        ),
        migrations.AlterModelTable(
            name='entitylocationrelationship',
            table='entity_location_relations',
        ),
    ]
