# Generated by Django 2.0.5 on 2018-09-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20180906_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityurls',
            name='url_type',
            field=models.CharField(choices=[('PAGEURL', 'PAGEURL'), ('SEARCHURL', 'SERCHURL')], max_length=24, null=True),
        ),
    ]
