# Generated by Django 2.0.5 on 2018-09-11 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('location', '0006_auto_20180911_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityUrlsRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.EntityUrls')),
            ],
            options={
                'db_table': 'entity_url_relations',
            },
        ),
    ]
