# Generated by Django 2.0.5 on 2018-09-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_entityurlsrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityurls',
            name='url_type',
            field=models.CharField(choices=[('PAGEURL', 'PAGEURL'), ('SEARCHURL', 'SEARCHURL')], max_length=24, null=True),
        ),
    ]
