# Generated by Django 2.0.5 on 2018-09-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_entityurls_entity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityurls',
            name='valid_reference',
        ),
    ]
