# Generated by Django 2.0.5 on 2018-09-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20180914_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoIpResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'geo_ip_results',
            },
        ),
    ]
