# Generated by Django 2.0.5 on 2018-09-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_auto_20180917_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitylocationrelationship',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
