# Generated by Django 2.0.5 on 2018-09-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0016_entitylocationrelationship_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityaddress',
            name='type_blueprint',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
