# Generated by Django 2.0.5 on 2018-09-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_entityaddress_type_blueprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityaddress',
            name='postal_code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
