# Generated by Django 2.0.5 on 2018-09-18 08:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_auto_20180917_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityaddress',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
