# Generated by Django 2.0.5 on 2018-09-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0021_entityaddress_centroid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitylocationrelationship',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_relations', to='location.EntityAddress'),
        ),
    ]
