# Generated by Django 2.0.5 on 2018-09-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_auto_20180919_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityurls',
            name='count',
            field=models.IntegerField(max_length=30, null=True, default=0),
        ),
    ]
