# Generated by Django 2.0.5 on 2018-09-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_auto_20180919_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityurls',
            name='url',
            field=models.CharField(db_index=True, max_length=500, null=True, unique=True),
        ),
    ]
