# Generated by Django 2.0.5 on 2018-09-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0023_auto_20180926_1219'),
        ('location', '0023_entityurls_count'),
    ]

    operations = [
    ]
