# Generated by Django 2.0.5 on 2018-10-08 09:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0025_entityurls_sitemap_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityurls',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
