# Generated by Django 2.0.5 on 2018-10-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0027_entityaddress_alternative_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityaddress',
            name='alternative_value',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='entityurls',
            name='url',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
        migrations.RunSQL(
            '''CREATE SEQUENCE IF NOT EXISTS entity_url_version_seq START 1;'''
        ),
    ]
