# Generated by Django 2.0.5 on 2018-10-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0029_entityurls_sequence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeoIpResults',
            new_name='GeocodingResults',
        ),
        migrations.AddField(
            model_name='entityaddress',
            name='geocoding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.GeocodingResults'),
        ),
        migrations.AlterModelTable(
            name='geocodingresults',
            table='geocoding_results',
        ),
    ]
