# Generated by Django 2.0.5 on 2018-10-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0029_entityurls_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityurls',
            name='locality_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entityurls',
            name='locality_latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='entityurls',
            name='locality_longitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='entityurls',
            name='locality_value',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='entityurls',
            name='sublocality_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entityurls',
            name='sublocality_latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='entityurls',
            name='sublocality_longitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='entityurls',
            name='sublocality_value',
            field=models.TextField(default='', null=True),
        ),
    ]
