# Generated by Django 2.0.5 on 2018-10-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0030_auto_20181023_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityurls',
            name='specialization',
            field=models.TextField(default='', null=True),
        ),
    ]
