# Generated by Django 2.0.5 on 2018-10-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0033_cityinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityurls',
            name='sublocality_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='entityurls',
            name='sublocality_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
