# Generated by Django 2.0.5 on 2018-10-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0034_auto_20181024_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityurls',
            name='locality_id',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='entityurls',
            name='specialization_id',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='entityurls',
            name='sublocality_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
