# Generated by Django 2.0.5 on 2018-10-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0030_auto_20181026_1105'),
        ('location', '0035_auto_20181026_1622'),
    ]

    operations = [
    ]
