# Generated by Django 2.0.5 on 2018-10-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0036_merge_20181026_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityurls',
            name='locality_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='entityurls',
            name='specialization_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='entityurls',
            name='sublocality_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
