# Generated by Django 2.0.5 on 2018-10-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0038_cityinventory_rank'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entityurls',
            index=models.Index(fields=['locality_value'], name='entity_urls_localit_1856a2_idx'),
        ),
        migrations.AddIndex(
            model_name='entityurls',
            index=models.Index(fields=['locality_value', 'sitemap_identifier'], name='entity_urls_localit_6c90e3_idx'),
        ),
    ]
