# Generated by Django 2.0.5 on 2018-10-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0039_auto_20181029_1657'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entityurls',
            index=models.Index(fields=['url'], name='entity_urls_url_e2b010_idx'),
        ),
        migrations.AddIndex(
            model_name='entityurls',
            index=models.Index(fields=['specialization_id', 'locality_id', 'sublocality_id'], name='entity_urls_special_14b8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='entityurls',
            index=models.Index(fields=['locality_id', 'sublocality_id'], name='entity_urls_localit_0ca6ee_idx'),
        ),
    ]
