# Generated by Django 2.0.5 on 2018-10-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0040_auto_20181029_2312'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entityurls',
            index=models.Index(fields=['specialization_id', 'sitemap_identifier'], name='entity_urls_special_b104c8_idx'),
        ),
    ]
