# Generated by Django 2.0.5 on 2018-10-31 06:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0041_auto_20181030_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityurls',
            name='locality_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='entityurls',
            name='sublocality_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
