# Generated by Django 2.0.5 on 2018-12-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0044_entitylocationrelationship_entity_geo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityaddress',
            name='no_of_childs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
