# Generated by Django 2.0.5 on 2018-12-07 10:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0045_entityaddress_no_of_childs'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityaddress',
            name='abs_centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='entityaddress',
            name='no_of_childs',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
