# Generated by Django 2.0.5 on 2018-12-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0046_auto_20181207_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityaddress',
            name='no_of_childs',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
