# Generated by Django 2.0.5 on 2018-12-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0047_auto_20181207_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityaddress',
            name='order',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='entityaddress',
            name='use_in_url',
            field=models.BooleanField(default=False, verbose_name='Use in URL'),
        ),
    ]
