# Generated by Django 2.0.5 on 2018-12-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0052_auto_20181215_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityaddress',
            name='search_slug',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
