# Generated by Django 2.0.5 on 2018-12-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0057_remove_entityaddress_geocoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityaddress',
            name='geocoding',
            field=models.ManyToManyField(related_name='addresses', through='location.AddressGeoMapping', to='location.GeocodingResults'),
        ),
    ]
