# Generated by Django 2.0.5 on 2018-12-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0059_auto_20181217_2237'),
        ('location', '0045_auto_20181126_1121'),
    ]

    operations = [
    ]
