# Generated by Django 2.0.5 on 2018-12-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0060_merge_20181218_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityurls',
            name='sitemap_identifier',
            field=models.CharField(choices=[('DOCTORS_CITY', 'DOCTORS_CITY'), ('DOCTORS_LOCALITY_CITY', 'DOCTORS_LOCALITY_CITY'), ('DOCTOR_PAGE', 'DOCTOR_PAGE'), ('LAB_CITY', 'LAB_CITY'), ('LAB_LOCALITY_CITY', 'LAB_LOCALITY_CITY'), ('LAB_PAGE', 'LAB_PAGE'), ('SPECIALIZATION_CITY', 'SPECIALIZATION_CITY'), ('SPECIALIZATION_LOCALITY_CITY', 'SPECIALIZATION_LOCALITY_CITY')], max_length=28, null=True),
        ),
    ]
