# Generated by Django 2.0.5 on 2018-12-26 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0062_auto_20181220_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityaddress',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.EntityAddress'),
        ),
    ]
