# Generated by Django 2.0.5 on 2018-12-26 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0063_auto_20181226_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityaddress',
            name='parent',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.EntityAddress'),
        ),
    ]
