# Generated by Django 2.0.5 on 2018-12-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0064_defaultrating_reviews'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='defaultrating',
            index=models.Index(fields=['url'], name='default_rat_url_0acc3a_idx'),
        ),
    ]
