# Generated by Django 2.0.5 on 2018-12-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0065_auto_20181226_1608'),
        ('location', '0064_auto_20181226_2048'),
    ]

    operations = [
    ]
