# Generated by Django 2.0.5 on 2018-12-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0066_merge_20181228_2036'),
        ('location', '0066_merge_20181228_1557'),
    ]

    operations = [
    ]
