# Generated by Django 2.0.5 on 2019-01-03 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0066_merge_20181228_1607'),
        ('location', '0066_merge_20181228_2036'),
    ]

    operations = [
    ]
