# Generated by Django 2.0.5 on 2018-12-28 10:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0066_merge_20181228_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'google_results',
            },
        ),
        migrations.CreateModel(
            name='GoogleSearchEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place_id', models.TextField()),
                ('place_result', django.contrib.postgres.fields.jsonb.JSONField()),
                ('doctor_details', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'google_search_place_entry',
            },
        ),
        migrations.CreateModel(
            name='GoogleSearches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_keywords', models.CharField(max_length=200)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField()),
                ('count', models.PositiveIntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'google_search',
            },
        ),
        migrations.AddField(
            model_name='googlesearchentry',
            name='place_search',
            field=models.ManyToManyField(related_name='assoc_search_results', through='location.GoogleResult', to='location.GoogleSearches'),
        ),
        migrations.AddField(
            model_name='googleresult',
            name='place_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_place_details', to='location.GoogleSearchEntry'),
        ),
        migrations.AddField(
            model_name='googleresult',
            name='search_results',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_search_details', to='location.GoogleSearches'),
        ),
    ]
