# Generated by Django 2.0.5 on 2019-01-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0067_merge_20181228_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityaddress',
            name='count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
