# Generated by Django 2.0.5 on 2019-01-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0068_entityaddress_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entityaddress',
            old_name='count',
            new_name='child_count',
        ),
    ]
