# Generated by Django 2.0.5 on 2019-01-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0069_auto_20190104_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityaddress',
            name='no_of_childs',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
