# Generated by Django 2.0.5 on 2019-01-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0070_auto_20190104_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultrating',
            name='ratings',
            field=models.FloatField(null=True),
        ),
    ]
