# Generated by Django 2.0.5 on 2019-01-07 14:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0071_tempurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
