# Generated by Django 2.0.5 on 2019-01-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0072_auto_20190107_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='sequence',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
