# Generated by Django 2.0.5 on 2019-01-08 09:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0073_auto_20190107_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityurls',
            name='breadcrumb',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='tempurl',
            name='breadcrumb',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
