# Generated by Django 2.0.5 on 2019-01-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0071_auto_20190108_1350'),
        ('location', '0074_auto_20190108_1514'),
    ]

    operations = [
    ]
