# Generated by Django 2.0.5 on 2019-01-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0075_merge_20190108_2128'),
        ('location', '0067_auto_20181230_1834'),
    ]

    operations = [
    ]
