# Generated by Django 2.0.5 on 2019-01-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0076_merge_20190109_1523'),
        ('location', '0076_merge_20190109_1456'),
    ]

    operations = [
    ]
