# Generated by Django 2.0.5 on 2019-01-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0077_merge_20190109_1556'),
        ('location', '0071_auto_20190108_1653'),
    ]

    operations = [
    ]
