# Generated by Django 2.0.5 on 2019-01-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0078_merge_20190109_1922'),
    ]

    operations = [
        migrations.RunSQL(
            '''CREATE OR REPLACE FUNCTION slugify_url(url varchar) RETURNS VARCHAR AS
            $$
            DECLARE
                result varchar;
            BEGIN
                result := regexp_replace(regexp_replace(regexp_replace(lower(url), '[^a-zA-Z0-9_, -]','','g'),'[_,-]',' ','g'),'[ -]+','-','g');
                result := trim(both '-' from result);
                RETURN result;
            END;
            $$
            LANGUAGE PLPGSQL;'''
        ),
    ]
