# Generated by Django 2.0.5 on 2019-01-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0067_merge_20190103_1222'),
        ('location', '0078_merge_20190109_1922'),
    ]

    operations = [
    ]
