# Generated by Django 2.0.5 on 2019-01-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0079_create_slugify_utl_function'),
        ('location', '0079_merge_20190111_1522'),
    ]

    operations = [
    ]
