# Generated by Django 2.0.5 on 2019-02-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0081_auto_20190129_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityLatLong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'city_lat_long',
            },
        ),
    ]
