# Generated by Django 2.0.5 on 2019-03-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0082_citylatlong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityurls',
            name='sitemap_identifier',
            field=models.CharField(choices=[('DOCTORS_CITY', 'DOCTORS_CITY'), ('DOCTORS_LOCALITY_CITY', 'DOCTORS_LOCALITY_CITY'), ('DOCTOR_PAGE', 'DOCTOR_PAGE'), ('LAB_CITY', 'LAB_CITY'), ('LAB_LOCALITY_CITY', 'LAB_LOCALITY_CITY'), ('LAB_PAGE', 'LAB_PAGE'), ('LAB_TEST', 'LAB_TEST'), ('SPECIALIZATION_CITY', 'SPECIALIZATION_CITY'), ('SPECIALIZATION_LOCALITY_CITY', 'SPECIALIZATION_LOCALITY_CITY')], max_length=28, null=True),
        ),
    ]
