# Generated by Django 2.0.5 on 2019-03-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0083_auto_20190313_1345'),
        ('location', '0083_auto_20190313_1224'),
    ]

    operations = [
    ]
