# Generated by Django 2.0.5 on 2019-03-19 08:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0084_merge_20190314_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityurls',
            name='bookable_doctors_count',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='tempurl',
            name='bookable_doctors_count',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
