# Generated by Django 2.0.5 on 2019-03-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0083_auto_20190313_1357'),
        ('location', '0084_merge_20190314_1707'),
    ]

    operations = [
    ]
