# Generated by Django 2.0.5 on 2019-04-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0085_merge_20190320_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityurls',
            name='ipd_procedure',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='entityurls',
            name='ipd_procedure_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tempurl',
            name='ipd_procedure',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='tempurl',
            name='ipd_procedure_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
