# Generated by Django 2.0.5 on 2019-04-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0085_merge_20190320_1344'),
        ('location', '0085_auto_20190319_1346'),
    ]

    operations = [
    ]
