# Generated by Django 2.0.5 on 2019-04-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0086_auto_20190419_1207'),
        ('location', '0087_auto_20190422_1700'),
    ]

    operations = [
    ]
