# Generated by Django 2.0.5 on 2019-04-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0087_auto_20190430_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareseourls',
            name='url',
            field=models.SlugField(max_length=2000, null=True, unique=True),
        ),
    ]
