# Generated by Django 2.0.5 on 2019-04-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0088_merge_20190422_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityurls',
            name='sitemap_identifier',
            field=models.CharField(choices=[('DOCTORS_CITY', 'DOCTORS_CITY'), ('DOCTORS_LOCALITY_CITY', 'DOCTORS_LOCALITY_CITY'), ('DOCTOR_PAGE', 'DOCTOR_PAGE'), ('HOSPITALS_CITY', 'HOSPITALS_CITY'), ('HOSPITALS_LOCALITY_CITY', 'HOSPITALS_LOCALITY_CITY'), ('HOSPITAL_PAGE', 'HOSPITAL_PAGE'), ('IPD_PROCEDURE_CITY', 'IPD_PROCEDURE_CITY'), ('LAB_CITY', 'LAB_CITY'), ('LAB_LOCALITY_CITY', 'LAB_LOCALITY_CITY'), ('LAB_PAGE', 'LAB_PAGE'), ('LAB_TEST', 'LAB_TEST'), ('SPECIALIZATION_CITY', 'SPECIALIZATION_CITY'), ('SPECIALIZATION_LOCALITY_CITY', 'SPECIALIZATION_LOCALITY_CITY')], max_length=28, null=True),
        ),
    ]
