# Generated by Django 2.0.5 on 2019-05-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0088_auto_20190430_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareseourls',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
