# Generated by Django 2.0.5 on 2019-04-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0089_auto_20190423_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityurls',
            name='sitemap_identifier',
            field=models.CharField(choices=[('DOCTORS_CITY', 'DOCTORS_CITY'), ('DOCTORS_LOCALITY_CITY', 'DOCTORS_LOCALITY_CITY'), ('DOCTOR_PAGE', 'DOCTOR_PAGE'), ('HOSPITALS_CITY', 'HOSPITALS_CITY'), ('HOSPITALS_LOCALITY_CITY', 'HOSPITALS_LOCALITY_CITY'), ('HOSPITAL_PAGE', 'HOSPITAL_PAGE'), ('IPD_PROCEDURE_CITY', 'IPD_PROCEDURE_CITY'), ('IPD_PROCEDURE_DOCTOR_CITY', 'IPD_PROCEDURE_DOCTOR_CITY'), ('IPD_PROCEDURE_HOSPITAL_CITY', 'IPD_PROCEDURE_HOSPITAL_CITY'), ('LAB_CITY', 'LAB_CITY'), ('LAB_LOCALITY_CITY', 'LAB_LOCALITY_CITY'), ('LAB_PAGE', 'LAB_PAGE'), ('LAB_TEST', 'LAB_TEST'), ('SPECIALIZATION_CITY', 'SPECIALIZATION_CITY'), ('SPECIALIZATION_LOCALITY_CITY', 'SPECIALIZATION_LOCALITY_CITY')], max_length=28, null=True),
        ),
    ]
