# Generated by Django 2.0.5 on 2019-05-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0090_auto_20190426_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityurls',
            name='ipd_procedure',
            field=models.TextField(default=None, null=True),
        ),
    ]
