# Generated by Django 2.0.5 on 2019-05-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0089_compareseourls_title'),
        ('location', '0092_auto_20190507_1713'),
    ]

    operations = [
    ]
