# Generated by Django 2.0.5 on 2020-02-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0093_merge_20190508_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polygon_data', models.TextField(blank=True, null=True)),
                ('center_point_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cluster_map',
            },
        ),
    ]
