# Generated by Django 2.0.5 on 2020-02-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0094_clustermap'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustermap',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
