# Generated by Django 2.0.5 on 2018-06-11 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_type', models.PositiveSmallIntegerField(choices=[('', 'Select'), (1, 'Product'), (2, 'Technology'), (3, 'Sales'), (4, 'Content'), (5, 'Marketing'), (6, 'QC'), (7, 'Support'), (8, 'Doctors')])),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resumes')),
            ],
            options={
                'db_table': 'careers',
            },
        ),
        migrations.CreateModel(
            name='OnlineLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_type', models.PositiveSmallIntegerField(choices=[('', 'Select'), (1, 'Doctor'), (2, 'Diagnostic Center'), (3, 'Hospital/Clinic')])),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'online_leads',
            },
        ),
    ]
