# Generated by Django 2.0.2 on 2018-07-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180625_0851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Careers',
            new_name='Career',
        ),
        migrations.RenameModel(
            old_name='OnlineLeads',
            new_name='OnlineLead',
        ),
        migrations.AlterModelTable(
            name='career',
            table='career',
        ),
        migrations.AlterModelTable(
            name='onlinelead',
            table='online_lead',
        ),
    ]
