# Generated by Django 2.0.2 on 2018-07-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180703_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinelead',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
