# Generated by Django 2.0.2 on 2018-07-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_onlinelead_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelead',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
    ]
