# Generated by Django 2.0.7 on 2018-08-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180723_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinelead',
            name='speciality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
