# Generated by Django 2.0.5 on 2018-08-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinyUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_url', models.URLField(max_length=256)),
                ('hash', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tiny_url',
            },
        ),
    ]
