# Generated by Django 2.0.5 on 2018-08-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_tinyurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurl',
            name='hash',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tinyurl',
            name='original_url',
            field=models.URLField(max_length=5000),
        ),
    ]
