# Generated by Django 2.0.5 on 2018-08-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20180829_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tinyurl',
            old_name='hash',
            new_name='short_code',
        ),
    ]
