# Generated by Django 2.0.5 on 2018-09-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_onlinelead_city_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelead',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
