# Generated by Django 2.0.5 on 2018-09-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20180903_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinelead',
            old_name='city_mapping',
            new_name='city_name',
        ),
    ]
