# Generated by Django 2.0.5 on 2018-09-04 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20180903_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinelead',
            name='city_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Cities'),
        ),
    ]
