# Generated by Django 2.0.5 on 2018-09-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20180904_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinelead',
            name='matrix_lead_id',
            field=models.IntegerField(null=True),
        ),
    ]
