# Generated by Django 2.0.5 on 2018-09-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_onlinelead_matrix_lead_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=84)),
                ('image', models.ImageField(upload_to='web/custom_images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
