# Generated by Django 2.0.5 on 2018-09-19 12:14

from django.db import migrations, models
import django.contrib.postgres.fields.jsonb


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinelead',
            name='utm_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
