# Generated by Django 2.0.5 on 2018-09-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_tinyurlhits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurl',
            name='short_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='tinyurlhits',
            table='tiny_url_hits',
        ),
    ]
