# Generated by Django 2.0.5 on 2018-10-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20180927_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinelead',
            name='source',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
