# Generated by Django 2.0.5 on 2019-01-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_nonbookabledoctorlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonbookabledoctorlead',
            name='masked_mobile',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='nonbookabledoctorlead',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='nonbookabledoctorlead',
            name='to_mobile',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
