# Generated by Django 2.0.5 on 2019-04-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20190108_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='from_app',
            field=models.BooleanField(default=False),
        ),
    ]
