# Generated by Django 2.0.5 on 2020-01-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20191120_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.FileField(upload_to='web/custom_images'),
        ),
    ]
