# Generated by Django 2.0.5 on 2018-06-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_consumeraccount_consumertransaction_pgtransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumertransaction',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='consumertransaction',
            old_name='order',
            new_name='reference_id',
        ),
        migrations.AddField(
            model_name='consumertransaction',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='error_status',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Error'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_viewable',
            field=models.BooleanField(default=True, verbose_name='Is Viewable'),
        ),
    ]
