# Generated by Django 2.0.5 on 2018-06-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180618_1244'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consumertransaction',
            table='consumer_transaction',
        ),
    ]
