# Generated by Django 2.0.6 on 2018-06-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180619_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgtransaction',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='pgtransaction',
            old_name='product',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='pgtransaction',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
