# Generated by Django 2.0.6 on 2018-06-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180619_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumertransaction',
            name='reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
