# Generated by Django 2.0.6 on 2018-07-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180706_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgtransaction',
            name='order_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
