# Generated by Django 2.0.6 on 2018-07-13 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0012_pgtransaction_order_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('refund_state', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Completed')], default=1)),
                ('consumer_transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.ConsumerTransaction')),
            ],
            options={
                'db_table': 'consumer_refund',
            },
        ),
        migrations.AddField(
            model_name='pgtransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consumerrefund',
            name='pg_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.PgTransaction'),
        ),
        migrations.AddField(
            model_name='consumerrefund',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
