# Generated by Django 2.0.5 on 2018-07-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_pgtransaction_order_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.PositiveIntegerField()),
                ('product_id', models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID')])),
                ('file', models.FileField(upload_to='doctor/documents/invoices')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
