# Generated by Django 2.0.5 on 2018-07-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180717_1418'),
        ('account', '0014_auto_20180716_1039'),
    ]

    operations = [
    ]
