# Generated by Django 2.0.5 on 2018-07-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_merge_20180718_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerrefund',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pgtransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
