# Generated by Django 2.0.6 on 2018-07-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20180720_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumertransaction',
            name='product_id',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID')], null=True),
        ),
    ]
