# Generated by Django 2.0.6 on 2018-07-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20180723_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgtransaction',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
