# Generated by Django 2.0.6 on 2018-07-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20180723_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
