# Generated by Django 2.0.6 on 2018-08-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20180727_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgtransaction',
            name='order_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
