# Generated by Django 2.0.2 on 2018-08-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20180726_1456'),
        ('account', '0021_auto_20180807_1129'),
    ]

    operations = [
    ]
