# Generated by Django 2.0.5 on 2018-09-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_merge_20180807_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerrefund',
            name='refund_state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (10, 'Completed')], default=1),
        ),
    ]
