# Generated by Django 2.0.5 on 2018-10-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20180906_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
