# Generated by Django 2.0.5 on 2018-10-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20181012_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerrefund',
            name='refund_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
