# Generated by Django 2.0.5 on 2018-11-06 06:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_order_matrix_lead_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.CharField(blank=True, max_length=10, null=True)),
                ('referer_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('appointment_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'order_log',
            },
        ),
    ]
