# Generated by Django 2.0.5 on 2018-11-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_orderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
