# Generated by Django 2.0.5 on 2018-11-13 13:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20181106_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='pg_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
