# Generated by Django 2.0.5 on 2018-11-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20181106_1255'),
        ('account', '0027_order_wallet_amount'),
    ]

    operations = [
    ]
