# Generated by Django 2.0.5 on 2018-11-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_orderlog_pg_data'),
        ('account', '0030_merge_20181112_1603'),
    ]

    operations = [
    ]
