# Generated by Django 2.0.5 on 2018-12-03 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0031_merge_20181114_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID')])),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'Credit'), (1, 'Debit')])),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('response_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=15, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('pg_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status_type', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('pb_gateway_name', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dummy_txn', to='account.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dummy_transaction',
            },
        ),
    ]
