# Generated by Django 2.0.5 on 2018-11-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20181012_1729'),
        ('account', '0031_merge_20181114_1519'),
    ]

    operations = [
    ]
