# Generated by Django 2.0.5 on 2018-12-03 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_merge_20181114_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.PgTransaction'),
        ),
    ]
