# Generated by Django 2.0.5 on 2018-12-03 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20181203_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummytransactions',
            name='order_id',
        ),
        migrations.AddField(
            model_name='dummytransactions',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dummy_txn', to='account.Order'),
        ),
    ]
