# Generated by Django 2.0.5 on 2018-12-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_auto_20181203_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummytransactions',
            name='bank_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dummytransactions',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dummytransactions',
            name='currency',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dummytransactions',
            name='pb_gateway_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dummytransactions',
            name='pg_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dummytransactions',
            name='response_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dummytransactions',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dummytransactions',
            name='status_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
