# Generated by Django 2.0.5 on 2018-12-04 09:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('authentication', '0077_auto_20181204_1311'),
        ('account', '0034_auto_20181203_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charged_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_approved', models.BooleanField(default=False)),
                ('status', models.PositiveIntegerField()),
                ('payout_time', models.DateTimeField(blank=True, null=True)),
                ('api_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('paid_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payouts', to='authentication.Merchant')),
            ],
            options={
                'db_table': 'merchant_payout',
            },
        ),
    ]
