# Generated by Django 2.0.5 on 2018-12-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_merchantpayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpayout',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Paid')], default=1),
        ),
    ]
