# Generated by Django 2.0.5 on 2018-12-04 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_auto_20181204_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpayout',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='merchantpayout',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
