# Generated by Django 2.0.5 on 2018-12-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_auto_20181204_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpayout',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'ATTEMPTED'), (3, 'Paid')], default=1),
        ),
    ]
