# Generated by Django 2.0.5 on 2018-12-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_auto_20181205_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummytransactions',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
