# Generated by Django 2.0.5 on 2018-12-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_auto_20181205_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumeraccount',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
