# Generated by Django 2.0.5 on 2018-12-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_merge_20181115_1407'),
        ('account', '0040_auto_20181205_1750'),
    ]

    operations = [
    ]
