# Generated by Django 2.0.5 on 2018-12-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_merge_20181218_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummytransactions',
            name='product_id',
            field=models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID')]),
        ),
    ]
