# Generated by Django 2.0.5 on 2018-12-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_order_cashback_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumertransaction',
            name='action',
            field=models.SmallIntegerField(choices=[(0, 'Cancellation'), (1, 'Payment'), (2, 'Refund'), (3, 'Sale'), (4, 'CashbackCredit')]),
        ),
    ]
