# Generated by Django 2.0.5 on 2018-12-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_auto_20181219_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumertransaction',
            name='source',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Wallet'), (2, 'Cashback')], null=True),
        ),
    ]
