# Generated by Django 2.0.5 on 2018-12-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_consumertransaction_source'),
        ('account', '0042_auto_20181219_1424'),
    ]

    operations = [
    ]
