# Generated by Django 2.0.5 on 2019-01-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_consumertransaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpayout',
            name='payout_ref_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
