# Generated by Django 2.0.5 on 2019-01-11 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20190102_1136'),
        ('account', '0045_merchantpayout_payout_ref_id'),
    ]

    operations = [
    ]
