# Generated by Django 2.0.5 on 2019-01-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_auto_20190111_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID')], null=True),
        ),
    ]
