# Generated by Django 2.0.5 on 2019-01-17 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0050_auto_20190115_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cashback', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'money_pool',
            },
        ),
    ]
