# Generated by Django 2.0.5 on 2019-02-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_auto_20190117_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgtransaction',
            name='bank_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pgtransaction',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pgtransaction',
            name='currency',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pgtransaction',
            name='pb_gateway_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pgtransaction',
            name='pg_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
