# Generated by Django 2.0.5 on 2019-01-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_auto_20190117_1657'),
        ('account', '0055_order_user'),
    ]

    operations = [
    ]
