# Generated by Django 2.0.5 on 2019-02-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_merge_20190129_1408'),
        ('account', '0053_auto_20190205_1720'),
    ]

    operations = [
    ]
