# Generated by Django 2.0.5 on 2019-02-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_merge_20190129_1408'),
        ('account', '0045_merge_20181228_1550'),
    ]

    operations = [
    ]
