# Generated by Django 2.0.5 on 2019-02-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_merge_20190205_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Payment Accepted'), (0, 'Payment Pending'), (3, 'Payment Failure')], default=0),
        ),
    ]
