# Generated by Django 2.0.5 on 2019-02-11 05:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_merge_20190205_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visitor_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
