# Generated by Django 2.0.5 on 2019-02-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_merge_20190205_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpayout',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('NEFT', 'NEFT'), ('IMPS', 'IMPS'), ('IFT', 'IFT')], max_length=100, null=True),
        ),
    ]
