# Generated by Django 2.0.5 on 2019-02-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_merchantpayout_payment_mode'),
        ('account', '0058_auto_20190212_1042'),
    ]

    operations = [
    ]
