# Generated by Django 2.0.5 on 2019-02-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_order_visitor_info'),
        ('account', '0059_merge_20190212_1151'),
    ]

    operations = [
    ]
