# Generated by Django 2.0.5 on 2019-03-14 10:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_merge_20190212_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpayout',
            name='pg_status',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='merchantpayout',
            name='status_api_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True),
        ),
    ]
