# Generated by Django 2.0.5 on 2019-03-01 08:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_merge_20190212_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='PgLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decoded_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('coded_response', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pg_log',
            },
        ),
    ]
