# Generated by Django 2.0.5 on 2019-03-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_pglogs'),
        ('account', '0057_merge_20190204_1401'),
    ]

    operations = [
    ]
