# Generated by Django 2.0.5 on 2019-03-19 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_pglogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreferrals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='referral', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
