# Generated by Django 2.0.5 on 2019-03-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_pglogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumertransaction',
            name='product_id',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'SUBSCRIPTION_PLAN_PRODUCT_ID')], null=True),
        ),
        migrations.AlterField(
            model_name='dummytransactions',
            name='product_id',
            field=models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'SUBSCRIPTION_PLAN_PRODUCT_ID')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product_id',
            field=models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'SUBSCRIPTION_PLAN_PRODUCT_ID')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='action',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('', 'Select'), (1, 'Opd Reschedule'), (2, 'Opd Create'), (4, 'Lab Create'), (3, 'Lab Reschedule'), (5, 'Subscription Plan Buy')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'SUBSCRIPTION_PLAN_PRODUCT_ID')], null=True),
        ),
        migrations.AlterField(
            model_name='pgtransaction',
            name='product_id',
            field=models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'SUBSCRIPTION_PLAN_PRODUCT_ID')]),
        ),
    ]
