# Generated by Django 2.0.5 on 2019-03-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_auto_20190314_1617'),
        ('account', '0062_auto_20190319_1410'),
    ]

    operations = [
    ]
