# Generated by Django 2.0.5 on 2019-03-19 10:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_merge_20190319_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpayout',
            name='status_api_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', editable=False),
        ),
    ]
