# Generated by Django 2.0.5 on 2019-03-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_auto_20190318_1424'),
        ('account', '0064_auto_20190319_1555'),
    ]

    operations = [
    ]
