# Generated by Django 2.0.5 on 2019-03-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_merge_20190320_1605'),
        ('account', '0064_merge_20190313_1047'),
    ]

    operations = [
    ]
