# Generated by Django 2.0.5 on 2019-04-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0068_auto_20190404_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumertransaction',
            name='reference_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
