# Generated by Django 2.0.5 on 2019-04-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0069_auto_20190411_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpayout',
            name='booking_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Doctor Booking'), (2, 'Lab Booking'), (3, 'Insurance Booking')], null=True),
        ),
    ]
