# Generated by Django 2.0.5 on 2019-04-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0071_merchantpayout_request_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummytransactions',
            name='reference_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
