# Generated by Django 2.0.5 on 2019-06-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('account', '0073_auto_20190425_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('payout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.MerchantPayout')),
            ],
            options={
                'db_table': 'payout_mapping',
            },
        ),
        migrations.AddField(
            model_name='dummytransactions',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
