# Generated by Django 2.0.5 on 2019-06-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0073_auto_20190425_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipt'),
        ),
    ]
