# Generated by Django 2.0.5 on 2019-06-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0074_auto_20190611_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutmapping',
            name='object_id',
            field=models.BigIntegerField(),
        ),
    ]
