# Generated by Django 2.0.5 on 2019-06-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0075_auto_20190611_1642'),
        ('account', '0074_auto_20190610_1115'),
    ]

    operations = [
    ]
