# Generated by Django 2.0.5 on 2019-06-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0076_merge_20190612_1344'),
        ('account', '0074_auto_20190523_1803'),
    ]

    operations = [
    ]
