# Generated by Django 2.0.5 on 2019-07-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0076_merge_20190612_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpayout',
            name='tds_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
