# Generated by Django 2.0.5 on 2019-07-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0077_merchantpayout_tds_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpayout',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'ATTEMPTED'), (3, 'Paid'), (4, 'Initiated'), (5, 'Failed')], default=1),
        ),
    ]
