# Generated by Django 2.0.5 on 2019-07-15 08:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0078_auto_20190712_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPayoutLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('req_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('res_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('merchant_payout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.MerchantPayout')),
            ],
            options={
                'db_table': 'merchant_payout_log',
            },
        ),
    ]
