# Generated by Django 2.0.5 on 2019-07-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0077_merchantpayout_tds_amount'),
        ('account', '0078_auto_20190618_1306'),
    ]

    operations = [
    ]
