# Generated by Django 2.0.5 on 2019-07-16 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0079_merchantpayoutlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpayout',
            name='recreated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.MerchantPayout'),
        ),
    ]
