# Generated by Django 2.0.5 on 2019-07-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0081_auto_20190716_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpayout',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'ATTEMPTED'), (3, 'Paid'), (4, 'Initiated'), (5, 'In Process'), (6, 'Failed from Queue'), (7, 'Failed from Detail')], default=1),
        ),
    ]
