# Generated by Django 2.0.5 on 2019-07-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0082_auto_20190716_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpayoutlog',
            name='endpoint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
