# Generated by Django 2.0.5 on 2019-07-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0080_pgtransaction_payment_captured'),
        ('account', '0083_merchantpayoutlog_endpoint'),
    ]

    operations = [
    ]
