# Generated by Django 2.0.5 on 2019-07-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0084_merge_20190717_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPayoutBulkProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_ids', models.TextField()),
            ],
            options={
                'db_table': 'merchant_payout_bulk_process',
            },
        ),
    ]
