# Generated by Django 2.0.5 on 2019-07-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0084_merge_20190717_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='PgStatusCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.PositiveSmallIntegerField(default=1)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'pg_status_code',
            },
        ),
    ]
