# Generated by Django 2.0.5 on 2019-07-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0085_merchantpayoutbulkprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpayoutbulkprocess',
            name='payout_ids',
            field=models.TextField(help_text='Enter comma separated payout ids here.'),
        ),
    ]
