# Generated by Django 2.0.5 on 2019-07-18 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0085_pgstatuscode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProcessStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_status', models.PositiveSmallIntegerField(choices=[(1, 'Initiated'), (2, 'Success'), (3, 'Failure')], default=1, editable=False)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_process_status',
            },
        ),
    ]
