# Generated by Django 2.0.5 on 2019-07-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0086_auto_20190718_1628'),
        ('account', '0087_auto_20190722_1253'),
    ]

    operations = [
    ]
