# Generated by Django 2.0.5 on 2019-07-24 06:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('authentication', '0108_merge_20190718_1833'),
        ('account', '0088_merge_20190722_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceMerchantPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('NEFT', 'NEFT'), ('IMPS', 'IMPS'), ('IFT', 'IFT')], max_length=100, null=True)),
                ('payout_ref_id', models.IntegerField(null=True, unique=True)),
                ('charged_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_approved', models.BooleanField(default=False)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'ATTEMPTED'), (3, 'Paid'), (4, 'Initiated'), (5, 'In Process'), (6, 'Failed from Queue'), (7, 'Failed from Detail')], default=1)),
                ('payout_time', models.DateTimeField(blank=True, null=True)),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', editable=False)),
                ('api_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status_api_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', editable=False)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('utr_no', models.CharField(blank=True, default='', max_length=500)),
                ('pg_status', models.CharField(blank=True, default='', max_length=500)),
                ('type', models.PositiveIntegerField(blank=True, choices=[(1, 'Automatic'), (2, 'Manual')], default=None, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('booking_type', models.IntegerField(blank=True, choices=[(1, 'Doctor Booking'), (2, 'Lab Booking'), (3, 'Insurance Purchase')], null=True)),
                ('tds_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('paid_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.Merchant')),
                ('recreated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.AdvanceMerchantPayout')),
            ],
            options={
                'db_table': 'advance_merchant_payout',
            },
        ),
    ]
