# Generated by Django 2.0.5 on 2019-07-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0090_advancemerchantamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpayout',
            name='remarks',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
