# Generated by Django 2.0.5 on 2019-07-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0091_merchantpayout_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancemerchantamount',
            name='total_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
