# Generated by Django 2.0.5 on 2019-07-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0092_advancemerchantamount_total_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancemerchantamount',
            old_name='total_balance',
            new_name='total_amount',
        ),
    ]
