# Generated by Django 2.0.5 on 2019-07-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0093_auto_20190726_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprocessstatus',
            name='current_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Initiate'), (2, 'Authorize'), (3, 'Success'), (4, 'Failure'), (5, 'Capture'), (6, 'Release')], default=1, editable=False),
        ),
    ]
