# Generated by Django 2.0.5 on 2019-08-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0094_auto_20190731_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPayoutProxy',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('account.merchantpayout',),
        ),
    ]
