# Generated by Django 2.0.5 on 2019-08-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0095_merchantpayoutproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchantPayoutProxy',
        ),
    ]
