# Generated by Django 2.0.5 on 2019-08-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0089_auto_20190726_1301'),
        ('account', '0096_delete_merchantpayoutproxy'),
    ]

    operations = [
    ]
