# Generated by Django 2.0.5 on 2019-08-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0097_merge_20190808_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgtransaction',
            name='reference_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
