# Generated by Django 2.0.5 on 2019-08-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0098_auto_20190823_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumertransaction',
            name='product_id',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID'), (11, 'VIP_PRODUCT_ID')], null=True),
        ),
        migrations.AlterField(
            model_name='dummytransactions',
            name='product_id',
            field=models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID'), (11, 'VIP_PRODUCT_ID')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product_id',
            field=models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID'), (11, 'VIP_PRODUCT_ID')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='action',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('', 'Select'), (1, 'Opd Reschedule'), (2, 'Opd Create'), (4, 'Lab Create'), (3, 'Lab Reschedule'), (5, 'Insurance Create'), (6, 'Subscription Plan Buy'), (7, 'Chat Consultation Create'), (11, 'Vip create')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID'), (11, 'VIP_PRODUCT_ID')], null=True),
        ),
        migrations.AlterField(
            model_name='pgtransaction',
            name='product_id',
            field=models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID'), (11, 'VIP_PRODUCT_ID')]),
        ),
    ]
