# Generated by Django 2.0.5 on 2019-09-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0099_auto_20190902_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumertransaction',
            name='action',
            field=models.SmallIntegerField(choices=[(0, 'Cancellation'), (1, 'Payment'), (2, 'Refund'), (3, 'Sale'), (4, 'CashbackCredit'), (5, 'ReferralCredit'), (6, 'PromotionalDebit')]),
        ),
    ]
