# Generated by Django 2.0.5 on 2019-08-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0099_auto_20190813_1542'),
        ('account', '0098_auto_20190823_1213'),
    ]

    operations = [
    ]
