# Generated by Django 2.0.5 on 2019-09-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0100_merge_20190830_1755'),
        ('account', '0099_auto_20190830_1739'),
    ]

    operations = [
    ]
