# Generated by Django 2.0.5 on 2019-09-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0100_auto_20190902_1653'),
        ('account', '0102_auto_20190903_1950'),
    ]

    operations = [
    ]
