# Generated by Django 2.0.5 on 2019-09-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0104_auto_20190925_1427'),
    ]

    operations = [
        migrations.RunSQL(
            '''CREATE UNIQUE INDEX pg_transaction_order_id_order_no_deleted_null_uniq ON pg_transaction (order_id, order_no) WHERE deleted IS NULL;'''
        ),
    ]
