# Generated by Django 2.0.5 on 2019-09-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0105_auto_20190926_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerrefund',
            name='refund_state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (10, 'Completed'), (5, 'Requested'), (15, 'Archived')], default=1),
        ),
    ]
