# Generated by Django 2.0.5 on 2019-09-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0106_auto_20190927_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumertransaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
