# Generated by Django 2.0.5 on 2019-09-30 14:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0107_consumertransaction_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumertransaction',
            name='ref_txns',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
