# Generated by Django 2.0.5 on 2019-10-01 10:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0109_auto_20191001_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumertransaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
