# Generated by Django 2.0.5 on 2019-11-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0110_auto_20191001_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumertransaction',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
