# Generated by Django 2.0.5 on 2019-11-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0111_order_single_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumertransaction',
            name='product_id',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID'), (11, 'VIP_PRODUCT_ID'), (8, 'GOLD_PRODUCT_ID'), (6, 'Provider Econsult')], null=True),
        ),
        migrations.AlterField(
            model_name='dummytransactions',
            name='product_id',
            field=models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID'), (11, 'VIP_PRODUCT_ID'), (8, 'GOLD_PRODUCT_ID'), (6, 'Provider Econsult')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product_id',
            field=models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID'), (11, 'VIP_PRODUCT_ID'), (8, 'GOLD_PRODUCT_ID'), (6, 'Provider Econsult')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='action',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('', 'Select'), (1, 'Opd Reschedule'), (2, 'Opd Create'), (4, 'Lab Create'), (3, 'Lab Reschedule'), (5, 'Insurance Create'), (6, 'Subscription Plan Buy'), (7, 'Chat Consultation Create'), (11, 'Vip create'), (12, 'Gold create'), (8, 'Provider Econsult Pay')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID'), (11, 'VIP_PRODUCT_ID'), (8, 'GOLD_PRODUCT_ID'), (6, 'Provider Econsult')], null=True),
        ),
        migrations.AlterField(
            model_name='pgtransaction',
            name='product_id',
            field=models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID'), (11, 'VIP_PRODUCT_ID'), (8, 'GOLD_PRODUCT_ID'), (6, 'Provider Econsult')]),
        ),
    ]
