# Generated by Django 2.0.5 on 2019-11-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0112_auto_20191121_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgtransaction',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pgtransaction',
            unique_together={('order', 'order_no', 'deleted', 'transaction_id')},
        ),
    ]
