# Generated by Django 2.0.5 on 2019-11-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0113_auto_20191127_1041'),
        ('account', '0112_auto_20191122_1712'),
    ]

    operations = [
    ]
