# Generated by Django 2.0.5 on 2019-12-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0113_auto_20191128_1735'),
        ('account', '0114_merge_20191127_1822'),
    ]

    operations = [
    ]
