# Generated by Django 2.0.5 on 2019-12-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0115_merge_20191205_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumertransaction',
            name='product_id',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID'), (11, 'VIP_PRODUCT_ID'), (8, 'GOLD_PRODUCT_ID'), (6, 'Provider Econsult'), (13, 'Partner Lab Order')], null=True),
        ),
        migrations.AlterField(
            model_name='dummytransactions',
            name='product_id',
            field=models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID'), (11, 'VIP_PRODUCT_ID'), (8, 'GOLD_PRODUCT_ID'), (6, 'Provider Econsult'), (13, 'Partner Lab Order')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product_id',
            field=models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID'), (11, 'VIP_PRODUCT_ID'), (8, 'GOLD_PRODUCT_ID'), (6, 'Provider Econsult'), (13, 'Partner Lab Order')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID'), (11, 'VIP_PRODUCT_ID'), (8, 'GOLD_PRODUCT_ID'), (6, 'Provider Econsult'), (13, 'Partner Lab Order')], null=True),
        ),
        migrations.AlterField(
            model_name='pgtransaction',
            name='product_id',
            field=models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID'), (11, 'VIP_PRODUCT_ID'), (8, 'GOLD_PRODUCT_ID'), (6, 'Provider Econsult'), (13, 'Partner Lab Order')]),
        ),
    ]
