# Generated by Django 2.0.5 on 2020-02-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0115_auto_20191205_1545'),
        ('account', '0116_auto_20191205_1534'),
    ]

    operations = [
    ]
