# Generated by Django 2.0.5 on 2020-02-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0116_auto_20191205_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpayout',
            name='payout_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Provider Payout'), (2, 'Revenue Payout')], default=None, null=True),
        ),
    ]
