# Generated by Django 2.0.5 on 2020-02-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0118_revenuepayoutmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenuepayoutmapping',
            name='payout',
        ),
        migrations.AddField(
            model_name='revenuepayoutmapping',
            name='provider_payout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_payout', to='account.MerchantPayout'),
        ),
        migrations.AddField(
            model_name='revenuepayoutmapping',
            name='revenue_payout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_payout', to='account.MerchantPayout'),
        ),
    ]
