# Generated by Django 2.0.5 on 2020-03-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0117_merge_20200226_1306'),
        ('account', '0119_auto_20200220_1703'),
    ]

    operations = [
    ]
