# Generated by Django 2.0.5 on 2018-05-15 08:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('lab', models.CharField(max_length=256)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'hospital_lead',
            },
        ),
    ]
