# Generated by Django 2.0.5 on 2018-05-25 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0038_medicalcondition'),
        ('lead', '0002_doctorlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorlead',
            name='doctor',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Doctor'),
        ),
        migrations.AddField(
            model_name='hospitallead',
            name='hospital',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Hospital'),
        ),
    ]
