# Generated by Django 2.0.5 on 2018-05-28 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_auto_20180525_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorHospitalLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.DoctorLead')),
                ('hospital_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.HospitalLead')),
            ],
            options={
                'db_table': 'doctor_hospital_lead',
            },
        ),
        migrations.AddField(
            model_name='doctorlead',
            name='hospital_leads',
            field=models.ManyToManyField(through='lead.DoctorHospitalLead', to='lead.HospitalLead'),
        ),
    ]
