# Generated by Django 2.0.5 on 2018-12-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_userlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlead',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'male'), (2, 'female')], null=True),
        ),
        migrations.AlterField(
            model_name='userlead',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userlead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
