# Generated by Django 2.0.5 on 2018-12-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_auto_20181220_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlead',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
