# Generated by Django 2.0.5 on 2018-12-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_auto_20181220_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlead',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=2, null=True),
        ),
    ]
