# Generated by Django 2.0.5 on 2018-12-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_auto_20181220_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlead',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='userlead',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userlead',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
