# Generated by Django 2.0.5 on 2019-08-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plusthreshold',
            name='lab_applicable_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plusthreshold',
            name='lab_discount_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plusthreshold',
            name='lab_total_free_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plusthreshold',
            name='opd_applicable_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plusthreshold',
            name='opd_discount_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plusthreshold',
            name='opd_total_free_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plusthreshold',
            name='package_count_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
