# Generated by Django 2.0.5 on 2019-08-27 11:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0112_user_data'),
        ('plus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=100, null=True)),
                ('pincode', models.PositiveIntegerField(default=None)),
                ('address', models.TextField(default=None)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default=None, max_length=50)),
                ('phone_number', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('title', models.CharField(choices=[('mr.', 'mr.'), ('mrs.', 'mrs.'), ('miss', 'miss'), ('mast.', 'mast.')], default=None, max_length=20)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('town', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('state_code', models.CharField(default='', max_length=10)),
                ('city_code', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('district_code', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plus_members', to='plus.PlusUser')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plus_member', to='authentication.UserProfile')),
            ],
            options={
                'db_table': 'plus_members',
            },
        ),
    ]
