# Generated by Django 2.0.5 on 2019-08-28 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0002_plusmembers'),
        ('plus', '0002_auto_20190827_1754'),
    ]

    operations = [
    ]
