# Generated by Django 2.0.5 on 2019-08-28 10:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0006_plusmembers_plus_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusPlanContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(choices=[('SALIENT_FEATURES', 'SALIENT_FEATURES'), ('WHATS_NOT_COVERED', 'WHATS_NOT_COVERED')], max_length=500)),
                ('content', models.TextField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_content', to='plus.PlusPlans')),
            ],
            options={
                'db_table': 'plus_plan_content',
            },
        ),
        migrations.AddField(
            model_name='plusmembers',
            name='is_primary_user',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='plususer',
            name='raw_plus_member',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
