# Generated by Django 2.0.5 on 2019-08-29 06:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plus', '0007_auto_20190828_1617'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plususer',
            unique_together={('user', 'plan')},
        ),
    ]
