# Generated by Django 2.0.5 on 2019-08-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0008_auto_20190829_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plusplans',
            old_name='amount',
            new_name='deal_price',
        ),
        migrations.AddField(
            model_name='plusplans',
            name='mrp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
