# Generated by Django 2.0.5 on 2019-08-29 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0010_plusplans_tax_rebate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusPlanParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'plus_plan_parameters',
            },
        ),
        migrations.CreateModel(
            name='PlusPlanParametersMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plus.PlusPlanParameters')),
                ('plus_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plus.PlusPlans')),
            ],
            options={
                'db_table': 'plus_plan_parameters_mapping',
            },
        ),
    ]
