# Generated by Django 2.0.5 on 2019-09-02 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0013_plusmembers_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'CREDIT'), (2, 'DEBIT')])),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, 'Plus Plan purchase'), (2, 'Premium payout')], null=True)),
                ('plus_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plus_transactions', to='plus.PlusUser')),
            ],
            options={
                'db_table': 'plus_transaction',
            },
        ),
    ]
