# Generated by Django 2.0.5 on 2019-09-05 10:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0017_auto_20190903_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusUserUtilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilization', django.contrib.postgres.fields.jsonb.JSONField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plus_plans_for_utilization', to='plus.PlusPlans')),
                ('plus_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plus_utilization', to='plus.PlusUser')),
            ],
            options={
                'db_table': 'plus_user_utilization',
            },
        ),
        migrations.AlterUniqueTogether(
            name='plususerutilization',
            unique_together={('plus_user', 'plan')},
        ),
    ]
