# Generated by Django 2.0.5 on 2019-09-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0018_auto_20190905_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='plusproposer',
            name='merchant_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
