# Generated by Django 2.0.5 on 2019-09-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0019_plusproposer_merchant_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plusmembers',
            old_name='town',
            new_name='city',
        ),
    ]
