# Generated by Django 2.0.5 on 2019-09-17 09:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0023_auto_20190911_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='plusplans',
            name='utm_source',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
