# Generated by Django 2.0.5 on 2019-09-18 10:44

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plus', '0024_plusplans_utm_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusDummyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plus_user_dummy_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plus_dummy_data',
            },
        ),
    ]
