# Generated by Django 2.0.5 on 2019-09-19 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0025_plusdummydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusPlanUtmSourceMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plus_plan_utmsources_mapping',
            },
        ),
        migrations.CreateModel(
            name='PlusPlanUtmSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=100)),
                ('source_details', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'plus_plan_utmsources',
            },
        ),
        migrations.RemoveField(
            model_name='plusplans',
            name='utm_source',
        ),
        migrations.AddField(
            model_name='plusplanutmsourcemapping',
            name='plus_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_utmsources', to='plus.PlusPlans'),
        ),
        migrations.AddField(
            model_name='plusplanutmsourcemapping',
            name='utm_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plus.PlusPlanUtmSources'),
        ),
    ]
