# Generated by Django 2.0.5 on 2019-09-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0026_auto_20190919_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='plusplans',
            name='is_retail',
            field=models.NullBooleanField(),
        ),
    ]
