# Generated by Django 2.0.5 on 2019-10-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0028_plususer_payment_type'),
        ('plus', '0030_auto_20191001_1711'),
    ]

    operations = [
    ]
