# Generated by Django 2.0.5 on 2019-10-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0033_plusplans_price_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='plusplans',
            name='is_gold',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='plusplanparameters',
            name='key',
            field=models.CharField(choices=[('CONVENIENCE_AMOUNT', 'CONVENIENCE_AMOUNT'), ('CONVENIENCE_PERCENTAGE', 'CONVENIENCE_PERCENTAGE'), ('DOCTOR_CONSULT_AMOUNT', 'DOCTOR_CONSULT_AMOUNT'), ('DOCTOR_CONSULT_COUNT', 'DOCTOR_CONSULT_COUNT'), ('DOCTOR_CONSULT_DISCOUNT', 'DOCTOR_CONSULT_DISCOUNT'), ('HEALTH_CHECKUPS_AMOUNT', 'HEALTH_CHECKUPS_AMOUNT'), ('HEALTH_CHECKUPS_COUNT', 'HEALTH_CHECKUPS_COUNT'), ('LABTEST_AMOUNT', 'LABTEST_AMOUNT'), ('LABTEST_COUNT', 'LABTEST_COUNT'), ('LAB_DISCOUNT', 'LAB_DISCOUNT'), ('MEMBERS_COVERED_IN_PACKAGE', 'MEMBERS_COVERED_IN_PACKAGE'), ('ONLINE_CHAT_AMOUNT', 'ONLINE_CHAT_AMOUNT'), ('ONLINE_CHAT_COUNT', 'ONLINE_CHAT_COUNT'), ('PACKAGES_COVERED', 'PACKAGES_COVERED'), ('PACKAGE_DISCOUNT', 'PACKAGE_DISCOUNT'), ('PACKAGE_IDS', 'PACKAGE_IDS'), ('PERCENTAGE_DISCOUNT', 'PERCENTAGE_DISCOUNT'), ('SPECIALIZATIONS', 'SPECIALIZATIONS'), ('TOTAL_TEST_COVERED_IN_PACKAGE', 'TOTAL_TEST_COVERED_IN_PACKAGE'), ('TOTAL_WORTH', 'TOTAL_WORTH')], max_length=100),
        ),
    ]
