# Generated by Django 2.0.5 on 2019-10-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0036_auto_20191015_1254'),
        ('plus', '0035_auto_20191015_1302'),
    ]

    operations = [
    ]
