# Generated by Django 2.0.5 on 2019-10-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0037_merge_20191015_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='plusappointmentmapping',
            name='extra_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
