# Generated by Django 2.0.5 on 2019-10-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0038_plusappointmentmapping_extra_charge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plusplans',
            unique_together=set(),
        ),
    ]
