# Generated by Django 2.0.5 on 2019-11-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0039_auto_20191023_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plusmembers',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
