# Generated by Django 2.0.5 on 2019-11-14 09:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0041_tempplususer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempplususer',
            name='raw_plus_member',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
