# Generated by Django 2.0.5 on 2019-11-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0041_auto_20191111_1152'),
        ('plus', '0044_auto_20191118_1020'),
    ]

    operations = [
    ]
