# Generated by Django 2.0.5 on 2019-11-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0047_plusdummydata_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plusmembers',
            name='title',
            field=models.CharField(choices=[('mr.', 'mr.'), ('mrs.', 'mrs.'), ('miss', 'miss'), ('mast.', 'mast.')], default=None, max_length=20, null=True),
        ),
    ]
