# Generated by Django 2.0.5 on 2019-11-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0048_auto_20191126_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempplususer',
            name='is_utilized',
            field=models.NullBooleanField(),
        ),
    ]
