# Generated by Django 2.0.5 on 2019-11-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0042_plususer_coupon'),
        ('plus', '0049_tempplususer_is_utilized'),
    ]

    operations = [
    ]
