# Generated by Django 2.0.5 on 2019-11-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0050_merge_20191127_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='plusplans',
            name='default_single_booking',
            field=models.NullBooleanField(),
        ),
    ]
