# Generated by Django 2.0.5 on 2019-12-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0051_plusplans_default_single_booking'),
        ('plus', '0042_auto_20191121_1643'),
    ]

    operations = [
    ]
