# Generated by Django 2.0.5 on 2019-12-05 05:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0052_merge_20191202_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorporateGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('GOLD', 'GOLD'), ('VIP', 'VIP')], max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlusUserUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(default=None, upload_to='insurance/upload', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])])),
                ('amount', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('paid_through', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CASH'), (2, 'CHEQUE'), (3, 'OTHER')], null=True)),
                ('payment_proof', models.FileField(blank=True, default=None, null=True, upload_to='insurance/upload/payment_proof')),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'plus_user_upload',
            },
        ),
        migrations.AddField(
            model_name='plusplans',
            name='corporate_doctor_upper_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plusplans',
            name='corporate_lab_upper_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plusplans',
            name='corporate_upper_limit_criteria',
            field=models.CharField(blank=True, choices=[('AGREED_PRICE', 'AGREED_PRICE'), ('COD_DEAL_PRICE', 'COD_DEAL_PRICE'), ('DEAL_PRICE', 'DEAL_PRICE'), ('MRP', 'MRP')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plusplans',
            name='is_corporate',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='corporate',
            name='corporate_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='corporate_group', to='plus.CorporateGroup'),
        ),
        migrations.AddField(
            model_name='plusplans',
            name='corporate_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='corporate_plan', to='plus.CorporateGroup'),
        ),
    ]
