# Generated by Django 2.0.5 on 2019-12-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0053_auto_20191205_1123'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='corporate',
            table='plus_corporates',
        ),
        migrations.AlterModelTable(
            name='corporategroup',
            table='plus_corporate_groups',
        ),
    ]
