# Generated by Django 2.0.5 on 2020-01-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0055_auto_20200116_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plususerupload',
            name='paid_through',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CASH'), (2, 'CHEQUE'), (3, 'OTHER'), (4, 'NEFT')], null=True),
        ),
    ]
