# Generated by Django 2.0.5 on 2020-01-16 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_booking', '0012_remove_corporates_corporate_group'),
        ('plus', '0056_auto_20200116_1225'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='plusplans',
        #     name='corporate_group',
        # ),
        migrations.AddField(
            model_name='plusplans',
            name='corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='corporate_plan', to='corporate_booking.Corporates'),
        ),
    ]
