# Generated by Django 2.0.5 on 2020-01-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0057_auto_20200116_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plusplans',
            name='corporate_group',
        ),
    ]
