# Generated by Django 2.0.5 on 2020-02-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0059_delete_corporategroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plusplans',
            name='plan_criteria',
            field=models.CharField(choices=[('AMOUNT_COUNT', 'AMOUNT_COUNT'), ('AMOUNT_DISCOUNT', 'AMOUNT_DISCOUNT'), ('COUNT_DISCOUNT', 'COUNT_DISCOUNT'), ('TOTAL_WORTH', 'TOTAL_WORTH'), ('TOTAL_WORTH_WITH_DISCOUNT', 'TOTAL_WORTH_WITH_DISCOUNT')], max_length=100, null=True),
        ),
    ]
