# Generated by Django 2.0.5 on 2020-02-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0061_auto_20200225_1143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plususerutilization',
            unique_together=set(),
        ),
    ]
