# Generated by Django 2.0.5 on 2020-02-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0062_auto_20200227_1210'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plususer',
            unique_together=set(),
        ),
    ]
