# Generated by Django 2.0.5 on 2020-03-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0062_auto_20200226_1821'),
        ('plus', '0063_auto_20200227_1448'),
    ]

    operations = [
    ]
