# Generated by Django 2.0.5 on 2020-03-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0060_auto_20200302_1539'),
        ('plus', '0064_merge_20200303_1708'),
    ]

    operations = [
    ]
