# Generated by Django 2.0.5 on 2020-03-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0065_merge_20200305_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='plusplans',
            name='chat_plan_description',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
