# Generated by Django 2.0.4 on 2018-04-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20180426_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='users/images', width_field='width'),
        ),
    ]
