# Generated by Django 2.0.4 on 2018-04-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20180426_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpVerifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=10)),
                ('country_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'otp_verification',
            },
        ),
    ]
