# Generated by Django 2.0.4 on 2018-04-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_otpverifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverifications',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
