# Generated by Django 2.0.4 on 2018-04-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20180430_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverifications',
            name='token',
        ),
        migrations.AddField(
            model_name='otpverifications',
            name='isExpired',
            field=models.BooleanField(default=False),
        ),
    ]
