# Generated by Django 2.0.4 on 2018-04-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20180430_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mobile',
            new_name='phone_number',
        ),
    ]
