# Generated by Django 2.0.5 on 2018-05-29 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20180529_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='land_mark',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='place_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.UserProfile'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.PositiveIntegerField(choices=[('home', 'Home Address'), ('office', 'Work Address'), ('other', 'Other')]),
        ),
    ]
