# Generated by Django 2.0.5 on 2018-05-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20180529_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('home', 'Home Address'), ('office', 'Work Address'), ('other', 'Other')], max_length=20),
        ),
    ]
