# Generated by Django 2.0.5 on 2018-05-31 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20180529_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_permission', to='doctor.Doctor'),
        ),
    ]
