# Generated by Django 2.0.5 on 2018-05-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20180529_1534'),
        ('authentication', '0017_auto_20180531_1545'),
    ]

    operations = [
    ]
