# Generated by Django 2.0.5 on 2018-06-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_merge_20180531_1552'),
        ('authentication', '0023_auto_20180531_1908'),
    ]

    operations = [
    ]
