# Generated by Django 2.0.2 on 2018-06-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_merge_20180602_1127'),
        ('authentication', '0024_merge_20180602_1112'),
    ]

    operations = [
    ]
