# Generated by Django 2.0.2 on 2018-06-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_auto_20180604_1018'),
        ('authentication', '0024_merge_20180602_1230'),
    ]

    operations = [
    ]
