# Generated by Django 2.0.5 on 2018-06-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_appointmenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttransaction',
            name='appointment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
