# Generated by Django 2.0.6 on 2018-06-12 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_auto_20180612_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'consumer_account',
            },
        ),
        migrations.CreateModel(
            name='ConsumerTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'Lab Appointment')])),
                ('order', models.IntegerField()),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'Credit'), (1, 'Debit')])),
                ('action', models.SmallIntegerField(choices=[(0, 'Cancellation'), (1, 'Payment'), (2, 'Refund'), (3, 'Sale')])),
                ('amount', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PgTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'Lab Appointment')])),
                ('order', models.PositiveIntegerField()),
                ('type', models.SmallIntegerField(choices=[(0, 'Credit'), (1, 'Debit')])),
                ('payment_mode', models.CharField(max_length=50)),
                ('response_code', models.IntegerField()),
                ('bank_id', models.CharField(max_length=50)),
                ('transaction_date', models.CharField(max_length=80)),
                ('bank_name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=15)),
                ('status_code', models.IntegerField()),
                ('pg_name', models.CharField(max_length=100)),
                ('status_type', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100)),
                ('pb_gateway_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pg_transaction',
            },
        ),
    ]
