# Generated by Django 2.0.6 on 2018-06-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_consumeraccount_consumertransaction_pgtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgtransaction',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
