# Generated by Django 2.0.5 on 2018-06-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_auto_20180613_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumeraccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='consumertransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pgtransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConsumerAccount',
        ),
        migrations.DeleteModel(
            name='ConsumerTransaction',
        ),
        migrations.DeleteModel(
            name='PgTransaction',
        ),
    ]
