# Generated by Django 2.0.6 on 2018-06-14 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_auto_20180613_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'Lab Appointment')])),
                ('order', models.IntegerField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'INITIALISED'), (1, 'COMPLETED')])),
                ('amount', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
