# Generated by Django 2.0.6 on 2018-06-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_auto_20180615_1805'),
        ('authentication', '0033_ordertransaction'),
    ]

    operations = [
    ]
