# Generated by Django 2.0.5 on 2018-06-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_merge_20180615_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderTransaction',
        ),
    ]
