# Generated by Django 2.0.6 on 2018-06-30 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0052_auto_20180628_1917'),
        ('authentication', '0035_auto_20180615_1906'),
    ]

    operations = [
    ]
