# Generated by Django 2.0.6 on 2018-06-30 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0052_auto_20180628_1917'),
        ('authentication', '0035_auto_20180615_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabUserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_type', models.CharField(choices=[('appointment', 'Appointment'), ('billing', 'Billing')], default='appointment', max_length=20)),
                ('read_permission', models.BooleanField(default=False)),
                ('write_permission', models.BooleanField(default=False)),
                ('delete_permission', models.BooleanField(default=False)),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_admins', to='diagnostic.Lab')),
                ('lab_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_network_admins', to='diagnostic.LabNetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_user_permission',
            },
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='permission_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('billing', 'Billing')], default='appointment', max_length=20),
        ),
    ]
