# Generated by Django 2.0.5 on 2018-06-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_auto_20180629_1443'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genericadmin',
            table='generic_admin',
        ),
    ]
