# Generated by Django 2.0.5 on 2018-06-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_auto_20180629_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericadmin',
            old_name='reference_id',
            new_name='object_id',
        ),
    ]
