# Generated by Django 2.0.6 on 2018-06-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_auto_20180630_1605'),
        ('authentication', '0038_auto_20180629_1516'),
    ]

    operations = [
    ]
