# Generated by Django 2.0.5 on 2018-07-06 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0060_hospital_is_appointment_manager'),
        ('authentication', '0039_merge_20180630_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericadmin',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='genericadmin',
            name='object_id',
        ),
        migrations.AddField(
            model_name='genericadmin',
            name='delete_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genericadmin',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manageable_doctors', to='doctor.Doctor'),
        ),
        migrations.AddField(
            model_name='genericadmin',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manageable_hospitals', to='doctor.Hospital'),
        ),
        migrations.AddField(
            model_name='genericadmin',
            name='hospital_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manageable_hospital_networks', to='doctor.HospitalNetwork'),
        ),
        migrations.AddField(
            model_name='genericadmin',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genericadmin',
            name='is_doc_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genericadmin',
            name='permission_type',
            field=models.CharField(choices=[(0, 'Appointment'), (1, 'Billing')], default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='genericadmin',
            name='read_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genericadmin',
            name='super_user_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genericadmin',
            name='write_permission',
            field=models.BooleanField(default=False),
        ),
    ]
