# Generated by Django 2.0.5 on 2018-07-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0039_merge_20180630_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
