# Generated by Django 2.0.5 on 2018-07-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_auto_20180706_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericadmin',
            name='delete_permission',
        ),
    ]
