# Generated by Django 2.0.5 on 2018-07-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0041_remove_genericadmin_delete_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericadmin',
            name='permission_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Appointment'), (2, 'Billing')], default=1, max_length=20),
        ),
    ]
