# Generated by Django 2.0.6 on 2018-07-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_staffprofile_employee_id'),
        ('authentication', '0042_auto_20180706_1632'),
    ]

    operations = [
    ]
