# Generated by Django 2.0.2 on 2018-08-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0045_auto_20180727_1126'),
        ('authentication', '0045_auto_20180801_1852'),
    ]

    operations = [
    ]
