# Generated by Django 2.0.5 on 2018-08-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('authentication', '0047_auto_20180802_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.BigIntegerField(blank=True, default=None, editable=False, null=True)),
                ('account_number', models.BigIntegerField(blank=True, default=None, null=True)),
                ('ifsc_code', models.BigIntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=128)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'billing_account',
            },
        ),
    ]
