# Generated by Django 2.0.7 on 2018-08-07 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0071_auto_20180802_1151'),
        ('authentication', '0047_auto_20180802_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericLabAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('permission_type', models.PositiveSmallIntegerField(choices=[(1, 'Appointment'), (2, 'Billing')], default=1, max_length=20)),
                ('is_lab_admin', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('super_user_permission', models.BooleanField(default=False)),
                ('read_permission', models.BooleanField(default=False)),
                ('write_permission', models.BooleanField(default=False)),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manageablelab', to='diagnostic.Lab')),
                ('lab_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manageable_lab_network', to='diagnostic.LabNetwork')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generic_lab_admin',
            },
        ),
    ]
