# Generated by Django 2.0.7 on 2018-08-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0048_genericlabadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericlabadmin',
            name='is_lab_admin',
        ),
    ]
