# Generated by Django 2.0.5 on 2018-08-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0048_billingaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaccount',
            name='name',
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Savings'), (2, 'Current')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='ifsc_code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='merchant_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
