# Generated by Django 2.0.7 on 2018-08-07 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0049_remove_genericlabadmin_is_lab_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericlabadmin',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manageable_lab_admins', to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='genericlabadmin',
            name='lab_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manageable_lab_network_admins', to='diagnostic.LabNetwork'),
        ),
    ]
