# Generated by Django 2.0.5 on 2018-08-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0049_auto_20180817_1918'),
    ]

    operations = [
        migrations.RunSQL(
            '''CREATE SEQUENCE IF NOT EXISTS merchant_id_seq START 10000000;'''
        ),
    ]
