# Generated by Django 2.0.2 on 2018-08-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0050_merchant_billing_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='account_copy',
            field=models.ImageField(blank=True, null=True, upload_to='billing/documents', verbose_name='Account/Cheque Image'),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='pan_copy',
            field=models.ImageField(blank=True, null=True, upload_to='billing/documents', verbose_name='Pan Card Image'),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='pan_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
