# Generated by Django 2.0.6 on 2018-08-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0051_auto_20180818_1537'),
        ('authentication', '0050_auto_20180807_1618'),
    ]

    operations = [
    ]
