# Generated by Django 2.0.5 on 2018-08-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0052_usersecretkey'),
        ('authentication', '0052_merge_20180821_1228'),
    ]

    operations = [
    ]
