# Generated by Django 2.0.5 on 2018-08-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0055_auto_20180823_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='landmark_place_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='locality_place_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
