# Generated by Django 2.0.5 on 2018-08-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0056_auto_20180824_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttoken',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
