# Generated by Django 2.0.5 on 2018-08-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0057_agenttoken_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaccount',
            name='account_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
