# Generated by Django 2.0.5 on 2018-10-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0059_spocdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spocdetails',
            name='std_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
