# Generated by Django 2.0.5 on 2018-10-24 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0061_auto_20181010_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericadmin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manages', to=settings.AUTH_USER_MODEL),
        ),
    ]
