# Generated by Django 2.0.5 on 2018-10-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0062_auto_20181024_1858'),
        ('authentication', '0062_auto_20181024_1536'),
    ]

    operations = [
    ]
