# Generated by Django 2.0.5 on 2018-11-05 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0066_genericadmin_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericlabadmin',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genericlabadmin',
            name='name',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='genericlabadmin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manages_lab', to=settings.AUTH_USER_MODEL),
        ),
    ]
