# Generated by Django 2.0.5 on 2018-11-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0067_auto_20181105_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericlabadmin',
            name='permission_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'All'), (1, 'Appointment'), (2, 'Billing')], default=1, max_length=20),
        ),
    ]
