# Generated by Django 2.0.5 on 2018-11-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0068_auto_20181105_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericadmin',
            name='source_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Other'), (1, 'Doctor'), (2, 'Hospital')], default=3, max_length=20),
        ),
    ]
