# Generated by Django 2.0.5 on 2018-11-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0069_genericadmin_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericadmin',
            name='entity_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Other'), (1, 'Doctor'), (2, 'Hospital')], default=3, max_length=20),
        ),
        migrations.AlterField(
            model_name='genericadmin',
            name='source_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CRM'), (2, 'App')], default=3, max_length=20),
        ),
    ]
