# Generated by Django 2.0.5 on 2018-11-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0071_auto_20181113_1050'),
        ('authentication', '0059_userprofile_is_insured'),
    ]

    operations = [
    ]
