# Generated by Django 2.0.5 on 2018-11-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0160_doctorclinic_priority'),
        ('authentication', '0071_auto_20181113_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_number', to='doctor.Doctor')),
            ],
            options={
                'db_table': 'doctor_number',
            },
        ),
        migrations.AlterUniqueTogether(
            name='doctornumber',
            unique_together={('phone_number', 'doctor')},
        ),
    ]
