# Generated by Django 2.0.5 on 2018-11-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0072_merge_20181115_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_insured',
        ),
    ]
