# Generated by Django 2.0.5 on 2018-11-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0072_auto_20181113_1934'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctornumber',
            unique_together=set(),
        ),
    ]
