# Generated by Django 2.0.5 on 2018-11-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0073_auto_20181115_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaccount',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Savings'), (2, 'Current')], null=True),
        ),
        migrations.AlterField(
            model_name='genericadmin',
            name='entity_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Other'), (1, 'Doctor'), (2, 'Hospital')], default=3),
        ),
        migrations.AlterField(
            model_name='genericadmin',
            name='permission_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'All'), (1, 'Appointment'), (2, 'Billing')], default=1),
        ),
        migrations.AlterField(
            model_name='genericadmin',
            name='source_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CRM'), (2, 'App')], default=1),
        ),
        migrations.AlterField(
            model_name='genericlabadmin',
            name='permission_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'All'), (1, 'Appointment'), (2, 'Billing')], default=1),
        ),
        migrations.AlterField(
            model_name='genericlabadmin',
            name='source_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CRM'), (2, 'App')], default=1),
        ),
    ]
