# Generated by Django 2.0.5 on 2018-11-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0162_doctorclinic_enabled'),
        ('authentication', '0074_auto_20181119_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornumber',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_doctor_number', to='doctor.Hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='doctornumber',
            unique_together={('phone_number', 'doctor', 'hospital')},
        ),
    ]
