# Generated by Django 2.0.5 on 2018-12-04 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('authentication', '0076_auto_20181128_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedMerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'associated_merchant',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_name', models.CharField(max_length=128, null=True)),
                ('account_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('ifsc_code', models.CharField(max_length=128, null=True)),
                ('pan_number', models.CharField(max_length=20, null=True)),
                ('pan_copy', models.ImageField(blank=True, null=True, upload_to='billing/documents', verbose_name='Pan Card Image')),
                ('account_copy', models.ImageField(blank=True, null=True, upload_to='billing/documents', verbose_name='Account/Cheque Image')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Savings'), (2, 'Current')], null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('verified_by_finance', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'merchant',
            },
        ),
        migrations.AddField(
            model_name='associatedmerchant',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to='authentication.Merchant'),
        ),
    ]
