# Generated by Django 2.0.5 on 2018-12-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0073_remove_userprofile_is_insured'),
        ('authentication', '0076_auto_20181128_1713'),
    ]

    operations = [
    ]
