# Generated by Django 2.0.5 on 2018-12-18 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0077_auto_20181204_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='verified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
