# Generated by Django 2.0.5 on 2018-12-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0077_auto_20181204_1311'),
        ('authentication', '0077_merge_20181207_1443'),
    ]

    operations = [
    ]
