# Generated by Django 2.0.5 on 2018-12-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0078_merchant_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='merchant_add_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_add_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_add_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_add_4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
