# Generated by Django 2.0.5 on 2018-12-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0079_auto_20181218_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='merchant',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='merchant',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='merchant',
            name='mobile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='merchant',
            name='pin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='merchant',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
