# Generated by Django 2.0.5 on 2018-12-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0080_auto_20181218_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
