# Generated by Django 2.0.5 on 2019-03-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0081_merchant_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_optin',
            field=models.NullBooleanField(default=None),
        ),
    ]
