# Generated by Django 2.0.5 on 2018-12-21 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0081_merchant_verified_at'),
        ('authentication', '0078_merge_20181218_1358'),
    ]

    operations = [
    ]
