# Generated by Django 2.0.5 on 2019-02-28 08:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0081_merchant_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='api_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='pg_status',
            field=models.PositiveIntegerField(choices=[(0, 'Not Initiated'), (1, 'Initiated'), (2, 'In Progress'), (3, 'Complete'), (4, 'Failure')], default=0, editable=False),
        ),
    ]
