# Generated by Django 2.0.5 on 2019-03-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0083_userprofile_whatsapp_is_declined'),
        ('authentication', '0082_statushistory'),
    ]

    operations = [
    ]
