# Generated by Django 2.0.5 on 2019-03-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0084_merge_20190305_1106'),
        ('authentication', '0084_merge_20190305_1928'),
    ]

    operations = [
    ]
