# Generated by Django 2.0.5 on 2019-03-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0082_merge_20181221_1335'),
        ('authentication', '0085_merge_20190306_1634'),
    ]

    operations = [
    ]
