# Generated by Django 2.0.5 on 2019-03-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0085_merge_20190306_1634'),
        ('authentication', '0082_auto_20190228_1400'),
    ]

    operations = [
    ]
