# Generated by Django 2.0.5 on 2019-03-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0086_merge_20190312_1254'),
        ('authentication', '0086_merge_20190319_1537'),
    ]

    operations = [
    ]
