# Generated by Django 2.0.5 on 2019-04-04 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0086_merge_20190319_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickLoginToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100)),
                ('expiration_time', models.DateTimeField(null=True)),
                ('is_consumed', models.BooleanField(default=False)),
                ('url_key', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'click_login_token',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clicklogintoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
