# Generated by Django 2.0.5 on 2019-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0087_auto_20190404_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicklogintoken',
            name='token',
            field=models.CharField(max_length=300),
        ),
    ]
