# Generated by Django 2.0.5 on 2019-04-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0087_merge_20190326_1307'),
        ('authentication', '0088_auto_20190404_1523'),
    ]

    operations = [
    ]
