# Generated by Django 2.0.5 on 2019-04-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0088_auto_20190404_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericadmin',
            name='auto_created_from_SPOCs',
            field=models.BooleanField(default=False),
        ),
    ]
