# Generated by Django 2.0.5 on 2019-04-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0089_genericadmin_auto_created_from_spocs'),
        ('authentication', '0089_merge_20190404_1811'),
    ]

    operations = [
    ]
