# Generated by Django 2.0.5 on 2019-04-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0090_merge_20190408_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericadmin',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
