# Generated by Django 2.0.5 on 2019-05-02 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0091_auto_20190422_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastLoginTimestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_login_timestamp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'last_login_timestamp',
            },
        ),
    ]
