# Generated by Django 2.0.5 on 2019-05-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0093_otpverifications_otp_request_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverifications',
            name='via_sms',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='otpverifications',
            name='via_whatsapp',
            field=models.NullBooleanField(default=None),
        ),
    ]
