# Generated by Django 2.0.5 on 2019-05-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0094_auto_20190517_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverifications',
            name='otp_request_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='otpverifications',
            name='via_sms',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='otpverifications',
            name='via_whatsapp',
            field=models.NullBooleanField(),
        ),
    ]
