# Generated by Django 2.0.5 on 2019-06-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0097_merchantnetrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantnetrevenue',
            name='tds_deducted',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
