# Generated by Django 2.0.5 on 2019-06-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0098_merchantnetrevenue_tds_deducted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantnetrevenue',
            old_name='totol_revenue',
            new_name='total_revenue',
        ),
    ]
