# Generated by Django 2.0.5 on 2019-06-19 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0076_merge_20190612_1344'),
        ('authentication', '0099_auto_20190618_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantTdsDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.CharField(blank=True, max_length=20, null=True)),
                ('tds_deducted', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_deduction', to='authentication.Merchant')),
                ('merchant_payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds', to='account.MerchantPayout')),
            ],
            options={
                'db_table': 'merchant_tds_deduction',
            },
        ),
    ]
