# Generated by Django 2.0.5 on 2019-07-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0103_auto_20190709_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernumberupdate',
            name='otp_expiry',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
