# Generated by Django 2.0.5 on 2019-07-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0104_usernumberupdate_otp_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileEmailUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_email', models.CharField(max_length=256)),
                ('new_email', models.CharField(max_length=256)),
                ('is_successfull', models.BooleanField(default=False)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_expiry', models.DateTimeField(default=None, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='email_updates', to='authentication.UserProfile')),
            ],
            options={
                'db_table': 'userprofile_email_updates',
            },
        ),
    ]
