# Generated by Django 2.0.5 on 2019-07-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('authentication', '0104_usernumberupdate_otp_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_question', models.TextField(verbose_name='Question')),
                ('test_answer', models.TextField(null=True, verbose_name='Answer')),
                ('object_id', models.BigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'generic_question_answer',
            },
        ),
    ]
