# Generated by Django 2.0.5 on 2019-07-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0105_genericquestionanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericquestionanswer',
            old_name='test_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='genericquestionanswer',
            old_name='test_question',
            new_name='question',
        ),
    ]
