# Generated by Django 2.0.5 on 2019-07-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0106_userprofileemailupdate_otp_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileemailupdate',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
