# Generated by Django 2.0.5 on 2019-07-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0106_auto_20190716_1551'),
        ('authentication', '0107_auto_20190717_1133'),
    ]

    operations = [
    ]
