# Generated by Django 2.0.5 on 2019-08-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0110_user_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
