# Generated by Django 2.0.5 on 2019-08-12 14:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0111_userprofile_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
