# Generated by Django 2.0.5 on 2019-09-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0112_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericadmin',
            name='is_partner_lab_admin',
            field=models.NullBooleanField(),
        ),
    ]
