# Generated by Django 2.0.5 on 2019-08-06 12:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0094_auto_20190731_1943'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='econsultation',
            name='coupon_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='econsultation',
            name='merchant_payout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='econsultations', to='account.MerchantPayout'),
        ),
        migrations.AddField(
            model_name='econsultation',
            name='money_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='econsult_pool', to='account.MoneyPool'),
        ),
        migrations.AddField(
            model_name='econsultation',
            name='price_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
