# Generated by Django 2.0.5 on 2019-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='econsultation',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Booked'), (3, 'Rescheduled by Doctor'), (4, 'Rescheduled by patient'), (5, 'Accepted'), (6, 'Cancelled'), (7, 'Completed'), (8, 'Expired')], default=1),
        ),
    ]
