# Generated by Django 2.0.5 on 2019-08-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_econsultation_status'),
        ('provider', '0002_auto_20190806_1813'),
    ]

    operations = [
    ]
