# Generated by Django 2.0.5 on 2019-08-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_merge_20190806_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='econsultation',
            name='validity',
        ),
    ]
