# Generated by Django 2.0.5 on 2019-08-14 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider', '0005_econsultation_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='econsultation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='econsultationss', to=settings.AUTH_USER_MODEL),
        ),
    ]
