# Generated by Django 2.0.5 on 2019-08-12 13:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_econsultation_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RocketChatGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_id', models.CharField(max_length=64)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('doctor_login_url', models.URLField()),
                ('patient_login_url', models.URLField()),
            ],
            options={
                'db_table': 'rc_groups',
            },
        ),
        migrations.CreateModel(
            name='RocketChatUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('rc_req_extras', django.contrib.postgres.fields.jsonb.JSONField()),
                ('response_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user_type', models.PositiveSmallIntegerField(choices=[(2, 'doctor'), (3, 'user')])),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rc_user', to='doctor.Doctor')),
                ('offline_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rc_user', to='doctor.OfflinePatients')),
                ('online_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rc_user', to='authentication.UserProfile')),
                ('login_token', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'rc_users',
            },
        ),
        migrations.AddField(
            model_name='econsultation',
            name='rc_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='econsultations', to='provider.RocketChatGroups'),
        ),
    ]
