# Generated by Django 2.0.5 on 2019-08-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0288_auto_20190807_1446'),
        ('authentication', '0109_merchant_payment_type'),
        ('provider', '0006_auto_20190812_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='econsultation',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='econsultations', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='econsultation',
            name='offline_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='econsultations', to='doctor.OfflinePatients'),
        ),
        migrations.AlterField(
            model_name='econsultation',
            name='online_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='econsultations', to='authentication.UserProfile'),
        ),
    ]
