# Generated by Django 2.0.5 on 2019-08-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_auto_20190813_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocketchatgroups',
            name='group_name',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
