# Generated by Django 2.0.5 on 2019-08-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_econsultation_user'),
        ('provider', '0008_rocketchatgroups_group_name'),
    ]

    operations = [
    ]
