# Generated by Django 2.0.5 on 2019-08-22 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0009_merge_20190822_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocketchatusers',
            name='doctor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rc_user', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='rocketchatusers',
            name='offline_patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rc_user', to='doctor.OfflinePatients'),
        ),
        migrations.AlterField(
            model_name='rocketchatusers',
            name='online_patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rc_user', to='authentication.UserProfile'),
        ),
    ]
