# Generated by Django 2.0.5 on 2019-09-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0010_auto_20190822_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='RocketChatSuperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'rc_super_user',
            },
        ),
    ]
