# Generated by Django 2.0.5 on 2019-09-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0313_hospital_is_partner_lab_enabled'),
        ('diagnostic', '0226_lab_is_b2b'),
        ('provider', '0011_rocketchatsuperuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderHospitalLabMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_labs', to='doctor.Hospital')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_hospitals', to='diagnostic.Lab')),
            ],
            options={
                'db_table': 'provider_hospital_lab_mapping',
            },
        ),
    ]
