# Generated by Django 2.0.5 on 2019-09-10 07:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0226_lab_is_b2b'),
        ('doctor', '0313_hospital_is_partner_lab_enabled'),
        ('provider', '0011_rocketchatsuperuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerHospitalLabMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_labs', to='doctor.Hospital')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_hospitals', to='diagnostic.Lab')),
            ],
            options={
                'db_table': 'partner_hospital_lab_mapping',
            },
        ),
        migrations.CreateModel(
            name='PartnerLabSamplesCollectOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('collection_datetime', models.DateTimeField(blank=True, null=True)),
                ('samples', django.contrib.postgres.fields.jsonb.JSONField()),
                ('selected_tests_details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('available_lab_tests', models.ManyToManyField(related_name='tests_lab_samples_collect_order', to='diagnostic.AvailableLabTest')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_lab_samples_collect_order', to='doctor.Doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosp_lab_samples_collect_order', to='doctor.Hospital')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_samples_collect_order', to='diagnostic.Lab')),
                ('status', models.SmallIntegerField(choices=[(1, 'Sample Scan Pending'), (2, 'Sample Collection Pending'), (3, 'Sample Collected'), (4, 'Report Generated'), (5, 'All Reports Generated'), (6, 'Report Viewed')])),
            ],
            options={
                'db_table': 'partner_lab_samples_collect_order',
            },
        ),
        migrations.CreateModel(
            name='PartnerLabTestSampleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('volume_unit', models.CharField(blank=True, choices=[('ml', 'ml')], default=None, max_length=16, null=True)),
                ('is_fasting_required', models.BooleanField(default=False)),
                ('report_tat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reference_value', models.CharField(blank=True, max_length=64, null=True)),
                ('material_required', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('instructions', models.CharField(blank=True, max_length=256, null=True)),
                ('lab_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample_details', to='diagnostic.LabTest')),
            ],
            options={
                'db_table': 'partner_lab_test_sample_details',
            },
        ),
        migrations.CreateModel(
            name='PartnerLabTestSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'partner_lab_test_samples',
            },
        ),
        migrations.CreateModel(
            name='TestSamplesLabAlerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'test_samples_lab_alerts',
            },
        ),
        migrations.AddField(
            model_name='partnerlabtestsampledetails',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='provider.PartnerLabTestSamples'),
        ),
        migrations.AddField(
            model_name='partnerlabsamplescollectorder',
            name='lab_alerts',
            field=models.ManyToManyField(to='provider.TestSamplesLabAlerts'),
        ),
        migrations.AddField(
            model_name='partnerlabsamplescollectorder',
            name='offline_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_lab_samples_collect_order', to='doctor.OfflinePatients'),
        ),
    ]
