# Generated by Django 2.0.5 on 2019-09-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_providerhospitallabmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderLabTestSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'provider_lab_test_samples',
            },
        ),
    ]
