# Generated by Django 2.0.5 on 2019-09-10 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_auto_20190910_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSamplesCollectBarcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(max_length=126)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_bar_code', to='provider.PartnerLabSamplesCollectOrder')),
                ('sample_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bar_codes', to='provider.PartnerLabTestSampleDetails')),
            ],
            options={
                'db_table': 'test_samples_collect_barcode',
            },
        ),
    ]
