# Generated by Django 2.0.5 on 2019-09-10 08:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_auto_20190910_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerlabsamplescollectorder',
            name='selected_tests_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
