# Generated by Django 2.0.5 on 2019-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_auto_20190910_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlabsamplescollectorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Sample Extraction Pending'), (2, 'Sample Scan Pending'), (3, 'Sample Pickup Pending'), (4, 'Sample Picked Up'), (5, 'Partial Report Generated'), (6, 'Report Generated'), (7, 'Report Viewed')]),
        ),
    ]
