# Generated by Django 2.0.5 on 2019-09-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_auto_20190912_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlabtestsampledetails',
            name='reference_value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
