# Generated by Django 2.0.5 on 2019-09-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_auto_20190917_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlabtestsampledetails',
            name='reference_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
