# Generated by Django 2.0.5 on 2019-09-06 10:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0229_delete_labsamples'),
        ('provider', '0013_auto_20190905_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderLabTestSampleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('fasting_required', models.BooleanField(default=False)),
                ('report_tat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reference_value', models.PositiveIntegerField(blank=True, null=True)),
                ('material_required', django.contrib.postgres.fields.jsonb.JSONField()),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_details', to='diagnostic.LabTest')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='provider.ProviderLabTestSamples')),
            ],
            options={
                'db_table': 'provider_lab_test_sample_details',
            },
        ),
    ]
