# Generated by Django 2.0.5 on 2019-09-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_auto_20190911_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLabTestSamplesOrderReportMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.FileField(upload_to='provider/cloud-lab/reports', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpeg', 'jpg', 'png'])])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='provider.PartnerLabSamplesCollectOrder')),
            ],
            options={
                'db_table': 'partner_lab_test_sample_order_report_mapping',
            },
        ),
    ]
