# Generated by Django 2.0.5 on 2019-09-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0014_auto_20190917_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerlabtestsamples',
            name='code',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
