# Generated by Django 2.0.5 on 2019-09-26 11:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0015_partnerlabtestsamples_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlabtestsampledetails',
            name='material_required',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
