# Generated by Django 2.0.5 on 2019-09-27 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0016_auto_20190926_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlabtestsampledetails',
            name='available_lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_details', to='diagnostic.AvailableLabTest'),
        ),
    ]
