# Generated by Django 2.0.5 on 2019-09-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0017_auto_20190927_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlabtestsamples',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
