# Generated by Django 2.0.5 on 2019-09-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0018_auto_20190927_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlabtestsampledetails',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
