# Generated by Django 2.0.5 on 2019-09-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0019_auto_20190927_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlabtestsampledetails',
            name='volume_unit',
            field=models.CharField(blank=True, choices=[('ml', 'ml'), ('mg', 'mg')], default=None, max_length=16, null=True),
        ),
    ]
