# Generated by Django 2.0.5 on 2019-10-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0023_partner_lab_sample_collect_order_ser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlabsamplescollectorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Sample Extraction Pending'), (2, 'Sample Scan Pending'), (3, 'Sample Pickup Pending'), (4, 'Sample Picked Up'), (5, 'Partial Report Generated'), (6, 'Report Generated'), (7, 'Report Viewed'), (8, 'Cancelled by Doctor'), (9, 'Cancelled by Lab')]),
        ),
    ]
