# Generated by Django 2.0.5 on 2019-10-25 07:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0024_auto_20191022_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerlabsamplescollectorder',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
