# Generated by Django 2.0.5 on 2019-11-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0024_partnerlabsamplescollectorder_extras'),
        ('provider', '0024_auto_20191022_1325'),
    ]

    operations = [
    ]
