# Generated by Django 2.0.5 on 2019-11-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0025_merge_20191104_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerlabsamplescollectorder',
            name='cancellation_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
