# Generated by Django 2.0.5 on 2018-12-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='banner/images', verbose_name='Banner image')),
                ('url', models.URLField(blank=True)),
                ('slider_location', models.SmallIntegerField(choices=[(1, 'Home Page'), (2, 'Doctor Search Page'), (3, 'Lab Search Page')])),
                ('slider_action', models.SmallIntegerField(choices=[(1, 'Lab Test'), (2, 'Procedure'), (4, 'Procedure Category'), (3, 'Specialization')])),
                ('object_id', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('enable', models.BooleanField(default=True, verbose_name='is enabled')),
                ('event_name', models.CharField(max_length=1000)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'banner',
            },
        ),
    ]
