# Generated by Django 2.0.5 on 2018-12-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='slider_action',
            field=models.SmallIntegerField(choices=[{1, 'Lab Test'}, {'Procedure', 2}, {'Procedure Category', 4}, {'Specialization', 3}]),
        ),
        migrations.AlterField(
            model_name='banner',
            name='slider_location',
            field=models.SmallIntegerField(choices=[{'Home Page', 1}, {2, 'Doctor Search Page'}, {'Lab Search Page', 3}]),
        ),
    ]
