# Generated by Django 2.0.5 on 2018-12-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_auto_20181214_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='slider_location',
            new_name='slider_locate',
        ),
    ]
