# Generated by Django 2.0.5 on 2018-12-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_auto_20181214_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='slider_action',
            field=models.SmallIntegerField(choices=[(1, 'test'), (2, 'procedure'), (4, 'procedure_category'), (3, 'specialization'), (5, 'condition')]),
        ),
    ]
