# Generated by Django 2.0.5 on 2018-12-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_auto_20181214_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='slider_action',
            field=models.SmallIntegerField(choices=[(1, 'Test'), (2, 'Procedure'), (4, 'Procedure Category'), (3, 'Specialization'), (5, 'Condition')]),
        ),
        migrations.AlterField(
            model_name='banner',
            name='slider_locate',
            field=models.SmallIntegerField(choices=[(1, 'Home Page'), (2, 'Doctor Search Page'), (3, 'Lab Search Page')]),
        ),
    ]
