# Generated by Django 2.0.5 on 2018-12-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0008_auto_20181217_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
