# Generated by Django 2.0.5 on 2018-12-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0010_auto_20181217_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='priority',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
