# Generated by Django 2.0.5 on 2018-12-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0011_auto_20181218_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='slider_locate',
            field=models.SmallIntegerField(choices=[(1, 'Home Page'), (2, 'Doctor Search Page'), (3, 'Lab Search Page'), (5, 'Procedure Search Page'), (4, 'Package Search Page')]),
        ),
    ]
