# Generated by Django 2.0.5 on 2018-12-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0012_auto_20181218_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
