# Generated by Django 2.0.5 on 2018-12-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0013_auto_20181218_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='slider_locate',
            field=models.SmallIntegerField(choices=[(1, 'home_page'), (2, 'doctor_search_page'), (3, 'lab_search_page'), (5, 'procedure_search_page'), (4, 'package_search_page')]),
        ),
    ]
