# Generated by Django 2.0.5 on 2019-01-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0014_auto_20181218_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='slider_action',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Test'), (2, 'Procedure'), (4, 'Procedure Category'), (3, 'Specialization'), (5, 'Condition')], null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='slider_locate',
            field=models.SmallIntegerField(choices=[(1, 'home_page'), (2, 'doctor_search_page'), (3, 'lab_search_page'), (5, 'procedure_search_page'), (4, 'package_search_page'), (6, 'offers_page')]),
        ),
    ]
