# Generated by Django 2.0.5 on 2019-01-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0019_auto_20190111_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='app_params',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='app_screen',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='show_in_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
