# Generated by Django 2.0.5 on 2019-01-15 09:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0020_auto_20190111_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='app_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
