# Generated by Django 2.0.5 on 2019-02-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0021_auto_20190115_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='radius',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
