# Generated by Django 2.0.5 on 2019-02-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0024_auto_20190225_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='radius',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
