# Generated by Django 2.0.5 on 2019-03-29 09:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0025_auto_20190226_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='url_params_excluded',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON format example: {"specialization_id": 3667, "test_ids": 87, "is_package": True, "Name": "Stringvalue"}', null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_params_included',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON format example: {"specialization_id": 3667, "test_ids": 87, "is_package": True, "Name": "Stringvalue"}', null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, max_length=10000, null=True, verbose_name='landing url'),
        ),
    ]
