# Generated by Django 2.0.5 on 2019-05-15 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0027_auto_20190409_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.PositiveIntegerField()),
                ('banner_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_location', to='banner.Banner')),
            ],
            options={
                'db_table': 'banner_location',
            },
        ),
    ]
