# Generated by Django 2.0.5 on 2019-05-10 11:21

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('banner', '0027_auto_20190409_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=500, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_banner',
            },
        ),
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Prepaid'), (2, 'COD'), (3, 'Insurance'), (4, 'Subscription Plan')], null=True)),
                ('notification_type', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(choices=[(1, 'Appointment Accepted'), (2, 'Appointment Cancelled'), (3, 'Appointment Rescheduled by Patient'), (4, 'Appointment Rescheduled by Doctor'), (5, 'Appointment Booked'), (20, 'Lab Appointment Accepted'), (21, 'Lab Appointment Cancelled'), (22, 'Lab Appointment Rescheduled by Patient'), (23, 'Lab Appointment Rescheduled by Lab'), (24, 'Lab Appointment Booked'), (25, 'Lab Report Uploaded'), (26, 'Send Lab Reports via CRM'), (6, 'Prescription Uploaded'), (7, 'Payment Pending'), (8, 'Receipt'), (10, 'Doctor Invoice'), (11, 'Lab Invoice'), (15, 'Insurance Confirmed'), (55, 'Cashback Credited'), (40, 'Refund break up'), (42, 'Refund Completed'), (60, 'IPD Procedure Mail'), (72, 'Pricing Change Mail'), (70, 'Lab Logo Change Mail'), (77, 'Appointment Reminder Provider SMS')]), blank=True, null=True, size=None)),
                ('item_min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'recommender',
            },
        ),
        migrations.CreateModel(
            name='RecommenderThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_data', to='banner.Recommender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
