# Generated by Django 2.0.5 on 2019-05-13 03:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0029_auto_20190510_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommender',
            name='payment_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Prepaid'), (2, 'COD'), (3, 'Insurance'), (4, 'Subscription Plan')], max_length=7, null=True),
        ),
    ]
