# Generated by Django 2.0.5 on 2019-05-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0031_emailbanner_enable_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbanner',
            name='banner_image',
            field=models.FileField(blank=True, null=True, upload_to='banner/email_banner'),
        ),
        migrations.AddField(
            model_name='emailbanner',
            name='banner_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
