# Generated by Django 2.0.5 on 2019-05-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0030_auto_20190515_1755'),
        ('banner', '0032_auto_20190514_1432'),
    ]

    operations = [
    ]
