# Generated by Django 2.0.5 on 2019-06-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0036_auto_20190614_1327'),
        ('banner', '0037_auto_20190607_1132'),
    ]

    operations = [
    ]
