# Generated by Django 2.0.5 on 2019-06-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0040_auto_20190614_1501'),
        ('banner', '0039_auto_20190614_1734'),
    ]

    operations = [
    ]
