# Generated by Django 2.0.5 on 2019-08-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0045_auto_20190730_1255'),
        ('banner', '0045_auto_20190801_2000'),
    ]

    operations = [
    ]
