# Generated by Django 2.0.5 on 2019-09-10 14:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0049_auto_20190829_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommender',
            name='payment_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Prepaid'), (2, 'COD'), (3, 'Insurance'), (4, 'Subscription Plan'), (5, 'VIP')], max_length=9, null=True),
        ),
    ]
