# Generated by Django 2.0.5 on 2019-11-15 06:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0053_auto_20191001_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommender',
            name='payment_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Prepaid'), (2, 'COD'), (3, 'Insurance'), (4, 'Subscription Plan'), (5, 'VIP'), (6, 'GOLD')], max_length=11, null=True),
        ),
    ]
