# Generated by Django 2.0.5 on 2019-12-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0054_auto_20191115_1224'),
        ('banner', '0055_auto_20191125_1540'),
    ]

    operations = [
    ]
