# Generated by Django 2.0.5 on 2019-12-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0056_merge_20191202_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='gold_check',
            field=models.CharField(choices=[('gold', 'Gold User'), ('non_gold', 'Non Gold User'), ('all', 'All')], default='all', max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='vip_check',
            field=models.CharField(choices=[('vip', 'VIP User'), ('non_vip', 'Non VIP User'), ('all', 'All')], default='all', max_length=100),
        ),
    ]
