# Generated by Django 2.0.5 on 2019-12-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0057_auto_20191212_1555'),
        ('banner', '0057_banner_body'),
    ]

    operations = [
    ]
