# Generated by Django 2.0.5 on 2018-09-18 12:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoIPEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('location_detail', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'geoip_entries',
            },
        ),
        migrations.CreateModel(
            name='VisitorIpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('visit_id', models.CharField(max_length=100)),
                ('visitor_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'visitor_ip_address',
            },
        ),
    ]
