# Generated by Django 2.0.5 on 2018-09-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitoripaddress',
            name='visit_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitoripaddress',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
