# Generated by Django 2.0.5 on 2018-10-01 08:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0002_auto_20180918_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdwordLocationCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criteria_id', models.PositiveIntegerField()),
                ('name', models.PositiveIntegerField()),
                ('cannonical_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('parent_id', models.PositiveIntegerField()),
                ('country_code', models.CharField(blank=True, max_length=32, null=True)),
                ('target_type', models.CharField(max_length=200, null=True)),
                ('latlong', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=24)),
            ],
            options={
                'db_table': 'adwords_location',
            },
        ),
    ]
