# Generated by Django 2.0.5 on 2019-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20190315_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID')]),
        ),
    ]
