# Generated by Django 2.0.5 on 2019-03-13 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20190313_1045'),
        ('cart', '0003_auto_20190312_1752'),
    ]

    operations = [
    ]
