# Generated by Django 2.0.5 on 2019-03-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20190315_1612'),
        ('cart', '0004_auto_20190318_1424'),
    ]

    operations = [
    ]
