# Generated by Django 2.0.5 on 2019-08-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20190726_1301'),
        ('cart', '0008_auto_20190807_1446'),
    ]

    operations = [
    ]
