# Generated by Django 2.0.5 on 2019-09-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20190813_1542'),
        ('cart', '0009_auto_20190830_1739'),
    ]

    operations = [
    ]
