# Generated by Django 2.0.5 on 2019-01-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostic', '0145_merge_20190108_1624'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratorMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('interator_class_name', models.CharField(max_length=40)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resource_contenttype', to='contenttypes.ContentType')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabTest')),
            ],
            options={
                'db_table': 'integrator_mapping',
            },
        ),
    ]
