# Generated by Django 2.0.5 on 2019-01-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20190123_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='integratormapping',
            name='service_type',
            field=models.CharField(choices=[('LabTest', 'LABTEST')], default=None, max_length=30),
        ),
    ]
