# Generated by Django 2.0.5 on 2019-01-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_integratormapping_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integratormapping',
            old_name='interator_class_name',
            new_name='integrator_class_name',
        ),
    ]
