# Generated by Django 2.0.5 on 2019-01-23 14:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_auto_20190123_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratorProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('integrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.IntegratorMapping')),
            ],
            options={
                'db_table': 'integrator_product_detail',
            },
        ),
    ]
