# Generated by Django 2.0.5 on 2019-02-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_integratorresponse'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='integratorresponse',
            table='integrator_response',
        ),
    ]
