# Generated by Django 2.0.5 on 2019-02-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_auto_20190206_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('xml_url', models.TextField(blank=True, null=True)),
                ('integrator_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.IntegratorResponse')),
            ],
            options={
                'db_table': 'integrator_report',
            },
        ),
    ]
