# Generated by Django 2.0.5 on 2019-02-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_integratorreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='integratorresponse',
            name='report_received',
            field=models.BooleanField(default=False),
        ),
    ]
