# Generated by Django 2.0.5 on 2019-03-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diagnostic', '0169_merge_20190318_1404'),
        ('integrations', '0012_integratorresponse_report_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratorPopMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('integrator_class_name', models.CharField(max_length=40)),
                ('service_type', models.CharField(choices=[('LabTest', 'PROFILES')], default=None, max_length=30)),
                ('integrator_pop_name', models.CharField(default=None, max_length=60)),
                ('integrator_code', models.CharField(max_length=40)),
                ('integrator_group_name', models.CharField(default=None, max_length=60)),
                ('is_active', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
                ('package', models.ForeignKey(limit_choices_to={'is_package': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabTest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
