# Generated by Django 2.0.5 on 2019-03-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_integratorpopmapping'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='integratorpopmapping',
            table='integrator_pop_mapping',
        ),
    ]
