# Generated by Django 2.0.5 on 2019-03-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_auto_20190318_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integratorpopmapping',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='integratorpopmapping',
            name='package',
        ),
        migrations.DeleteModel(
            name='IntegratorPopMapping',
        ),
    ]
