# Generated by Django 2.0.5 on 2019-03-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_auto_20190319_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='integratorprofilemapping',
            name='integrator_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
