# Generated by Django 2.0.5 on 2019-03-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_integratorprofilemapping_integrator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='integratormapping',
            name='name_params_required',
            field=models.BooleanField(default=False),
        ),
    ]
