# Generated by Django 2.0.5 on 2019-03-25 07:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('integrations', '0017_integratormapping_name_params_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('integrator_class_name', models.CharField(max_length=40)),
                ('retry_count', models.PositiveIntegerField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pushed and not accepted'), (2, 'Pushed and accepted'), (3, 'Not pushed')], default=3)),
                ('api_status', models.PositiveIntegerField()),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('response_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('api_name', models.CharField(max_length=40)),
                ('api_endpoint', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'integrator_history',
            },
        ),
    ]
