# Generated by Django 2.0.5 on 2019-03-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0020_auto_20190327_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integratormapping',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabTest'),
        ),
        migrations.AlterField(
            model_name='integratorprofilemapping',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabTest'),
        ),
    ]
