# Generated by Django 2.0.5 on 2019-03-28 10:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diagnostic', '0173_merge_20190320_1712'),
        ('integrations', '0021_auto_20190327_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratorTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('integrator_class_name', models.CharField(max_length=40)),
                ('service_type', models.CharField(choices=[('LabTest', 'LABTEST')], default=None, max_length=30)),
                ('integrator_product_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('integrator_test_name', models.CharField(default=None, max_length=60)),
                ('name_params_required', models.BooleanField(default=False)),
                ('integrator_type', models.CharField(blank=True, max_length=30, null=True)),
                ('is_package', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabTest')),
            ],
            options={
                'db_table': 'integrator_test',
            },
        ),
    ]
