# Generated by Django 2.0.5 on 2019-03-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diagnostic', '0173_merge_20190320_1712'),
        ('integrations', '0022_integratortest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntegratorTest',
            new_name='IntegratorTestMapping',
        ),
        migrations.AlterModelTable(
            name='integratortestmapping',
            table='integrator_test_mapping',
        ),
    ]
