# Generated by Django 2.0.5 on 2019-03-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0023_auto_20190328_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integratortestmapping',
            old_name='integrator_type',
            new_name='test_type',
        ),
        migrations.RemoveField(
            model_name='integratortestmapping',
            name='is_package',
        ),
    ]
