# Generated by Django 2.0.5 on 2019-03-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0025_integratortestmapping_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integratortestmapping',
            name='user',
        ),
    ]
