# Generated by Django 2.0.5 on 2019-04-02 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0179_auto_20190402_1111'),
        ('integrations', '0026_remove_integratortestmapping_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratorTestParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integrator_class_name', models.CharField(max_length=40)),
                ('integrator_test_name', models.CharField(blank=True, max_length=60, null=True)),
                ('test_parameter_new', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.TestParameterNew')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
