# Generated by Django 2.0.5 on 2019-04-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0027_integratortestparameter'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='integratortestparameter',
            table='integrator_test_parameter',
        ),
    ]
