# Generated by Django 2.0.5 on 2019-04-02 08:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0028_auto_20190402_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='integratortestparameter',
            name='response_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
