# Generated by Django 2.0.5 on 2019-04-23 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0197_auto_20190423_1503'),
        ('integrations', '0030_auto_20190403_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='integratortestparametermapping',
            name='test_parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.TestParameter'),
        ),
    ]
