# Generated by Django 2.0.5 on 2019-04-24 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0031_integratortestparametermapping_test_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integratortestparametermapping',
            name='test_parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrator_mapped_parameters', to='diagnostic.TestParameter'),
        ),
    ]
