# Generated by Django 2.0.5 on 2019-04-24 08:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0032_auto_20190424_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='integratorreport',
            name='json_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
