# Generated by Django 2.0.5 on 2019-04-25 05:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0033_integratorreport_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integratorreport',
            name='json_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
    ]
