# Generated by Django 2.0.5 on 2019-07-29 11:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0284_merge_20190726_1626'),
        ('integrations', '0034_auto_20190425_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratorDoctorMappings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integrator_doctor_id', models.PositiveIntegerField()),
                ('integrator_hospital_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('specialities', models.CharField(blank=True, max_length=40, null=True)),
                ('hospital_name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('primary_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('helpline_sos', models.CharField(blank=True, max_length=20, null=True)),
                ('integrator_doctor_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('integrator_class_name', models.CharField(max_length=30)),
                ('doctor_clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorClinic')),
            ],
            options={
                'db_table': 'integrator_doctor_mappings',
            },
        ),
        migrations.CreateModel(
            name='IntegratorHospitalMappings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integrator_hospital_name', models.CharField(blank=True, max_length=60, null=True)),
                ('integrator_class_name', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Hospital')),
            ],
            options={
                'db_table': 'integrator_hospital_mappings',
            },
        ),
    ]
