# Generated by Django 2.0.5 on 2019-08-05 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0215_availablelabtest_insurance_agreed_price'),
        ('integrations', '0034_auto_20190425_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratorLabTestParameterMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integrator_class_name', models.CharField(max_length=40)),
                ('integrator_test_parameter_code', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('test_parameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='integrator_mapped_test_parameters', to='diagnostic.TestParameter')),
            ],
            options={
                'db_table': 'integrator_lab_test_parameter_mapping',
            },
        ),
    ]
