# Generated by Django 2.0.5 on 2019-08-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0035_integratorlabtestparametermapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integratorlabtestparametermapping',
            unique_together={('integrator_class_name', 'integrator_test_parameter_code')},
        ),
    ]
