# Generated by Django 2.0.5 on 2019-07-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0036_auto_20190729_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integratordoctormappings',
            name='specialities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
