# Generated by Django 2.0.5 on 2019-07-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0037_auto_20190729_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integratordoctormappings',
            name='first_name',
            field=models.CharField(max_length=80),
        ),
    ]
