# Generated by Django 2.0.5 on 2019-08-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0037_integratorlabtestparametermapping_integrator_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='integratortestmapping',
            name='integrator_city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='integratortestmapping',
            name='integrator_city_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integratortestmapping',
            name='integrator_test_name',
            field=models.CharField(max_length=150),
        ),
    ]
