# Generated by Django 2.0.5 on 2019-07-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0038_auto_20190729_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integratordoctormappings',
            name='first_name',
            field=models.CharField(max_length=160),
        ),
    ]
