# Generated by Django 2.0.5 on 2019-08-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0037_integratorlabtestparametermapping_integrator_test_name'),
        ('integrations', '0039_auto_20190729_2230'),
    ]

    operations = [
    ]
