# Generated by Django 2.0.5 on 2019-08-29 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0039_auto_20190828_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integratortestcitymapping',
            name='integrator_test_mapping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mapped_city_test', to='integrations.IntegratorTestMapping'),
        ),
    ]
