# Generated by Django 2.0.5 on 2019-09-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0040_auto_20190829_1334'),
        ('integrations', '0039_auto_20190729_2230'),
    ]

    operations = [
    ]
