# Generated by Django 2.0.5 on 2019-09-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0041_integratorlabcode'),
        ('integrations', '0041_merge_20190902_1549'),
    ]

    operations = [
    ]
