# Generated by Django 2.0.5 on 2019-09-03 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0224_auto_20190828_2335'),
        ('integrations', '0041_merge_20190902_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratorLabCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_code', models.CharField(blank=True, max_length=30, null=True)),
                ('warehouse_code', models.CharField(blank=True, max_length=50, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_code', to='diagnostic.Lab')),
            ],
            options={
                'db_table': 'integrator_lab_code',
            },
        ),
    ]
