# Generated by Django 2.0.5 on 2019-09-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0042_integratorlabcode'),
        ('integrations', '0040_merge_20190828_1556'),
    ]

    operations = [
    ]
