# Generated by Django 2.0.5 on 2019-09-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0043_merge_20190903_1645'),
        ('integrations', '0041_merge_20190902_1549'),
    ]

    operations = [
    ]
