# Generated by Django 2.0.5 on 2019-09-26 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0044_integratordoctorcliniccode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integratordoctorcliniccode',
            name='doctor_clinic',
        ),
        migrations.DeleteModel(
            name='IntegratorDoctorClinicCode',
        ),
    ]
