# Generated by Django 2.0.5 on 2019-09-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0044_merge_20190903_1650'),
        ('integrations', '0042_integratorlabcode'),
    ]

    operations = [
    ]
