# Generated by Django 2.0.5 on 2019-09-26 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0318_merge_20190916_1822'),
        ('integrations', '0045_auto_20190926_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratorHospitalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_code', models.CharField(blank=True, max_length=30, null=True)),
                ('clinic_code', models.CharField(blank=True, max_length=50, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hos_code', to='doctor.Hospital')),
            ],
            options={
                'db_table': 'integrator_hospital_code',
            },
        ),
    ]
