# Generated by Django 2.0.5 on 2019-09-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0318_merge_20190916_1822'),
        ('integrations', '0046_integratorhospitalcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratorDoctorClinicMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_clinic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctor.DoctorClinic')),
                ('integrator_doctor_mapping', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='integrator_doctor', to='integrations.IntegratorDoctorMappings')),
            ],
            options={
                'db_table': 'integrator_doctor_clinic_mapping',
            },
        ),
    ]
