# Generated by Django 2.0.5 on 2019-10-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0047_integratordoctorclinicmapping'),
        ('integrations', '0043_merge_20190923_1221'),
    ]

    operations = [
    ]
