# Generated by Django 2.0.5 on 2019-10-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0048_merge_20191001_2012'),
        ('integrations', '0045_merge_20190904_1736'),
    ]

    operations = [
    ]
