# Generated by Django 2.0.5 on 2018-07-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20180613_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotification',
            name='notification_type',
            field=models.PositiveIntegerField(choices=[(1, 'Appointment Accepted'), (2, 'Appointment Cancelled'), (3, 'Appointment Rescheduled by Patient'), (4, 'Appointment Rescheduled by Doctor'), (5, 'Appointment Booked'), (10, 'Doctor Invoice'), (11, 'Lab Invoice')]),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='notification_type',
            field=models.PositiveIntegerField(choices=[(1, 'Appointment Accepted'), (2, 'Appointment Cancelled'), (3, 'Appointment Rescheduled by Patient'), (4, 'Appointment Rescheduled by Doctor'), (5, 'Appointment Booked'), (10, 'Doctor Invoice'), (11, 'Lab Invoice')]),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='notification_type',
            field=models.PositiveIntegerField(choices=[(1, 'Appointment Accepted'), (2, 'Appointment Cancelled'), (3, 'Appointment Rescheduled by Patient'), (4, 'Appointment Rescheduled by Doctor'), (5, 'Appointment Booked'), (10, 'Doctor Invoice'), (11, 'Lab Invoice')]),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='notification_type',
            field=models.PositiveIntegerField(choices=[(1, 'Appointment Accepted'), (2, 'Appointment Cancelled'), (3, 'Appointment Rescheduled by Patient'), (4, 'Appointment Rescheduled by Doctor'), (5, 'Appointment Booked'), (10, 'Doctor Invoice'), (11, 'Lab Invoice')]),
        ),
    ]
