# Generated by Django 2.0.5 on 2018-07-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20180719_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='target_app',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'staff'), (2, 'doctor'), (3, 'user')], null=True),
        ),
    ]
