# Generated by Django 2.0.2 on 2018-08-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20180727_1126'),
        ('notification', '0007_auto_20180801_1413'),
    ]

    operations = [
    ]
