# Generated by Django 2.0.5 on 2018-12-28 06:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_auto_20180824_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='cc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=[], default=[], size=None),
        ),
    ]
