# Generated by Django 2.0.5 on 2018-12-28 06:44

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_emailnotification_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='attachments',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=[], default=[], size=None),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='bcc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=[], default=[], size=None),
        ),
    ]
