# Generated by Django 2.0.5 on 2019-01-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_auto_20181228_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailnotification',
            name='attachments',
        ),
    ]
