# Generated by Django 2.0.5 on 2019-01-02 05:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0014_remove_emailnotification_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='attachments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=[], default=[]),
        ),
    ]
