# Generated by Django 2.0.5 on 2019-01-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0015_emailnotification_attachments'),
        ('notification', '0012_auto_20190102_1149'),
    ]

    operations = [
    ]
