# Generated by Django 2.0.5 on 2019-01-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0016_merge_20190103_1239'),
        ('notification', '0012_auto_20181129_2035'),
    ]

    operations = [
    ]
