# Generated by Django 2.0.5 on 2019-02-05 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notification', '0017_auto_20190111_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
