# Generated by Django 2.0.5 on 2019-02-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0018_auto_20190205_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
