# Generated by Django 2.0.5 on 2019-02-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0018_auto_20190107_1926'),
        ('notification', '0017_auto_20190111_1552'),
    ]

    operations = [
    ]
