# Generated by Django 2.0.5 on 2019-02-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0019_auto_20190205_1253'),
        ('notification', '0018_auto_20190129_1517'),
    ]

    operations = [
    ]
