# Generated by Django 2.0.5 on 2019-02-19 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0019_auto_20190205_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhtsappNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.BigIntegerField()),
                ('viewed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('read_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('template_name', models.CharField(max_length=100)),
                ('notification_type', models.PositiveIntegerField(choices=[(1, 'Appointment Accepted'), (2, 'Appointment Cancelled'), (3, 'Appointment Rescheduled by Patient'), (4, 'Appointment Rescheduled by Doctor'), (5, 'Appointment Booked'), (20, 'Lab Appointment Accepted'), (21, 'Lab Appointment Cancelled'), (22, 'Lab Appointment Rescheduled by Patient'), (23, 'Lab Appointment Rescheduled by Lab'), (24, 'Lab Appointment Booked'), (25, 'Lab Report Uploaded'), (26, 'Send Lab Reports via CRM'), (6, 'Prescription Uploaded'), (7, 'Payment Pending'), (8, 'Receipt'), (10, 'Doctor Invoice'), (11, 'Lab Invoice'), (55, 'Cashback Credited')])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whtsapp_notification',
            },
        ),
    ]
