# Generated by Django 2.0.5 on 2019-02-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0020_merge_20190212_1058'),
        ('notification', '0020_merge_20190213_1419'),
    ]

    operations = [
    ]
