# Generated by Django 2.0.5 on 2019-02-19 09:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0020_whtsappnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='whtsappnotification',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
