# Generated by Django 2.0.5 on 2019-02-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0021_merge_20190213_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
