# Generated by Django 2.0.5 on 2019-02-19 10:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0021_whtsappnotification_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whtsappnotification',
            name='params',
        ),
        migrations.AddField(
            model_name='whtsappnotification',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
