# Generated by Django 2.0.5 on 2019-02-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0022_auto_20190219_1612'),
        ('notification', '0021_merge_20190213_1425'),
    ]

    operations = [
    ]
