# Generated by Django 2.0.5 on 2019-03-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0023_merge_20190226_1805'),
        ('notification', '0022_auto_20190228_1554'),
    ]

    operations = [
    ]
