# Generated by Django 2.0.5 on 2019-03-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0019_merge_20190204_1401'),
        ('notification', '0025_auto_20190305_1235'),
    ]

    operations = [
    ]
