# Generated by Django 2.0.5 on 2019-03-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0026_auto_20190311_1523'),
        ('notification', '0028_merge_20190313_1047'),
    ]

    operations = [
    ]
