# Generated by Django 2.0.5 on 2019-04-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0030_auto_20190319_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='object_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
