# Generated by Django 2.0.5 on 2019-05-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0035_whtsappnotification_extras'),
        ('notification', '0035_auto_20190520_1346'),
    ]

    operations = [
    ]
