# Generated by Django 2.0.5 on 2019-06-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0037_auto_20190522_1047'),
        ('notification', '0027_auto_20190405_1614'),
    ]

    operations = [
    ]
