# Generated by Django 2.0.5 on 2019-06-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0039_auto_20190607_1132'),
        ('notification', '0038_merge_20190613_1654'),
    ]

    operations = [
    ]
