# Generated by Django 2.0.5 on 2019-06-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0040_merge_20190614_1237'),
        ('notification', '0040_merge_20190613_1818'),
    ]

    operations = [
    ]
