# Generated by Django 2.0.5 on 2019-06-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0039_auto_20190614_1327'),
        ('notification', '0041_merge_20190614_1243'),
    ]

    operations = [
    ]
