# Generated by Django 2.0.5 on 2019-06-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0039_auto_20190614_1449'),
        ('notification', '0042_merge_20190614_1444'),
    ]

    operations = [
    ]
