# Generated by Django 2.0.5 on 2019-06-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0044_auto_20190614_1501'),
        ('notification', '0043_auto_20190614_1734'),
    ]

    operations = [
    ]
