# Generated by Django 2.0.5 on 2019-08-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0049_auto_20190801_2000'),
        ('notification', '0049_auto_20190730_1255'),
    ]

    operations = [
    ]
