# Generated by Django 2.0.5 on 2019-08-09 06:40

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0049_auto_20190730_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_name', models.CharField(help_text='Give name without extension', max_length=100)),
                ('template_type', models.CharField(choices=[('EMAIL', 'EMAIL'), ('SMS', 'SMS')], max_length=100)),
                ('content', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('sample_parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dynamic_template',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dynamictemplates',
            unique_together={('template_name', 'template_type')},
        ),
    ]
