# Generated by Django 2.0.5 on 2019-08-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0050_auto_20190809_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictemplates',
            name='virtual_content',
            field=models.TextField(null=True),
        ),
    ]
