# Generated by Django 2.0.5 on 2019-08-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0051_dynamictemplates_virtual_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictemplates',
            name='subject',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
