# Generated by Django 2.0.5 on 2019-08-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0052_dynamictemplates_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictemplates',
            name='recipient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
