# Generated by Django 2.0.5 on 2019-08-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0053_dynamictemplates_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictemplates',
            name='bcc',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='dynamictemplates',
            name='cc',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
