# Generated by Django 2.0.5 on 2019-08-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0053_dynamictemplates_recipient'),
        ('notification', '0051_auto_20190806_1813'),
    ]

    operations = [
    ]
