# Generated by Django 2.0.5 on 2019-08-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0056_auto_20190829_1322'),
        ('notification', '0054_auto_20190823_1416'),
    ]

    operations = [
    ]
