# Generated by Django 2.0.5 on 2019-11-15 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0323_merge_20191106_1315'),
        ('notification', '0060_auto_20191001_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDIntimateEmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.BigIntegerField()),
                ('preferred_date', models.DateTimeField(blank=True, null=True)),
                ('time_slot', models.DateTimeField(blank=True, null=True)),
                ('gender', models.PositiveIntegerField(blank=True, choices=[(1, 'male'), (2, 'female')], null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctor.Doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctor.Hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ipd_intimate_email_notification',
            },
        ),
    ]
