# Generated by Django 2.0.5 on 2019-11-25 11:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0063_auto_20191125_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipdintimateemailnotification',
            name='email_notification',
        ),
        migrations.AddField(
            model_name='ipdintimateemailnotification',
            name='email_notifications',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
