# Generated by Django 2.0.5 on 2019-11-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0064_auto_20191125_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdintimateemailnotification',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
