# Generated by Django 2.0.5 on 2019-11-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0065_auto_20191126_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdintimateemailnotification',
            name='time_slot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
