# Generated by Django 2.0.5 on 2019-11-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0067_auto_20191126_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdintimateemailnotification',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=100, null=True),
        ),
    ]
