# Generated by Django 2.0.5 on 2019-11-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0069_ipdintimateemailnotification_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdintimateemailnotification',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
