# Generated by Django 2.0.5 on 2018-10-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_key', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('details', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'procedure_category',
            },
        ),
        migrations.CreateModel(
            name='ProcedureCategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manual', models.BooleanField(default=False)),
                ('child_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_child_category', to='procedure.ProcedureCategory')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_parent_category', to='procedure.ProcedureCategory')),
            ],
            options={
                'db_table': 'procedure_category_mapping',
            },
        ),
        migrations.AddField(
            model_name='procedure',
            name='search_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='procedurecategory',
            name='parents',
            field=models.ManyToManyField(through='procedure.ProcedureCategoryMapping', to='procedure.ProcedureCategory'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='categories',
            field=models.ManyToManyField(to='procedure.ProcedureCategory'),
        ),
    ]
