# Generated by Django 2.0.5 on 2018-10-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0002_auto_20181025_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurecategory',
            name='parents',
            field=models.ManyToManyField(related_name='children', through='procedure.ProcedureCategoryMapping', to='procedure.ProcedureCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='procedurecategorymapping',
            unique_together={('parent_category', 'child_category')},
        ),
    ]
