# Generated by Django 2.0.5 on 2018-10-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0003_auto_20181025_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='procedurecategory',
            options={'ordering': ['name']},
        ),
    ]
