# Generated by Django 2.0.5 on 2018-10-29 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0006_auto_20181027_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurecategory',
            name='preferred_procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_preferred_in', to='procedure.Procedure'),
        ),
    ]
