# Generated by Django 2.0.5 on 2018-10-29 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0007_procedurecategory_preferred_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurecategory',
            name='preferred_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_in_category', to='procedure.Procedure'),
        ),
    ]
