# Generated by Django 2.0.5 on 2018-10-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0008_auto_20181029_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurecategory',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
