# Generated by Django 2.0.5 on 2018-10-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0010_auto_20181029_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduretocategorymapping',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
