# Generated by Django 2.0.5 on 2018-10-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0011_proceduretocategorymapping_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorclinicprocedure',
            name='listing_price',
        ),
        migrations.AddField(
            model_name='doctorclinicprocedure',
            name='deal_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctorclinicprocedure',
            name='agreed_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctorclinicprocedure',
            name='mrp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
