# Generated by Django 2.0.5 on 2018-11-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0012_auto_20181031_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={},
        ),
        migrations.AlterModelOptions(
            name='procedurecategory',
            options={},
        ),
    ]
