# Generated by Django 2.0.5 on 2018-11-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0016_auto_20181112_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='duration',
            field=models.IntegerField(default=60),
        ),
    ]
