# Generated by Django 2.0.5 on 2018-11-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0017_auto_20181113_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
