# Generated by Django 2.0.5 on 2019-02-26 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0202_merge_20190222_1705'),
        ('common', '0022_feature'),
        ('procedure', '0020_auto_20190219_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorClinicIpdProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipd_procedure_clinic_mappings', to='doctor.DoctorClinic')),
            ],
            options={
                'db_table': 'doctor_clinic_ipd_procedure',
            },
        ),
        migrations.CreateModel(
            name='IpdProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_key', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('details', models.TextField(blank=True)),
                ('is_live', models.BooleanField(default=False)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'ipd_procedure',
            },
        ),
        migrations.CreateModel(
            name='IpdProcedureFeatureMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=500)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipd_procedures_mappings', to='common.Feature')),
                ('ipd_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_mappings', to='procedure.IpdProcedure')),
            ],
            options={
                'db_table': 'ipd_procedure_feature_mapping',
            },
        ),
        migrations.AddField(
            model_name='ipdprocedure',
            name='features',
            field=models.ManyToManyField(related_name='of_ipd_procedures', through='procedure.IpdProcedureFeatureMapping', to='common.Feature'),
        ),
        migrations.AddField(
            model_name='doctorclinicipdprocedure',
            name='ipd_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_clinic_ipd_mappings', to='procedure.IpdProcedure'),
        ),
        migrations.AlterUniqueTogether(
            name='ipdprocedurefeaturemapping',
            unique_together={('ipd_procedure', 'feature')},
        ),
        migrations.AlterUniqueTogether(
            name='doctorclinicipdprocedure',
            unique_together={('ipd_procedure', 'doctor_clinic')},
        ),
    ]
