# Generated by Django 2.0.5 on 2019-02-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0021_auto_20190226_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorclinicipdprocedure',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
