# Generated by Django 2.0.5 on 2019-02-27 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0022_doctorclinicipdprocedure_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipdprocedure',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='ipdprocedure',
            name='min_price',
        ),
    ]
