# Generated by Django 2.0.5 on 2019-03-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0024_auto_20190227_1534'),
        ('procedure', '0024_auto_20190301_1344'),
    ]

    operations = [
    ]
