# Generated by Django 2.0.5 on 2019-03-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0026_ipdprocedurelead'),
        ('procedure', '0025_ipdprocedure_deleted'),
    ]

    operations = [
    ]
