# Generated by Django 2.0.5 on 2019-03-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0027_merge_20190307_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdprocedure',
            name='about',
            field=models.TextField(blank=True, verbose_name='Short description'),
        ),
    ]
