# Generated by Django 2.0.5 on 2019-03-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0028_ipdprocedure_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdprocedure',
            name='search_key',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='ipdprocedurecategory',
            name='search_key',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='search_key',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='procedurecategory',
            name='search_key',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
