# Generated by Django 2.0.5 on 2019-03-28 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0029_auto_20190320_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpdProcedureDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(blank=True, verbose_name='Detail')),
            ],
            options={
                'db_table': 'ipd_procedure_details',
            },
        ),
        migrations.CreateModel(
            name='IpdProcedureDetailType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'ipd_procedure_detail_type',
            },
        ),
        migrations.AddField(
            model_name='ipdproceduredetail',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procedure.IpdProcedureDetailType', verbose_name='Detail Type'),
        ),
    ]
