# Generated by Django 2.0.5 on 2019-03-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0032_auto_20190328_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdproceduredetailtype',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
