# Generated by Django 2.0.5 on 2019-03-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0033_ipdproceduredetailtype_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdproceduredetailtype',
            name='show_doctors',
            field=models.BooleanField(default=False),
        ),
    ]
