# Generated by Django 2.0.5 on 2019-04-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0034_ipdproceduredetailtype_show_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdprocedure',
            name='show_about',
            field=models.BooleanField(default=False),
        ),
    ]
