# Generated by Django 2.0.5 on 2019-04-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0036_ipdprocedurelead_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdprocedure',
            name='synonyms',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
