# Generated by Django 2.0.5 on 2019-04-24 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0037_ipdprocedure_synonyms'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpdProcedureSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'ipd_procedure_synonym',
            },
        ),
        migrations.CreateModel(
            name='IpdProcedureSynonymMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('ipd_procedure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.IpdProcedure')),
                ('ipd_procedure_synonym_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.IpdProcedureSynonym')),
            ],
            options={
                'db_table': 'procedure_synonym_mapping',
            },
        ),
    ]
