# Generated by Django 2.0.5 on 2019-04-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0038_ipdproceduresynonym_ipdproceduresynonymmapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipdproceduresynonymmapping',
            old_name='ipd_procedure_id',
            new_name='ipd_procedure',
        ),
        migrations.RenameField(
            model_name='ipdproceduresynonymmapping',
            old_name='ipd_procedure_synonym_id',
            new_name='ipd_procedure_synonym',
        ),
    ]
