# Generated by Django 2.0.5 on 2019-04-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0040_auto_20190424_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipdproceduresynonymmapping',
            old_name='ipd_procedure_id',
            new_name='ipd_procedure',
        ),
        migrations.RenameField(
            model_name='ipdproceduresynonymmapping',
            old_name='ipd_procedure_synonym_id',
            new_name='ipd_procedure_synonym',
        ),
    ]
