# Generated by Django 2.0.5 on 2019-05-02 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0041_auto_20190429_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarIpdProcedureMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('ipd_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_ipds_1', to='procedure.IpdProcedure')),
                ('similar_ipd_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_ipds_2', to='procedure.IpdProcedure')),
            ],
            options={
                'db_table': 'similar_ipd_procedure_mapping',
            },
        ),
    ]
