# Generated by Django 2.0.5 on 2019-05-02 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0042_similaripdproceduremapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similaripdproceduremapping',
            name='ipd_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_ipds', to='procedure.IpdProcedure'),
        ),
        migrations.AlterUniqueTogether(
            name='similaripdproceduremapping',
            unique_together={('ipd_procedure', 'similar_ipd_procedure')},
        ),
    ]
