# Generated by Django 2.0.5 on 2019-05-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0043_auto_20190502_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdprocedurelead',
            name='city',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ipdprocedurelead',
            name='lat',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ipdprocedurelead',
            name='long',
            field=models.FloatField(default=None, null=True),
        ),
    ]
