# Generated by Django 2.0.5 on 2019-05-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0044_auto_20190507_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdprocedurelead',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
