# Generated by Django 2.0.5 on 2019-05-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0045_auto_20190507_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdprocedurelead',
            name='matrix_lead_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ipdprocedurelead',
            name='source',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ipdprocedurelead',
            name='specialty',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
