# Generated by Django 2.0.5 on 2019-05-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0254_merge_20190510_1419'),
        ('procedure', '0046_auto_20190509_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpdProcedurePracticeSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ipd_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.IpdProcedure')),
                ('practice_specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.PracticeSpecialization')),
            ],
            options={
                'db_table': 'ipd_procedure_practice_specialization',
            },
        ),
    ]
