# Generated by Django 2.0.5 on 2019-05-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0049_auto_20190521_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdprocedurelead',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ipdprocedurelead',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ipdprocedurelead',
            name='long',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ipdprocedurelead',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ipdprocedurelead',
            name='specialty',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
