# Generated by Django 2.0.5 on 2019-05-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0050_auto_20190521_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdprocedurelead',
            name='source',
            field=models.CharField(blank=True, choices=[('c_app', 'Consumer App'), ('crm', 'CRM'), ('web', 'Consumer Web'), ('d_app', 'Doctor App'), ('d_web', 'Provider Web'), ('d_web_url', 'Doctor Web URL'), ('d_token_url', 'Doctor Token URL'), ('ivr', 'Auto IVR')], default=None, max_length=256, null=True),
        ),
    ]
