# Generated by Django 2.0.5 on 2019-05-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0052_auto_20190522_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdprocedurelead',
            name='payment_type',
            field=models.IntegerField(blank=True, choices=[(None, '--Select--'), (1, 'CASH'), (2, 'INSURANCE'), (3, 'GOVERNMENT_PANEL')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ipdprocedurelead',
            name='source',
            field=models.CharField(blank=True, choices=[('docprimechat', 'DocPrime Chat'), ('crm', 'CRM'), ('docprimeweb', 'DocPrime Web')], default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ipdprocedurelead',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(None, '--Select--'), (1, 'NEW'), (2, 'COST_REQUESTED'), (3, 'COST_SHARED'), (4, 'OPD'), (5, 'NOT_INTERESTED'), (6, 'COMPLETED')], default=1, null=True),
        ),
    ]
