# Generated by Django 2.0.5 on 2019-05-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0055_auto_20190523_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdprocedurelead',
            name='referer_doctor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ipdprocedurelead',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
