# Generated by Django 2.0.5 on 2019-05-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0056_auto_20190524_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdprocedure',
            name='icon',
            field=models.ImageField(null=True, upload_to='ipd_procedure/images'),
        ),
    ]
