# Generated by Django 2.0.5 on 2019-05-31 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0259_auto_20190529_1156'),
        ('procedure', '0057_ipdprocedure_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpdCostEstimateRoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'ipd_cost_estimate_room_type',
            },
        ),
        migrations.CreateModel(
            name='IpdCostEstimateRoomTypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ipd_cost_estimate_room_type_mapping',
            },
        ),
        migrations.CreateModel(
            name='IpdProcedureCostEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stay_duration', models.IntegerField(blank=True, null=True)),
                ('costs', models.ManyToManyField(related_name='of_ipd_procedures', through='procedure.IpdCostEstimateRoomTypeMapping', to='procedure.IpdCostEstimateRoomType')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Hospital')),
                ('ipd_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.IpdProcedure')),
            ],
            options={
                'db_table': 'ipd_procedure_cost_estimate',
            },
        ),
        migrations.CreateModel(
            name='IpdProcedureLeadCostEstimateMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_estimate', to='procedure.IpdProcedureCostEstimate')),
                ('ipd_procedure_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='procedure.IpdProcedureLead')),
            ],
            options={
                'db_table': 'ipd_procedure_lead_cost_estimate',
            },
        ),
        migrations.AddField(
            model_name='ipdcostestimateroomtypemapping',
            name='cost_estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.IpdProcedureCostEstimate'),
        ),
        migrations.AddField(
            model_name='ipdcostestimateroomtypemapping',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.IpdCostEstimateRoomType'),
        ),
        migrations.AlterUniqueTogether(
            name='ipdprocedurecostestimate',
            unique_together={('ipd_procedure', 'hospital')},
        ),
    ]
