# Generated by Django 2.0.5 on 2019-05-31 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0032_merge_20190516_1820'),
        ('doctor', '0259_auto_20190529_1156'),
        ('procedure', '0057_ipdprocedure_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('is_live', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('show_tnc', models.BooleanField(default=False)),
                ('tnc', models.TextField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.Coupon')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_offers', to='doctor.Hospital')),
                ('ipd_procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipd_offers', to='procedure.IpdProcedure')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_offers', to='doctor.HospitalNetwork')),
            ],
            options={
                'db_table': 'offer',
            },
        ),
    ]
