# Generated by Django 2.0.5 on 2019-06-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0058_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdprocedurelead',
            name='source',
            field=models.CharField(blank=True, choices=[('docprimechat', 'DocPrime Chat'), ('crm', 'CRM'), ('docprimeweb', 'DocPrime Web'), ('Costestimate', 'Cost Estimate')], default=None, max_length=256, null=True),
        ),
    ]
