# Generated by Django 2.0.5 on 2019-05-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0058_auto_20190531_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdcostestimateroomtypemapping',
            name='cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
