# Generated by Django 2.0.5 on 2019-06-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0059_auto_20190606_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdprocedurelead',
            name='source',
            field=models.CharField(blank=True, choices=[('docprimechat', 'DocPrime Chat'), ('crm', 'CRM'), ('docprimeweb', 'DocPrime Web'), ('Costestimate', 'Cost Estimate'), ('DocprimeApp', 'Docprime Consumer App')], default=None, max_length=256, null=True),
        ),
    ]
