# Generated by Django 2.0.5 on 2019-06-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0060_auto_20190603_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdprocedurelead',
            name='procedure_cost_estimates',
            field=models.ManyToManyField(related_name='procedure_cost_estimates', through='procedure.IpdProcedureLeadCostEstimateMapping', to='procedure.IpdProcedureCostEstimate'),
        ),
    ]
