# Generated by Django 2.0.5 on 2019-06-20 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0273_auto_20190618_1236'),
        ('procedure', '0060_auto_20190617_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialIpdLeadPracticeSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.PracticeSpecialization')),
            ],
            options={
                'db_table': 'potential_ipd_lead_practice_specialization',
            },
        ),
    ]
