# Generated by Django 2.0.5 on 2019-06-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0273_auto_20190618_1236'),
        ('procedure', '0061_potentialipdleadpracticespecialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdprocedurelead',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Doctor'),
        ),
    ]
