# Generated by Django 2.0.5 on 2019-06-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0059_auto_20190606_1202'),
        ('procedure', '0062_auto_20190610_1604'),
    ]

    operations = [
    ]
