# Generated by Django 2.0.5 on 2019-06-13 06:41

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procedure', '0063_merge_20190612_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCostEstimateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
                ('source', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('status', models.PositiveSmallIntegerField(choices=[('', 'Select'), (1, 'Created'), (2, 'Upload in progress'), (3, 'Upload successful'), (4, 'Upload Failed')], default=1, editable=False)),
                ('error_msg', django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True)),
                ('lines', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_cost_estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
