# Generated by Django 2.0.5 on 2019-06-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0064_uploadcostestimatedata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ipdprocedureleadcostestimatemapping',
            unique_together={('ipd_procedure_lead', 'cost_estimate')},
        ),
    ]
