# Generated by Django 2.0.5 on 2019-06-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0060_auto_20190617_1051'),
        ('procedure', '0065_auto_20190617_1233'),
    ]

    operations = [
    ]
