# Generated by Django 2.0.5 on 2019-06-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0066_merge_20190618_1829'),
        ('procedure', '0062_ipdprocedurelead_doctor'),
    ]

    operations = [
    ]
