# Generated by Django 2.0.5 on 2019-07-15 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0054_lastusagetimestamp'),
        ('procedure', '0068_auto_20190627_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialIpdCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.MatrixMappedCity')),
            ],
            options={
                'db_table': 'potential_ipd_city',
            },
        ),
        migrations.AlterField(
            model_name='ipdprocedurelead',
            name='source',
            field=models.CharField(blank=True, choices=[('docprimechat', 'DocPrime Chat'), ('crm', 'CRM'), ('docprimeweb', 'DocPrime Web'), ('Costestimate', 'Cost Estimate'), ('DocprimeApp', 'Docprime Consumer App'), ('seo_dp', 'SEO Doctor Profile')], default=None, max_length=256, null=True),
        ),
    ]
