# Generated by Django 2.0.5 on 2019-07-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0069_auto_20190715_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdprocedurelead',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ipdprocedurelead',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ipdprocedurelead',
            name='requested_date_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
