# Generated by Django 2.0.5 on 2019-07-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0054_lastusagetimestamp'),
        ('procedure', '0070_auto_20190715_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdprocedurelead',
            name='matrix_city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_lead_in', to='common.MatrixMappedCity'),
        ),
    ]
