# Generated by Django 2.0.5 on 2019-07-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0071_ipdprocedurelead_matrix_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdprocedurelead',
            name='is_valid',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ipdprocedurelead',
            name='source',
            field=models.CharField(blank=True, choices=[('docprimechat', 'DocPrime Chat'), ('crm', 'CRM'), ('docprimeweb', 'DocPrime Web'), ('Costestimate', 'Cost Estimate'), ('DocprimeApp', 'Docprime Consumer App'), ('seo_dp', 'SEO Doctor Profile'), ('dropoff', 'DropOff')], default=None, max_length=256, null=True),
        ),
    ]
