# Generated by Django 2.0.5 on 2020-01-08 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0072_auto_20190725_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdprocedure',
            name='svg_icon',
            field=models.ImageField(null=True, upload_to='ipd_procedure/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
