# Generated by Django 2.0.5 on 2018-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(db_index=True, max_length=48),
        ),
    ]
