# Generated by Django 2.0.5 on 2018-11-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_matrixcitymapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=48)),
                ('file', models.FileField(upload_to='common/pdf/test')),
            ],
            options={
                'db_table': 'pdftest',
            },
        ),
    ]
