# Generated by Django 2.0.5 on 2018-11-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_pdftester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftester',
            name='name',
            field=models.CharField(db_index=True, max_length=48000),
        ),
    ]
