# Generated by Django 2.0.5 on 2019-01-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_paymentoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoptions',
            name='priority',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
