# Generated by Django 2.0.5 on 2018-11-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20181127_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdftester',
            name='name',
        ),
        migrations.AddField(
            model_name='pdftester',
            name='html',
            field=models.TextField(default='', max_length=48000),
            preserve_default=False,
        ),
    ]
