# Generated by Django 2.0.5 on 2018-11-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20181127_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftester',
            name='file',
            field=models.FileField(blank=True, upload_to='common/pdf/test'),
        ),
    ]
