# Generated by Django 2.0.5 on 2019-01-14 07:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_userconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfig',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='rtl',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='text',
        ),
        migrations.AddField(
            model_name='userconfig',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
