# Generated by Django 2.0.5 on 2018-11-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20181127_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftester',
            name='html',
            field=models.TextField(max_length=50000000),
        ),
    ]
