# Generated by Django 2.0.5 on 2018-11-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20181127_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftester',
            name='css',
            field=models.TextField(blank=True, max_length=50000000),
        ),
    ]
