# Generated by Django 2.0.5 on 2019-01-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20190114_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='key',
            field=models.CharField(default='', max_length=500),
        ),
    ]
