# Generated by Django 2.0.5 on 2018-12-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_pdftester_css'),
        ('common', '0004_appointmenthistory'),
    ]

    operations = [
    ]
