# Generated by Django 2.0.5 on 2019-01-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20190114_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='key',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
