# Generated by Django 2.0.5 on 2019-01-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_paymentoptions_priority'),
        ('common', '0010_auto_20190114_1701'),
    ]

    operations = [
    ]
