# Generated by Django 2.0.5 on 2019-01-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_merge_20190115_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfig',
            name='share_text',
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='share_url',
        ),
    ]
