# Generated by Django 2.0.5 on 2019-02-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_paymentoptions'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='paymentoptions',
        #     name='payment_gateway',
        #     field=models.TextField(blank=True, default=''),
        # ),
        # migrations.AddField(
        #     model_name='paymentoptions',
        #     name='priority',
        #     field=models.IntegerField(default=0, null=True),
        # ),
    ]
