# Generated by Django 2.0.5 on 2019-01-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20190116_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoptions',
            name='payment_gateway',
            field=models.TextField(blank=True, default=''),
        ),
    ]
