# Generated by Django 2.0.5 on 2019-02-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_paymentoptions_payment_gateway'),
        ('common', '0012_auto_20190201_1814'),
    ]

    operations = [
    ]
