# Generated by Django 2.0.5 on 2019-02-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('', 'Select'), (1, 'Feedback'), (2, 'Reopen'), (3, 'Other')], default=0),
        ),
    ]
