# Generated by Django 2.0.5 on 2019-02-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_appointmentmasknumber'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointmentmasknumber',
            table='appointment_mast_number',
        ),
    ]
