# Generated by Django 2.0.5 on 2019-02-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_appointmenthistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenthistory',
            name='source',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('crm', 'CRM'), ('web', 'Web'), ('app', 'App')], default='', max_length=10),
        ),
    ]
