# Generated by Django 2.0.5 on 2019-02-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='name',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
