# Generated by Django 2.0.5 on 2019-02-12 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20190212_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='name',
            field=models.FileField(upload_to='doctor/qrcode', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jfif', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
