# Generated by Django 2.0.5 on 2019-02-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20190206_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmasknumber',
            name='mask_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
