# Generated by Django 2.0.5 on 2019-02-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_remark_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='content',
            field=models.TextField(),
        ),
    ]
