# Generated by Django 2.0.5 on 2019-02-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20190213_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenthistory',
            name='source',
            field=models.CharField(blank=True, choices=[('c_app', 'Consumer App'), ('crm', 'CRM'), ('web', 'Web'), ('d_app', 'Doctor App')], default='', max_length=10),
        ),
    ]
