# Generated by Django 2.0.5 on 2019-02-12 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20190212_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='name',
            field=models.FileField(upload_to='qrcode', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jfif', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
