# Generated by Django 2.0.5 on 2019-02-11 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20190206_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=48)),
            ],
            options={
                'db_table': 'matrix_city',
            },
        ),
        migrations.CreateModel(
            name='MatrixState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=48)),
            ],
            options={
                'db_table': 'matrix_state',
            },
        ),
        migrations.AddField(
            model_name='matrixcity',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.MatrixState'),
        ),
    ]
