# Generated by Django 2.0.5 on 2019-02-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_appointmentmasknumber_is_deleted'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointmentmasknumber',
            table='appointment_mask_number',
        ),
    ]
