# Generated by Django 2.0.5 on 2019-02-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20190212_1754'),
        ('common', '0014_appointmenthistory_user'),
    ]

    operations = [
    ]
