# Generated by Django 2.0.5 on 2019-02-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20190208_1655'),
        ('common', '0014_appointmenthistory_user'),
    ]

    operations = [
    ]
