# Generated by Django 2.0.5 on 2019-02-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_merge_20190212_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmasknumber',
            name='is_mask_number',
            field=models.BooleanField(default=True),
        ),
    ]
