# Generated by Django 2.0.5 on 2019-02-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_appointmentmasknumber_is_mask_number'),
        ('common', '0017_auto_20190213_1715'),
    ]

    operations = [
    ]
