# Generated by Django 2.0.5 on 2019-02-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_appointmentmasknumber_is_mask_number'),
        ('common', '0018_auto_20190211_1503'),
    ]

    operations = [
    ]
