# Generated by Django 2.0.5 on 2019-02-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_merge_20190214_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNonBookable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_type', models.CharField(blank=True, choices=[('doctor', 'Doctor Clinic'), ('lab', 'Lab')], default='', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'global_non_bookable_timing',
            },
        ),
    ]
