# Generated by Django 2.0.5 on 2019-02-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_service')
    ]

    operations = [
    ]
