# Generated by Django 2.0.5 on 2019-03-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_globalnonbookable'),
        ('common', '0024_merge_20190228_1435'),
    ]

    operations = [
    ]
