# Generated by Django 2.0.5 on 2019-03-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_merge_20190228_1435'),
        ('common', '0021_merge_20190214_1320'),
    ]

    operations = [
    ]
