# Generated by Django 2.0.5 on 2019-03-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_merge_20190304_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matrixmappedcity',
            options={'verbose_name_plural': 'Matrix Mapped Cities'},
        ),
        migrations.AlterModelOptions(
            name='matrixmappedstate',
            options={'verbose_name_plural': 'Matrix Mapped States'},
        ),
    ]
