# Generated by Django 2.0.5 on 2019-03-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_merge_20190213_1625'),
        ('common', '0026_auto_20190304_1259'),
    ]

    operations = [
    ]
