# Generated by Django 2.0.5 on 2019-03-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20190304_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
