# Generated by Django 2.0.5 on 2019-03-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20190304_1259'),
        ('common', '0014_merge_20190204_1401'),
    ]

    operations = [
    ]
