# Generated by Django 2.0.5 on 2019-03-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20190311_1750'),
        ('common', '0027_feature_priority'),
    ]

    operations = [
    ]
