# Generated by Django 2.0.5 on 2019-03-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_feature_priority'),
        ('common', '0027_merge_20190308_1423'),
    ]

    operations = [
    ]
