# Generated by Django 2.0.5 on 2019-03-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_auto_20190315_0958'),
        ('common', '0028_merge_20190312_1851'),
    ]

    operations = [
    ]
