# Generated by Django 2.0.5 on 2019-03-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_merge_20190318_1404'),
        ('common', '0030_qrcode_data'),
    ]

    operations = [
    ]
