# Generated by Django 2.0.5 on 2019-03-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_merge_20190318_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenthistory',
            name='source',
            field=models.CharField(blank=True, choices=[('c_app', 'Consumer App'), ('crm', 'CRM'), ('web', 'Consumer Web'), ('d_app', 'Doctor App'), ('d_web', 'Provider Web'), ('d_web_url', 'Doctor Web URL'), ('d_token_url', 'Doctor Token URL')], default='', max_length=10),
        ),
    ]
