# Generated by Django 2.0.5 on 2019-04-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_merge_20190319_1423'),
        ('common', '0031_merge_20190319_1347'),
    ]

    operations = [
    ]
