# Generated by Django 2.0.5 on 2019-03-29 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_syncbookinganalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixmappedcity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matrixmappedcity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matrixmappedstate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matrixmappedstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
