# Generated by Django 2.0.5 on 2019-04-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_auto_20190329_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncbookinganalytics',
            name='last_updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='syncbookinganalytics',
            name='synced_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
