# Generated by Django 2.0.5 on 2019-04-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_merge_20190408_1616'),
        ('common', '0032_merge_20190410_1251'),
    ]

    operations = [
    ]
