# Generated by Django 2.0.5 on 2019-04-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_merge_20190409_1318'),
        ('common', '0033_merge_20190410_1252'),
    ]

    operations = [
    ]
