# Generated by Django 2.0.5 on 2019-04-02 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0033_auto_20190401_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncbookinganalytics',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='syncbookinganalytics',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='syncbookinganalytics',
            unique_together={('object_id', 'content_type')},
        ),
    ]
