# Generated by Django 2.0.5 on 2019-04-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_auto_20190402_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncbookinganalytics',
            name='last_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='syncbookinganalytics',
            name='synced_at',
            field=models.DateTimeField(null=True),
        ),
    ]
