# Generated by Django 2.0.5 on 2019-04-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_merge_20190411_1136'),
        ('common', '0033_refunddetails'),
    ]

    operations = [
    ]
