# Generated by Django 2.0.5 on 2019-04-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_auto_20190402_1639'),
        ('common', '0035_merge_20190417_1804'),
    ]

    operations = [
    ]
