# Generated by Django 2.0.5 on 2019-04-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_auto_20190416_1457'),
        ('common', '0036_merge_20190418_1401'),
    ]

    operations = [
    ]
