# Generated by Django 2.0.5 on 2019-04-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_merge_20190422_1412'),
        ('common', '0037_merge_20190418_1525'),
    ]

    operations = [
    ]
