# Generated by Django 2.0.5 on 2019-05-20 12:21

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0038_merge_20190422_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_version', models.CharField(max_length=20)),
                ('os', models.PositiveSmallIntegerField()),
                ('os_version', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('installed_date', models.DateTimeField()),
                ('firebase_reg_id', models.CharField(max_length=200)),
                ('app_name', models.CharField(max_length=200)),
                ('ping_status', models.CharField(max_length=50)),
                ('last_ping_time', models.DateTimeField()),
                ('last_usage', models.DateTimeField()),
                ('dnd', models.BooleanField(default=False)),
                ('d_token', models.CharField(max_length=200)),
                ('res', models.CharField(max_length=100)),
                ('adv_id', models.CharField(max_length=100)),
                ('apps_flyer_id', models.CharField(max_length=100)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_details',
            },
        ),
    ]
