# Generated by Django 2.0.5 on 2019-05-22 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_devicedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedetails',
            old_name='d_token',
            new_name='device_id',
        ),
        migrations.RemoveField(
            model_name='devicedetails',
            name='installed_date',
        ),
        migrations.RemoveField(
            model_name='devicedetails',
            name='last_usage',
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='adv_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='app_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='app_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='apps_flyer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='firebase_reg_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='last_ping_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='os',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='os_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='ping_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='res',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
