# Generated by Django 2.0.5 on 2019-05-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_auto_20190521_1511'),
        ('common', '0039_devicedetails'),
    ]

    operations = [
    ]
