# Generated by Django 2.0.5 on 2019-06-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_blacklistuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_name', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'blocked_states',
            },
        ),
        migrations.AddField(
            model_name='blacklistuser',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blacklistuser',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.BlockedStates'),
        ),
        migrations.AlterModelTable(
            name='blacklistuser',
            table='blacklist_users',
        ),
    ]
