# Generated by Django 2.0.5 on 2019-06-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_auto_20190522_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedetails',
            name='os',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
