# Generated by Django 2.0.5 on 2019-05-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_auto_20190522_1832'),
        ('common', '0040_merge_20190522_1234'),
    ]

    operations = [
    ]
