# Generated by Django 2.0.5 on 2019-06-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_auto_20190603_1940'),
        ('common', '0041_merge_20190522_1845'),
    ]

    operations = [
    ]
