# Generated by Django 2.0.5 on 2019-06-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_genericnotes_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericnotes',
            name='object_id',
            field=models.BigIntegerField(),
        ),
    ]
