# Generated by Django 2.0.5 on 2019-06-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_merge_20190603_1943'),
        ('common', '0042_auto_20190607_1655'),
    ]

    operations = [
    ]
