# Generated by Django 2.0.5 on 2019-06-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_auto_20190607_1655'),
        ('common', '0044_auto_20190607_1816'),
    ]

    operations = [
    ]
