# Generated by Django 2.0.5 on 2019-06-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0045_merge_20190610_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistuser',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
