# Generated by Django 2.0.5 on 2019-06-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0046_blacklistuser_enabled'),
        ('common', '0043_merge_20190610_1545'),
    ]

    operations = [
    ]
