# Generated by Django 2.0.5 on 2019-06-24 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0047_merge_20190612_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('document_type', models.PositiveSmallIntegerField(choices=[('', 'Select'), (1, 'Credit Letter')], default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='credit_letter')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
