# Generated by Django 2.0.5 on 2019-06-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0048_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[('', 'Select'), (1, 'Document'), (2, 'Credit Letter')], default=0),
        ),
    ]
