# Generated by Django 2.0.5 on 2019-06-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0049_auto_20190624_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[('', 'Select'), (1, 'Document'), (2, 'Credit Letter')], default=1),
        ),
    ]
