# Generated by Django 2.0.5 on 2019-06-25 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0050_auto_20190624_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericnotes',
            name='notes_file',
            field=models.FileField(null=True, upload_to='notes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
