# Generated by Django 2.0.5 on 2019-06-25 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0051_genericnotes_notes_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericnotes',
            name='notes_file',
            field=models.FileField(blank=True, null=True, upload_to='notes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
