# Generated by Django 2.0.5 on 2019-06-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0051_virtualappointment'),
        ('common', '0052_auto_20190625_1838'),
    ]

    operations = [
    ]
