# Generated by Django 2.0.5 on 2019-07-05 12:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0053_merge_20190626_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUsageTimestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('registered_on_app', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('c_app', 'Consumer App'), ('crm', 'CRM'), ('web', 'Consumer Web'), ('d_app', 'Doctor App'), ('d_web', 'Provider Web'), ('d_web_url', 'Doctor Web URL'), ('d_token_url', 'Doctor Token URL'), ('ivr', 'Auto IVR')], max_length=20)),
                ('last_app_open_timestamp', models.DateTimeField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_usage', to='common.DeviceDetails')),
            ],
            options={
                'db_table': 'last_usage_timestamp',
            },
        ),
    ]
