# Generated by Django 2.0.5 on 2019-07-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0054_lastusagetimestamp'),
        ('common', '0054_auto_20190701_1933'),
    ]

    operations = [
    ]
