# Generated by Django 2.0.5 on 2019-08-09 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0293_merge_20190809_1727'),
        ('common', '0056_sponsorlistingspecialization_sponsorlistingurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlistingspecialization',
            name='poc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poc_specialization', to='doctor.PurchaseOrderCreation'),
        ),
        migrations.AddField(
            model_name='sponsorlistingspecialization',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_specialization', to='doctor.PracticeSpecialization'),
        ),
        migrations.AddField(
            model_name='sponsorlistingurl',
            name='poc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poc_sponsorlisting', to='doctor.PurchaseOrderCreation'),
        ),
    ]
