# Generated by Django 2.0.5 on 2019-09-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0056_auto_20190830_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenthistory',
            name='source',
            field=models.CharField(blank=True, choices=[('c_app', 'Consumer App'), ('crm', 'CRM'), ('web', 'Consumer Web'), ('d_app', 'Doctor App'), ('d_web', 'Provider Web'), ('d_web_url', 'Doctor Web URL'), ('d_token_url', 'Doctor Token URL'), ('ivr', 'Auto IVR'), ('thyrocare_api', 'Thyrocare API')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lastusagetimestamp',
            name='source',
            field=models.CharField(choices=[('c_app', 'Consumer App'), ('crm', 'CRM'), ('web', 'Consumer Web'), ('d_app', 'Doctor App'), ('d_web', 'Provider Web'), ('d_web_url', 'Doctor Web URL'), ('d_token_url', 'Doctor Token URL'), ('ivr', 'Auto IVR'), ('thyrocare_api', 'Thyrocare API')], max_length=20),
        ),
    ]
