# Generated by Django 2.0.5 on 2019-08-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0297_merge_20190819_1135'),
        ('common', '0057_auto_20190809_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorListingLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('poc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poc_lat_long', to='doctor.PurchaseOrderCreation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SponsorListingUtmTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utm_term', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('poc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poc_utm_term', to='doctor.PurchaseOrderCreation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sponsorlistingspecialization',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sponsorlistingspecialization',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sponsorlistingspecialization',
            name='radius',
        ),
    ]
