# Generated by Django 2.0.5 on 2019-09-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0057_documentsproofs'),
        ('common', '0057_auto_20190904_1631'),
    ]

    operations = [
    ]
