# Generated by Django 2.0.5 on 2019-08-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0058_auto_20190819_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorlistingurl',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='sponsorlistingurl',
            name='start_date',
        ),
    ]
