# Generated by Django 2.0.5 on 2019-09-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0056_auto_20190830_1739'),
        ('common', '0059_auto_20190820_1254'),
    ]

    operations = [
    ]
