# Generated by Django 2.0.5 on 2019-09-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0060_merge_20190904_1157'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sponsorlistinglocation',
            table='sponsor_listing_location',
        ),
        migrations.AlterModelTable(
            name='sponsorlistingspecialization',
            table='sponsor_listing_specialization',
        ),
        migrations.AlterModelTable(
            name='sponsorlistingurl',
            table='sponsor_listing_url',
        ),
        migrations.AlterModelTable(
            name='sponsorlistingutmterm',
            table='sponsor_listing_utm_term',
        ),
    ]
