# Generated by Django 2.0.5 on 2019-09-04 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0313_merge_20190904_1157'),
        ('common', '0061_auto_20190904_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredListingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poc_sponsor_service', to='doctor.PurchaseOrderCreation')),
                ('sponsored_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsoredlisting_services', to='doctor.SponsoredServices')),
            ],
            options={
                'db_table': 'sponsoredlisting_service',
            },
        ),
    ]
