# Generated by Django 2.0.5 on 2019-09-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0315_remove_hospitalsponsoredservices_poc'),
        ('common', '0062_sponsoredlistingservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsoredlistingservice',
            name='sponsored_service',
        ),
        migrations.AddField(
            model_name='sponsoredlistingservice',
            name='hospital_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospservices', to='doctor.HospitalSponsoredServices'),
        ),
    ]
