# Generated by Django 2.0.5 on 2019-09-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0063_auto_20190905_1549'),
        ('common', '0058_merge_20190906_1304'),
    ]

    operations = [
    ]
