# Generated by Django 2.0.5 on 2019-09-10 13:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0064_merge_20190910_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlistingspecialization',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsorlistingspecialization',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='sponsorlistingspecialization',
            name='radius',
            field=models.FloatField(null=True),
        ),
    ]
