# Generated by Django 2.0.5 on 2019-09-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0065_auto_20190910_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorlistingspecialization',
            name='location',
        ),
        migrations.AddField(
            model_name='sponsorlistingspecialization',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsorlistingspecialization',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
