# Generated by Django 2.0.5 on 2019-09-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0066_auto_20190916_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorlistinglocation',
            name='poc',
        ),
        migrations.DeleteModel(
            name='SponsorListingLocation',
        ),
    ]
