# Generated by Django 2.0.5 on 2019-09-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0067_auto_20190916_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlistingspecialization',
            name='location',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
