# Generated by Django 2.0.5 on 2019-09-17 12:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0318_merge_20190916_1822'),
        ('common', '0069_auto_20190917_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorListingSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('radius', models.FloatField(null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('poc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poc_specialization', to='doctor.PurchaseOrderCreation')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_specialization', to='doctor.PracticeSpecialization')),
            ],
            options={
                'db_table': 'sponsor_listing_specialization',
            },
        ),
    ]
