# Generated by Django 2.0.5 on 2019-10-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0070_sponsorlistingspecialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_key', models.CharField(blank=True, choices=[('', 'Select'), ('is_gold', 'is_gold'), ('is_vip', 'is_vip')], default=None, max_length=500, null=True)),
                ('search_value', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'search_criteria',
            },
        ),
    ]
