# Generated by Django 2.0.5 on 2019-11-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0071_searchcriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPlaceIDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place_id', models.TextField()),
            ],
            options={
                'db_table': 'doctor_place_ids',
            },
        ),
        migrations.CreateModel(
            name='GoogleLatLong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('coordinates', models.TextField()),
                ('is_hospital_done', models.BooleanField(default=False)),
                ('is_doctor_done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'google_lat_long',
            },
        ),
        migrations.CreateModel(
            name='HospitalPlaceIDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place_id', models.TextField()),
                ('google_coordinates', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosp_place_ids', to='common.GoogleLatLong')),
            ],
            options={
                'db_table': 'hospital_place_ids',
            },
        ),
        migrations.AddField(
            model_name='doctorplaceids',
            name='google_coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_place_ids', to='common.GoogleLatLong'),
        ),
    ]
