# Generated by Django 2.0.5 on 2019-11-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0072_auto_20191122_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlelatlong',
            name='coordinates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
