# Generated by Django 2.0.5 on 2019-11-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0072_certifications'),
        ('common', '0072_auto_20191122_1617'),
    ]

    operations = [
    ]
