# Generated by Django 2.0.5 on 2019-11-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0073_auto_20191125_1653'),
        ('common', '0073_merge_20191125_1222'),
    ]

    operations = [
    ]
