# Generated by Django 2.0.5 on 2018-09-25 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ratings_review', '0002_remove_ratingsreview_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingsreview',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
