# Generated by Django 2.0.5 on 2018-09-26 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_review', '0003_ratingsreview_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.PositiveIntegerField(choices=[(0, 'NoAction'), (1, 'Like'), (2, 'Dislike'), (3, 'Report')], default=0)),
            ],
            options={
                'db_table': 'review_action',
            },
        ),
        migrations.AddField(
            model_name='ratingsreview',
            name='appoitnment_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratingsreview',
            name='appoitnment_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lab'), (2, 'Opd')], null=True),
        ),
        migrations.AddField(
            model_name='ratingsreview',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ratingsreview',
            name='ratings',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ratingsreview',
            name='review',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reviewactions',
            name='rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings_review.RatingsReview'),
        ),
    ]
