# Generated by Django 2.0.5 on 2018-09-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_review', '0004_auto_20180926_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCompliments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_high_rating', models.CharField(max_length=100)),
                ('doc_low_rating', models.CharField(max_length=100)),
                ('lab_high_rating', models.CharField(max_length=100)),
                ('lab_low_rating', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
