# Generated by Django 2.0.5 on 2018-09-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_review', '0005_reviewcompliments'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reviewcompliments',
            table='review_compliments',
        ),
    ]
