# Generated by Django 2.0.5 on 2018-10-01 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_review', '0006_auto_20180927_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewactions',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings_review.RatingsReview'),
        ),
    ]
