# Generated by Django 2.0.5 on 2018-10-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_review', '0008_auto_20181001_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingsreview',
            old_name='appoitnment_type',
            new_name='appointment_type',
        ),
    ]
