# Generated by Django 2.0.5 on 2018-11-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_review', '0012_auto_20181025_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcompliments',
            name='rating_level',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
