# Generated by Django 2.0.5 on 2019-02-07 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings_review', '0013_auto_20181119_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCompliments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(default=None, max_length=128)),
                ('rating_level', models.PositiveSmallIntegerField(default=None)),
            ],
            options={
                'db_table': 'app_compliments',
            },
        ),
        migrations.CreateModel(
            name='AppRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ratings', models.PositiveIntegerField(null=True)),
                ('review', models.CharField(blank=True, max_length=5000, null=True)),
                ('app_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Consumer'), (2, 'Provider')], null=True)),
                ('is_live', models.BooleanField(default=True)),
                ('compliment', models.ManyToManyField(related_name='compliment_app', to='ratings_review.AppCompliments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_ratings',
            },
        ),
    ]
