# Generated by Django 2.0.5 on 2019-01-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_review', '0013_auto_20181119_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingsreview',
            name='moderation_comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ratingsreview',
            name='moderation_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lab'), (2, 'Opd')], default=2),
        ),
    ]
