# Generated by Django 2.0.5 on 2019-02-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_review', '0014_appcompliments_appratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appratings',
            name='app_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='appratings',
            name='app_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='appratings',
            name='brand',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='appratings',
            name='device_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='appratings',
            name='model',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='appratings',
            name='platform',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
