# Generated by Django 2.0.5 on 2019-01-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_review', '0014_auto_20190129_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingsreview',
            name='moderation_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Denied')], default=2),
        ),
    ]
