# Generated by Django 2.0.5 on 2019-02-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_review', '0015_auto_20190129_1859'),
        ('ratings_review', '0015_auto_20190207_1836'),
    ]

    operations = [
    ]
