# Generated by Django 2.0.5 on 2019-03-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_review', '0016_merge_20190213_1753'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratingsreview',
            unique_together={('appointment_id', 'appointment_type')},
        ),
    ]
