# Generated by Django 2.0.5 on 2019-03-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_review', '0017_auto_20190308_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingsreview',
            name='appointment_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lab'), (2, 'Opd'), (3, 'Hospital')], null=True),
        ),
    ]
