# Generated by Django 2.0.5 on 2019-04-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salespoint', '0002_salespointtestmapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salespointtestmapping',
            old_name='test',
            new_name='available_lab_test',
        ),
    ]
