# Generated by Django 2.0.5 on 2019-04-05 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salespoint', '0003_auto_20190404_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespointtestmapping',
            name='available_lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sales_point_mappings', to='diagnostic.AvailableLabTest'),
        ),
    ]
