# Generated by Django 2.0.5 on 2019-04-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salespoint', '0004_auto_20190405_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salespointtestmapping',
            old_name='available_lab_test',
            new_name='available_tests',
        ),
    ]
