# Generated by Django 2.0.5 on 2019-07-26 11:32

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0089_auto_20190726_1301'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20180926_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_id', models.PositiveIntegerField(default=1)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Booked')], default=1)),
                ('extra_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('effective_price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('cashback', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(1, 'Payment Accepted'), (0, 'Payment Pending')], default=0)),
                ('price_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('money_pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.MoneyPool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_consultation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_consultation',
            },
        ),
    ]
