# Generated by Django 2.0.5 on 2019-09-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20190729_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconsultation',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Booked'), (2, 'Cancelled')], default=1),
        ),
    ]
