# Generated by Django 2.0.5 on 2019-09-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20190902_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconsultation',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Prepaid')], default=1),
        ),
    ]
