# Generated by Django 2.0.5 on 2019-03-12 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnostic', '0167_merge_20190304_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unlimited_online_consultation', models.BooleanField(default=True)),
                ('priority_queue', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subscription_plan',
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField(verbose_name='Times per year?')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.Lab')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabNetwork')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='subscription_plan.Plan')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabTest')),
            ],
            options={
                'db_table': 'subscription_plan_feature',
            },
        ),
        migrations.CreateModel(
            name='UserPlanMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expire_at', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscribed_user_mapping', to='subscription_plan.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan_mapping', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription_plan_user',
            },
        ),
    ]
