# Generated by Django 2.0.5 on 2019-03-12 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplanmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan_mapping', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
