# Generated by Django 2.0.5 on 2019-03-13 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0002_auto_20190312_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeatureMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Times per year?')),
            ],
        ),
        migrations.RemoveField(
            model_name='planfeature',
            name='count',
        ),
        migrations.RemoveField(
            model_name='planfeature',
            name='plan',
        ),
        migrations.AddField(
            model_name='planfeaturemapping',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_mappings', to='subscription_plan.PlanFeature'),
        ),
        migrations.AddField(
            model_name='planfeaturemapping',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_mappings', to='subscription_plan.Plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.ManyToManyField(related_name='plans_included_in', through='subscription_plan.PlanFeatureMapping', to='subscription_plan.PlanFeature'),
        ),
    ]
