# Generated by Django 2.0.5 on 2019-03-13 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0003_auto_20190313_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeature',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.Lab'),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.LabNetwork'),
        ),
    ]
