# Generated by Django 2.0.5 on 2019-03-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0004_auto_20190313_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplanmapping',
            name='expire_at',
            field=models.DateTimeField(null=True),
        ),
    ]
