# Generated by Django 2.0.5 on 2019-03-15 12:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_auto_20190315_1750'),
        ('subscription_plan', '0008_planfeature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplanmapping',
            name='extra_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplanmapping',
            name='money_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.MoneyPool'),
        ),
    ]
