# Generated by Django 2.0.5 on 2019-04-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0009_auto_20190315_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplanmapping',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Cancelled'), (1, 'Booked')], default=1),
        ),
    ]
