# Generated by Django 2.0.5 on 2019-05-07 07:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0028_auto_20190507_1229'),
        ('subscription_plan', '0010_userplanmapping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplanmapping',
            name='coupon',
            field=models.ManyToManyField(blank=True, null=True, related_name='plan_coupon', to='coupon.Coupon'),
        ),
        migrations.AddField(
            model_name='userplanmapping',
            name='coupon_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
