# Generated by Django 2.0.5 on 2019-06-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0011_auto_20190507_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='plan/images', verbose_name='Icon'),
        ),
    ]
