# Generated by Django 2.0.5 on 2018-10-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flat_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('validity', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[('', 'Select'), (1, 'Doctor'), (2, 'Lab'), (3, 'All')])),
                ('count', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
    ]
