# Generated by Django 2.0.5 on 2018-10-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
