# Generated by Django 2.0.5 on 2018-10-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='tnc',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
