# Generated by Django 2.0.5 on 2018-10-29 06:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0113_auto_20181026_1932'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon', '0003_coupon_tnc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpecificCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'user_specific_coupon',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_user_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.Lab'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='lab_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='diagnostic.LabNetwork'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='diagnostic.LabTest'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='show_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percentage_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='userspecificcoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_specific_coupon', to='coupon.Coupon'),
        ),
        migrations.AddField(
            model_name='userspecificcoupon',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
