# Generated by Django 2.0.5 on 2018-10-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0113_auto_20181026_1932'),
        ('coupon', '0004_auto_20181029_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='test',
        ),
        migrations.AddField(
            model_name='coupon',
            name='test',
            field=models.ManyToManyField(blank=True, null=True, to='diagnostic.LabTest'),
        ),
    ]
