# Generated by Django 2.0.5 on 2018-11-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_auto_20181115_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='heading',
            field=models.CharField(default='', max_length=500),
        ),
    ]
