# Generated by Django 2.0.5 on 2018-11-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_coupon_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_corporate',
            field=models.BooleanField(default=False),
        ),
    ]
