# Generated by Django 2.0.5 on 2018-11-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0009_coupon_total_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='new_user_constraint',
            field=models.BooleanField(default=False),
        ),
    ]
