# Generated by Django 2.0.5 on 2018-11-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0010_coupon_new_user_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
