# Generated by Django 2.0.5 on 2018-11-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0013_auto_20181129_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
