# Generated by Django 2.0.5 on 2018-12-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0014_auto_20181129_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.IntegerField(choices=[(1, 'Discount'), (2, 'Cashback')], default=1),
        ),
    ]
