# Generated by Django 2.0.5 on 2018-12-19 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0016_randomgeneratedcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='step_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Valid only at multiples of this appointment number'),
        ),
    ]
