# Generated by Django 2.0.5 on 2018-12-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0016_randomgeneratedcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
