# Generated by Django 2.0.5 on 2018-12-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0171_merge_20181207_1957'),
        ('procedure', '0019_commonprocedure'),
        ('diagnostic', '0138_merge_20181218_1938'),
        ('coupon', '0017_coupon_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='doctor.PracticeSpecialization'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='procedures',
            field=models.ManyToManyField(blank=True, to='procedure.Procedure'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='procedure_categories',
            field=models.ManyToManyField(blank=True, to='procedure.ProcedureCategory'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='test_categories',
            field=models.ManyToManyField(blank=True, to='diagnostic.LabTestCategory'),
        ),
    ]
