# Generated by Django 2.0.5 on 2018-12-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0138_merge_20181218_1938'),
        ('coupon', '0018_coupon_specializations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='test',
            field=models.ManyToManyField(blank=True, to='diagnostic.LabTest'),
        ),
    ]
