# Generated by Django 2.0.5 on 2019-01-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0015_coupon_coupon_type'),
        ('coupon', '0019_auto_20181228_1122'),
    ]

    operations = [
    ]
