# Generated by Django 2.0.5 on 2019-01-22 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20190116_1840'),
        ('coupon', '0020_merge_20190102_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='payment_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.PaymentOptions'),
        ),
    ]
