# Generated by Django 2.0.5 on 2019-01-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0020_merge_20190102_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspecificcoupon',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
