# Generated by Django 2.0.5 on 2019-01-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0021_userspecificcoupon_count'),
        ('coupon', '0021_coupon_payment_option'),
    ]

    operations = [
    ]
