# Generated by Django 2.0.5 on 2019-01-29 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0022_merge_20190129_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='payment_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.PaymentOptions'),
        ),
    ]
