# Generated by Django 2.0.5 on 2019-04-30 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_booking', '0003_auto_20190429_1257'),
        ('coupon', '0024_auto_20190218_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='corporate_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporate_booking.CorporateDeal'),
        ),
    ]
