# Generated by Django 2.0.5 on 2019-05-01 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0025_coupon_random_coupon_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomgeneratedcoupon',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
