# Generated by Django 2.0.5 on 2019-05-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0026_auto_20190501_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomgeneratedcoupon',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='randomgeneratedcoupon',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='randomgeneratedcoupon',
            name='validity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
