# Generated by Django 2.0.5 on 2019-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0010_userplanmapping_status'),
        ('coupon', '0027_auto_20190501_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='plan',
            field=models.ManyToManyField(blank=True, null=True, to='subscription_plan.Plan'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.IntegerField(choices=[('', 'Select'), (1, 'Doctor'), (2, 'Lab'), (3, 'All'), (4, 'SUBSCRIPTION_PLAN')]),
        ),
    ]
