# Generated by Django 2.0.5 on 2019-05-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0028_auto_20190507_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='total_used_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
