# Generated by Django 2.0.5 on 2019-05-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0028_auto_20190507_1229'),
        ('coupon', '0025_coupon_corporate_deal'),
    ]

    operations = [
    ]
