# Generated by Django 2.0.5 on 2019-05-16 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0029_merge_20190516_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='corporate_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporate_booking.CorporateDeal'),
        ),
    ]
