# Generated by Django 2.0.5 on 2019-05-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0029_merge_20190516_1714'),
        ('coupon', '0030_auto_20190516_1612'),
    ]

    operations = [
    ]
