# Generated by Django 2.0.5 on 2019-05-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0031_merge_20190516_1716'),
        ('coupon', '0029_coupon_total_used_count'),
    ]

    operations = [
    ]
