# Generated by Django 2.0.5 on 2019-07-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0284_merge_20190726_1626'),
        ('coupon', '0033_auto_20190619_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='doctors_exclude',
            field=models.ManyToManyField(blank=True, related_name='doctors_exclude', to='doctor.Doctor'),
        ),
    ]
