# Generated by Django 2.0.5 on 2019-07-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0284_merge_20190726_1626'),
        ('coupon', '0034_coupon_doctors_exclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='hospitals_exclude',
            field=models.ManyToManyField(blank=True, related_name='hospitals_exclude', to='doctor.Hospital'),
        ),
    ]
