# Generated by Django 2.0.5 on 2019-08-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0035_coupon_hospitals_exclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_lensfit',
            field=models.BooleanField(default=False),
        ),
    ]
