# Generated by Django 2.0.5 on 2019-09-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0035_coupon_hospitals_exclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_lensfit',
            field=models.NullBooleanField(),
        ),
    ]
