# Generated by Django 2.0.5 on 2019-11-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0041_auto_20191111_1152'),
        ('coupon', '0038_coupon_is_lensfit'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_for_gold_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_for_vip_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='users_vip_gold_plans',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_vip_gold_plans', to='plus.PlusPlans'),
        ),
    ]
