# Generated by Django 2.0.5 on 2019-11-21 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0039_auto_20191120_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspecificcoupon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_specific_coupon', to=settings.AUTH_USER_MODEL),
        ),
    ]
