# Generated by Django 2.0.5 on 2019-11-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0041_auto_20191111_1152'),
        ('coupon', '0041_auto_20191121_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='vip_gold_plans',
            field=models.ManyToManyField(blank=True, null=True, related_name='vip_gold_plans', to='plus.PlusPlans'),
        ),
    ]
