# Generated by Django 2.0.5 on 2019-12-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0042_coupon_vip_gold_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='tnc',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
