# Generated by Django 2.0.5 on 2019-03-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DP_CityMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('CityId', models.IntegerField(null=True)),
                ('CityName', models.CharField(blank=True, max_length=500, null=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'managed': False,
                'db_table': 'DP_CityMaster',
            },
        ),
        migrations.CreateModel(
            name='DP_InsurerMaster',
            fields=[
                ('InsurerMasterId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('InsurerId', models.IntegerField(blank=True, null=True)),
                ('InsurerName', models.CharField(blank=True, max_length=500, null=True)),
                ('IsActive', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': False,
                'db_table': 'DP_InsurerMaster',
            },
        ),
        migrations.CreateModel(
            name='DP_OpdConsultsAndTests',
            fields=[
                ('OpdConsultsAndTestsId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Appointment_Id', models.BigIntegerField(blank=True, null=True)),
                ('StatusId', models.IntegerField(blank=True, null=True)),
                ('TypeId', models.IntegerField(blank=True, null=True)),
                ('GMValue', models.IntegerField(blank=True, null=True)),
                ('PromoCost', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('SpecialityId', models.IntegerField(blank=True, null=True)),
                ('Category', models.IntegerField(blank=True, null=True)),
                ('ProviderId', models.IntegerField(blank=True, null=True)),
                ('CityId', models.IntegerField(blank=True, null=True)),
                ('StateId', models.IntegerField(blank=True, null=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'managed': False,
                'db_table': 'DP_OpdConsultsAndTests',
            },
        ),
        migrations.CreateModel(
            name='DP_OPDStatusMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPDStatusId', models.IntegerField(null=True)),
                ('OPDStatus', models.CharField(blank=True, max_length=500, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': False,
                'db_table': 'DP_OPDStatusMaster',
            },
        ),
        migrations.CreateModel(
            name='DP_SpecialityMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecialityId', models.IntegerField(null=True)),
                ('Speciality', models.CharField(blank=True, max_length=500, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': False,
                'db_table': 'DP_SpecialityMaster',
            },
        ),
        migrations.CreateModel(
            name='DP_StateMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateId', models.IntegerField(null=True)),
                ('StateName', models.CharField(blank=True, max_length=500, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': False,
                'db_table': 'DP_StateMaster',
            },
        ),
        migrations.CreateModel(
            name='DP_TeleDStatusMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeleStatusId', models.BigIntegerField(null=True)),
                ('TeleStatus', models.CharField(blank=True, max_length=500, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': False,
                'db_table': 'DP_TeleDStatusMaster',
            },
        ),
        migrations.CreateModel(
            name='DP_UnderWritingDetails',
            fields=[
                ('UnderWritingId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('CaseId', models.IntegerField(blank=True, null=True)),
                ('InsurerId', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField()),
                ('StatusId', models.IntegerField(blank=True, null=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'managed': False,
                'db_table': 'DP_UnderWritingDetails',
            },
        ),
        migrations.CreateModel(
            name='TeleDeal',
            fields=[
                ('TeleDealId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('InsurerId', models.IntegerField(blank=True, null=True)),
                ('Fees', models.IntegerField(blank=True, null=True)),
                ('Tax', models.IntegerField(blank=True, null=True)),
                ('DealStartDate', models.DateTimeField()),
                ('DealEndDate', models.DateTimeField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'managed': False,
                'db_table': 'TeleDeal',
            },
        ),
    ]
