# Generated by Django 2.0.5 on 2019-05-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinganalytics', '0003_auto_20190419_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='DP_CorporateDeals',
            fields=[
                ('CorporateDealId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('CorporateName', models.CharField(blank=True, max_length=5000, null=True)),
                ('DealStartDate', models.DateTimeField()),
                ('DealEndDate', models.DateTimeField()),
                ('GrossAmount', models.IntegerField(blank=True, null=True)),
                ('ExpectedProviderFee', models.IntegerField(blank=True, null=True)),
                ('NumberOfEmployees', models.IntegerField(blank=True, null=True)),
                ('PaymentDate', models.DateTimeField()),
                ('TDSDeducted', models.CharField(blank=True, max_length=5000, null=True)),
                ('ReceiptNumber', models.CharField(blank=True, max_length=5000, null=True)),
                ('IsActive', models.BooleanField(default=False)),
                ('CreatedDate', models.DateTimeField()),
                ('UpdatedDate', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'DP_CorporateDeals',
            },
        ),
    ]
