# Generated by Django 2.0.2 on 2018-07-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180712_2006'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
        migrations.AlterModelTable(
            name='articleimage',
            table='article_image',
        ),
    ]
