# Generated by Django 2.0.5 on 2018-07-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20180713_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='icon',
            field=models.ImageField(height_field='height', null=True, upload_to='articles/icons', width_field='width'),
        ),
    ]
