# Generated by Django 2.0.5 on 2018-07-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='icon',
            field=models.ImageField(null=True, upload_to='articles/icons'),
        ),
    ]
