# Generated by Django 2.0.2 on 2018-07-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20180713_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='articles.ArticleCategory'),
        ),
    ]
