# Generated by Django 2.0.5 on 2018-08-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20180821_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header_image',
            field=models.ImageField(null=True, upload_to='articles/header/images'),
        ),
    ]
