# Generated by Django 2.0.5 on 2018-08-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20180831_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='name',
            field=models.ImageField(upload_to='article/images'),
        ),
    ]
