# Generated by Django 2.0.5 on 2018-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20180831_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header_image_alt',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
