# Generated by Django 2.0.5 on 2018-09-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20180906_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='icon',
            field=models.ImageField(blank=True, default='', null=True, upload_to='articles/icons'),
        ),
    ]
