# Generated by Django 2.0.5 on 2018-09-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20180913_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLinkedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
            options={
                'db_table': 'article_linked_urls',
            },
        ),
        migrations.CreateModel(
            name='LinkedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_article', to='articles.Article')),
                ('linked_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_articles', to='articles.Article')),
            ],
            options={
                'db_table': 'linked_articles',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='linked_articles',
            field=models.ManyToManyField(through='articles.LinkedArticle', to='articles.Article'),
        ),
        migrations.AlterUniqueTogether(
            name='linkedarticle',
            unique_together={('article', 'linked_article')},
        ),
    ]
