# Generated by Django 2.0.5 on 2018-09-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_auto_20180920_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelinkedurl',
            name='url',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
