# Generated by Django 2.0.5 on 2018-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20180920_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
