# Generated by Django 2.0.5 on 2018-09-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20180920_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedarticle',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
