# Generated by Django 2.0.5 on 2018-09-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_linkedarticle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_articles', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='linkedarticle',
            name='linked_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_article', to='articles.Article'),
        ),
    ]
