# Generated by Django 2.0.5 on 2018-09-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20180925_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedarticle',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
