# Generated by Django 2.0.5 on 2018-09-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_auto_20180925_1759'),
        ('articles', '0024_auto_20180924_1541'),
    ]

    operations = [
    ]
