# Generated by Django 2.0.5 on 2018-11-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_merge_20180925_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContentBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=1000)),
                ('rank', models.PositiveSmallIntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'article_content_box',
            },
        ),
        migrations.AddField(
            model_name='articlelinkedurl',
            name='content_box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.ArticleContentBox'),
        ),
        migrations.AddField(
            model_name='linkedarticle',
            name='content_box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.ArticleContentBox'),
        ),
    ]
