# Generated by Django 2.0.5 on 2018-11-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_auto_20181113_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontentbox',
            name='name',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
