# Generated by Django 2.0.5 on 2018-12-10 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0171_merge_20181207_1957'),
        ('articles', '0031_articlecontentbox_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_articles', to='doctor.Doctor'),
        ),
    ]
