# Generated by Django 2.0.5 on 2019-08-05 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0284_merge_20190726_1626'),
        ('articles', '0034_auto_20190109_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.PracticeSpecialization')),
            ],
            options={
                'db_table': 'medicine_specialization',
            },
        ),
    ]
