# Generated by Django 2.0.5 on 2019-08-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0035_medicinespecialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_visit',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='article',
            name='pharmeasy_product_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pharmeasy_url',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
    ]
