# Generated by Django 2.0.5 on 2019-09-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0036_auto_20190826_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_visit',
            new_name='is_widget_available',
        ),
    ]
