# Generated by Django 2.0.5 on 2019-09-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0037_auto_20190903_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pharmeasy_url',
            field=models.TextField(null=True),
        ),
    ]
