# Generated by Django 2.0.6 on 2018-06-26 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0035_auto_20180615_1906'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.PositiveSmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID')])),
                ('name', models.CharField(max_length=100)),
                ('insurance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insured_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_profile', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PgInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID')])),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('order_id', models.PositiveIntegerField()),
                ('type', models.SmallIntegerField(choices=[(0, 'Credit'), (1, 'Debit')])),
                ('payment_mode', models.CharField(max_length=50)),
                ('response_code', models.IntegerField()),
                ('bank_id', models.CharField(max_length=50)),
                ('transaction_date', models.CharField(max_length=80)),
                ('bank_name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=15)),
                ('status_code', models.IntegerField()),
                ('pg_name', models.CharField(max_length=100)),
                ('status_type', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('pb_gateway_name', models.CharField(max_length=100)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.Insurance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.PositiveSmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID')])),
                ('insured_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.Insurance')),
                ('profile', models.ManyToManyField(to='authentication.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.PositiveSmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID')])),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.Insurance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Insurer'),
        ),
    ]
