# Generated by Django 2.0.6 on 2018-06-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20180626_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insured_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profileinsurance',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profileinsurance',
            name='insured_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
