# Generated by Django 2.0.6 on 2018-06-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20180626_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
