# Generated by Django 2.0.6 on 2018-06-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_auto_20180626_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuranceTransaction',
        ),
        migrations.AlterModelTable(
            name='insurance',
            table='insurance',
        ),
        migrations.AlterModelTable(
            name='insurer',
            table='insurer',
        ),
        migrations.AlterModelTable(
            name='pginsurance',
            table='pg_insurance',
        ),
        migrations.AlterModelTable(
            name='profileinsurance',
            table='profile_insurance',
        ),
        migrations.AlterModelTable(
            name='userinsurance',
            table='user_insurance',
        ),
    ]
