# Generated by Django 2.0.5 on 2018-07-27 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_auto_20180627_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='insurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.Insurer'),
        ),
    ]
