# Generated by Django 2.0.5 on 2018-10-04 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_auto_20180727_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Insurer')),
            ],
            options={
                'db_table': 'insurance_plans',
            },
        ),
        migrations.CreateModel(
            name='InsuranceThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.InsurancePlans')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Insurer')),
            ],
            options={
                'db_table': 'insurance_threshold',
            },
        ),
        migrations.CreateModel(
            name='InsuredMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateTimeField()),
                ('email', models.EmailField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.InsurancePlans')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Insurer')),
            ],
            options={
                'db_table': 'insured_members',
            },
        ),
        migrations.CreateModel(
            name='InsurerFloat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Insurer')),
            ],
            options={
                'db_table': 'insurer_float',
            },
        ),
    ]
