# Generated by Django 2.0.5 on 2019-03-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_auto_20180727_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='product_id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'SUBSCRIPTION_PLAN_PRODUCT_ID')]),
        ),
        # migrations.AlterField(
        #     model_name='pginsurance',
        #     name='product_id',
        #     field=models.SmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'SUBSCRIPTION_PLAN_PRODUCT_ID')]),
        # ),
        # migrations.AlterField(
        #     model_name='profileinsurance',
        #     name='product_id',
        #     field=models.PositiveSmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'SUBSCRIPTION_PLAN_PRODUCT_ID')]),
        # ),
        migrations.AlterField(
            model_name='userinsurance',
            name='product_id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'SUBSCRIPTION_PLAN_PRODUCT_ID')]),
        ),
    ]
