# Generated by Django 2.0.5 on 2018-10-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_insuranceplans_insurancethreshold_insuredmembers_insurerfloat'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceplans',
            name='amount',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='insurancethreshold',
            name='lab_amount_limit',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='insurancethreshold',
            name='lab_count_limit',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='insurancethreshold',
            name='max_age',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='insurancethreshold',
            name='min_age',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='insurancethreshold',
            name='opd_amount_limit',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='insurancethreshold',
            name='opd_count_limit',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='insurancethreshold',
            name='tenure',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='insuredmembers',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='insuredmembers',
            name='pincode',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='insurerfloat',
            name='current_float',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='insurerfloat',
            name='max_float',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
