# Generated by Django 2.0.5 on 2018-10-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_auto_20181004_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceplans',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insuranceplans',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insurancethreshold',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insurancethreshold',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insurer',
            name='is_disabeld',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insurer',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
