# Generated by Django 2.0.5 on 2018-10-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_auto_20181005_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancethreshold',
            old_name='insurance_variant',
            new_name='insurance_plan',
        ),
    ]
