# Generated by Django 2.0.5 on 2018-10-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0058_auto_20180829_1443'),
        ('insurance', '0011_auto_20181005_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredmembers',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.UserProfile'),
        ),
    ]
