# Generated by Django 2.0.5 on 2018-10-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_auto_20181012_1729'),
    ]

    operations = [

        migrations.AlterField(
            model_name='insuredmembers',
            name='relation',
            field=models.CharField(choices=[('husband', 'Husband'), ('wife', 'Wife'), ('son', 'Son'), ('daughter', 'Daughter'), ('self', 'Self')], max_length=50),
        ),
    ]
