# Generated by Django 2.0.5 on 2018-10-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0015_auto_20181015_1235'),
        ('insurance', '0014_auto_20181015_1503'),
    ]

    operations = [
    ]
