# Generated by Django 2.0.5 on 2018-10-17 05:53

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0016_merge_20181016_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='bank_id',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='pb_gateway_name',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='pg_name',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='response_code',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='type',
        ),
        migrations.AddField(
            model_name='insurancetransaction',
            name='insured_members',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
