# Generated by Django 2.0.5 on 2018-10-16 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0016_merge_20181016_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredmembers',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insuredmembers',
            name='heart_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insuredmembers',
            name='hypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insuredmembers',
            name='liver_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
