# Generated by Django 2.0.5 on 2018-10-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0017_auto_20181016_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredmembers',
            name='diabetes',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='heart_disease',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='hypertension',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='liver_disease',
            field=models.BooleanField(default=None),
        ),
    ]
