# Generated by Django 2.0.5 on 2018-10-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0018_auto_20181016_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuredmembers',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='insuredmembers',
            name='heart_disease',
        ),
        migrations.RemoveField(
            model_name='insuredmembers',
            name='liver_disease',
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='hypertension',
            field=models.NullBooleanField(),
        ),
    ]
