# Generated by Django 2.0.5 on 2018-10-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0019_auto_20181016_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredmembers',
            name='diabetes',
            field=models.NullBooleanField(),
        ),
    ]
