# Generated by Django 2.0.5 on 2018-10-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0021_auto_20181016_1537'),
        ('insurance', '0018_auto_20181017_1335'),
    ]

    operations = [
    ]
