# Generated by Django 2.0.5 on 2018-10-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0022_merge_20181017_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancetransaction',
            old_name='order_id',
            new_name='order',
        ),
    ]
