# Generated by Django 2.0.5 on 2018-10-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0022_merge_20181017_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancetransaction',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='insurancetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
