# Generated by Django 2.0.5 on 2018-10-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0023_auto_20181022_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurerfloat',
            name='current_float',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='insurerfloat',
            name='max_float',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
