# Generated by Django 2.0.5 on 2018-10-23 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20181012_1729'),
        ('insurance', '0025_auto_20181022_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancetransaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Order'),
        ),
        migrations.AddField(
            model_name='insurancetransaction',
            name='policy_number',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insuredmembers',
            name='insurance_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.InsurancePlans'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.Insurer'),
        ),
    ]
