# Generated by Django 2.0.5 on 2018-10-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0026_auto_20181023_1134'),
        ('insurance', '0016_merge_20181017_1606'),
    ]

    operations = [
    ]
