# Generated by Django 2.0.5 on 2018-11-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0028_auto_20181113_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancethreshold',
            name='tenure',
        ),
        migrations.AddField(
            model_name='insurancetransaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinsurance',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinsurance',
            name='policy_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinsurance',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
