# Generated by Django 2.0.5 on 2018-11-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0029_auto_20181114_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceplans',
            name='policy_tenure',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
