# Generated by Django 2.0.5 on 2018-11-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0030_insuranceplans_policy_tenure'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.CharField(blank=True, max_length=100, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'insurance_disease',
            },
        ),
        migrations.RemoveField(
            model_name='insuredmembers',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='insuredmembers',
            name='heart_disease',
        ),
        migrations.RemoveField(
            model_name='insuredmembers',
            name='hypertension',
        ),
        migrations.RemoveField(
            model_name='insuredmembers',
            name='liver_disease',
        ),
        migrations.AddField(
            model_name='insuranceplans',
            name='adult_count',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='insuranceplans',
            name='child_count',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='insuredmembers',
            name='district',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuredmembers',
            name='middle_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuredmembers',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuredmembers',
            name='title',
            field=models.CharField(blank=True, choices=[('mr.', 'mr.'), ('mrs.', 'mrs.'), ('miss', 'miss')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='insuredmembers',
            name='town',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuredmembers',
            name='user_insurance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.UserInsurance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinsurance',
            name='premium_amount',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
