# Generated by Django 2.0.5 on 2018-11-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0031_auto_20181122_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancetransaction',
            name='status_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Initiate'), (2, 'Created'), (3, 'Processed'), (4, 'Completed'), (5, 'Failed')], default=1),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='relation',
            field=models.CharField(choices=[('husband', 'Husband'), ('wife', 'Wife'), ('son', 'Son'), ('daughter', 'Daughter'), ('self', 'Self')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='title',
            field=models.CharField(choices=[('mr.', 'mr.'), ('mrs.', 'mrs.'), ('miss', 'miss')], default=None, max_length=20),
        ),
    ]
