# Generated by Django 2.0.5 on 2018-11-23 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_merge_20181115_1407'),
        ('insurance', '0033_auto_20181123_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceDiseaseReponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'insurance_disease_response',
            },
        ),
        migrations.CreateModel(
            name='InsurancePlanContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsurerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_float', models.PositiveIntegerField(default=None)),
            ],
            options={
                'db_table': 'insurer_account',
            },
        ),
        migrations.RemoveField(
            model_name='insurerfloat',
            name='insurer',
        ),
        migrations.RenameField(
            model_name='insuranceplans',
            old_name='type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='insurancedisease',
            name='is_disabled',
        ),
        migrations.RemoveField(
            model_name='insuranceplans',
            name='is_disabled',
        ),
        migrations.RemoveField(
            model_name='insurancethreshold',
            name='insurer',
        ),
        migrations.RemoveField(
            model_name='insurancethreshold',
            name='is_disabled',
        ),
        migrations.RemoveField(
            model_name='insuredmembers',
            name='insurance_plan',
        ),
        migrations.RemoveField(
            model_name='insuredmembers',
            name='insurer',
        ),
        migrations.RemoveField(
            model_name='insurer',
            name='is_disabled',
        ),
        migrations.RemoveField(
            model_name='insurer',
            name='max_float',
        ),
        migrations.RemoveField(
            model_name='userinsurance',
            name='insurance_transaction',
        ),
        migrations.RemoveField(
            model_name='userinsurance',
            name='insurer',
        ),
        migrations.AddField(
            model_name='insurancedisease',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insuranceplans',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insurancethreshold',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insurancetransaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CREDIT'), (2, 'DEBIT')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancetransaction',
            name='user_insurance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='insurance.UserInsurance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurer',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='insurer/images', verbose_name='Insurer Logo'),
        ),
        migrations.AddField(
            model_name='userinsurance',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Order'),
        ),
        migrations.AlterField(
            model_name='insuranceplans',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='insurance.Insurer'),
        ),
        migrations.AlterField(
            model_name='insurancethreshold',
            name='insurance_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='insurance.InsurancePlans'),
        ),
        migrations.AlterField(
            model_name='insurancetransaction',
            name='amount',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance', to='authentication.UserProfile'),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='user_insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='insurance.UserInsurance'),
        ),
        migrations.AlterField(
            model_name='userinsurance',
            name='insurance_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_users', to='insurance.InsurancePlans'),
        ),
        migrations.AlterField(
            model_name='userinsurance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchased_insurance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='InsurerFloat',
        ),
        migrations.AddField(
            model_name='insureraccount',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float', to='insurance.Insurer'),
        ),
        migrations.AddField(
            model_name='insuranceplancontent',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='insurance.InsurancePlans'),
        ),
        migrations.AddField(
            model_name='insurancediseasereponse',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_members', to='insurance.InsuranceDisease'),
        ),
        migrations.AddField(
            model_name='insurancediseasereponse',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diseases', to='insurance.InsuredMembers'),
        ),
        migrations.AddField(
            model_name='insurancetransaction',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='insurance.InsurerAccount'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='insurance_plan',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='insured_members',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='insurer',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='policy_number',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='status_type',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='insurancetransaction',
            unique_together={('user_insurance', 'account', 'transaction_type')},
        ),
    ]
