# Generated by Django 2.0.5 on 2018-11-26 13:15

from django.db import migrations, models
import ondoc.insurance.models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0034_auto_20181123_1914'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='userinsurance',
        #     name='policy_number',
        #     field=models.CharField(blank=True, default=ondoc.insurance.models.generate_insurance_policy_number, max_length=50, null=True),
        # ),
    ]
