# Generated by Django 2.0.5 on 2018-11-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0035_auto_20181126_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsuranceDiseaseReponse',
            new_name='InsuranceDiseaseResponse',
        ),
    ]
