# Generated by Django 2.0.5 on 2018-11-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0035_auto_20181126_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceplancontent',
            name='content',
            field=models.TextField(),
        ),
    ]
