# Generated by Django 2.0.5 on 2018-11-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0036_auto_20181126_1914'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='insuranceplancontent',
            unique_together={('plan', 'title')},
        ),
        migrations.AlterModelTable(
            name='insuranceplancontent',
            table='insurance_plan_content',
        ),
    ]
