# Generated by Django 2.0.5 on 2018-11-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0037_auto_20181126_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceplancontent',
            name='title',
            field=models.CharField(choices=[('WHATS_COVERED', 'WHATS_COVERED'), ('WHATS_NOT_COVERED', 'WHATS_NOT_COVERED')], max_length=500),
        ),
    ]
