# Generated by Django 2.0.5 on 2018-11-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0036_auto_20181127_1658'),
        ('insurance', '0038_auto_20181126_2012'),
    ]

    operations = [
    ]
