# Generated by Django 2.0.5 on 2018-11-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0039_merge_20181127_2021'),
        ('insurance', '0039_merge_20181128_1112'),
    ]

    operations = [
    ]
