# Generated by Django 2.0.5 on 2018-11-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0039_merge_20181127_1706'),
        ('insurance', '0040_merge_20181128_1244'),
    ]

    operations = [
    ]
