# Generated by Django 2.0.5 on 2018-11-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0040_merge_20181128_1704'),
        ('insurance', '0041_merge_20181128_1247'),
    ]

    operations = [
    ]
