# Generated by Django 2.0.5 on 2018-11-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0042_merge_20181128_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredmembers',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
