# Generated by Django 2.0.5 on 2018-11-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0043_auto_20181129_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredmembers',
            name='relation',
            field=models.CharField(choices=[('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('self', 'Self')], default=None, max_length=50),
        ),
    ]
