# Generated by Django 2.0.5 on 2018-11-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0043_auto_20181129_1550'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='insuranceplancontent',
            unique_together=set(),
        ),
    ]
