# Generated by Django 2.0.5 on 2018-11-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0044_auto_20181129_1841'),
        ('insurance', '0044_auto_20181129_1651'),
    ]

    operations = [
    ]
