# Generated by Django 2.0.5 on 2018-11-29 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0044_auto_20181129_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinsurance',
            name='coi',
            field=models.FileField(default=None, null=True, upload_to='insurance/coi', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
