# Generated by Django 2.0.5 on 2018-11-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0045_merge_20181129_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredmembers',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
