# Generated by Django 2.0.5 on 2018-11-30 09:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import ondoc.insurance.models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0046_auto_20181129_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedisease',
            name='disease',
            field=models.CharField(default='Liver Disease', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insurancedisease',
            name='enabled',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='insurancedisease',
            name='is_live',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='insuranceplans',
            name='adult_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insuranceplans',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insuranceplans',
            name='child_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insuranceplans',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insuranceplans',
            name='policy_tenure',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='insurancethreshold',
            name='child_min_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insurancethreshold',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insurancethreshold',
            name='lab_amount_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insurancethreshold',
            name='lab_count_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insurancethreshold',
            name='max_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insurancethreshold',
            name='min_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insurancethreshold',
            name='opd_amount_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insurancethreshold',
            name='opd_count_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insurancetransaction',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='user_insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='insurance.UserInsurance'),
        ),
        migrations.AlterField(
            model_name='userinsurance',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userinsurance',
            name='insurance_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_users', to='insurance.InsurancePlans'),
        ),
        migrations.AlterField(
            model_name='userinsurance',
            name='insured_members',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='userinsurance',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Order'),
        ),
        # migrations.AlterField(
        #     model_name='userinsurance',
        #     name='policy_number',
        #     field=models.CharField(default=ondoc.insurance.models.generate_insurance_policy_number, max_length=50),
        # ),
        migrations.AlterField(
            model_name='userinsurance',
            name='premium_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinsurance',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
