# Generated by Django 2.0.5 on 2018-11-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0045_userinsurance_coi'),
        ('insurance', '0047_auto_20181130_1506'),
    ]

    operations = [
    ]
