# Generated by Django 2.0.5 on 2018-11-30 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import ondoc.insurance.models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0048_merge_20181130_1722'),
    ]

    operations = [
        # migrations.RunSQL(
        #     '''CREATE SEQUENCE IF NOT EXISTS userinsurance_policy_num_seq START 1;'''
        # ),
        # migrations.AlterField(
        #     model_name='userinsurance',
        #     name='policy_number',
        #     field=models.CharField(default=ondoc.insurance.models.generate_insurance_policy_number, max_length=50, unique=True),
        # )
    ]
