# Generated by Django 2.0.5 on 2018-11-30 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0049_auto_20181130_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinsurance',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
