# Generated by Django 2.0.5 on 2018-12-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0050_auto_20181130_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceplans',
            name='total_allowed_members',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
