# Generated by Django 2.0.5 on 2018-12-04 10:31

from django.db import migrations, models
import ondoc.insurance.models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0051_insuranceplans_total_allowed_members'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='userinsurance',
        #     name='policy_number',
        #     field=models.CharField(default=ondoc.insurance.models.generate_insurance_policy_number, max_length=100, unique=True),
        # ),
    ]
