# Generated by Django 2.0.5 on 2018-12-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0052_auto_20181204_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='address',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='company_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='gstin_number',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='intermediary_code',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='intermediary_contact_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='intermediary_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='signature',
            field=models.ImageField(null=True, upload_to='insurer/images', verbose_name='Insurer Signature'),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='logo',
            field=models.ImageField(null=True, upload_to='insurer/images', verbose_name='Insurer Logo'),
        ),
    ]
