# Generated by Django 2.0.5 on 2018-12-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0053_auto_20181206_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
