# Generated by Django 2.0.5 on 2018-12-07 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0054_auto_20181206_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='insurer_document',
            field=models.FileField(null=True, upload_to='insurer/documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
