# Generated by Django 2.0.5 on 2018-12-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0055_insurer_insurer_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceplancontent',
            name='title',
            field=models.CharField(choices=[('SALIENT_FEATURES', 'SALIENT_FEATURES'), ('WHATS_NOT_COVERED', 'WHATS_NOT_COVERED')], max_length=500),
        ),
    ]
