# Generated by Django 2.0.5 on 2018-12-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0056_auto_20181217_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='cgst',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='igst',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='insurer',
            name='sgst',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
