# Generated by Django 2.0.5 on 2018-12-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0057_auto_20181218_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancethreshold',
            name='child_max_age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
