# Generated by Django 2.0.5 on 2019-01-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0059_stategstcode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stategstcode',
            table='state_gst_code',
        ),
    ]
