# Generated by Django 2.0.5 on 2019-01-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0060_auto_20190102_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredmembers',
            name='state_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userinsurance',
            name='receipt_number',
            field=models.BigIntegerField(default=0),
        ),
        # migrations.RunSQL(
        #     '''CREATE SEQUENCE IF NOT EXISTS userinsurance_policy_reciept_seq START 1;'''
        # ),
    ]
