# Generated by Django 2.0.5 on 2019-01-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0062_auto_20190107_1926'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stategstcode',
            table='insurance_state',
        ),
    ]
