# Generated by Django 2.0.5 on 2019-01-16 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0063_auto_20190116_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_code', models.CharField(max_length=10)),
                ('city_name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_live', models.BooleanField(default=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_cities', to='insurance.StateGSTCode')),
            ],
            options={
                'db_table': 'insurance_city',
            },
        ),
        migrations.CreateModel(
            name='InsuranceDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district_code', models.CharField(max_length=10)),
                ('district_name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_live', models.BooleanField(default=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_districts', to='insurance.StateGSTCode')),
            ],
            options={
                'db_table': 'insurance_district',
            },
        ),
    ]
