# Generated by Django 2.0.5 on 2019-02-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0064_insurancecity_insurancedistrict'),
    ]

    operations = [

        migrations.RunSQL(
            '''CREATE SEQUENCE IF NOT EXISTS userinsurance_policy_num_seq START 1;'''
        ),
        migrations.RunSQL(
            '''CREATE SEQUENCE IF NOT EXISTS userinsurance_policy_reciept_seq START 1;'''
        ),
    ]
