# Generated by Django 2.0.5 on 2019-03-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0066_fields_alteration'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceplans',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
