# Generated by Django 2.0.5 on 2019-03-13 10:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_merge_20190313_1047'),
        ('insurance', '0066_fields_alteration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinsurance',
            name='money_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.MoneyPool'),
        ),
        migrations.AddField(
            model_name='userinsurance',
            name='price_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
