# Generated by Django 2.0.5 on 2019-03-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0067_insuranceplans_is_selected'),
        ('insurance', '0067_auto_20190313_1624'),
    ]

    operations = [
    ]
