# Generated by Django 2.0.5 on 2019-03-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0067_insuranceplans_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.StateGSTCode'),
        ),
    ]
