# Generated by Django 2.0.5 on 2019-03-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0068_insurer_state'),
        ('insurance', '0068_merge_20190313_1834'),
    ]

    operations = [
    ]
