# Generated by Django 2.0.5 on 2019-03-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0069_merge_20190313_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinsurance',
            name='matrix_lead_id',
            field=models.IntegerField(null=True),
        ),
    ]
