# Generated by Django 2.0.5 on 2019-03-15 13:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0071_insurancebannerlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancebannerlead',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
