# Generated by Django 2.0.5 on 2019-03-26 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0073_auto_20190315_1932'),
        ('insurance', '0009_auto_20190318_1424'),
    ]

    operations = [
    ]
