# Generated by Django 2.0.5 on 2019-03-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0074_merge_20190326_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='product_id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID')]),
        ),
    ]
