# Generated by Django 2.0.5 on 2019-03-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0075_auto_20190326_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='insurer_merchant_code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
