# Generated by Django 2.0.5 on 2019-04-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0077_insurancedeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinsurance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
