# Generated by Django 2.0.5 on 2019-04-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0079_auto_20190404_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancetransaction',
            name='user_insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='insurance.UserInsurance', to_field='id2'),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='user_insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='insurance.UserInsurance', to_field='id2'),
        ),
        migrations.AlterField(
            model_name='userinsurance',
            name='id2',
            field=models.BigIntegerField(unique=True),
        ),
    ]
