# Generated by Django 2.0.5 on 2019-04-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0080_auto_20190404_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancetransaction',
            name='user_insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='insurance.UserInsurance'),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='user_insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='insurance.UserInsurance'),
        ),
        migrations.RemoveField(
            model_name='userinsurance',
            name='id2',
        ),

    ]
