# Generated by Django 2.0.5 on 2019-04-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0081_auto_20190404_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='master_policy_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinsurance',
            name='policy_number',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
