# Generated by Django 2.0.5 on 2019-04-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0082_auto_20190409_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='master_policy_number',
            field=models.CharField(max_length=50),
        ),
    ]
