# Generated by Django 2.0.5 on 2019-04-10 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0083_auto_20190409_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurerPolicyNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurer_policy_number', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'insurer_policy_numbers',
            },
        ),
        migrations.AddField(
            model_name='insurerpolicynumber',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_number_history', to='insurance.Insurer'),
        ),
    ]
