# Generated by Django 2.0.5 on 2019-04-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0084_auto_20190410_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='master_policy_number',
            field=models.CharField(blank=False, max_length=50, null=True),
        ),
    ]
