# Generated by Django 2.0.5 on 2019-04-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0085_insurer_master_policy_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurerpolicynumber',
            name='start_date',
        ),
    ]
