# Generated by Django 2.0.5 on 2019-04-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0086_remove_insurerpolicynumber_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredmembers',
            name='title',
            field=models.CharField(choices=[('mr.', 'mr.'), ('mrs.', 'mrs.'), ('miss', 'miss'), ('mast.', 'mast.')], default=None, max_length=20),
        ),
    ]
