# Generated by Django 2.0.5 on 2019-04-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0090_auto_20190411_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='user_insurance',
        ),
    ]
