# Generated by Django 2.0.5 on 2019-04-11 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0091_remove_insurancetransaction_user_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancetransaction',
            name='user_insurance2',
        ),
        migrations.AddField(
            model_name='insurancetransaction',
            name='user_insurance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='insurance.UserInsurance'),
        ),
    ]
