# Generated by Django 2.0.5 on 2019-04-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0092_auto_20190411_1223'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='insurancetransaction',
            unique_together={('user_insurance', 'account', 'transaction_type')},
        ),
    ]
