# Generated by Django 2.0.5 on 2019-04-15 07:11

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0093_auto_20190411_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance_dummy_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_insurance_dummy_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurance_dummy_data',
            },
        ),
    ]
