# Generated by Django 2.0.5 on 2019-04-15 07:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0094_insurance_dummy_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insurance_dummy_data',
            new_name='InsuranceDummyData',
        ),
    ]
