# Generated by Django 2.0.5 on 2019-04-25 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0091_auto_20190422_1159'),
        ('insurance', '0095_auto_20190415_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='transfer_premium_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurer', to='authentication.Merchant'),
        ),
    ]
