# Generated by Django 2.0.5 on 2019-04-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0098_auto_20190425_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancetransaction',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Insurance purchase'), (2, 'Premium payout')], null=True),
        ),
    ]
