# Generated by Django 2.0.5 on 2019-04-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0099_insurancetransaction_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinsurance',
            name='onhold_reason',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userinsurance',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Cancelled'), (3, 'Expired'), (4, 'Onhold')], default=1),
        ),
    ]
