# Generated by Django 2.0.5 on 2019-04-30 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0100_auto_20190429_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCancelMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_days', models.PositiveIntegerField(default=0)),
                ('max_days', models.PositiveIntegerField(default=0)),
                ('refund_percentage', models.PositiveIntegerField(default=0)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurance_cancel_master', to='insurance.Insurer')),
            ],
            options={
                'db_table': 'insurance_cancel_master',
            },
        ),
    ]
