# Generated by Django 2.0.5 on 2019-04-30 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0100_auto_20190429_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceMIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_type', models.CharField(choices=[('USER_INSURANCE_DOCTOR_RESOURCE', 'USER_INSURANCE_DOCTOR_RESOURCE'), ('USER_INSURANCE_LAB_RESOURCE', 'USER_INSURANCE_LAB_RESOURCE'), ('USER_INSURANCE_RESOURCE', 'USER_INSURANCE_RESOURCE')], max_length=100)),
                ('attachment_file', models.FileField(default=None, null=True, upload_to='insurance/mis', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xls', 'xlsx'])])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
