# Generated by Django 2.0.5 on 2019-04-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0101_insurancemis'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='insurancemis',
            table='insurance_mis',
        ),
    ]
