# Generated by Django 2.0.5 on 2019-04-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0102_auto_20190430_1339'),
        ('insurance', '0101_insurancecancelmaster'),
    ]

    operations = [
    ]
