# Generated by Django 2.0.5 on 2019-05-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0105_auto_20190502_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinsurance',
            old_name='onhold_reason',
            new_name='cancel_reason',
        ),
        migrations.AddField(
            model_name='userinsurance',
            name='cancel_case_type',
            field=models.PositiveIntegerField(choices=[(1, 'Refund'), (2, 'Non-Refund')], default=1),
        ),
    ]
