# Generated by Django 2.0.5 on 2019-05-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0106_auto_20190503_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedisease',
            name='is_female_related',
            field=models.BooleanField(default=False),
        ),
    ]
