# Generated by Django 2.0.5 on 2019-05-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0106_auto_20190503_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancemis',
            name='attachment_type',
            field=models.CharField(choices=[('ALL_MIS_ZIP', 'ALL_MIS_ZIP'), ('INSURED_MEMBERS_RESOURCE', 'INSURED_MEMBERS_RESOURCE'), ('USER_INSURANCE_DOCTOR_RESOURCE', 'USER_INSURANCE_DOCTOR_RESOURCE'), ('USER_INSURANCE_LAB_RESOURCE', 'USER_INSURANCE_LAB_RESOURCE'), ('USER_INSURANCE_RESOURCE', 'USER_INSURANCE_RESOURCE')], max_length=100),
        ),
    ]
