# Generated by Django 2.0.5 on 2019-05-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0107_auto_20190503_1349'),
        ('insurance', '0107_insurancedisease_is_female_related'),
    ]

    operations = [
    ]
