# Generated by Django 2.0.5 on 2019-05-08 07:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0109_insurancecoveredentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancelead',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
        migrations.AlterField(
            model_name='insurancelead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
