# Generated by Django 2.0.5 on 2019-05-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0110_auto_20190508_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecoveredentity',
            name='specialization_search_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
