# Generated by Django 2.0.5 on 2019-05-10 11:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0092_lastlogintimestamp'),
        ('insurance', '0110_auto_20190508_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndorsementRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=100, null=True)),
                ('relation', models.CharField(choices=[('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('self', 'Self')], default=None, max_length=50)),
                ('pincode', models.PositiveIntegerField(default=None)),
                ('address', models.TextField(default=None)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default=None, max_length=50)),
                ('phone_number', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('title', models.CharField(choices=[('mr.', 'mr.'), ('mrs.', 'mrs.'), ('miss', 'miss'), ('mast.', 'mast.')], default=None, max_length=20)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('town', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=10, null=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Reject')], default=1)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='endorse_members', to='insurance.UserInsurance')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_endorse_request', to='insurance.InsuredMembers')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorsement_insurance', to='authentication.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
