# Generated by Django 2.0.5 on 2019-05-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0111_insuranceeligiblecities'),
        ('insurance', '0111_insurancecoveredentity_specialization_search_key'),
    ]

    operations = [
    ]
