# Generated by Django 2.0.5 on 2019-05-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0111_endorsementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedummydata',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Booking'), (2, 'Endorsement')], default=1),
        ),
    ]
