# Generated by Django 2.0.5 on 2019-05-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0114_auto_20190513_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredmemberdocument',
            name='document_first_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/images'),
        ),
        migrations.AlterField(
            model_name='insuredmemberdocument',
            name='document_second_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/images'),
        ),
    ]
