# Generated by Django 2.0.5 on 2019-05-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0115_auto_20190513_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredmemberdocument',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
