# Generated by Django 2.0.5 on 2019-05-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0116_insuredmemberdocument_is_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuredmemberdocument',
            old_name='document_first_image',
            new_name='document_image',
        ),
        migrations.RemoveField(
            model_name='insuredmemberdocument',
            name='document_second_image',
        ),
        migrations.AddField(
            model_name='insuredmemberdocument',
            name='endorsement_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_documents', to='insurance.EndorsementRequest'),
        ),
    ]
