# Generated by Django 2.0.5 on 2019-05-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0117_auto_20190514_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsementrequest',
            name='city_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='endorsementrequest',
            name='district_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='endorsementrequest',
            name='state_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='city_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='district_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='insuredmembers',
            name='state_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
