# Generated by Django 2.0.5 on 2019-05-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0119_insuredmemberhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredmemberhistory',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_history', to='insurance.InsuredMembers'),
        ),
    ]
