# Generated by Django 2.0.5 on 2019-05-15 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0120_insuredmemberhistory_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsementrequest',
            name='member_type',
            field=models.CharField(choices=[('adult', 'adult'), ('child', 'child')], default='adult', max_length=20),
        ),
        migrations.AlterField(
            model_name='insuredmemberdocument',
            name='document_image',
            field=models.FileField(upload_to='users/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
