# Generated by Django 2.0.5 on 2019-05-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0121_auto_20190515_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsementrequest',
            name='mail_coi_to_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endorsementrequest',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
