# Generated by Django 2.0.5 on 2019-05-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0122_auto_20190516_1921'),
        ('insurance', '0112_merge_20190517_1958'),
    ]

    operations = [
    ]
