# Generated by Django 2.0.5 on 2019-05-22 06:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0123_merge_20190521_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceplans',
            name='plan_usages',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
