# Generated by Django 2.0.5 on 2019-05-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0123_merge_20190521_1734'),
        ('insurance', '0113_thirdpartyadministrator'),
    ]

    operations = [
    ]
