# Generated by Django 2.0.5 on 2019-05-22 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0124_insuranceplans_plan_usages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurerpolicynumber',
            name='insurer',
        ),
        migrations.AddField(
            model_name='insurerpolicynumber',
            name='insurance_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan_policy_number', to='insurance.InsurancePlans'),
        ),
    ]
