# Generated by Django 2.0.5 on 2019-05-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0113_thirdpartyadministrator'),
        ('insurance', '0125_auto_20190522_1716'),
    ]

    operations = [
    ]
