# Generated by Django 2.0.5 on 2019-05-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0124_merge_20190522_1609'),
        ('insurance', '0126_merge_20190523_1630'),
    ]

    operations = [
    ]
