# Generated by Django 2.0.5 on 2019-05-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0128_insurerpolicynumber_insurer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurerpolicynumber',
            name='insurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_number_history', to='insurance.Insurer'),
        ),
    ]
