# Generated by Django 2.0.5 on 2019-05-24 13:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0130_auto_20190524_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceplans',
            name='plan_usages',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
