# Generated by Django 2.0.5 on 2019-05-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0131_auto_20190524_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceplans',
            name='internal_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
