# Generated by Django 2.0.5 on 2019-05-29 13:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0132_insuranceplans_internal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=250)),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_address', models.CharField(blank=True, max_length=300, null=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_bank', to='insurance.UserInsurance')),
            ],
            options={
                'db_table': 'user_bank',
            },
        ),
        migrations.CreateModel(
            name='UserBankDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_image', models.FileField(upload_to='users/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_bank_document', to='insurance.UserInsurance')),
            ],
            options={
                'db_table': 'user_bank_document',
            },
        ),
    ]
