# Generated by Django 2.0.5 on 2019-06-06 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0133_userbank_userbankdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurerpolicynumber',
            name='apd_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='apd_account', to='insurance.InsurerAccount'),
        ),
    ]
