# Generated by Django 2.0.5 on 2019-06-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0134_insurerpolicynumber_apd_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='insureraccount',
            name='apd_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userinsurance',
            name='master_policy_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_reference', to='insurance.InsurerPolicyNumber'),
        ),
    ]
