# Generated by Django 2.0.5 on 2019-06-10 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0135_auto_20190606_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurerpolicynumber',
            name='apd_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_apd_account', to='insurance.InsurerAccount'),
        ),
    ]
