# Generated by Django 2.0.5 on 2019-06-11 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0136_auto_20190610_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurerAccountTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=None)),
            ],
            options={
                'db_table': 'insurer_account_transfer',
            },
        ),
        migrations.AlterField(
            model_name='insureraccount',
            name='apd_account_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='insureraccounttransfer',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='insurance.InsurerAccount'),
        ),
        migrations.AddField(
            model_name='insureraccounttransfer',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='insurance.InsurerAccount'),
        ),
    ]
