# Generated by Django 2.0.5 on 2019-06-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0137_auto_20190611_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinsurance',
            name='premium_transferred',
            field=models.BooleanField(default=False),
        ),
    ]
