# Generated by Django 2.0.5 on 2019-06-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0138_userinsurance_premium_transferred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinsurance',
            name='premium_transferred',
            field=models.NullBooleanField(default=False),
        ),
    ]
