# Generated by Django 2.0.5 on 2019-06-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0140_auto_20190618_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinsurance',
            name='cancel_customer_type',
            field=models.PositiveIntegerField(choices=[(1, 'Fraud'), (2, 'Other')], default=2),
        ),
    ]
