# Generated by Django 2.0.5 on 2019-06-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0141_userinsurance_cancel_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'bank_holidays',
            },
        ),
    ]
