# Generated by Django 2.0.5 on 2019-06-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0141_userinsurance_cancel_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinsurance',
            name='cancel_initiate_by',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Self'), (2, 'Admin')], null=True),
        ),
    ]
