# Generated by Django 2.0.5 on 2019-06-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0142_bankholidays'),
        ('insurance', '0142_auto_20190627_1156'),
    ]

    operations = [
    ]
