# Generated by Django 2.0.5 on 2019-06-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0143_auto_20190624_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsementrequest',
            name='mail_coi_to_customer',
            field=models.NullBooleanField(default=False),
        ),
    ]
