# Generated by Django 2.0.5 on 2019-06-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0144_auto_20190626_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsementrequest',
            name='mail_status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Mail Pending'), (2, 'Mail Sent')], null=True),
        ),
    ]
