# Generated by Django 2.0.5 on 2019-06-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0145_endorsementrequest_mail_status'),
        ('insurance', '0143_merge_20190627_1717'),
    ]

    operations = [
    ]
