# Generated by Django 2.0.5 on 2019-07-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0146_merge_20190627_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinsurance',
            name='appointment_status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Created'), (2, 'Booked')], null=True),
        ),
    ]
