# Generated by Django 2.0.5 on 2019-07-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0147_userinsurance_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinsurance',
            name='onhold_reason',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
