# Generated by Django 2.0.5 on 2019-08-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0148_auto_20190726_1301'),
        ('insurance', '0149_auto_20190725_1849'),
    ]

    operations = [
    ]
