# Generated by Django 2.0.5 on 2019-09-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0151_auto_20190830_1739'),
        ('insurance', '0152_auto_20190813_1542'),
    ]

    operations = [
    ]
