# Generated by Django 2.0.5 on 2019-12-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0155_auto_20191128_1735'),
        ('insurance', '0155_auto_20191121_1852'),
    ]

    operations = [
    ]
