# Generated by Django 2.0.2 on 2018-04-14 03:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0002_auto_20180412_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'clinical_speciality',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'college',
            },
        ),
        migrations.CreateModel(
            name='DoctorMobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.PositiveSmallIntegerField(blank=True, default=91, null=True)),
                ('number', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('is_phone_number_verified', models.BooleanField(default=False, verbose_name='Phone Number Verified?')),
            ],
            options={
                'db_table': 'doctor_mobile',
            },
        ),
        migrations.CreateModel(
            name='HospitalClinicalSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospital_clinical_speciality',
            },
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='registration_details',
            new_name='license',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_phone_number_verified',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='years_operational',
        ),
        migrations.AddField(
            model_name='doctorqualification',
            name='passing_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AddField(
            model_name='hospital',
            name='operational_since',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800)]),
        ),
        migrations.AddField(
            model_name='hospital',
            name='parking',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('', 'Select'), (1, 'Easy'), (2, 'Difficult')], null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='hospitalclinicalspeciality',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Hospital'),
        ),
        migrations.AddField(
            model_name='hospitalclinicalspeciality',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.ClinicalSpeciality'),
        ),
        migrations.AddField(
            model_name='doctormobile',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
        migrations.AddField(
            model_name='doctorqualification',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.College'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorqualification',
            unique_together={('doctor', 'qualification', 'specialization', 'college')},
        ),
        migrations.AlterUniqueTogether(
            name='hospitalclinicalspeciality',
            unique_together={('hospital', 'speciality')},
        ),
        migrations.AlterUniqueTogether(
            name='doctormobile',
            unique_together={('doctor', 'number')},
        ),
    ]
