# Generated by Django 2.0.4 on 2018-04-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20180416_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorlanguage',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='doctor.Doctor'),
        ),
    ]
