# Generated by Django 2.0.2 on 2018-04-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20180414_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='network_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('', 'Select'), (1, 'Non Network Hospital'), (2, 'Network Hospital')], null=True),
        ),
    ]
