# Generated by Django 2.0.4 on 2018-04-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20180426_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpdAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.PositiveSmallIntegerField()),
                ('fees', models.PositiveSmallIntegerField()),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('time_slot', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.Doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Hospital')),
            ],
            options={
                'db_table': 'opd_appointment',
            },
        ),
    ]
