# Generated by Django 2.0.4 on 2018-04-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_opdappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opdappointment',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='opdappointment',
            name='time_slot_end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='opdappointment',
            name='time_slot_start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
