# Generated by Django 2.0.2 on 2018-04-16 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='awards',
        ),
    ]
