# Generated by Django 2.0.4 on 2018-05-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdappointment',
            name='time_slot_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opdappointment',
            name='time_slot_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
