# Generated by Django 2.0.4 on 2018-05-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20180501_1404'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorhospital',
            unique_together={('start', 'end', 'day', 'hospital', 'doctor')},
        ),
    ]
