# Generated by Django 2.0.2 on 2018-04-18 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_auto_20180418_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.HospitalNetwork'),
        ),
    ]
