# Generated by Django 2.0.2 on 2018-04-19 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_auto_20180418_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalnetworkmapping',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='hospitalnetworkmapping',
            name='network',
        ),
        migrations.DeleteModel(
            name='HospitalNetworkMapping',
        ),
    ]
