# Generated by Django 2.0.4 on 2018-04-23 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_auto_20180419_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorOnboardingToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100)),
                ('verified_token', models.CharField(max_length=100, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Generated'), (2, 'Rejected'), (3, 'Consumed')], default=1)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Doctor')),
            ],
            options={
                'db_table': 'doctor_onboarding_token',
            },
        ),
    ]
