# Generated by Django 2.0.2 on 2018-04-28 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_doctoronboardingtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='primary_mobile',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
