# Generated by Django 2.0.2 on 2018-04-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_doctor_primary_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormobile',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary Number?'),
        ),
    ]
