# Generated by Django 2.0.2 on 2018-04-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_doctormobile_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='primary_mobile',
        ),
    ]
