# Generated by Django 2.0.2 on 2018-04-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_remove_doctor_primary_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='onboarding_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not Onboarded'), (2, 'Onboarding Request Sent'), (3, 'Onboarded')], default=1),
        ),
    ]
