# Generated by Django 2.0.2 on 2018-05-01 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_doctor_onboarding_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='primary_mobile',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
