# Generated by Django 2.0.2 on 2018-05-01 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_doctor_primary_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoronboardingtoken',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctoronboardingtoken',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
