# Generated by Django 2.0.2 on 2018-05-01 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_auto_20180501_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Email?')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Phone Number Verified?')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
            ],
            options={
                'db_table': 'doctor_email',
            },
        ),
        migrations.AlterUniqueTogether(
            name='doctoremail',
            unique_together={('doctor', 'email')},
        ),
    ]
