# Generated by Django 2.0.2 on 2018-05-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_doctordocument_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='primary_mobile',
        ),
        migrations.AlterField(
            model_name='doctordocument',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PAN Card'), (2, 'Address Proof'), (3, 'GST Certificate'), (4, 'MCI Registration Number'), (5, 'Cancel Cheque Copy'), (7, 'Aadhar Card')]),
        ),
    ]
