# Generated by Django 2.0.2 on 2018-05-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20180501_1632'),
        ('doctor', '0025_auto_20180502_1406'),
    ]

    operations = [
    ]
