# Generated by Django 2.0.2 on 2018-05-02 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0026_merge_20180502_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoremail',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorexperience',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorimage',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctormobile',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorqualification',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='doctor.Doctor'),
        ),
    ]
