# Generated by Django 2.0.5 on 2018-05-03 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0027_auto_20180502_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorassociation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctoraward',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctormedicalservice',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_services', to='doctor.Doctor'),
        ),
    ]
