# Generated by Django 2.0.4 on 2018-05-03 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0027_auto_20180502_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_slot_start', models.TimeField()),
                ('time_slot_end', models.TimeField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='doctor.Doctor')),
            ],
            options={
                'db_table': 'doctor_leave',
            },
        ),
    ]
