# Generated by Django 2.0.4 on 2018-05-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_doctorleave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorleave',
            old_name='date_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='doctorleave',
            old_name='date_start',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='doctorleave',
            old_name='time_slot_end',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='doctorleave',
            name='time_slot_start',
        ),
    ]
