# Generated by Django 2.0.4 on 2018-05-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_auto_20180503_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorleave',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
