# Generated by Django 2.0.2 on 2018-05-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0030_auto_20180503_1632'),
        ('doctor', '0028_auto_20180503_1129'),
    ]

    operations = [
    ]
