# Generated by Django 2.0.2 on 2018-05-07 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0031_merge_20180504_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordocument',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='doctor.Doctor'),
        ),
    ]
