# Generated by Django 2.0.2 on 2018-05-15 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0035_auto_20180512_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordocument',
            name='name',
            field=models.FileField(upload_to='doctor/documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jfif', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
