# Generated by Django 2.0.2 on 2018-05-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0036_auto_20180515_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorhospital',
            name='end',
            field=models.DecimalField(choices=[(7, '7 AM'), (7.5, '7:30 AM'), (8, '8 AM'), (8.5, '8:30 AM'), (9, '9 AM'), (9.5, '9:30 AM'), (10, '10 AM'), (10.5, '10:30 AM'), (11, '11 AM'), (11.5, '11:30 AM'), (12, '12 PM'), (12.5, '12:30 PM'), (13, '1 PM'), (13.5, '1:30 PM'), (14, '2 PM'), (14.5, '2:30 PM'), (15, '3 PM'), (15.5, '3:30 PM'), (16, '4 PM'), (16.5, '4:30 PM'), (17, '5 PM'), (17.5, '5:30 PM'), (18, '6 PM'), (18.5, '6:30 PM'), (19, '7 PM'), (19.5, '7:30 PM'), (20, '8 PM'), (20.5, '8:30 PM'), (21, '9 PM'), (21.5, '9:30 PM'), (22, '10 PM'), (22.5, '10:30 PM')], decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='doctorhospital',
            name='start',
            field=models.DecimalField(choices=[(7, '7 AM'), (7.5, '7:30 AM'), (8, '8 AM'), (8.5, '8:30 AM'), (9, '9 AM'), (9.5, '9:30 AM'), (10, '10 AM'), (10.5, '10:30 AM'), (11, '11 AM'), (11.5, '11:30 AM'), (12, '12 PM'), (12.5, '12:30 PM'), (13, '1 PM'), (13.5, '1:30 PM'), (14, '2 PM'), (14.5, '2:30 PM'), (15, '3 PM'), (15.5, '3:30 PM'), (16, '4 PM'), (16.5, '4:30 PM'), (17, '5 PM'), (17.5, '5:30 PM'), (18, '6 PM'), (18.5, '6:30 PM'), (19, '7 PM'), (19.5, '7:30 PM'), (20, '8 PM'), (20.5, '8:30 PM'), (21, '9 PM'), (21.5, '9:30 PM'), (22, '10 PM'), (22.5, '10:30 PM')], decimal_places=1, max_digits=3),
        ),
    ]
