# Generated by Django 2.0.2 on 2018-05-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0036_doctorleave_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdappointment',
            name='patient_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
