# Generated by Django 2.0.2 on 2018-05-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0037_auto_20180517_1205'),
        ('doctor', '0038_medicalcondition'),
    ]

    operations = [
    ]
