# Generated by Django 2.0.5 on 2018-05-31 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0040_remove_doctor_hospitals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdappointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_appointments', to='doctor.Hospital'),
        ),
    ]
