# Generated by Django 2.0.5 on 2018-06-02 07:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0041_auto_20180531_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(through='doctor.DoctorHospital', to='doctor.Hospital'),
        ),
        migrations.AddField(
            model_name='opdappointment',
            name='profile_detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
