# Generated by Django 2.0.5 on 2018-06-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0041_auto_20180531_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(through='doctor.DoctorHospital', to='doctor.Hospital'),
        ),
    ]
