# Generated by Django 2.0.2 on 2018-06-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0042_auto_20180602_1230'),
        ('doctor', '0042_doctor_hospitals'),
    ]

    operations = [
    ]
