# Generated by Django 2.0.5 on 2018-06-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0044_opdappointment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdappointment',
            name='otp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
