# Generated by Django 2.0.2 on 2018-06-13 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0046_auto_20180612_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormobile',
            name='number',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(7000000000)]),
        ),
    ]
