# Generated by Django 2.0.5 on 2018-06-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0047_auto_20180615_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorhospital',
            name='effective_price',
        ),
        migrations.AddField(
            model_name='opdappointment',
            name='discounted_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opdappointment',
            name='effective_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opdappointment',
            name='mrp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
