# Generated by Django 2.0.5 on 2018-06-25 05:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0047_auto_20180613_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField()),
                ('result_count', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
