# Generated by Django 2.0.2 on 2018-06-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0048_doctorspecialization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorspecialization',
            unique_together={('doctor', 'specialization')},
        ),
        migrations.AlterModelTable(
            name='doctorspecialization',
            table='doctor_specialization',
        ),
    ]
