# Generated by Django 2.0.5 on 2018-06-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0048_doctorsearchresult'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctorsearchresult',
            table='doctor_search_result',
        ),
    ]
