# Generated by Django 2.0.6 on 2018-06-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0047_auto_20180613_1214'),
        ('doctor', '0049_auto_20180618_1244'),
    ]

    operations = [
    ]
