# Generated by Django 2.0.5 on 2018-06-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0049_auto_20180618_1244'),
        ('doctor', '0047_auto_20180613_1214'),
    ]

    operations = [
    ]
