# Generated by Django 2.0.2 on 2018-06-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0050_auto_20180625_1625'),
        ('doctor', '0049_auto_20180625_1055'),
    ]

    operations = [
    ]
