# Generated by Django 2.0.6 on 2018-06-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0050_merge_20180618_1756'),
        ('doctor', '0050_merge_20180619_1156'),
    ]

    operations = [
    ]
