# Generated by Django 2.0.6 on 2018-06-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0051_merge_20180620_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdappointment',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Prepaid'), (2, 'COD'), (3, 'Insurance')], default=1),
        ),
        migrations.AlterField(
            model_name='doctorhospital',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctorhospital',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='opdappointment',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='opdappointment',
            name='effective_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='opdappointment',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='opdappointment',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
