# Generated by Django 2.0.2 on 2018-06-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0051_merge_20180625_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorhospital',
            name='deal_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorhospital',
            name='followup_charges',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctorhospital',
            name='followup_duration',
            field=models.PositiveSmallIntegerField(null=True),
        )
    ]
