# Generated by Django 2.0.6 on 2018-06-30 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0055_auto_20180628_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assoc_hospitals', to='doctor.HospitalNetwork'),
        ),
    ]
