# Generated by Django 2.0.5 on 2018-06-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0056_auto_20180630_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(related_name='assoc_doctors', through='doctor.DoctorHospital', to='doctor.Hospital'),
        ),
    ]
