# Generated by Django 2.0.2 on 2018-06-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0057_auto_20180630_1700'),
    ]

    operations = [
        migrations.RunSQL('''DO $$ 
    BEGIN
        BEGIN
            ALTER TABLE doctor_hospital ADD COLUMN mrp smallint;
        EXCEPTION
            WHEN duplicate_column THEN RAISE NOTICE 'column <column_name> already exists in <table_name>.';

        END;
    END;
$$''')
    ]
