# Generated by Django 2.0.2 on 2018-07-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0058_auto_20180630_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opdappointment',
            old_name='discounted_price',
            new_name='deal_price',
        ),
    ]
