# Generated by Django 2.0.5 on 2018-07-03 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0060_hospital_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hospital', to=settings.AUTH_USER_MODEL),
        ),
    ]
