# Generated by Django 2.0.5 on 2018-07-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0064_doctor_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='matrix_lead_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='matrix_reference_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
