# Generated by Django 2.0.6 on 2018-07-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0060_hospital_is_appointment_manager'),
        ('doctor', '0060_opdappointment_outstanding'),
        ('doctor', '0066_auto_20180705_1838'),
    ]

    operations = [
    ]
