# Generated by Django 2.0.5 on 2018-07-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0066_auto_20180705_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='about',
            new_name='raw_about',
        ),
    ]
