# Generated by Django 2.0.5 on 2018-07-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0066_auto_20180705_1838'),
        ('doctor', '0060_hospital_is_appointment_manager'),
    ]

    operations = [
    ]
