# Generated by Django 2.0.5 on 2018-07-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0067_auto_20180710_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
