# Generated by Django 2.0.6 on 2018-07-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0067_merge_20180706_2116'),
        ('doctor', '0067_merge_20180706_2115'),
    ]

    operations = [
    ]
