# Generated by Django 2.0.5 on 2018-07-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0068_merge_20180709_1823'),
        ('doctor', '0069_aboutdoctor'),
    ]

    operations = [
    ]
