# Generated by Django 2.0.5 on 2018-07-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0070_merge_20180711_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='search_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
