# Generated by Django 2.0.5 on 2018-07-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0071_healthtip'),
        ('doctor', '0072_hospital_search_key'),
    ]

    operations = [
    ]
