# Generated by Django 2.0.2 on 2018-07-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0073_merge_20180712_1912'),
        ('doctor', '0047_auto_20180608_1631'),
    ]

    operations = [
    ]
