# Generated by Django 2.0.2 on 2018-07-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0074_merge_20180716_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldocument',
            name='height',
        ),
        migrations.RemoveField(
            model_name='hospitaldocument',
            name='width',
        ),
        migrations.AlterField(
            model_name='doctorimage',
            name='cropped_image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='doctor/images', width_field='width'),
        ),
        migrations.AlterField(
            model_name='hospitaldocument',
            name='name',
            field=models.ImageField(upload_to='hospital/documents'),
        ),
    ]
