# Generated by Django 2.0.2 on 2018-07-19 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0075_auto_20180719_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldocument',
            name='name',
            field=models.FileField(upload_to='hospital/documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jfif', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
