# Generated by Django 2.0.5 on 2018-07-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0076_auto_20180719_1507'),
        ('doctor', '0074_commonmedicalcondition'),
    ]

    operations = [
    ]
