# Generated by Django 2.0.5 on 2018-07-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0077_merge_20180719_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='Is Live'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='Is Live'),
        ),
    ]
