# Generated by Django 2.0.5 on 2018-07-24 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0079_commonspecialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'doctor_mapping',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Is Staff Doctor'),
        ),
        migrations.AddField(
            model_name='doctormapping',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_mapping', to='doctor.Doctor'),
        ),
        migrations.AddField(
            model_name='doctormapping',
            name='profile_to_be_shown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_to_be_shown_mapping', to='doctor.Doctor'),
        ),
    ]
