# Generated by Django 2.0.5 on 2018-07-25 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0079_commonspecialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorClinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Hospital')),
            ],
            options={
                'db_table': 'doctor_clinic',
            },
        ),
        migrations.AlterUniqueTogether(
            name='doctorclinic',
            unique_together={('doctor', 'hospital')},
        ),
    ]
