# Generated by Django 2.0.5 on 2018-07-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0080_auto_20180724_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorimage',
            name='name',
            field=models.ImageField(height_field='height', upload_to='doctor/images', verbose_name='Original Image Name', width_field='width'),
        ),
    ]
