# Generated by Django 2.0.5 on 2018-07-27 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0080_auto_20180724_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonmedicalcondition',
            name='condition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_condition', to='doctor.MedicalCondition'),
        ),
        migrations.AlterField(
            model_name='commonspecialization',
            name='specialization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_specialization', to='doctor.Specialization'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorassociation',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associations', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctoraward',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctordocument',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctoremail',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorexperience',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorhospital',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorhospital',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Hospital'),
        ),
        migrations.AlterField(
            model_name='doctorimage',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorlanguage',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorlanguage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Language'),
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctormapping',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_mapping', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctormapping',
            name='profile_to_be_shown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_to_be_shown_mapping', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctormedicalservice',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_services', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctormedicalservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.MedicalService'),
        ),
        migrations.AlterField(
            model_name='doctormobile',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobiles', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorqualification',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.College'),
        ),
        migrations.AlterField(
            model_name='doctorqualification',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifications', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorqualification',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Qualification'),
        ),
        migrations.AlterField(
            model_name='doctorqualification',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Specialization'),
        ),
        migrations.AlterField(
            model_name='doctorspecialization',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctorspecializations', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorspecialization',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.GeneralSpecialization'),
        ),
        migrations.AlterField(
            model_name='hospitalaccreditation',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalaward',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalcertification',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Hospital'),
        ),
        migrations.AlterField(
            model_name='hospitaldocument',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalimage',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalnetworkaccreditation',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.HospitalNetwork'),
        ),
        migrations.AlterField(
            model_name='hospitalnetworkaward',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.HospitalNetwork'),
        ),
        migrations.AlterField(
            model_name='hospitalnetworkcertification',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.HospitalNetwork'),
        ),
        migrations.AlterField(
            model_name='hospitalnetworkemail',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.HospitalNetwork'),
        ),
        migrations.AlterField(
            model_name='hospitalnetworkhelpline',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.HospitalNetwork'),
        ),
        migrations.AlterField(
            model_name='hospitalnetworkmanager',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.HospitalNetwork'),
        ),
        migrations.AlterField(
            model_name='hospitalspeciality',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Hospital'),
        ),
        migrations.AlterField(
            model_name='medicalconditionspecialization',
            name='medical_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.MedicalCondition'),
        ),
        migrations.AlterField(
            model_name='medicalconditionspecialization',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Specialization'),
        ),
        migrations.AlterField(
            model_name='opdappointment',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_appointements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opdappointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='opdappointment',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_appointments', to='doctor.Hospital'),
        ),
        migrations.AlterField(
            model_name='opdappointment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='authentication.UserProfile'),
        ),
        migrations.AlterField(
            model_name='opdappointment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.OpdAppointment'),
        ),
        migrations.AlterField(
            model_name='prescriptionfile',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Prescription'),
        ),
    ]
