# Generated by Django 2.0.5 on 2018-07-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0081_auto_20180728_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldocument',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PAN Card'), (2, 'Address Proof'), (3, 'GST Certificate'), (5, 'Cancel Cheque Copy'), (8, 'COI/Company Registration'), (9, 'Email Confirmation')], default=2),
        ),
        migrations.AlterField(
            model_name='hospitalnetworkdocument',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PAN Card'), (2, 'Address Proof'), (3, 'GST Certificate'), (5, 'Cancel Cheque Copy'), (8, 'COI/Company Registration'), (9, 'Email Confirmation')]),
        ),
    ]
