# Generated by Django 2.0.5 on 2018-07-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0081_auto_20180725_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(related_name='assoc_doctors', through='doctor.DoctorClinic', to='doctor.Hospital'),
        ),
    ]
