# Generated by Django 2.0.5 on 2018-07-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0082_auto_20180725_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorclinic',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_clinics', to='doctor.Doctor'),
        ),
    ]
