# Generated by Django 2.0.5 on 2018-07-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0081_auto_20180728_1223'),
        ('doctor', '0082_auto_20180729_0945'),
    ]

    operations = [
    ]
