# Generated by Django 2.0.2 on 2018-07-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0083_merge_20180730_1229'),
        ('doctor', '0083_merge_20180730_1150'),
    ]

    operations = [
    ]
