# Generated by Django 2.0.5 on 2018-07-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0084_auto_20180725_1713'),
        ('doctor', '0080_auto_20180724_1612'),
    ]

    operations = [
    ]
