# Generated by Django 2.0.5 on 2018-07-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0084_merge_20180730_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldocument',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_documents', to='doctor.Hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalnetworkdocument',
            name='hospital_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_network_documents', to='doctor.HospitalNetwork'),
        ),
    ]
