# Generated by Django 2.0.2 on 2018-07-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0085_merge_20180725_2003'),
        ('doctor', '0085_auto_20180730_1302'),
    ]

    operations = [
    ]
