# Generated by Django 2.0.5 on 2018-07-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0086_merge_20180730_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorhospital',
            name='followup_charges',
        ),
        migrations.RemoveField(
            model_name='doctorhospital',
            name='followup_duration',
        ),
        migrations.AddField(
            model_name='doctorclinic',
            name='followup_charges',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctorclinic',
            name='followup_duration',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
