# Generated by Django 2.0.2 on 2018-07-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0087_auto_20180730_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorclinictiming',
            name='followup_charges',
        ),
        migrations.RemoveField(
            model_name='doctorclinictiming',
            name='followup_duration',
        ),
        migrations.AlterField(
            model_name='doctorclinic',
            name='followup_charges',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorclinic',
            name='followup_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
