# Generated by Django 2.0.2 on 2018-08-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0088_auto_20180730_2101'),
        ('doctor', '0081_auto_20180727_1126'),
    ]

    operations = [
    ]
