# Generated by Django 2.0.7 on 2018-08-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0088_auto_20180730_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorOpdAppointment',
            fields=[
            ],
            options={
                'default_permissions': [],
                'proxy': True,
                'indexes': [],
            },
            bases=('doctor.opdappointment',),
        ),
    ]
