# Generated by Django 2.0.7 on 2018-08-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0089_doctoropdappointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorOpdAppointment',
        ),
        migrations.AlterField(
            model_name='opdappointment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Booked'), (3, 'Rescheduled by Doctor'), (4, 'Rescheduled by patient'), (5, 'Accepted'), (6, 'Cancelled'), (7, 'Completed')], default=1),
        ),
    ]
