# Generated by Django 2.0.5 on 2018-08-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0091_doctor_is_test_doctor'),
        ('doctor', '0090_auto_20180802_1403'),
    ]

    operations = [
    ]
