# Generated by Django 2.0.5 on 2018-08-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0093_doctor_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmedicalcondition',
            name='icon',
            field=models.ImageField(null=True, upload_to='doctor/medical_condition_icons'),
        ),
    ]
