# Generated by Django 2.0.5 on 2018-08-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0094_commonmedicalcondition_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonmedicalcondition',
            name='icon',
        ),
        migrations.AddField(
            model_name='commonspecialization',
            name='icon',
            field=models.ImageField(null=True, upload_to='doctor/common_specialization_icons'),
        ),
    ]
