# Generated by Django 2.0.5 on 2018-08-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0095_auto_20180817_1743'),
        ('doctor', '0094_opdappointment_cancellation_type'),
    ]

    operations = [
    ]
