# Generated by Django 2.0.5 on 2018-08-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0096_merge_20180821_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonspecialization',
            name='specialization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='common_specialization', to='doctor.GeneralSpecialization'),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='specialization',
            field=models.ManyToManyField(through='doctor.MedicalConditionSpecialization', to='doctor.GeneralSpecialization'),
        ),
        migrations.AlterField(
            model_name='medicalconditionspecialization',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.GeneralSpecialization'),
        ),
    ]
