# Generated by Django 2.0.5 on 2018-08-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0097_auto_20180827_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalspecialization',
            name='search_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='search_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
