# Generated by Django 2.0.5 on 2018-08-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0098_auto_20180827_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmedicalcondition',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonspecialization',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
