# Generated by Django 2.0.5 on 2018-08-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0099_auto_20180828_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorclinictiming',
            name='type',
            field=models.IntegerField(choices=[(1, 'Fixed'), (2, 'On Call')], default=1),
        ),
    ]
