# Generated by Django 2.0.5 on 2018-09-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0100_doctorclinictiming_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdappointment',
            name='matrix_lead_id',
            field=models.IntegerField(null=True),
        ),
    ]
