# Generated by Django 2.0.5 on 2018-09-04 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0101_competitorinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorinfo',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_doctor', to='doctor.Doctor'),
        ),
        migrations.AddField(
            model_name='competitorinfo',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_hospital', to='doctor.Hospital'),
        ),
        migrations.AlterModelTable(
            name='competitorinfo',
            table='competitor_info',
        ),
    ]
