# Generated by Django 2.0.5 on 2018-09-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0102_auto_20180904_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorinfo',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_doctor', to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='competitorinfo',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_hospital', to='doctor.Hospital'),
        ),
    ]
