# Generated by Django 2.0.5 on 2018-09-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0103_auto_20180904_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorinfo',
            name='processed_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='competitorinfo',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
