# Generated by Django 2.0.5 on 2018-09-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0104_auto_20180904_1515'),
        ('doctor', '0102_auto_20180904_1457'),
        ('doctor', '0101_opdappointment_matrix_lead_id'),
    ]

    operations = [
    ]
