# Generated by Django 2.1 on 2018-09-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0106_auto_20180906_1821'),
        ('doctor', '0106_auto_20180906_1814'),
    ]

    operations = [
    ]
