# Generated by Django 2.0.5 on 2018-09-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0107_merge_20180906_2000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorclinictiming',
            unique_together=set(),
        ),
    ]
