# Generated by Django 2.0.5 on 2018-09-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0108_auto_20180911_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Is Enabled'),
        ),
    ]
