# Generated by Django 2.0.5 on 2018-09-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0111_specializationdepartment_specializationfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specializationdepartment',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='specializationfield',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
