# Generated by Django 2.0.5 on 2018-09-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0111_competitorhit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitorinfo',
            unique_together={('name', 'hospital_name', 'doctor')},
        ),
    ]
