# Generated by Django 2.0.5 on 2018-09-20 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0111_competitorhit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorMonthlyVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(choices=[('', 'Select'), (1, 'Practo'), (2, 'Lybrate')])),
                ('monthly_visit', models.BigIntegerField(verbose_name='Monthly Visits through Competitor')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_doctor_hits', to='doctor.Doctor')),
            ],
            options={
                'db_table': 'competitor_monthly_visits',
            },
        ),
        migrations.RemoveField(
            model_name='competitorhit',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='CompetitorHit',
        ),
        migrations.AlterUniqueTogether(
            name='competitormonthlyvisit',
            unique_together={('doctor', 'name')},
        ),
    ]
