# Generated by Django 2.0.5 on 2018-09-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0113_generalspecialization_synonyms'),
        ('doctor', '0113_auto_20180921_1943'),
    ]

    operations = [
    ]
