# Generated by Django 2.0.5 on 2018-09-18 12:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0113_auto_20180918_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicespecialization',
            name='general_specialization_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=100),
        ),
    ]
