# Generated by Django 2.0.5 on 2018-09-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0114_merge_20180921_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('agreed_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('listing_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('details', models.CharField(max_length=2000)),
                ('duration', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Hospital')),
            ],
            options={
                'db_table': 'doctor_procedure',
            },
        ),
        migrations.AlterUniqueTogether(
            name='doctorprocedure',
            unique_together={('name', 'doctor', 'hospital')},
        ),
    ]
