# Generated by Django 2.0.5 on 2018-09-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0114_auto_20180918_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPracticeSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorpracticespecializations', to='doctor.Doctor')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.PracticeSpecialization')),
            ],
            options={
                'db_table': 'doctor_practice_specialization',
            },
        ),
        migrations.AlterUniqueTogether(
            name='doctorpracticespecialization',
            unique_together={('doctor', 'specialization')},
        ),
    ]
