# Generated by Django 2.0.5 on 2018-09-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0114_merge_20180921_1956'),
        ('doctor', '0115_auto_20180920_1426'),
    ]

    operations = [
    ]
