# Generated by Django 2.0.5 on 2018-09-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0115_auto_20180925_1233'),
        ('doctor', '0116_merge_20180924_1924'),
    ]

    operations = [
    ]
