# Generated by Django 2.0.5 on 2018-09-20 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0116_auto_20180920_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonspecialization',
            name='specialization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_specialization', to='doctor.PracticeSpecialization'),
        ),
        migrations.AddField(
            model_name='medicalconditionspecialization',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.PracticeSpecialization'),
        ),
    ]
