# Generated by Django 2.0.5 on 2018-09-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0116_auto_20180925_1550'),
        ('doctor', '0117_merge_20180925_1448'),
    ]

    operations = [
    ]
