# Generated by Django 2.0.5 on 2018-09-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0118_medicalcondition_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicespecialization',
            name='search_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
