# Generated by Django 2.0.5 on 2018-09-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0119_practicespecialization_search_key'),
        ('doctor', '0117_merge_20180925_1448'),
    ]

    operations = [
    ]
