# Generated by Django 2.0.5 on 2018-09-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0118_merge_20180925_2140'),
        ('doctor', '0120_merge_20180925_1847'),
    ]

    operations = [
    ]
