# Generated by Django 2.1 on 2018-09-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0121_merge_20180925_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorqualification',
            options={'ordering': ('created_at',)},
        ),
    ]
