# Generated by Django 2.0.5 on 2018-10-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0122_auto_20180926_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Is Enabled'),
        ),
    ]
