# Generated by Django 2.0.5 on 2018-10-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('doctor', '0123_opdappointment_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opdappointment',
            name='coupon',
        ),
        migrations.AddField(
            model_name='opdappointment',
            name='coupon',
            field=models.ManyToManyField(blank=True, null=True, to='coupon.Coupon'),
        ),
    ]
