# Generated by Django 2.0.5 on 2018-10-11 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0123_hospital_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormobile',
            name='number',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(5000000000)]),
        ),
    ]
