# Generated by Django 2.0.5 on 2018-10-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0123_hospital_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.IntegerField()),
                ('unique_identifier', models.CharField(max_length=1000)),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Doctor'), (5, 'Hospital')], null=True)),
            ],
            options={
                'db_table': 'source_identifier',
            },
        ),
        migrations.AlterField(
            model_name='hospital',
            name='building',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='sourceidentifier',
            unique_together={('unique_identifier',)},
        ),
    ]
