# Generated by Django 2.0.5 on 2018-10-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0123_hospital_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdappointment',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opdappointment',
            name='rating_declined',
            field=models.BooleanField(default=False),
        ),
    ]
