# Generated by Django 2.0.5 on 2018-10-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0124_auto_20181004_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdappointment',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
