# Generated by Django 2.0.5 on 2018-10-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0126_auto_20181012_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='source',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
