# Generated by Django 2.0.5 on 2018-10-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0126_auto_20181004_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdappointment',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
