# Generated by Django 2.0.5 on 2018-10-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0124_auto_20181012_2313'),
        ('doctor', '0127_doctor_source'),
    ]

    operations = [
    ]
