# Generated by Django 2.0.5 on 2018-10-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0127_auto_20181005_1843'),
        ('doctor', '0124_auto_20181011_1645'),
    ]

    operations = [
    ]
