# Generated by Django 2.0.5 on 2018-10-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0128_merge_20181013_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormobile',
            name='country_code',
        ),
        migrations.AddField(
            model_name='doctormobile',
            name='std_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
