# Generated by Django 2.0.5 on 2018-10-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0129_auto_20181013_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormobile',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
