# Generated by Django 2.0.5 on 2018-10-16 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0133_doctor_enable_for_online_booking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctormobile',
            unique_together={('doctor', 'number', 'std_code')},
        ),
    ]
