# Generated by Django 2.0.5 on 2018-10-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0134_auto_20181016_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorassociation',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='doctoraward',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='doctorexperience',
            name='hospital',
            field=models.CharField(max_length=2000),
        ),
    ]
