# Generated by Django 2.0.5 on 2018-10-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0134_auto_20181016_0751'),
        ('doctor', '0127_auto_20181005_1843'),
    ]

    operations = [
    ]
