# Generated by Django 2.0.5 on 2018-10-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0135_merge_20181016_1238'),
        ('doctor', '0135_auto_20181017_0033'),
    ]

    operations = [
    ]
