# Generated by Django 2.0.5 on 2018-10-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0136_merge_20181017_0035'),
        ('doctor', '0128_merge_20181017_1601'),
    ]

    operations = [
    ]
