# Generated by Django 2.0.5 on 2018-10-23 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0136_auto_20181017_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPlaceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('clinic_hospital_name', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('doctor_clinic_address', models.TextField()),
                ('clinic_address', models.TextField()),
            ],
            options={
                'db_table': 'doctor_place_sheet',
            },
        ),
        migrations.CreateModel(
            name='GoogleDetailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('DETAIL', 'DETAIL'), ('FINDPLACE', 'FINDPLACE')], max_length=48)),
                ('parameter', models.CharField(choices=[('CLINIC_ADDRESS', 'CLINIC_ADDRESS'), ('DOCTOR_CLINIC_ADDRESS', 'DOCTOR_CLINIC_ADDRESS')], max_length=48)),
                ('raw_value', models.TextField()),
                ('extracted_value', models.TextField()),
                ('doc_place_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorPlaceSheet')),
            ],
            options={
                'db_table': 'google_api_details',
            },
        ),
    ]
