# Generated by Django 2.0.5 on 2018-10-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0137_doctorplacesheet_googledetailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorplacesheet',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
    ]
