# Generated by Django 2.0.5 on 2018-10-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0137_merge_20181017_1614'),
        ('doctor', '0136_auto_20181017_1404'),
    ]

    operations = [
    ]
