# Generated by Django 2.0.5 on 2018-10-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0138_auto_20181023_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googledetailing',
            name='extracted_value',
        ),
        migrations.RemoveField(
            model_name='googledetailing',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='googledetailing',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='googledetailing',
            name='raw_value',
        ),
        migrations.AddField(
            model_name='googledetailing',
            name='clinic_detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='googledetailing',
            name='clinic_formatted_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='googledetailing',
            name='clinic_international_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='googledetailing',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='googledetailing',
            name='clinic_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='googledetailing',
            name='clinic_place_search',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='googledetailing',
            name='doctor_detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='googledetailing',
            name='doctor_formatted_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='googledetailing',
            name='doctor_international_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='googledetailing',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='googledetailing',
            name='doctor_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='googledetailing',
            name='doctor_place_search',
            field=models.TextField(null=True),
        ),
    ]
