# Generated by Django 2.0.5 on 2018-10-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0138_merge_20181017_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='enable_for_online_booking',
            new_name='enabled_for_online_booking',
        ),
        migrations.AddField(
            model_name='doctor',
            name='enabled_for_online_booking_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
