# Generated by Django 2.0.5 on 2018-10-23 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0139_auto_20181019_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPopularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identifier', models.CharField(max_length=500)),
                ('popularity', models.PositiveSmallIntegerField(choices=[(1, 'Key'), (2, 'Non-Key')])),
                ('popularity_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('rating_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('votes', models.PositiveIntegerField()),
                ('reviews', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'doctor_popularity',
            },
        ),
        migrations.AlterUniqueTogether(
            name='doctorpopularity',
            unique_together={('unique_identifier',)},
        ),
    ]
