# Generated by Django 2.0.5 on 2018-10-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0139_auto_20181019_0103'),
        ('doctor', '0137_merge_20181018_1136'),
    ]

    operations = [
    ]
