# Generated by Django 2.0.5 on 2018-10-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0139_auto_20181019_0103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorclinicprocedure',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='doctorclinicprocedure',
            name='doctor_clinic',
        ),
        migrations.RemoveField(
            model_name='doctorclinicprocedure',
            name='procedure',
        ),
        migrations.DeleteModel(
            name='DoctorClinicProcedure',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
    ]
