# Generated by Django 2.0.5 on 2018-10-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0139_auto_20181019_0103'),
        ('doctor', '0140_auto_20181024_1621'),
    ]

    operations = [
    ]
