# Generated by Django 2.0.5 on 2018-10-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0140_merge_20181024_1459'),
        ('doctor', '0141_merge_20181025_1546'),
    ]

    operations = [
    ]
