# Generated by Django 2.0.5 on 2018-10-23 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0141_auto_20181023_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpopularity',
            name='popularity_score',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
