# Generated by Django 2.0.5 on 2018-10-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0142_merge_20181025_1818'),
        ('doctor', '0141_merge_20181025_1506'),
    ]

    operations = [
    ]
