# Generated by Django 2.0.5 on 2018-10-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0143_practicespecialization_synonyms'),
        ('doctor', '0145_merge_20181026_2055'),
    ]

    operations = [
    ]
