# Generated by Django 2.0.5 on 2018-10-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0140_auto_20181024_1835'),
        ('doctor', '0145_merge_20181026_2055'),
    ]

    operations = [
    ]
