# Generated by Django 2.0.5 on 2018-10-30 01:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0147_auto_20181029_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitReasonMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('practice_specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_visit_reasons', to='doctor.PracticeSpecialization')),
            ],
            options={
                'db_table': 'visit_reason_mapping',
            },
        ),
        migrations.AddField(
            model_name='visitreason',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitreason',
            name='search_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='visitreason',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='visitreason',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='visitreasonmapping',
            name='visit_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_practice_specializations', to='doctor.VisitReason'),
        ),
        migrations.RemoveField(
            model_name='visitreason',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='visitreason',
            name='practice_specialization',
        ),
        migrations.AddField(
            model_name='visitreason',
            name='practice_specializations',
            field=models.ManyToManyField(related_name='visiting_reasons', through='doctor.VisitReasonMapping', to='doctor.PracticeSpecialization'),
        ),
        migrations.AlterUniqueTogether(
            name='visitreasonmapping',
            unique_together={('visit_reason', 'practice_specialization')},
        ),
    ]
