# Generated by Django 2.0.5 on 2018-10-30 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0148_auto_20181030_0726'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visitreason',
            unique_together={('name',)},
        ),
    ]
