# Generated by Django 2.0.5 on 2018-10-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0146_merge_20181029_1454'),
        ('doctor', '0149_auto_20181030_0817'),
    ]

    operations = [
    ]
