# Generated by Django 2.0.5 on 2018-10-30 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0150_auto_20181030_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdappointment',
            name='cancellation_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.CancellationReason'),
        ),
    ]
