# Generated by Django 2.0.5 on 2018-11-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0151_auto_20181030_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormobile',
            name='source',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
