# Generated by Django 2.0.5 on 2018-11-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0151_auto_20181030_1529'),
        ('doctor', '0150_merge_20181030_1305'),
    ]

    operations = [
    ]
