# Generated by Django 2.0.5 on 2018-11-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0151_auto_20181030_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['name']},
        ),
    ]
