# Generated by Django 2.0.5 on 2018-11-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0152_practicespecializationcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicespecializationcontent',
            name='search_key',
        ),
    ]
