# Generated by Django 2.0.5 on 2018-11-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0153_remove_practicespecializationcontent_search_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicespecializationcontent',
            name='content',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
