# Generated by Django 2.0.5 on 2018-11-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0154_auto_20181102_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_gold',
            field=models.BooleanField(default=False, verbose_name='Is Gold'),
        ),
    ]
