# Generated by Django 2.0.5 on 2018-11-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0155_doctor_is_gold'),
        ('doctor', '0152_doctormobile_source'),
    ]

    operations = [
    ]
