# Generated by Django 2.0.5 on 2018-11-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0156_merge_20181103_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormobile',
            name='source',
            field=models.CharField(blank=True, default='', max_length=2000),
            preserve_default=False,
        ),
    ]
