# Generated by Django 2.0.5 on 2018-11-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0157_auto_20181103_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorclinic',
            name='enabled_for_online_booking',
            field=models.BooleanField(default=False, verbose_name='enabled_for_online_booking?'),
        ),
    ]
