# Generated by Django 2.0.5 on 2018-11-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0157_auto_20181103_0043'),
        ('doctor', '0152_merge_20181102_1213'),
    ]

    operations = [
    ]
