# Generated by Django 2.0.5 on 2018-11-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0158_doctorclinic_enabled_for_online_booking'),
        ('doctor', '0158_merge_20181105_1016'),
    ]

    operations = [
    ]
