# Generated by Django 2.0.5 on 2018-11-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0159_auto_20181113_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorclinic',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
