# Generated by Django 2.0.5 on 2018-11-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0159_merge_20181110_1247'),
        ('doctor', '0160_doctorclinic_priority'),
    ]

    operations = [
    ]
