# Generated by Django 2.0.5 on 2018-11-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0160_doctorclinic_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledetailing',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
