# Generated by Django 2.0.5 on 2018-11-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0161_merge_20181114_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdappointment',
            name='insurance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.UserInsurance'),
        ),
    ]
