# Generated by Django 2.0.5 on 2018-11-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0017_auto_20181113_1521'),
        ('doctor', '0161_merge_20181114_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdappointment',
            name='procedures',
            field=models.ManyToManyField(null=True, to='procedure.Procedure'),
        ),
    ]
