# Generated by Django 2.0.5 on 2018-11-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0161_auto_20181115_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorclinic',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
    ]
