# Generated by Django 2.0.5 on 2018-11-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0162_opdappointment_procedures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdappointment',
            name='procedures',
            field=models.ManyToManyField(blank=True, null=True, to='procedure.Procedure'),
        ),
    ]
