# Generated by Django 2.0.5 on 2018-11-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0162_doctorclinic_enabled'),
        ('doctor', '0145_auto_20181113_1137'),
    ]

    operations = [
    ]
