# Generated by Django 2.0.5 on 2018-11-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0162_doctorclinic_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='ratings',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
