# Generated by Django 2.0.5 on 2018-11-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0163_auto_20181115_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opdappointment',
            name='procedures',
        ),
    ]
