# Generated by Django 2.0.5 on 2018-11-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0017_auto_20181113_1521'),
        ('doctor', '0164_remove_opdappointment_procedures'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpdAppointmentProcedureMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.IntegerField(blank=True, null=True)),
                ('agreed_price', models.IntegerField(blank=True, null=True)),
                ('deal_price', models.IntegerField(blank=True, null=True)),
                ('opd_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_mappings', to='doctor.OpdAppointment')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opd_appointment_mappings', to='procedure.Procedure')),
            ],
            options={
                'db_table': 'opd_appointment_procedure_mapping',
            },
        ),
        migrations.AddField(
            model_name='opdappointment',
            name='procedures',
            field=models.ManyToManyField(blank=True, null=True, through='doctor.OpdAppointmentProcedureMapping', to='procedure.Procedure'),
        ),
    ]
