# Generated by Django 2.0.5 on 2018-11-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0165_auto_20181116_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdappointmentproceduremapping',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='opdappointmentproceduremapping',
            name='deal_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='opdappointmentproceduremapping',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
