# Generated by Django 2.0.5 on 2018-11-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0166_auto_20181118_1752'),
        ('doctor', '0162_doctorclinic_enabled'),
    ]

    operations = [
    ]
