# Generated by Django 2.0.5 on 2018-11-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0167_merge_20181122_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='enabled_for_online_booking',
            field=models.BooleanField(default=True, verbose_name='enabled_for_online_booking?'),
        ),
    ]
