# Generated by Django 2.0.5 on 2018-11-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0162_auto_20181127_2034'),
        ('doctor', '0167_merge_20181122_1240'),
    ]

    operations = [
    ]
