# Generated by Django 2.0.5 on 2018-11-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0167_merge_20181122_1240'),
        ('doctor', '0163_merge_20181120_1236'),
    ]

    operations = [
    ]
