# Generated by Django 2.0.5 on 2018-11-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0168_merge_20181127_1204'),
        ('doctor', '0168_hospital_enabled_for_online_booking'),
    ]

    operations = [
    ]
