# Generated by Django 2.0.5 on 2018-11-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0168_merge_20181128_1247'),
        ('doctor', '0168_merge_20181128_1704'),
    ]

    operations = [
    ]
