# Generated by Django 2.0.5 on 2018-12-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0169_merge_20181129_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='matrix_lead_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
