# Generated by Django 2.0.5 on 2018-11-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0169_merge_20181129_1149'),
        ('doctor', '0169_merge_20181128_1809'),
    ]

    operations = [
    ]
