# Generated by Django 2.0.5 on 2018-12-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0169_merge_20181129_1830'),
        ('doctor', '0165_remove_opdappointment_ratings'),
    ]

    operations = [
    ]
