# Generated by Django 2.0.5 on 2018-12-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0170_merge_20181129_1237'),
        ('doctor', '0170_auto_20181206_2204'),
    ]

    operations = [
    ]
