# Generated by Django 2.0.5 on 2018-12-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0170_opdappointment_merchant_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorclinic',
            name='is_billing_enabled',
            field=models.BooleanField(default=False, verbose_name='Enabled for Billing'),
        ),
    ]
