# Generated by Django 2.0.5 on 2018-12-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0170_opdappointment_merchant_payout'),
        ('doctor', '0170_auto_20181206_2204'),
        ('doctor', '0170_merge_20181203_1839'),
    ]

    operations = [
    ]
