# Generated by Django 2.0.5 on 2018-12-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0170_auto_20181203_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlineopdappointments',
            name='deal_price',
        ),
        migrations.RemoveField(
            model_name='offlineopdappointments',
            name='effective_price',
        ),
        migrations.RemoveField(
            model_name='offlineopdappointments',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='offlineopdappointments',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='offlineopdappointments',
            name='time_slot_end',
        ),
        migrations.AddField(
            model_name='offlinepatients',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_doc', to='doctor.Doctor'),
        ),
        migrations.AddField(
            model_name='offlinepatients',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_hos', to='doctor.Hospital'),
        ),
        migrations.AddField(
            model_name='offlinepatients',
            name='share_with_hospital',
            field=models.BooleanField(default=False),
        ),
    ]
