# Generated by Django 2.0.5 on 2018-12-11 11:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import ondoc.doctor.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0171_merge_20181207_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorMobileOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp', models.PositiveIntegerField()),
                ('validity', models.DateTimeField(default=ondoc.doctor.models.doctor_mobile_otp_validity)),
                ('usable_counter', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'doctor_mobile_otp',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='doctormobile',
            name='mark_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctormobile',
            name='otp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctormobileotp',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles_otp', to='doctor.DoctorMobile'),
        ),
    ]
