# Generated by Django 2.0.5 on 2018-12-31 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0171_merge_20181207_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpracticespecialization',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization', to='doctor.PracticeSpecialization'),
        ),
    ]
