# Generated by Django 2.0.5 on 2018-12-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0171_merge_20181207_1443'),
        ('doctor', '0171_merge_20181207_1957'),
    ]

    operations = [
    ]
