# Generated by Django 2.0.5 on 2018-12-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0172_opdappointment_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdappointment',
            name='cashback_processed',
            field=models.BooleanField(default=False),
        ),
    ]
