# Generated by Django 2.0.5 on 2018-12-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0173_auto_20181211_1730'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctormobileotp',
            managers=[
            ],
        ),
    ]
