# Generated by Django 2.0.5 on 2018-12-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0173_opdappointment_cashback_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opdappointment',
            name='cashback_processed',
        ),
    ]
