# Generated by Django 2.0.5 on 2018-12-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0174_auto_20181206_1738'),
        ('doctor', '0170_auto_20181206_2204'),
    ]

    operations = [
    ]
