# Generated by Django 2.0.5 on 2018-12-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0175_merge_20181207_1847'),
        ('doctor', '0171_merge_20181207_1957'),
    ]

    operations = [
    ]
