# Generated by Django 2.0.5 on 2018-12-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0174_auto_20181211_1759'),
        ('doctor', '0175_opdappointment_price_data'),
    ]

    operations = [
    ]
