# Generated by Django 2.0.5 on 2019-01-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0175_opdappointment_price_data'),
        ('doctor', '0172_auto_20181231_1658'),
    ]

    operations = [
    ]
