# Generated by Django 2.0.5 on 2018-12-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0175_opdappointment_price_data'),
        ('doctor', '0172_merge_20181218_1358'),
    ]

    operations = [
    ]
