# Generated by Django 2.0.5 on 2019-01-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0176_hospital_pyhsical_aggrement_signed'),
        ('doctor', '0176_merge_20190102_1610'),
    ]

    operations = [
    ]
