# Generated by Django 2.0.5 on 2018-12-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0176_merge_20181217_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineopdappointments',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offlineopdappointments',
            name='error_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='offlinepatients',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offlinepatients',
            name='error_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
