# Generated by Django 2.0.5 on 2019-01-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0176_searchscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchscore',
            old_name='doctors_in_clinic',
            new_name='doctors_in_clinic_score',
        ),
        migrations.RenameField(
            model_name='searchscore',
            old_name='years_of_experience',
            new_name='years_of_experience_score',
        ),
    ]
