# Generated by Django 2.0.5 on 2019-01-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0177_auto_20190108_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='search_score',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
