# Generated by Django 2.0.5 on 2019-01-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0178_doctor_search_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchscore',
            name='final_score',
            field=models.FloatField(default=None, null=True),
        ),
    ]
