# Generated by Django 2.0.5 on 2018-12-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0178_offlinepatients_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinepatients',
            name='calculated_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offlineopdappointments',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Booked'), (3, 'Rescheduled by Doctor'), (4, 'No Show'), (5, 'Accepted'), (6, 'Cancelled'), (7, 'Completed')], default=1),
        ),
    ]
