# Generated by Django 2.0.5 on 2018-12-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0179_auto_20181224_1808'),
        ('doctor', '0175_opdappointment_price_data'),
    ]

    operations = [
    ]
