# Generated by Django 2.0.5 on 2019-01-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0177_merge_20190108_1624'),
        ('doctor', '0179_auto_20190108_1822'),
    ]

    operations = [
    ]
