# Generated by Django 2.0.5 on 2019-01-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0180_merge_20190109_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='search_score',
            field=models.PositiveIntegerField(default=0, editable=False, null=True),
        ),
    ]
