# Generated by Django 2.0.5 on 2019-01-10 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0180_merge_20181227_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.OpdAppointment'),
        ),
        migrations.AlterField(
            model_name='prescriptionfile',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_file', to='doctor.Prescription'),
        ),
    ]
