# Generated by Django 2.0.5 on 2019-01-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0180_merge_20190109_1922'),
        ('doctor', '0178_auto_20190109_1728'),
    ]

    operations = [
    ]
