# Generated by Django 2.0.5 on 2019-01-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0181_auto_20190109_1923'),
        ('doctor', '0181_auto_20190110_1145'),
    ]

    operations = [
    ]
