# Generated by Django 2.0.5 on 2019-01-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0182_merge_20190110_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='search_score',
            field=models.FloatField(default=0, editable=False, null=True),
        ),
    ]
