# Generated by Django 2.0.5 on 2019-01-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0176_merge_20181228_1607'),
        ('doctor', '0183_auto_20190110_1156'),
    ]

    operations = [
    ]
