# Generated by Django 2.0.5 on 2019-01-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0183_auto_20190110_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDoctorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
                ('source', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[('', 'Select'), (1, 'Created'), (2, 'Upload in progress'), (3, 'Upload successful'), (4, 'Upload Failed')], null=True)),
                ('error_msg', models.TextField(blank=True)),
                ('lines', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
