# Generated by Django 2.0.5 on 2019-01-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0181_auto_20190110_1146'),
        ('doctor', '0184_merge_20190111_1522'),
    ]

    operations = [
    ]
