# Generated by Django 2.0.5 on 2019-01-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0184_uploaddoctordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddoctordata',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('', 'Select'), (1, 'Created'), (2, 'Upload in progress'), (3, 'Upload successful'), (4, 'Upload Failed')], default=1),
        ),
    ]
