# Generated by Django 2.0.5 on 2019-01-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0184_merge_20190111_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicespecialization',
            name='doctors_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
