# Generated by Django 2.0.5 on 2019-01-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0185_auto_20190111_0005'),
        ('doctor', '0184_merge_20190111_1522'),
    ]

    operations = [
    ]
