# Generated by Django 2.0.5 on 2019-01-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0185_practicespecialization_doctors_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicespecialization',
            old_name='doctors_count',
            new_name='doctor_count',
        ),
    ]
