# Generated by Django 2.0.5 on 2019-01-18 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0187_auto_20190115_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddoctordata',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_doctor_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
