# Generated by Django 2.0.5 on 2019-01-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0186_auto_20190117_1754'),
        ('doctor', '0188_uploaddoctordata_user'),
    ]

    operations = [
    ]
