# Generated by Django 2.0.5 on 2019-01-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0189_merge_20190118_1535'),
        ('doctor', '0185_merge_20190111_1744'),
    ]

    operations = [
    ]
