# Generated by Django 2.0.5 on 2019-01-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0190_merge_20190122_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationreason',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='cancellationreason',
            name='visible_on_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cancellationreason',
            name='visible_on_front_end',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='cancellationreason',
            unique_together={('name', 'type')},
        ),
    ]
