# Generated by Django 2.0.5 on 2019-01-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0181_merge_20190110_1034'),
        ('doctor', '0193_auto_20190125_1516'),
    ]

    operations = [
    ]
