# Generated by Django 2.0.5 on 2019-01-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0185_opdappointment_money_pool'),
        ('doctor', '0194_auto_20190125_1556'),
    ]

    operations = [
    ]
