# Generated by Django 2.0.5 on 2019-01-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0194_auto_20190125_1556'),
        ('doctor', '0194_merge_20190125_1601'),
    ]

    operations = [
    ]
