# Generated by Django 2.0.5 on 2019-02-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0196_auto_20190125_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='disable_reason',
            field=models.PositiveIntegerField(blank=True, choices=[('', 'Select'), (1, 'Doctor not associated with the hospital anymore'), (2, 'Doctor only for IPD services'), (3, 'Doctor available only On-Call'), (4, 'Incorrect contact details'), (5, 'MoU agreement needed'), (6, 'Doctor not interested for tie-up'), (7, 'Issue in discount % / consultation charges'), (8, 'Duplicate'), (9, 'Others (please specify)')], null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='disable_reason',
            field=models.PositiveIntegerField(blank=True, choices=[('', 'Select'), (1, 'Incorrect contact details'), (2, 'MoU agreement needed'), (3, 'Hospital not interested for tie-up'), (4, 'Issue in discount % / consultation charges'), (5, 'Duplicate'), (9, 'Others (please specify)')], null=True),
        ),
    ]
