# Generated by Django 2.0.5 on 2019-01-31 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0196_auto_20190125_1718'),
        ('doctor', '0195_merge_20190129_1408'),
    ]

    operations = [
    ]
