# Generated by Django 2.0.5 on 2019-02-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0196_auto_20190125_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationreason',
            name='is_comment_needed',
            field=models.BooleanField(default=False),
        ),
    ]
