# Generated by Django 2.0.5 on 2019-02-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0197_merge_20190131_1512'),
        ('doctor', '0176_merge_20181228_1550'),
    ]

    operations = [
    ]
