# Generated by Django 2.0.5 on 2019-02-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0197_cancellationreason_is_comment_needed'),
        ('doctor', '0197_auto_20190204_1631'),
    ]

    operations = [
    ]
