# Generated by Django 2.0.5 on 2019-02-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0197_merge_20190131_1512'),
        ('doctor', '0198_merge_20190204_1758'),
    ]

    operations = [
    ]
