# Generated by Django 2.0.5 on 2019-03-01 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0199_merge_20190205_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ImageField(blank=True, null=True, upload_to='doctor/stickers', verbose_name='Original Image Name')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='doctor.Doctor')),
            ],
            options={
                'db_table': 'doctor_sticker',
            },
        ),
    ]
