# Generated by Django 2.0.5 on 2019-02-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0199_merge_20190205_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True),
        ),
    ]
