# Generated by Django 2.0.5 on 2019-02-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0199_merge_20190205_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='data_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In Progress'), (2, 'Submitted For QC Check'), (3, 'QC approved'), (4, 'Reopened')], default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='data_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In Progress'), (2, 'Submitted For QC Check'), (3, 'QC approved'), (4, 'Reopened')], default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='hospitalnetwork',
            name='data_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In Progress'), (2, 'Submitted For QC Check'), (3, 'QC approved'), (4, 'Reopened')], default=1, editable=False),
        ),
    ]
