# Generated by Django 2.0.5 on 2019-02-11 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0199_merge_20190205_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorleave',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.Hospital'),
        ),
    ]
