# Generated by Django 2.0.5 on 2019-02-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0200_auto_20190206_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='welcome_calling_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='welcome_calling_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
