# Generated by Django 2.0.5 on 2019-02-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0200_hospital_is_mask_number_required'),
        ('doctor', '0200_doctor_avg_rating'),
    ]

    operations = [
    ]
