# Generated by Django 2.0.5 on 2019-03-05 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0200_doctorsticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorimage',
            name='new_image',
            field=models.FileField(null=True, upload_to='doctor', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jfif', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
