# Generated by Django 2.0.5 on 2019-03-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0201_doctorimage_new_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorimage',
            name='new_image',
        ),
    ]
