# Generated by Django 2.0.5 on 2019-02-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0201_merge_20190214_1831'),
        ('doctor', '0201_merge_20190219_1659'),
    ]

    operations = [
    ]
