# Generated by Django 2.0.5 on 2019-02-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0202_merge_20190222_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
