# Generated by Django 2.0.5 on 2019-02-27 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_service'),
        ('doctor', '0202_merge_20190222_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalServiceMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_mappings', to='doctor.Hospital')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_service_mappings', to='common.Service')),
            ],
            options={
                'db_table': 'hospital_service_mapping',
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='service',
            field=models.ManyToManyField(related_name='of_hospitals', through='doctor.HospitalServiceMapping', to='common.Service'),
        ),
        migrations.AlterUniqueTogether(
            name='hospitalservicemapping',
            unique_together={('hospital', 'service')},
        ),
    ]
