# Generated by Django 2.0.5 on 2019-02-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0204_auto_20190227_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalnetwork',
            name='open_for_email',
            field=models.BooleanField(default=True),
        ),
    ]
