# Generated by Django 2.0.5 on 2019-02-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0204_hospital_deleted'),
        ('doctor', '0204_auto_20190227_1233'),
    ]

    operations = [
    ]
