# Generated by Django 2.0.5 on 2019-02-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0204_auto_20190211_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalnetwork',
            name='welcome_calling_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospitalnetwork',
            name='welcome_calling_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
