# Generated by Django 2.0.5 on 2019-03-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0204_auto_20190227_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='bed_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
