# Generated by Django 2.0.5 on 2019-02-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0205_hospitalnetwork_open_for_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalnetwork',
            old_name='open_for_email',
            new_name='open_for_communication',
        ),
    ]
