# Generated by Django 2.0.5 on 2019-03-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0205_merge_20190228_1442'),
        ('doctor', '0205_hospital_bed_count'),
    ]

    operations = [
    ]
