# Generated by Django 2.0.5 on 2019-02-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0206_auto_20190228_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='open_for_communication',
            field=models.BooleanField(default=True),
        ),
    ]
