# Generated by Django 2.0.5 on 2019-03-02 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0206_auto_20190301_1418'),
        ('doctor', '0206_merge_20190301_1641'),
    ]

    operations = [
    ]
