# Generated by Django 2.0.5 on 2019-02-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0206_auto_20190212_1325'),
        ('doctor', '0200_hospital_is_mask_number_required'),
    ]

    operations = [
    ]
