# Generated by Django 2.0.5 on 2019-03-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0207_merge_20190302_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True),
        ),
    ]
