# Generated by Django 2.0.5 on 2019-02-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0202_merge_20190222_1705'),
        ('doctor', '0208_auto_20190215_1608'),
    ]

    operations = [
    ]
