# Generated by Django 2.0.5 on 2019-03-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0209_merge_20190226_1415'),
        ('doctor', '0206_merge_20190301_1641'),
    ]

    operations = [
    ]
