# Generated by Django 2.0.5 on 2019-03-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0207_hospital_open_for_communication'),
        ('doctor', '0210_merge_20190304_1109'),
    ]

    operations = [
    ]
