# Generated by Django 2.0.5 on 2019-03-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0211_merge_20190304_1959'),
        ('doctor', '0205_auto_20190228_1215'),
    ]

    operations = [
    ]
