# Generated by Django 2.0.5 on 2019-03-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0211_merge_20190304_1959'),
        ('doctor', '0202_remove_doctorimage_new_image'),
    ]

    operations = [
    ]
