# Generated by Django 2.0.5 on 2019-03-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0208_hospital_avg_rating'),
        ('doctor', '0211_merge_20190304_1959'),
    ]

    operations = [
    ]
