# Generated by Django 2.0.5 on 2019-03-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0212_merge_20190306_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='source_type',
            field=models.IntegerField(choices=[(1, 'Agent'), (2, 'Provider')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='source_type',
            field=models.IntegerField(choices=[(1, 'Agent'), (2, 'Provider')], editable=False, null=True),
        ),
    ]
