# Generated by Django 2.0.5 on 2019-03-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0212_hospitalhelpline'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='about',
            field=models.TextField(blank='', default=''),
        ),
    ]
