# Generated by Django 2.0.5 on 2019-03-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0213_hospital_about'),
        ('doctor', '0212_merge_20190305_1100'),
    ]

    operations = [
    ]
