# Generated by Django 2.0.5 on 2019-03-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0214_auto_20190306_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
