# Generated by Django 2.0.5 on 2019-03-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0214_merge_20190306_1133'),
        ('doctor', '0214_auto_20190306_1152'),
    ]

    operations = [
    ]
