# Generated by Django 2.0.5 on 2019-03-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0213_auto_20190306_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_listed_on_docprime',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='providersignuplead',
            name='is_docprime',
            field=models.NullBooleanField(editable=False),
        ),
    ]
