# Generated by Django 2.0.5 on 2019-03-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0216_auto_20190306_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='opd_timings',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
