# Generated by Django 2.0.5 on 2019-03-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0217_auto_20190306_1243'),
        ('doctor', '0216_auto_20190308_1249'),
    ]

    operations = [
    ]
