# Generated by Django 2.0.5 on 2019-03-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0198_merge_20190204_1401'),
        ('doctor', '0217_auto_20190306_1243'),
    ]

    operations = [
    ]
