# Generated by Django 2.0.5 on 2019-03-12 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0220_auto_20190311_1735'),
        ('doctor', '0218_merge_20190308_1305'),
    ]

    operations = [
    ]
