# Generated by Django 2.0.5 on 2019-03-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0212_merge_20190308_1423'),
        ('doctor', '0221_merge_20190312_0914'),
    ]

    operations = [
    ]
