# Generated by Django 2.0.5 on 2019-03-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0222_merge_20190313_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersignuplead',
            name='matrix_lead_id',
            field=models.IntegerField(null=True),
        ),
    ]
