# Generated by Django 2.0.5 on 2019-03-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0222_merge_20190313_1751'),
        ('doctor', '0222_hospital_city_search_key'),
    ]

    operations = [
    ]
