# Generated by Django 2.0.5 on 2019-03-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0223_merge_20190314_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='city_search_key',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=100, null=True),
        ),
    ]
