# Generated by Django 2.0.5 on 2019-03-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0224_auto_20190314_1709'),
        ('doctor', '0220_merge_20190313_1047'),
    ]

    operations = [
    ]
