# Generated by Django 2.0.5 on 2019-03-15 10:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0224_auto_20190314_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalPlaceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place_id', models.TextField()),
                ('place_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('reviews', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Hospital')),
            ],
            options={
                'db_table': 'hospital_place_details',
            },
        ),
    ]
