# Generated by Django 2.0.5 on 2019-03-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0224_auto_20190314_1709'),
        ('doctor', '0223_providersignuplead_matrix_lead_id'),
    ]

    operations = [
    ]
