# Generated by Django 2.0.5 on 2019-03-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0225_hospitalplacedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalplacedetails',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reviews', to='doctor.Hospital'),
        ),
    ]
