# Generated by Django 2.0.5 on 2019-03-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0225_merge_20190314_1713'),
        ('doctor', '0226_auto_20190315_1718'),
    ]

    operations = [
    ]
