# Generated by Django 2.0.5 on 2019-03-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0226_auto_20190318_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdappointment',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Prepaid'), (2, 'COD'), (3, 'Insurance'), (4, 'Subscription Plan')], default=1),
        ),
    ]
