# Generated by Django 2.0.5 on 2019-03-20 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0227_merge_20190320_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalplacedetails',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_place_details', to='doctor.Hospital'),
        ),
    ]
