# Generated by Django 2.0.5 on 2019-03-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0228_auto_20190320_1504'),
        ('doctor', '0227_auto_20190320_1117'),
    ]

    operations = [
    ]
