# Generated by Django 2.0.5 on 2019-03-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0228_auto_20190320_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='search_key',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='generalspecialization',
            name='search_key',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='search_key',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='search_key',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='practicespecialization',
            name='search_key',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='visitreason',
            name='search_key',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
