# Generated by Django 2.0.5 on 2019-03-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0229_merge_20190320_1605'),
        ('doctor', '0229_auto_20190320_1642'),
    ]

    operations = [
    ]
