# Generated by Django 2.0.5 on 2019-03-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0230_merge_20190320_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorclinic',
            name='welcome_calling_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorclinic',
            name='welcome_calling_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
