# Generated by Django 2.0.5 on 2019-03-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0225_merge_20190319_1423'),
        ('doctor', '0230_merge_20190320_1712'),
    ]

    operations = [
    ]
