# Generated by Django 2.0.5 on 2019-03-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0231_auto_20190328_1116'),
        ('doctor', '0231_doctor_rating_data'),
    ]

    operations = [
    ]
