# Generated by Django 2.0.5 on 2019-03-29 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0231_doctor_rating_data'),
        ('doctor', '0232_auto_20190326_1349'),
    ]

    operations = [
    ]
