# Generated by Django 2.0.5 on 2019-03-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', 'indexing_on_search_key'),
        ('doctor', '0233_auto_20190329_1553'),
    ]

    operations = [
    ]
