# Generated by Django 2.0.5 on 2019-04-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0233_merge_20190329_1016'),
        ('doctor', '0234_merge_20190329_1825'),
    ]

    operations = [
    ]
