# Generated by Django 2.0.5 on 2019-04-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0234_merge_20190329_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_location_verified',
            field=models.BooleanField(default=False, verbose_name='Location Verified'),
        ),
    ]
