# Generated by Django 2.0.5 on 2019-04-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0235_auto_20190401_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='is_cod_enabled',
            new_name='enabled_for_cod',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='is_prepaid_enabled',
            new_name='enabled_for_prepaid',
        ),
    ]
