# Generated by Django 2.0.5 on 2019-04-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0235_merge_20190401_1224'),
        ('doctor', '0236_auto_20190401_1419'),
    ]

    operations = [
    ]
