# Generated by Django 2.0.5 on 2019-04-11 09:01

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0068_auto_20190404_2025'),
        ('doctor', '0239_auto_20190404_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInvoiceItems',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=200)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='authentication.GenericAdmin')),
            ],
            options={
                'db_table': 'general_invoice_items',
            },
        ),
        migrations.CreateModel(
            name='SelectedInvoiceItems',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('calculated_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_items',
                                   to='doctor.PartnersAppInvoice')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected',
                                                   to='doctor.GeneralInvoiceItems')),
            ],
            options={
                'db_table': 'selected_invoice_items',
            },
        ),
        migrations.CreateModel(
            name='PartnersAppInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_serial_id', models.CharField(max_length=100)),
                ('consultation_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selected_invoice_items', django.contrib.postgres.fields.jsonb.JSONField()),
                ('payment_status', models.IntegerField(choices=[(1, 'Paid'), (2, 'Pending')])),
                ('payment_type', models.IntegerField(blank=True, choices=[(1, 'Online'), (2, 'Cash')], null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invoice_title', models.CharField(max_length=300)),
                ('sub_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True,
                                                       validators=[django.core.validators.MinValueValidator(0),
                                                                   django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True,
                                                            validators=[django.core.validators.MinValueValidator(0),
                                                                        django.core.validators.MaxValueValidator(
                                                                            100)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_invoice_generated', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='partners/invoice')),
                ('invoice_url', models.URLField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('appointment',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners_app_invoice',
                                   to='doctor.OpdAppointment')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                related_name='patners_app_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partners_app_invoice',
            },
        ),
    ]
