# Generated by Django 2.0.5 on 2019-04-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0239_auto_20190404_2028'),
        ('doctor', '0235_hospital_is_location_verified'),
    ]

    operations = [
    ]
