# Generated by Django 2.0.5 on 2019-04-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0240_merge_20190412_2014'),
        ('doctor', '0240_auto_20190417_1210'),
    ]

    operations = [
    ]
