# Generated by Django 2.0.5 on 2019-04-18 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0240_merge_20190412_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdappointment',
            name='money_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opd_apps', to='account.MoneyPool'),
        ),
    ]
