# Generated by Django 2.0.5 on 2019-04-12 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0240_generalinvoiceitems_selectedinvoiceitems_walkinpatientinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinvoiceitems',
            name='admin',
        ),
        migrations.AddField(
            model_name='generalinvoiceitems',
            name='hospitals',
            field=models.ManyToManyField(related_name='invoice_items', to='doctor.Hospital'),
        ),
        migrations.AddField(
            model_name='generalinvoiceitems',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
