# Generated by Django 2.0.5 on 2019-04-16 12:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0241_opdappointment_auto_ivr_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdappointment',
            name='auto_ivr_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
    ]
