# Generated by Django 2.0.5 on 2019-04-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0240_merge_20190412_2014'),
        ('doctor', '0241_auto_20190412_1650'),
    ]

    operations = [
    ]
