# Generated by Django 2.0.5 on 2019-04-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0241_auto_20190412_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinpatientinvoice',
            name='invoice_url',
            field=models.URLField(null=True, blank=True),
        ),
        migrations.RenameField(
            model_name='walkinpatientinvoice',
            old_name='invoice_id',
            new_name='invoice_serial_id',
        ),
    ]
