# Generated by Django 2.0.5 on 2019-04-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0242_merge_20190415_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineopdappointments',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
