# Generated by Django 2.0.5 on 2019-04-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0242_partnersappinvoice_encoded_url'),
        ('doctor', '0241_auto_20190418_1649'),
    ]

    operations = [
    ]
