# Generated by Django 2.0.5 on 2019-04-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0242_walkinpatientinvoice_invoice_url'),
        ('doctor', '0240_merge_20190412_2014'),
    ]

    operations = [
    ]
