# Generated by Django 2.0.5 on 2019-04-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0243_merge_20190418_1829'),
        ('doctor', '0244_merge_20190418_1852'),
    ]

    operations = [
    ]
