# Generated by Django 2.0.5 on 2019-04-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0245_merge_20190419_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicespecialization',
            name='is_insurance_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
