# Generated by Django 2.0.5 on 2019-04-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0245_merge_20190419_0907'),
        ('doctor', '0241_auto_20190418_1554'),
    ]

    operations = [
    ]
