# Generated by Django 2.0.5 on 2019-04-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0245_merge_20190419_1303'),
        ('doctor', '0245_merge_20190419_0907'),
    ]

    operations = [
    ]
