# Generated by Django 2.0.5 on 2019-04-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0246_auto_20190419_1633'),
        ('doctor', '0245_merge_20190419_0907'),
    ]

    operations = [
    ]
