# Generated by Django 2.0.5 on 2019-05-03 09:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0246_practicespecialization_is_insurance_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdappointment',
            name='coupon_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
