# Generated by Django 2.0.5 on 2019-04-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0246_practicespecialization_is_insurance_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='priority_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='priority_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalnetwork',
            name='priority_score',
            field=models.IntegerField(default=0),
        ),
    ]
