# Generated by Django 2.0.5 on 2019-04-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0246_merge_20190423_1626'),
        ('doctor', '0247_merge_20190423_1058'),
    ]

    operations = [
    ]
