# Generated by Django 2.0.5 on 2019-04-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0246_practicespecialization_is_insurance_enabled'),
        ('doctor', '0248_merge_20190424_1135'),
    ]

    operations = [
    ]
