# Generated by Django 2.0.5 on 2019-05-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0249_auto_20190429_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledetailing',
            name='hospital_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
