# Generated by Django 2.0.5 on 2019-05-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0250_googledetailing_hospital_id'),
        ('doctor', '0247_opdappointment_coupon_data'),
    ]

    operations = [
    ]
