# Generated by Django 2.0.5 on 2019-05-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0250_googledetailing_hospital_id'),
        ('doctor', '0247_hospitalimage_cropped_image'),
    ]

    operations = [
    ]
