# Generated by Django 2.0.5 on 2019-05-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0250_googledetailing_hospital_id'),
        ('doctor', '0249_merge_20190425_1948'),
    ]

    operations = [
    ]
