# Generated by Django 2.0.5 on 2019-05-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0251_merge_20190502_2119'),
        ('doctor', '0249_merge_20190425_1948'),
    ]

    operations = [
    ]
