# Generated by Django 2.0.5 on 2019-05-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0251_merge_20190507_1219'),
        ('doctor', '0251_merge_20190502_2119'),
    ]

    operations = [
    ]
