# Generated by Django 2.0.5 on 2019-05-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0252_merge_20190508_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersappinvoice',
            name='consultation_fees',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
