# Generated by Django 2.0.5 on 2019-05-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0252_merge_20190507_1740'),
        ('doctor', '0253_auto_20190509_1509'),
    ]

    operations = [
    ]
