# Generated by Django 2.0.5 on 2019-05-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0253_auto_20190509_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='search_distance',
            field=models.FloatField(default=15000),
        ),
    ]
