# Generated by Django 2.0.5 on 2019-05-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0254_merge_20190510_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='url',
            field=models.CharField(db_index=True, editable=False, max_length=2000, null=True),
        ),
    ]
