# Generated by Django 2.0.5 on 2019-05-13 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0254_auto_20190513_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='provider_encrypted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encrypted_hospitals', to=settings.AUTH_USER_MODEL),
        ),
    ]
