# Generated by Django 2.0.5 on 2019-05-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0254_hospital_google_avg_rating'),
        ('doctor', '0254_merge_20190510_1419'),
    ]

    operations = [
    ]
