# Generated by Django 2.0.5 on 2019-05-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0254_merge_20190510_1419'),
        ('doctor', '0254_hospital_search_distance'),
    ]

    operations = [
    ]
