# Generated by Django 2.0.5 on 2019-05-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0255_doctor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='url',
            field=models.CharField(db_index=True, editable=False, max_length=2000, null=True),
        ),
    ]
