# Generated by Django 2.0.5 on 2019-05-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0255_auto_20190513_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinepatients',
            name='encrypted_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
