# Generated by Django 2.0.5 on 2019-05-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0256_hospital_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdappointment',
            name='status_change_comments',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
