# Generated by Django 2.0.5 on 2019-05-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0254_merge_20190510_1419'),
        ('doctor', '0256_offlinepatients_encrypted_name'),
    ]

    operations = [
    ]
