# Generated by Django 2.0.5 on 2019-05-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0255_merge_20190516_1754'),
        ('doctor', '0256_hospital_url'),
    ]

    operations = [
    ]
