# Generated by Django 2.0.5 on 2019-05-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0256_hospital_url'),
        ('doctor', '0255_merge_20190517_1133'),
    ]

    operations = [
    ]
