# Generated by Django 2.0.5 on 2019-05-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0257_opdappointment_status_change_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdappointment',
            name='is_cod_to_prepaid',
            field=models.NullBooleanField(default=False),
        ),
    ]
