# Generated by Django 2.0.5 on 2019-05-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0257_opdappointment_status_change_comments'),
        ('doctor', '0257_merge_20190523_1130'),
    ]

    operations = [
    ]
