# Generated by Django 2.0.5 on 2019-05-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0256_hospital_url'),
        ('doctor', '0257_merge_20190520_1800'),
    ]

    operations = [
    ]
