# Generated by Django 2.0.5 on 2019-05-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0258_merge_20190522_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='encrypted_hospital_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='encryption_hint',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
