# Generated by Django 2.0.5 on 2019-06-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0259_auto_20190529_1156'),
        ('doctor', '0258_merge_20190529_1122'),
    ]

    operations = [
    ]
