# Generated by Django 2.0.5 on 2019-05-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0251_doctorclinictiming_cod_deal_price'),
        ('doctor', '0259_auto_20190529_1156'),
    ]

    operations = [
    ]
