# Generated by Django 2.0.5 on 2019-05-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0259_auto_20190524_1820'),
        ('doctor', '0257_opdappointment_status_change_comments'),
    ]

    operations = [
    ]
