# Generated by Django 2.0.5 on 2019-06-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0260_merge_20190604_1428'),
        ('doctor', '0260_merge_20190604_1228'),
    ]

    operations = [
    ]
