# Generated by Django 2.0.5 on 2019-05-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0260_merge_20190524_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinepatients',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
