# Generated by Django 2.0.5 on 2019-06-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0260_merge_20190604_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='has_proper_hospital_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_big_hospital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_ipd_hospital',
            field=models.BooleanField(default=False),
        ),
    ]
