# Generated by Django 2.0.5 on 2019-06-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0257_merge_20190524_1533'),
        ('doctor', '0260_merge_20190604_1428'),
    ]

    operations = [
    ]
