# Generated by Django 2.0.5 on 2019-06-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0260_merge_20190531_1548'),
        ('doctor', '0260_merge_20190604_1428'),
    ]

    operations = [
    ]
