# Generated by Django 2.0.5 on 2019-05-28 06:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0261_auto_20190527_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderEncrypt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=None)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypt_details', to='doctor.Hospital')),
            ],
            options={
                'db_table': 'provider_encrypt',
            },
        ),
    ]
