# Generated by Django 2.0.5 on 2019-06-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0261_merge_20190612_1344'),
        ('doctor', '0261_merge_20190612_1333'),
    ]

    operations = [
    ]
