# Generated by Django 2.0.5 on 2019-05-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0264_auto_20190528_1947'),
        ('doctor', '0259_auto_20190529_1156'),
    ]

    operations = [
    ]
