# Generated by Django 2.0.5 on 2019-06-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0265_merge_20190530_1354'),
        ('doctor', '0260_merge_20190604_1428'),
    ]

    operations = [
    ]
