# Generated by Django 2.0.5 on 2019-06-12 10:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0266_merge_20190612_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedPartnersAppInvoiceLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'encrypted_partners_app_invoice_logs',
            },
        ),
        migrations.AddField(
            model_name='partnersappinvoice',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
