# Generated by Django 2.0.5 on 2019-06-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0267_auto_20190612_1538'),
        ('doctor', '0262_merge_20190612_1550'),
    ]

    operations = [
    ]
