# Generated by Django 2.0.5 on 2019-06-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0261_merge_20190613_1524'),
        ('doctor', '0268_merge_20190614_1657'),
    ]

    operations = [
    ]
