# Generated by Django 2.0.5 on 2019-06-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0261_auto_20190612_1456'),
        ('doctor', '0269_merge_20190614_2143'),
    ]

    operations = [
    ]
