# Generated by Django 2.0.5 on 2019-06-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0270_auto_20190617_1520'),
        ('doctor', '0270_merge_20190617_1212'),
    ]

    operations = [
    ]
