# Generated by Django 2.0.5 on 2019-06-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0271_merge_20190617_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalnetwork',
            name='new_about',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hospitalnetwork',
            name='use_new_about',
            field=models.BooleanField(default=False),
        ),
    ]
