# Generated by Django 2.0.5 on 2019-06-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0272_auto_20190618_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='use_new_about',
        ),
        migrations.RemoveField(
            model_name='hospitalnetwork',
            name='use_new_about',
        ),
    ]
