# Generated by Django 2.0.5 on 2019-06-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0273_auto_20190618_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerencrypt',
            name='google_drive',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
