# Generated by Django 2.0.5 on 2019-06-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0274_opdappointment_hospital_reference_id'),
        ('doctor', '0274_providerencrypt_google_drive'),
    ]

    operations = [
    ]
