# Generated by Django 2.0.5 on 2019-07-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0277_auto_20190710_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdappointment',
            name='appointment_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Regular'), (2, 'Followup')], null=True),
        ),
    ]
