# Generated by Django 2.0.5 on 2019-07-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0277_auto_20190710_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicespecialization',
            name='priority',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
