# Generated by Django 2.0.5 on 2019-07-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0278_opdappointment_appointment_type'),
        ('doctor', '0278_practicespecialization_priority'),
    ]

    operations = [
    ]
