# Generated by Django 2.0.5 on 2019-07-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0279_merge_20190717_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarspecializationgroup',
            name='show_on_front_end',
            field=models.BooleanField(default=False),
        ),
    ]
