# Generated by Django 2.0.5 on 2019-07-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0280_similarspecializationgroup_show_on_front_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarspecializationgroup',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
