# Generated by Django 2.0.5 on 2019-07-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0282_doctorclinictiming_insurance_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicespecialization',
            name='search_distance',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
