# Generated by Django 2.0.5 on 2019-07-26 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0282_doctorclinictiming_insurance_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.IntegerField(choices=[('hospital', 1), ('lab', 2)])),
                ('provider_name', models.CharField(max_length=500)),
                ('gst_number', models.CharField(max_length=1000)),
                ('total_amount_paid', models.IntegerField(help_text='Inclusive of GST')),
                ('active_till', models.DateTimeField()),
                ('appointment_count', models.IntegerField()),
                ('agreement_details', models.TextField()),
                ('invoice_no', models.CharField(blank=True, help_text='Either enter a valid invoice number or upload the invoice image', max_length=1000, null=True)),
                ('invoice_image', models.FileField(blank=True, null=True, upload_to='qrcode', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jfif', 'jpg', 'jpeg', 'png'])])),
            ],
            options={
                'db_table': 'purchase_order_creation',
            },
        ),
    ]
