# Generated by Django 2.0.5 on 2019-07-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0282_doctorclinictiming_insurance_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationreason',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('', 'Both'), (1, 'Doctor Appointment'), (2, 'LAB_PRODUCT_ID'), (3, 'INSURANCE_PRODUCT_ID'), (4, 'SUBSCRIPTION_PLAN_PRODUCT_ID'), (5, 'CHAT_PRODUCT_ID')], default=None, null=True),
        ),
    ]
