# Generated by Django 2.0.5 on 2019-07-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0283_purchaseordercreation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseordercreation',
            old_name='invoice_no',
            new_name='proof_of_payment',
        ),
        migrations.RenameField(
            model_name='purchaseordercreation',
            old_name='invoice_image',
            new_name='proof_of_payment_image',
        ),
        migrations.AlterField(
            model_name='purchaseordercreation',
            name='provider_type',
            field=models.CharField(choices=[('hospital', 'HOSPITAL'), ('lab', 'LAB')], max_length=10),
        ),
    ]
