# Generated by Django 2.0.5 on 2019-07-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0283_doctorclinictiming_custom_deal_price'),
        ('doctor', '0283_practicespecialization_search_distance'),
    ]

    operations = [
    ]
