# Generated by Django 2.0.5 on 2019-08-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0284_merge_20190726_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicespecialization',
            name='is_similar_specialization',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
