# Generated by Django 2.0.5 on 2019-08-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0284_merge_20190726_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
