# Generated by Django 2.0.5 on 2019-08-05 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0284_merge_20190726_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpdFollowupAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_follow_up', models.BooleanField(default=False, verbose_name='System Generated Followup')),
                ('agent_appointment_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Regular'), (2, 'Followup')], null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctor.OpdAppointment')),
            ],
        ),
    ]
