# Generated by Django 2.0.5 on 2019-08-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0284_merge_20190726_1626'),
        ('doctor', '0246_merge_20190424_1637'),
    ]

    operations = [
    ]
