# Generated by Django 2.0.5 on 2019-08-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0285_opdfollowupappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opdfollowupappointment',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='OpdFollowupAppointment',
        ),
    ]
