# Generated by Django 2.0.5 on 2019-07-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0285_auto_20190726_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordercreation',
            name='provider_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
