# Generated by Django 2.0.5 on 2019-08-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0285_hospital_seo_title'),
        ('doctor', '0285_auto_20190806_1635'),
    ]

    operations = [
    ]
