# Generated by Django 2.0.5 on 2019-08-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0285_practicespecialization_is_similar_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicespecialization',
            name='is_similar_specialization',
            field=models.BooleanField(default=True),
        ),
    ]
