# Generated by Django 2.0.5 on 2019-08-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0286_merge_20190806_1743'),
        ('doctor', '0283_auto_20190726_1301'),
    ]

    operations = [
    ]
