# Generated by Django 2.0.5 on 2019-08-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0285_practicespecialization_is_similar_specialization'),
        ('doctor', '0286_merge_20190806_1743'),
    ]

    operations = [
    ]
