# Generated by Django 2.0.5 on 2019-08-06 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0286_merge_20190806_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinepatients',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
