# Generated by Django 2.0.5 on 2019-07-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0286_purchaseordercreation_provider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordercreation',
            name='provider_name_hospital',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doctor.Hospital'),
        ),
        migrations.AlterField(
            model_name='purchaseordercreation',
            name='provider_name_lab',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diagnostic.Lab'),
        ),
    ]
