# Generated by Django 2.0.5 on 2019-08-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0286_merge_20190806_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_ipd_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
