# Generated by Django 2.0.5 on 2019-08-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0284_merge_20190726_1626'),
        ('doctor', '0287_auto_20190726_1626'),
    ]

    operations = [
    ]
