# Generated by Django 2.0.5 on 2019-08-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0287_merge_20190808_1356'),
        ('doctor', '0287_doctor_is_ipd_doctor'),
    ]

    operations = [
    ]
