# Generated by Django 2.0.5 on 2019-08-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0287_merge_20190806_1834'),
        ('doctor', '0288_merge_20190808_1414'),
    ]

    operations = [
    ]
