# Generated by Django 2.0.5 on 2019-08-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0289_merge_20190808_1435'),
        ('doctor', '0286_auto_20190806_1244'),
    ]

    operations = [
    ]
