# Generated by Django 2.0.5 on 2019-08-05 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0289_auto_20190805_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordercreation',
            name='proof_of_payment_image',
            field=models.FileField(blank=True, null=True, upload_to='purchaseorder', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jfif', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
