# Generated by Django 2.0.5 on 2019-08-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0289_merge_20190808_1435'),
        ('doctor', '0288_auto_20190807_1446'),
    ]

    operations = [
    ]
