# Generated by Django 2.0.5 on 2019-08-06 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0290_auto_20190805_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdappointment',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='opdpurchaseorder', to='doctor.PurchaseOrderCreation'),
        ),
        migrations.AlterField(
            model_name='purchaseordercreation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseordercreation',
            name='provider_name_hospital',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospitalpurchaseorder', to='doctor.Hospital'),
        ),
        migrations.AlterField(
            model_name='purchaseordercreation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
