# Generated by Django 2.0.5 on 2019-08-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0291_practicespecialization_breadcrumb_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='enabled_for_insurance',
            field=models.NullBooleanField(verbose_name='Enabled for Insurance'),
        ),
    ]
