# Generated by Django 2.0.5 on 2019-08-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0291_auto_20190806_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordercreation',
            name='product_type',
            field=models.CharField(choices=[('Pay at Clinic', 'Pay at Clinic'), ('Sponsor Listing', 'Sponsor Listing')], default='Pay at Clinic', max_length=100),
        ),
    ]
