# Generated by Django 2.0.5 on 2019-08-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0290_merge_20190809_1656'),
        ('doctor', '0292_purchaseordercreation_product_type'),
    ]

    operations = [
    ]
