# Generated by Django 2.0.5 on 2019-08-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0292_purchaseordercreation_product_type'),
        ('doctor', '0289_merge_20190808_1435'),
    ]

    operations = [
    ]
