# Generated by Django 2.0.5 on 2019-08-13 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0294_auto_20190812_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdappointment',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opdpurchaseorder', to='doctor.PurchaseOrderCreation'),
        ),
    ]
