# Generated by Django 2.0.5 on 2019-08-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0295_auto_20190813_1243'),
        ('doctor', '0291_practicespecialization_breadcrumb_priority'),
    ]

    operations = [
    ]
