# Generated by Django 2.0.5 on 2019-08-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0292_hospital_enabled_for_insurance'),
        ('doctor', '0296_merge_20190814_1132'),
    ]

    operations = [
    ]
