# Generated by Django 2.0.5 on 2019-08-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0296_merge_20190814_1132'),
        ('doctor', '0285_merge_20190806_1629'),
    ]

    operations = [
    ]
