# Generated by Django 2.0.5 on 2019-08-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0293_merge_20190809_1727'),
        ('doctor', '0296_merge_20190814_1132'),
    ]

    operations = [
    ]
