# Generated by Django 2.0.5 on 2019-08-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0297_merge_20190819_1135'),
        ('doctor', '0297_merge_20190819_1555'),
    ]

    operations = [
    ]
