# Generated by Django 2.0.5 on 2019-08-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0297_merge_20190819_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='enabled_for_insurance',
            field=models.NullBooleanField(verbose_name='Enabled for Insurance'),
        ),
    ]
