# Generated by Django 2.0.5 on 2019-08-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0297_merge_20190819_1555'),
        ('doctor', '0291_auto_20190813_1542'),
    ]

    operations = [
    ]
