# Generated by Django 2.0.5 on 2019-08-20 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0300_auto_20190820_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalNetworkSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.HospitalNetwork')),
            ],
            options={
                'db_table': 'hospital_network_speciality',
            },
        ),
    ]
