# Generated by Django 2.0.5 on 2019-08-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0301_hospitalnetworkspeciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalnetwork',
            name='always_open',
            field=models.BooleanField(default=False, verbose_name='Are hospitals open 24X7'),
        ),
    ]
