# Generated by Django 2.0.5 on 2019-08-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0303_hospitalnetwork_service'),
        ('doctor', '0298_practicespecialization_bucket_size'),
    ]

    operations = [
    ]
