# Generated by Django 2.0.5 on 2019-08-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0298_merge_20190822_1504'),
        ('doctor', '0304_merge_20190826_1658'),
    ]

    operations = [
    ]
