# Generated by Django 2.0.5 on 2019-08-27 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0304_merge_20190826_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSponsoredServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_services', to='doctor.Doctor')),
            ],
            options={
                'db_table': 'doctor_sponsored_services',
            },
        ),
        migrations.CreateModel(
            name='HospitalSponsoredServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospital_services', to='doctor.Hospital')),
            ],
            options={
                'db_table': 'hospital_sponsored_services',
            },
        ),
        migrations.CreateModel(
            name='SponsoredServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'sponsored_services',
            },
        ),
        migrations.AddField(
            model_name='hospitalsponsoredservices',
            name='sponsored_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hosp_sponsored_services', to='doctor.SponsoredServices'),
        ),
        migrations.AddField(
            model_name='doctorsponsoredservices',
            name='sponsored_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_sponsored_services', to='doctor.SponsoredServices'),
        ),
        migrations.AlterUniqueTogether(
            name='hospitalsponsoredservices',
            unique_together={('hospital', 'sponsored_service')},
        ),
        migrations.AlterUniqueTogether(
            name='doctorsponsoredservices',
            unique_together={('doctor', 'sponsored_service')},
        ),
    ]
