# Generated by Django 2.0.5 on 2019-08-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0304_merge_20190826_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='enabled_for_plus_plans',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hospital',
            name='enabled_for_plus_plans',
            field=models.NullBooleanField(),
        ),
    ]
