# Generated by Django 2.0.5 on 2019-08-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0304_merge_20190826_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordercreation',
            name='gst_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
