# Generated by Django 2.0.5 on 2019-09-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0304_merge_20190826_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_cloud_lab_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
