# Generated by Django 2.0.5 on 2019-08-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0297_merge_20190816_1138'),
        ('doctor', '0304_merge_20190826_1658'),
    ]

    operations = [
    ]
