# Generated by Django 2.0.5 on 2019-08-28 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0305_auto_20190827_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredServicePracticeSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary_specialization', models.BooleanField(default=False)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='spec_sponsored_services', to='doctor.PracticeSpecialization')),
                ('sponsored_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='spec_sponsored_services', to='doctor.SponsoredServices')),
            ],
            options={
                'db_table': 'specialization_sponsored_services',
            },
        ),
    ]
