# Generated by Django 2.0.5 on 2019-09-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0305_merge_20190830_1755'),
        ('doctor', '0306_sponsoredservicepracticespecialization'),
    ]

    operations = [
    ]
