# Generated by Django 2.0.5 on 2019-08-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0306_opdappointment_plus_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalnetwork',
            name='enabled_for_plus_plans',
            field=models.NullBooleanField(),
        ),
    ]
