# Generated by Django 2.0.5 on 2019-09-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0308_auto_20190830_1739'),
        ('doctor', '0306_sponsoredservicepracticespecialization'),
    ]

    operations = [
    ]
