# Generated by Django 2.0.5 on 2019-09-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0309_merge_20190903_1915'),
        ('doctor', '0309_merge_20190903_1916'),
    ]

    operations = [
    ]
