# Generated by Django 2.0.5 on 2019-09-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0305_auto_20190828_1601'),
        ('doctor', '0309_merge_20190903_1911'),
        ('doctor', '0309_merge_20190903_1915'),
    ]

    operations = [
    ]
