# Generated by Django 2.0.5 on 2019-09-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0310_merge_20190903_1929'),
        ('doctor', '0307_merge_20190902_1858'),
    ]

    operations = [
    ]
