# Generated by Django 2.0.5 on 2019-09-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0312_auto_20190903_1950'),
        ('doctor', '0310_merge_20190903_1921'),
    ]

    operations = [
    ]
