# Generated by Django 2.0.5 on 2019-09-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0298_merge_20190820_1528'),
        ('doctor', '0312_auto_20190903_1950'),
    ]

    operations = [
    ]
