# Generated by Django 2.0.5 on 2019-09-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0312_auto_20190903_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_partner_lab_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
