# Generated by Django 2.0.5 on 2019-09-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0313_merge_20190904_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalsponsoredservices',
            name='poc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poc_hospital_services', to='doctor.PurchaseOrderCreation'),
        ),
    ]
