# Generated by Django 2.0.5 on 2019-09-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0313_merge_20190904_1219'),
        ('doctor', '0305_merge_20190827_1647'),
    ]

    operations = [
    ]
