# Generated by Django 2.0.5 on 2019-09-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0313_hospital_is_partner_lab_enabled'),
        ('doctor', '0313_merge_20190904_1219'),
    ]

    operations = [
    ]
