# Generated by Django 2.0.5 on 2019-09-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0314_hospitalsponsoredservices_poc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalsponsoredservices',
            name='poc',
        ),
    ]
