# Generated by Django 2.0.5 on 2019-09-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0314_merge_20190911_1911'),
        ('doctor', '0314_auto_20190910_2022'),
    ]

    operations = [
    ]
