# Generated by Django 2.0.5 on 2019-09-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0315_remove_hospitalsponsoredservices_poc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalimage',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagehospital', to='doctor.Hospital'),
        ),
    ]
