# Generated by Django 2.0.5 on 2019-09-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0313_merge_20190904_1219'),
        ('doctor', '0316_auto_20190905_1739'),
    ]

    operations = [
    ]
