# Generated by Django 2.0.5 on 2019-09-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0315_merge_20190913_1621'),
        ('doctor', '0317_merge_20190910_1914'),
    ]

    operations = [
    ]
