# Generated by Django 2.0.5 on 2019-09-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0318_merge_20190916_1822'),
        ('doctor', '0314_merge_20190905_1209'),
    ]

    operations = [
    ]
