# Generated by Django 2.0.5 on 2019-10-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0320_merge_20191009_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='google_avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
