# Generated by Django 2.0.5 on 2019-11-06 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0321_auto_20191018_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalplacedetails',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospital_place_details', to='doctor.Hospital'),
        ),
    ]
