# Generated by Django 2.0.5 on 2019-11-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0321_auto_20191018_1716'),
        ('doctor', '0321_auto_20191022_1434'),
    ]

    operations = [
    ]
