# Generated by Django 2.0.5 on 2019-11-05 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0072_certifications'),
        ('doctor', '0321_auto_20191018_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalcertification',
            name='certification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospital_certifications', to='common.Certifications'),
        ),
    ]
