# Generated by Django 2.0.5 on 2019-11-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0322_merge_20191106_1310'),
        ('doctor', '0322_auto_20191106_1255'),
    ]

    operations = [
    ]
