# Generated by Django 2.0.5 on 2019-11-05 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0322_hospitalcertification_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalcertification',
            name='certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospital_certifications', to='common.Certifications'),
        ),
    ]
