# Generated by Django 2.0.5 on 2019-11-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0072_certifications'),
        ('doctor', '0323_auto_20191105_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalnetworkcertification',
            name='certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospital_network_certifications', to='common.Certifications'),
        ),
    ]
