# Generated by Django 2.0.5 on 2019-11-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0323_merge_20191106_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdappointment',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Prepaid'), (2, 'COD'), (3, 'Insurance'), (4, 'Subscription Plan'), (5, 'VIP'), (6, 'GOLD')], default=1),
        ),
    ]
