# Generated by Django 2.0.5 on 2019-11-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0323_merge_20191106_1315'),
        ('doctor', '0324_hospitalnetworkcertification_certification'),
    ]

    operations = [
    ]
