# Generated by Django 2.0.5 on 2019-11-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0324_googlemaprecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemaprecords',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
