# Generated by Django 2.0.5 on 2019-11-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0325_googlemaprecords_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemaprecords',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlemaprecords',
            name='combined_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlemaprecords',
            name='combined_rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlemaprecords',
            name='has_booking',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlemaprecords',
            name='has_phone',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlemaprecords',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='googlemaprecords',
            name='is_potential',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlemaprecords',
            name='lead_rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googlemaprecords',
            name='monday_timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlemaprecords',
            name='multi_speciality',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='googlemaprecords',
            name='place_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
