# Generated by Django 2.0.5 on 2019-11-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0326_auto_20191119_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlemaprecords',
            name='monday_timing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
