# Generated by Django 2.0.5 on 2019-11-21 09:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0327_auto_20191119_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlemaprecords',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
