# Generated by Django 2.0.5 on 2019-11-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0325_auto_20191121_1852'),
        ('doctor', '0328_auto_20191121_1501'),
    ]

    operations = [
    ]
