# Generated by Django 2.0.5 on 2019-11-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0328_auto_20191121_1501'),
        ('doctor', '0325_merge_20191107_1726'),
    ]

    operations = [
    ]
