# Generated by Django 2.0.5 on 2019-11-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0329_merge_20191125_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemaprecords',
            name='is_bookable',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
