# Generated by Django 2.0.5 on 2019-11-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0330_googlemaprecords_is_bookable'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemaprecords',
            name='hospital_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlemaprecords',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
