# Generated by Django 2.0.5 on 2019-11-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0330_googlemaprecords_is_bookable'),
        ('doctor', '0329_merge_20191127_1822'),
    ]

    operations = [
    ]
