# Generated by Django 2.0.5 on 2019-11-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0331_merge_20191128_1140'),
        ('doctor', '0331_merge_20191128_1138'),
    ]

    operations = [
    ]
