# Generated by Django 2.0.5 on 2019-12-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0332_merge_20191128_1735'),
        ('doctor', '0333_auto_20191128_1155'),
    ]

    operations = [
    ]
