# Generated by Django 2.0.5 on 2019-12-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0334_merge_20191202_1127'),
        ('doctor', '0334_commonhospital_percentage'),
    ]

    operations = [
    ]
