# Generated by Django 2.0.5 on 2019-12-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0337_auto_20191205_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='enabled_for_gold',
            field=models.NullBooleanField(),
        ),
    ]
