# Generated by Django 2.0.5 on 2019-12-10 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0337_auto_20191205_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonspecialization',
            name='icon',
            field=models.FileField(null=True, upload_to='doctor/common_specialization_icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
