# Generated by Django 2.0.5 on 2019-12-17 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0338_hospital_enabled_for_gold'),
        ('doctor', '0338_auto_20191210_1828'),
    ]

    operations = [
    ]
