# Generated by Django 2.0.5 on 2019-12-23 06:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0339_merge_20191217_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorclinictiming',
            name='convenience_pricing',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
