# Generated by Django 2.0.5 on 2019-12-23 13:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0340_doctorclinictiming_convenience_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorclinictiming',
            name='convenience_pricing',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
