# Generated by Django 2.0.5 on 2020-01-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0342_commonspecialization_svg_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchscore',
            name='discount',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='searchscore',
            name='partner_app_activity',
            field=models.FloatField(default=None, null=True),
        ),
    ]
