# Generated by Django 2.0.5 on 2020-02-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0342_commonspecialization_svg_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemaprecords',
            name='has_phlebo',
            field=models.SmallIntegerField(choices=[(1, 'NA'), (2, 'Yes'), (3, 'No')], default=1),
        ),
        migrations.AddField(
            model_name='googlemaprecords',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
