# Generated by Django 2.0.5 on 2020-01-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0343_auto_20200120_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchScoreParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('param', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.PositiveIntegerField(blank=True, null=True)),
                ('is_enabled', models.NullBooleanField(default=False)),
                ('is_live', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'search_score_params',
            },
        ),
    ]
