# Generated by Django 2.0.5 on 2020-01-27 09:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0346_auto_20200127_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreWeightage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('param', models.CharField(blank=True, max_length=200, null=True)),
                ('weightage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'score_weightage',
            },
        ),
        migrations.RemoveField(
            model_name='searchscoreparams',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='searchscoreparams',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='searchscoreparams',
            name='score',
        ),
        migrations.AddField(
            model_name='searchscoreparams',
            name='score_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchscoreparams',
            name='weightage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weightage_percentage', to='doctor.ScoreWeightage'),
        ),
    ]
