# Generated by Django 2.0.5 on 2020-02-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0347_auto_20200212_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdappointment',
            name='revenue_transferred',
            field=models.NullBooleanField(),
        ),
    ]
