# Generated by Django 2.0.5 on 2020-03-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0348_auto_20200127_1542'),
        ('doctor', '0347_auto_20200212_1744'),
    ]

    operations = [
    ]
