# Generated by Django 2.0.5 on 2020-03-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0348_opdappointment_revenue_transferred'),
        ('doctor', '0349_merge_20200304_1458'),
    ]

    operations = [
    ]
