# Generated by Django 2.0.5 on 2019-01-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0231_doctor_rating_data'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                CREATE EXTENSION pg_trgm;
                '''
        ),
        migrations.RunSQL(''' 
                CREATE  INDEX idx_doctor_search_key ON doctor USING GIST (search_key gist_trgm_ops);
        '''),
    ]
